### ISSUE TITLE
Modify owl:versionInfo in gist ontology declarations

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#100]
It seems weird to include a local path in the gist ontologies' owl:versionInfo, especially in the public download, but also in the repository files given that it's now a public repo:

```
<owl:versionInfo rdf:datatype="&xs;string">Created with e6Tools Graphical OWL Editor from S:\_SemanticArts\Offerings\gist\_daveGistGit\gist\gist9.0.0.vsd Page:address</owl:versionInfo>
```
How about something along the lines of:

```
<owl:versionInfo rdf:datatype="&xs;string">Version 9.0.0 created with e6Tools Graphical OWL Editor</owl:versionInfo>
```

Or, given that we will be phasing out e6, just:

```
<owl:versionInfo rdf:datatype="&xs;string">Version 9.0.0</owl:versionInfo>
```

**Comment by uscholdm** [comment]
Good point. Unfortunately, this a comment generated by e6, we cannot change it.

**Comment by rjyounes** [comment]
Will be resolved once we are no longer generating OWL files in e6.
