### ISSUE TITLE
Promote isSpecifiedBy from gistHR to gistCore and improve definition

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#1000]
Current definition: "When a thing is a further clarification of something else." (Which needs to be brought into conformance with our definition conventions in any case.)

Specifying something does not always imply _further_ elaboration or clarification, but can also be used in the initial definition of something. I this sense is more or less a synonym for "is defined by," but I don't think we need distinct predicates for this nuance. `isSpecifiedBy` should cover both (and "defines" carries its own ambiguity).

Cambridge dictionary: "To explain or describe something clearly and exactly: He said we should meet but didn't specify a time. The peace treaty clearly specifies the terms for the withdrawal of troops."

Proposal (first draft): "Relates something to another thing that defines, elaborates, clarifies, or provides a specification for it."

**Comment by uscholdm** [comment]
This is interesting. FWIW, an early definition of this for one of our clients is:
- Relates something to a particular entry in an overall specification.

That's too specific - I like your proposal.

**Comment by dylan-sa** [comment]
`isSpecifiedBy` is in one of the sub-gists but not yet in gist Core. I think it is a good candidate for promotion to gist Core given its use in client ontologies.

I like @rjyounes's proposal for the definition.
