### ISSUE TITLE
Change name of uniqueText to avoid confusion

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#1004]
The property is used when the object can have only a single text string. It does not mean that the text string is unique to all objects.

I've found that this is a common misunderstanding - see, e.g., #560, #1003.

I propose renaming it to avoid this common confusion. I don't have a concrete suggestion at the moment..

**Comment by uscholdm** [comment]
#631 is also related.

**Comment by uscholdm** [comment]
> The property is used when the object can have only a single text string. It does not mean that the text string is unique to all objects.

I assume this means it is not acting as if it was inverse functional.  That would mean two different tags could have the same unique text, is that what we want?

**Comment by rjyounes** [comment]
> I assume this means it is not acting as if it was inverse functional. 

Correct.

> That would mean two different tags could have the same unique text, is that what we want?

That's a good question. Maybe in the same way that we can have distinct IDs with the same string. We may want to know, e.g., who applied the tag to which thing, requiring different tags for different things that are being tagged.

**Comment by uscholdm** [comment]
> That's a good question. Maybe in the same way that we can have distinct IDs with the same string. We may want to know, e.g., who applied the tag to which thing, requiring different tags for different things that are being tagged.

This gets into thing vs. string and altlabels.  Im struggling to think of an example when we would want two tags to have the same string. What about synonyms, 'car' and 'auto', or 'New York City' and' the big apple'. Easily handled with altLabel. I think a Tag is a weaker wimpy thing that people make up on the fly, in which case two different tags would never have the same text. The text would differ exactly as the tags differed.

So Im leaning in favor of having, at a minimum, a scopeNote to this effect. It could be enforced via SHACL.

Outside the context of Tags, are there may well be more than one individual with the same unique text. None come to mind, but I can't think of a good reason to rule out the possibility.

**Comment by stevenchalem** [comment]
"soleText" ?
"singularText" ?
"exclusiveText" ?

**Comment by uscholdm** [comment]
> "soleText" ? "singularText" ? "exclusiveText" ?

These are all more or less synonyms, so from a meaning perspective, it may not be any better. However, these sound a bit weaker than uniqueText, so that might help.  

Nevertheless, I'm leaning towards expecting users to understand what functional means, and to clarify the potential confusion about uniqueness _not_ going the other way in a scope note.  This is less disruptive than renaming a property that we've had for years

**Comment by rjyounes** [comment]
> Nevertheless, I'm leaning towards expecting users to understand what functional means, and to clarify the potential confusion about uniqueness not going the other way in a scope note. This is less disruptive than renaming a property that we've had for years

You've convinced me.

**Comment by uscholdm** [comment]
Is it worth adding a scop note to clarify the potential confusion about uniqueness not going the other way.  If not close again.

**Comment by rjyounes** [comment]
> Is it worth adding a scope note to clarify the potential confusion about uniqueness not going the other way?

Yes, that's a good idea.

**Comment by uscholdm** [comment]
I propose: 
- `While a given individual can only have one text string, we allow for the case where two different objects could have the same unique text.`

**Comment by rjyounes** [comment]
I like this better than what was in your PR.

**Comment by uscholdm** [comment]
> I like this better than what was in your PR.

Huh?  It's exactly the same. Maybe I edited it to align after creating the PR. The original was repeating what was in the definition, so I tightened it up.

**Comment by rjyounes** [comment]
Yes, I saw something different when I looked at this earlier.
