### ISSUE TITLE
Seems https://ontologies.semanticarts.com/ is offline right now, so gist Core is unavailable...!

### ISSUE THREAD

**Issue by pmcb55** [semanticarts/gist#1014]
Hi there,

I seems the entire Semantic Arts `ontologies` subdomain is offline right now (i.e., https://ontologies.semanticarts.com/), meaning nobody can retrieve Gist Core from it's PURL: curl -L https://w3id.org/semanticarts/ontology/gistCore

Is this part of planning maintanence, or something else...?

**Comment by rjyounes** [comment]
@pmcb55 Thanks for the heads up. @Jamie-SA?

**Comment by rjyounes** [comment]
It seems there is an internet outage in the SA office. I will leave the issue open and add a comment when it's back up.

**Comment by rjyounes** [comment]
@pmcb55 gistCore is now back online.
