### ISSUE TITLE
Cannot tell gist ontology release date by looking in the ontology

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#1017]
One can't tell gist ontology release date by looking in the ontology.
It would be nice to be able to do so.
Suggest we add indication of gist release date as an ontology annotation.
Be sure to use a property that will keep gist as OWL-DL.

**Comment by rjyounes** [comment]
Agree and would advocate for adding a new gist property `releaseDateTime` - or `releaseDate`, depending on how granular we want to be, as a subproperty of `gist:atDateTime`. `skos:changeNote` and `skos:historyNote` are not interpretable as a release date until you add text to specify that. `dcterms:created` is an RDF property which would take gist out of DL.
