### ISSUE TITLE
Cannot tell when a gist concept was first created or most recently modified.

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#1018]
Looking in a gistCore ontology file, one cannot tell when a gist concept was first created or most recently modified.
It would be nice if each Concept had an annotation about when it was created (date & version) and when it was most recently changed (date & version).  This could be automated into a skos history note, perhaps.  Other options that don't break OWL-DL could also be considered. 

E.g.
```
gist:Aspect a owl:Class
; skos:historyNote "Created 2020-03-04; gistCore11.0.0"
; skos:historyNote "Modified 2023-07-11; gistCore12.1.0"
.
```

**Comment by uscholdm** [comment]
This would be nice, but to do manually might be onerous and prone to errors and incompleteness. Not sure how automatable it is.

**Comment by rjyounes** [comment]
I agree. This came up at a meeting in relation to #1017, which is straightforward, but I think this is too ambitious. Closing.
