### ISSUE TITLE
Use either weight or mass for magnitudes and units

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#105]
Gist defines MassUnit and Weight magnitude. Granted that they are interchangeable on the earth's surface, as the notes indicate, it would make more sense if they both referenced mass or both referenced weight, unless there is a reason not to. If there's a reason not to, add it to the notes on the terms so people like me don't get confused.

**Comment by uscholdm** [comment]
Yes, gist:Mass would be a better name for gsit:Weight. Consistency between the unit and the magnitude is handy.

**Comment by rjyounes** [comment]
Deprecate gist:Weight and add an equivalence to gist:Mass, even though not technically correct. Put in gistDeprecated file.

**Comment by uscholdm** [comment]
> Deprecate gist:Weight and add an equivalence to gist:Mass to the gist:Weight definition, even though not technically correct.

Quibble: The equivalence is technically correct. What is wrong is using the term Weight to mean Mass, but that's now deprecated history.
