### ISSUE TITLE
Define inverse of gist:produces

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#106]
Define gist:producedBy as inverse of gist:produces.

**Comment by uscholdm** [comment]
We generally do not create inverses unless there is a specific need. Strictly it is never needed, one can always use the ^ notation in SPARQL, or owl:inverse construct in the OWL.

**Comment by rjyounes** [comment]
You may legitimately want to define an inverse to state a restriction, correct?

**Comment by rjyounes** [comment]
No, the restriction can be stated using owl:inverseOf.
```
X a owl:Class ;
owl:equivalentClass [
owl:Restriction [
   owl:onProperty [
      a rdf:Property ;
     owl:inverseOf gist:produces
] ] ] 
```
