### ISSUE TITLE
Remove domain and range from gist:allows

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#1063]
Too restrictive - I've found several other contexts in which I'd like to use it but can't.

Current domain is `gist:Intention`
Current range is `gist:Behavior`

**Comment by uscholdm** [comment]
> Too restrictive - I've found several other contexts in which I'd like to use it but can't.

Can you give some examples?

**Comment by rjyounes** [comment]
Michael: What can allow something? Person, Organization, Intention

DECISION: Remove domain and range.
