### ISSUE TITLE
Change skos:definition of gist:directs to remove references to sensor-related terms

### ISSUE THREAD

**Issue by turingtest37** [semanticarts/gist#1079]
The current (12.1.0) definition of `gist:directs` is "The set of actuators that a controller can affect".
The classes `gist:Actuator` and `gist:Controller` have been removed as per Issue #462 .

As a starting point for a new definition (thanks, Merriam-Webster) I propose  "To issue orders to someone or something by right of authority."

**Comment by rjyounes** [comment]
The question is whether we want the generic predicate in gist at all, given that it was defined for IoT. Essentially we'd be adding a _new_ predicate with the same _name_ as the old one. Unless we have a use case we don't need it in gistCore.

**Comment by rjyounes** [comment]
We've decided the predicate should be removed. See PR #1089.
