### ISSUE TITLE
Add hasUnitOfMeasure as equivalent property to hasUofM

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#108]
hasUofM does not immediately suggest unit of measure. hasUnitOfMeasure is semantically transparent. hasUofM could be deprecated if desired.

**Comment by rjyounes** [comment]
Duplicates #144, and I don't like the equivalent property suggestion.

**Comment by uscholdm** [comment]
I think deprecation relies on equivalentPrpoerty, but we want it to eventually go away.

**Comment by rjyounes** [comment]
Oh you're right, I'll add that to #144.
