### ISSUE TITLE
Modify definition of Requirement and move Specification to be a direct subclass of Intention (was: Remove Requirement)

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#1087]
See discussion in PR #1077.

Currently `Requirement` encompasses two rather different meanings, clearly indicated by the disjointness of the definition: "A documented physical or functional need that a particular design, product, or process must be able to perform.  Alternately, the obligation of a person or organization to behave in a certain way (i.e., drive on the right side of the road)."

The proposal from @uscholdm and myself is to delete this class and promote its two subclasses, `Specification` and `Restriction`, to be direct subclasses of `Intention`.

**Comment by uscholdm** [comment]
> The proposal from @uscholdm and myself is to delete this property

You mean delete the class, `Reqirement`.

**Comment by rjyounes** [comment]
> You mean delete the class, Requirement.

Yes, corrected above.

**Comment by rjyounes** [comment]
DECISION: Add to PR #1077:

* Move `Specification` up to be a direct subclass of `Intention`
* Change definition of `Requirement`: "The obligation of a person or organization to behave in a certain way (i.e., drive on the right side of the road)."

**Comment by uscholdm** [comment]
Fixed in https://github.com/semanticarts/gist/pull/1077
