### ISSUE TITLE
Generate gist-doc for version 13

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#1088]
Also adjust links to this doc on the SA website and repository README.

**Comment by rjyounes** [comment]
@pwin I think merging this documentation back into the main gist repository will help us keep it in lock-step with major releases. Do you agree?

**Comment by pwin** [comment]
Agree

**Comment by rjyounes** [comment]
Instead of generating post-release, could we give Peter the new ontology for him to generate the doc before the release? Might work if we can get a quick turnaround.

**Comment by rjyounes** [comment]
Closing - duplicates https://github.com/semanticarts/gist-doc/issues/12.
