### ISSUE TITLE
Bad inferences in Artifact and Component

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#111]
Each is inferred to be a subclass of the other. Protege justification doesn't give a complete justification. Could the reasoners be wrong? Both Pellet and Hermit give the same results. I don't immediately see the logic, however.

**Comment by uscholdm** [comment]
Did you click the ? to get an explanation?  That give an explicit chain of reasoning, which can be less than clear, but usually gives a good hint.

**Comment by rjyounes** [comment]
I did, but it produced nothing useful. However, I have since restarted Protege and I'm no longer seeing the error. Strange.
