### ISSUE TITLE
Deprecate gist:hasSuperCategory and use gist:hasBroader instead

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#1115]
Since we introduce `hasBroader` in gist 13.0.0, it is now confusing that we have it in addition to `gist:hasSuperCategory`. `hasBroader` is meant to apply to more cases, such as aspects, than is `hasSuperCategory`, but it could apply equally well to categories. I propose that we:

- Deprecate `gist:hasSuperCategory` and `gist:hasDirectSuperCategory`
- Define a new property `gist:hasDirectBroader` that serves the same purpose as `gist:hasDirectSuperCategory`

**Comment by rjyounes** [comment]
DECISION:
* Delete `hasSuperCategory`
* Change `hadDirectSuperCategory` to `hasDirectBroader` and make subproperty of `hasBroader`
* Change `hasUniqueSuperCategory` to `hasUniqueBroader` and make subproperty of `hasBroader`
* Rewrite any relevant restrictions (e.g., on `Taxonomy`)

**Comment by stevenchalem** [comment]
Maybe this is overly pedantic, but shouldn't the textual definition of `broader` be something like "Relates a thing to another thing with a broader meaning _that encompasses it_" or "_that subsumes it_"? "Citrus Fruits" is broader than "Limes", and "Vertebrates" is broader than "Mammals". Now, "Limes" is a pretty narrow category and "Vertebrates" is a pretty broad category, so we could say the "Vertebrates" is broader than "Limes".  But we're not meaning to talk just about broadness here; we also mean the the object encompasses the subject.

**Comment by philblackwood** [comment]
Also modify data conversion scripts to rename properties

**Comment by philblackwood** [comment]
@stevenchalem we might want to tune the definition in the future. My first impression is that people will understand the simple definition provided as it is intended (I hope so).

**Comment by uscholdm** [comment]
> Maybe this is overly pedantic, but shouldn't the textual definition of `broader` be something like "Relates a thing to another thing with a broader meaning _that encompasses it_" or "_that subsumes it_"? "Citrus Fruits" is broader than "Limes", and "Vertebrates" is broader than "Mammals". Now, "Limes" is a pretty narrow category and "Vertebrates" is a pretty broad category, so we could say the "Vertebrates" is broader than "Limes". But we're not meaning to talk just about broadness here; we also mean the the object encompasses the subject.

Your point is accurate, and it would not be a bad idea to clarify as you say, for those folk who may wonder what we mean.

**Comment by rjyounes** [comment]
@stevenchalem This is a good point. Feel free to add an issue. I agree with @philblackwood that it is _broadly_ understood - most people are familiar with the meaning from SKOS.
