### ISSUE TITLE
fix definition of GeoSegment

### ISSUE THREAD

**Issue by philblackwood** [semanticarts/gist#1134]
The definition of GeoSegment appears to have a typo. It says a GeoSegment is a single portion of a _GeoRegion_ instead of being a single portion of a _GeoRoute_.

Current definition of GeoSegment: "A single portion of a GeoRegion which has been divided (i.e., segmented)."

Proposed: "A single portion of a GeoRoute consisting of consecutive GeoPoints belonging to the GeoRoute."

Proposed addition to GeoRoute: "Each consecutive pair of GeoPoints in a GeoRoute is a GeoSegment."

**Comment by uscholdm** [comment]
I agree - I also noticed this just now.
