### ISSUE TITLE
atDateTime properties should use xsd:dateTime in restrictions 

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#1144]
The range of `gist:atDateTime` is `xsd:dateTime` but there are a bunch of restrictions that use `rdfs:Literal` as the local range.  For example:
- `gist:startDateTime exactly 1 rdfs:Literal`

 I propose that all such occurrences of `rdfs:Literal` be changed to `xsd:dateTime`.

See also #1132

**Comment by rjyounes** [comment]
@uscholdm I think we can fast-track this; it's hard to see anyone objecting. Do you want to take it on?

**Comment by uscholdm** [comment]
Sure

**Comment by uscholdm** [comment]
There is nothing to do here. I was apparently looking at an old version of gist.

**Comment by uscholdm** [comment]
There is nothing to do here. I was apparently looking at an old version of gist.

**Comment by uscholdm** [comment]
c

**Comment by uscholdm** [comment]
Having  hard time closing it as non planned.
