### ISSUE TITLE
GIST:Function

### ISSUE THREAD

**Issue by DougalW** [semanticarts/gist#117]
Hi, GIST:Function shows up in the owl files as under GIST:Intention, but the documentation of that package makes no mention of Function.
Also, the description of Function states that: "A function is what a specific made item is intended to do.  For instance: transmit electricity, provide ballast, control ambient temperature.", but what about business functions? They are effectively logical groupings of resources (e.g. people, machinery, information, raw materials) and events that occur together to deliver some form of value to the organisation.

**Comment by uscholdm** [comment]
I had forgotten that we had a class for Function. It might be a bad idea. It's used in a wide variety of different ways. You pointed out one very different yet common use. So naming a class "Function" is going to be problematic, given it is ambiguous.

**Comment by DougalW** [comment]
Hi Michael

Here’s my use case for this class, and I’d value your opinion on alternative ways to model this or other similar examples you’ve seen.

In manufacturing we often have a Stock Item (physical resources e.g. raw materials) consumed via activities and machinery at discrete Locations called Work Centres, inside a Plant (although sometimes there’s no plant e.g. how SpaceX is making Starship in a field in Texas, just a Site and Site can in turn hold multiple Plants), which transforms the resources into intermediate Work Pieces and finally into a Product (Finished Product).

Many ERP system classify groups of these entities into an overarching class to enable costing and pricing. SAP S/4 calls this a Cost Centre, which is a pretty bad term. I’m calling this Manufacturing Function because actual client data looks like a functional description of the grouped entities. Also, a lot of machinery can be reconfigured on the fly so Work Centre is effectively virtual to accommodate this variability and it’s nature is governed by the Manufacturing Function it is assigned to.

Looks something like this (without data properties):



I also have a use case for Business Function, which I have yet to model out.

My other question is, I’ve placed Business Function and Manufacturing Function under Function, but in a way they seem to be Collections (but not Categories). What do you think?

Cheers

Dougal Watt
CTO
Meaningful Technology

Mobile: +64 21 549 613
Linkedin:  <http://www.linkedin.com/in/dougalwatt/>www. <http://www.linkedin.com/in/dougalwatt/>linkedin.com/in/dougalwatt/ <http://www.linkedin.com/in/dougalwatt/>
Website: meaningful.co.nz <https://meaningful.co.nz/>

**Comment by DanCarey404** [comment]
@DougalW , your example code didn't make it into the comment.

**Comment by DougalW** [comment]
Updated now

**Comment by rjyounes** [comment]
Dan: Dougal seems to be getting into process, which may be called "function" in English but is not the same as gist:Function.
