### ISSUE TITLE
More examples of strange GeoRegions

### ISSUE THREAD

**Issue by johnwcowan** [semanticarts/gist#119]
Isle Royale is a U.S. island in Lake Superior, which is on the U.S.-Canada border.  Siskiwit Lake is the largest lake on the island. It contains several islands, including Ryan Island, the largest, which contains Moose Flats, a seasonal pond, which contains Moose Boulder. When Moose Flats is a pond, Moose Boulder becomes the largest island in the largest lake on the largest island in the largest lake on the largest island in the largest lake in the world.

===================

Until 2015, the India-Bangladesh border was almost fractal in its complexity.  An _enclave_ is part of a country inside another country; an _exclave_ is a part of a country outside its main borders.  Hawaii is an exclave of the U.S., but it is not enclaved by any country; Botswana is an enclave of South Africa, but not an exclave because it is the mainland of the country.

As of 2015, within the main body of Bangladesh there were 102 enclaves of Indian territory, which in turn contained 21 Bangladeshi counter-enclaves, one of which contained an Indian counter-counter-enclave – the world's only third-order enclave. Within the Indian mainland were 71 Bangladeshi enclaves, containing 3 Indian counter-enclaves. 

A joint census in 2010 found 51,549 people residing in these enclaves: 37,334 in Indian enclaves within Bangladesh and 14,215 in Bangladeshi enclaves within India.  As you can imagine, this was very hard on the residents, as they could not reach any sort of government services (in particular, passports!) in their own country without crossing into another country.  Likewise, there were typically no buses, schools, or other advantages of belonging to a country.

Now there is only one enclave of Bangladesh inside India for which special provisions already existed: in 1992, a corridor was established allowing its inhabitants to cross Indian territory to reach the mainland of Bangladesh.  Under the 2015 settlement agreement India received 51 Bangladeshi enclaves (covering 7,110 acres/2,880 ha) in the Indian mainland, while Bangladesh received 111 Indian enclaves (covering 17,160 acres/6,940 ha) in the Bangladeshi mainland.

**Comment by uscholdm** [comment]
Totally brilliant!

**Comment by rjyounes** [comment]
Close the issue and add comments to #151.
