### ISSUE TITLE
Not all tools load .owl files

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#121]
TopBraid Composer does not load .owl files.   This is bad for our clients (e.g. Platts) who may wish to use gist files. It is also a hassle for any of us (me in particular) who wish to load files into TBC.  I suggest that we use .rdf if we use rdf/xml and .ttl for turtle.

**Comment by Jamie-SA** [comment]
Do all tools load .rdf files?
They technically are XML files so should they have a .xml extension?

**Comment by Jamie-SA** [comment]
The [spec](https://www.w3.org/TR/rdf-syntax-grammar/#section-MIME-Type) recommends use of ".rdf".

Protege seems to treat .rdf and .xml differently. With the .rdf format not using other local files to import. Seems odd.

**Comment by uscholdm** [comment]
*   Do all tools load .rdf files?

They should. It is an anomly that TBC prevents it.


  *   They technically are XML files so should they have a .xml extension?

Never once have I seen an owl file in rdf-xml syntax with an .xml extension.  We have always used .owl or .ttl. I started using .rdf with FIBO, since that is what they used.  I also like to use TBC from time to time.

**Comment by rjyounes** [comment]
Duplicates #129.
