### ISSUE TITLE
Remove gistWiki 

### ISSUE THREAD

**Issue by Jamie-SA** [semanticarts/gist#123]
In the updates to gist 9.0.0, gistWiki didn't get updated to use SSL. Switch to https on at least these lines (there might be others...):

Line  3: <!ENTITY gist "http://ontologies.semanticarts.com/gist/">
Line 10: xmlns:gist="http://ontologies.semanticarts.com/gist/"
Line 16: <owl:Ontology rdf:about="http://ontologies.semanticarts.com/o/gistWiki">
Line 19: <owl:imports rdf:resource="http://ontologies.semanticarts.com/o/gistTop9.0.0"/>
Line 20: <owl:versionIRI rdf:resource="http://ontologies.semanticarts.com/o/gistWiki9.0.0"/>

**Comment by uscholdm** [comment]
I thought we were getting rid of gistWiki entirely?

M.

**Comment by Jamie-SA** [comment]
Dave confirmed that gistWiki should be removed.

**Comment by rjyounes** [comment]
Closing issue.

**Comment by rjyounes** [comment]
Added #177 to remove gistWiki.

**Comment by rjyounes** [comment]
Don't need #177 since this is already includes the possibility of removing gistWiki. Does this constitute a major change? Can we do it for February?

**Comment by rjyounes** [comment]
Group decision: gistWiki is only there due to error. Removing it can be a patch.
