### ISSUE TITLE
Gist 9.0.0 fails load from URL into Protege

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#124]
Gist 9.0.0 does not load properly from web URL into Protege. 

Steps to reproduce:

1. open protege (e.g. version 
2. select File > Open from URL > ...
3. put in URL:  https://ontologies.semanticarts.com/o/gistCore9.0.0
4. Observe this failure message:
  sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
5. Try the http version of the URL (technically incorrect):  http://ontologies.semanticarts.com/o/gistCore9.0.0
6. Observe that it cannot locate the next imported ontology automatically on the web (as gist 8.0.0 does), it prompts for it. 

Desired behavior:
Behave like gist8.0.0, which properly loads all imports with no additional dialogs, but using the proper HTTPS URLs.

**Comment by Jamie-SA** [comment]
@marksem what version of Protege are you using?
If not the latest version could you update and try again?

**Comment by marksem** [comment]
Works in Protege 5.5.0 (latest).

(Problem shows itself in older versions of Protege, such as 5.2.0)
