### ISSUE TITLE
Currency Unit

### ISSUE THREAD

**Issue by DougalW** [semanticarts/gist#125]
The 'Currency Unit' class has this rdfs:comment "A unit of money. Note: this is the only unit whose conversion factors include time (i.e., the conversion rates change on a daily basis)."
I can't see where time is a factor in the axioms on this class - there's no 'Time Instant' axiom.
Cheers, Dougal

**Comment by uscholdm** [comment]
Thank you for your comment.  This is a note to the reader about how currency is different from other units.   In the event that someone wanted to track conversions over time, they would have to extend the ontology.

Its always a judgment call how much of what is in fact true is worth including in gist. If we put everything in, it would have a lot of bloat that which was of interest to relatively few.

**Comment by DougalW** [comment]
Thanks for your reply. I appreciate this perspective, it's a fine line to walk. This seems to work ok if I extend Currency with a restriction e.g. a data property to capture datetime data on the Currency class. 

    

    <rdf:Description rdf:about="https://ontologies.semanticarts.com/gist/CurrencyUnit">
        <rdfs:subClassOf>
            <owl:Restriction>
                <owl:onProperty rdf:resource="https://ontologies.semanticarts.com/gist/localDate"/>
                <owl:someValuesFrom rdf:resource="http://www.w3.org/2001/XMLSchema#date"/>
            </owl:Restriction>
        </rdfs:subClassOf>
    </rdf:Description>
</rdf:RDF>

However I can't make any modification to the underlying GIST definition or Protege will force-reload the GIST import. It does seem to sometimes display odd behaviour anyway: see https://github.com/protegeproject/protege/issues/722

**Comment by rjyounes** [comment]
WON'T FIX: This is an important point that will not be handled in gist at this time.
