### ISSUE TITLE
Manage versioned and unversioned IRIs in an OWL-compliant way

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#127]
1. According to the OWL spec:

- The server should redirect requests for an unversioned IRI to the IRI of the latest version. This needs to be fixed.

2. We should add rdfs:isDefinedBy assertions to every class and property in all gist ontologies. This is not required by the OWL spec, but we have agreed at past meetings that this is a good way to indicate which terms are defined in which ontologies (since the term IRIs themselves do not indicate this).

3. According to the OWL spec, owl:imports assertions should point to the _unversioned_ IRI. This is extremely problematic, because when requesting a previous version, that version will nevertheless import the most recent versioning, thus potentially resulting in incompatibilities. It is not clear what we should do here: if we want to comply with the spec, we will create version clashes when retrieving the ontologies over HTTP.

**Comment by uscholdm** [comment]
Another related issue is the fact that TobBraid Composer, the preferred tool of Platts, does NOT support version IRIs. TBC does not load imported gist ontologies like it should - in my experiments anyway.  Ideally we can have a single approach that work across all tools. Worst case, we can use a script to postprocess the single sourc version to produce a version that is specific to a particular tool and/or customer.

**Comment by tedhills** [comment]
With regard to #3, I think the tools (Protege and TBC) are the problem. Clearly, TBC is out of sync with the spec. As far as Protege goes, you can work around the problem by downloading the files locally and then telling Protege how to resolve the imports. But in general, neither tool is supporting the spirit of semver.org, and in my opinion that is a serious shortcoming of both tools.

**Comment by tedhills** [comment]
I just read https://www.w3.org/TR/owl2-syntax/#Ontology_IRI_and_Version_IRI sections 3.1 through 3.3 more closely. I was trying to deduce what the difference would be between an ontology IRI as given by the owl:ontologyIRI property value and the IRI which is the subject of the assertion <IRI> rdf:type owl:Ontology. If I have understood the spec correctly, then a single ontology, named by the subject of the assertion <IRI> rdf:type owl:Ontology, can be expressed in multiple physically distinct documents, each of which could have a different encoding (say, Turtle or RDF/XML or even a database), and it is the owl:ontologyIRI that points to a physically distinct document in some unspecified encoding (though, regardless of encoding, the document must be accessible via http).

I think this is a correct interpretation of the OWL spec, though the following points make me uncertain:

1. There is no example given in the spec that supports (or contradicts) this interpretation.
2. There is apparently no mechanism for communicating the encoding of an ontology. (Perhaps this is accomplished through the HTTP Content-type header?)
3. It is difficult to discuss this topic, since the term "ontology IRI" refers to the object of the owl:ontologyIRI property, leaving us with no convenient name for the subject of the "rdf:type owl:Ontology" assertion.

Thoughts?

**Comment by tedhills** [comment]
On re-review of the above, I am thinking that there is no explicitly defined owl:ontologyIRI property, and that the subject of the "rdf:type owl:Ontology" assertion is the ontology IRI property. I wish the spec were clearer on this point. Can anyone illuminate this for me?

**Comment by uscholdm** [comment]
That could explain why no one, including the W3C uses it.

**Comment by uscholdm** [comment]
I also don't see much evidence that there is an explicit ontologyIRI property. I googled and found this; https://github.com/lcnetdev/bibframe-ontology/issues/53 , which says:
-----------
http://www.w3.org/2002/07/owl#ontologyIRI does not exist, which leads to an accusation of namespace hijacking in tools like http://oops.linkeddata.es/

While the functional-style specification for OWL 2 does include an ontologyIRI property, the OWL2 serialization at http://www.w3.org/2002/07/owl explicitly states that it is only a partial description of OWL2.

Perhaps the ontologyIRI property is available from a different namespace, but as it cannot be resolved at the given URI, I would recommend removing it from the BIBFRAME vocab definition.
-----------

But while the text, 'OntologyIRI' exists in the 'functional-style specification for OWL 2' it does not exist in a way that clearly suggests that it is a property.

**Comment by tedhills** [comment]
Thanks, Michael. I am going to assume that the ontology IRI of the OWL spec is the subject of the triple having "rdf:type owl:Ontology" as its predicate and object. I can live with that.

That means that the requirement that an ontology with an owl:versionIRI property also have an ontology IRI is trivially satisfied by the assertion "<OntologyIri> owl:versionIRI <OntologyVersionIri> ."

**Comment by uscholdm** [comment]
I think that the original comment that triggered Rebecca to add an ontologyIRI property is here:

>  An ontology without an ontology IRI MUST NOT contain a version IRI. 

Perhaps what is meant by this is: 
> Note that if you want an ontology to have a version IRI, you will need to make sure it has an ontology IRI, which is achieved by creating an explicit instance of owl:ontology using rdf:type. The subject of that triple is also the subject of the triple assigning the version IRI. 

If there is no ontology IRI, there is no way to assign a version IRI to the ontology, there is nothing there to be the subject of the versionIRI triple.

**Comment by tedhills** [comment]
yep

**Comment by rjyounes** [comment]
You may be right about this. It's unfortunate that the references we've cited don't make clear whether ontologyIRI is defined or not. In https://www.w3.org/TR/owl2-syntax/#Ontology_IRI_and_Version_IRI, neither are referred to by formal property names - I.e., version IRI is referred to as "version IRI," not "versionIRI." Anyway, apologies if I've sent everyone on a wild goose chase in this regard. 

Regarding #3, I'm now convinced that we must violate the spec in order to make imports work, as I comment in https://github.com/semanticarts/gist/issues/128.

I also find it problematic that the spec requires that the value of rdfs:isDefinedBy be unversioned. Since this is the only way we have currently agreed on (though not implemented; there are other, and, I think better, mechanisms to do this, but we have not agreed to them) to link a term to the ontology that defines it after, say, importing the ontologies into a triple store, like imports it ought to refer to a specific version. Note that this interpretation of the predicate is not dictated by any stated assumptions in the OWL spec.

"The rdfs:isDefinedBy annotation property can be used to provide an IRI with another IRI such that the latter provides information about the definition of the former; the way in which this information is provided is not described by this specification." -- https://www.w3.org/TR/owl2-syntax/

Therefore, we would be deciding that by gist convention this is the way we link a term to its defining ontology.

**Comment by uscholdm** [comment]
I'm confused by an apparent contradiction.  On the one hand you say:

- I also find it problematic that the spec requires that the value of rdfs:isDefinedBy be unversioned.

On the other hand you say that 

- the owl2 spec does not say anything about the way in which information about how an IRI is defined .

**Comment by rjyounes** [comment]
Yes, a mistake. I forgot to remove the first one. I'm going to remove it now for the sake of clarity to others, though it will render these two comments mysterious.

**Comment by Jamie-SA** [comment]
I finally found where in the specs it specifies handling of the Ontology IRI in RDF. See Table 1 in https://www.w3.org/TR/2012/REC-owl2-mapping-to-rdf-20121211/#Translation_of_Axioms_without_Annotations

**Comment by rjyounes** [comment]
This makes it clear that the ontologyIRI is, as Ted suggests, simply the IRI used as the subject of the assertions in the ontology header, rather than there being a predicate owl:ontologyIRI.

```
ontologyIRI rdf:type owl:Ontology .
[ ontologyIRI owl:versionIRI versionIRI ] .
ontologyIRI owl:imports importedOntologyIRI1 .
...
ontologyIRI owl:imports importedOntologyIRIk .
```

**Comment by Jamie-SA** [comment]
The server should now return the latest version when asking for the un-versioned IRI.

**Comment by uscholdm** [comment]
This works, with a slight oddity.  I seem to get the same result if I load gistCore (unversioned) or gistCore9.0.0 as I should.  When I load gistCore8.0.0, it almost works - caveat is that the IRI for gistCore is unversioned. Fairly  peculiare. Maybe there is a wrong import in gist8?

![image](https://user-images.githubusercontent.com/10777545/71222183-5bd5ff00-2284-11ea-898b-ed38415fd82d.png)

![image](https://user-images.githubusercontent.com/10777545/71222204-6b554800-2284-11ea-89a4-107a29a19821.png)

**Comment by rjyounes** [comment]
I'm getting the same results that Michael reports.

**Comment by rjyounes** [comment]
Closing based on previous discussions.
