### ISSUE TITLE
Ontology Versioning (Proposal from Ted Hills)

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#128]
Hello All,
 
Yesterday Dan and I discussed the management of ontology versioning and modules. We both have multi-module ontologies to manage at MS, and they have to be released for use throughout the organization. Dan and I pretty quickly moved to the same position on how versionIRI properties should be managed. I wrote the attached 3-page paper to capture those thoughts. I also added some thoughts about filenames, which we touched on in our discussion but didn’t dig into too much.
 
This is a significant departure from how gist is managed, so I’m very interested in your thoughts and feedback. This is what I’m going to institute for the Morgan Stanley Research Ontology, so I’ll get a real chance to test this. After sufficient testing and vetting, I will put it forward as the way to manage all of the ontologies in the mscore ecosystem. I believe that gist would benefit from this approach, too.
 
Thanks for your time,
Ted Hills
+1 908 200 8713
thills@acm.org
https://www.linkedin.com/in/theodorehills/
[OntologyVersioning.docx](https://github.com/semanticarts/gist/files/3962071/OntologyVersioning.docx)

**Comment by marksem** [comment]
I gave the doc. a read.  A few comments:

1. 
> In import statements, specify the ontology IRI and not the versionIRI of any ontology being imported.

I strongly disagree with this approach.  It brings in unknown axioms. 

2. 
> It is recommended that the owl:versionInfo annotation property not be used, as its text is not functional

I disagree with this. For the same reason that we have URIs _plus_ rdfs:labels for most things, I believe we should use versionIRIs _plus_ owl:versionInfo.  The textual version is for display of the version, e.g., in applications.

3.
> By leaving version numbers out of import statements, the user who controls the environment in which the ontology is used may select any version of an imported ontology that he deems appropriate

In all versions of triples stores I've used (admittedly not all), the user already has this control of which ontologies get loaded into the TS.  I have not seen cases where the import statements proscribe and limit what ontologies are loaded into the TS. Therefore, this does not bolster an argument for leaving version numbers out of import statements.

**Comment by uscholdm** [comment]
I strongly agree with @marksem on all of these points.

**Comment by uscholdm** [comment]
> It is recommended that the version of the ontology that is to be loaded into a triple store for use with ABox data be loaded into a named graph whose name is the ontology’s IRI.

This unnecessarily limits a named graph to contain exactly one file.  We like to load all of the gist files in one named graph - the set of axiom transitively imported are collective viewed as gist.

**Comment by uscholdm** [comment]
> During development, ontologies should not contain versionIRIs.
This is what we currently do with gist. The development IRIs are suffixed with X.x.x

**Comment by uscholdm** [comment]
> It is rare that an ontology user would want to import less than an entire (coherent group of) ontology (modules).
I disagree.  Gist was divided into modules to allow this.  I usually import it in toto, but not always.  I don't want to be forced to.

**Comment by DougalW** [comment]
I''m currently refactoring our Accounting Ontology to fit within GIST, and have found that versioning and modularity within GIST are invaluable. In the future our platform will pervasively manage ontologies deployed to client virtual private clouds. The proposed approach just would not work for our workflows and requirements.

**Comment by rjyounes** [comment]
I completely agree with Mark and Michael, and would add to the issue of imported IRIs:

On the semantic web (which, we should remind ourselves, is where OWL was born), the user doesn’t control the environment – i.e., what he receives when he makes a request is controlled by the server, where the unversioned IRI redirects to the latest version.  Only by importing a specific version of an ontology can he control what he gets and this prevent possible incompatibilities between the importing and imported ontologies. (Sorry for the use of the politically-incorrect masculine pronoun, I still like to follow the English grammar spec). In this case the OWL spec is flat-out wrong to require that imported IRIs be unversioned, because this is incompatible with the user having control over what he requests. Therefore, I think gist is correct to violate the letter of the spec.

**Comment by rjyounes** [comment]
Attaching Ted's proposal.

[OntologyVersioning.docx](https://github.com/semanticarts/gist/files/4678035/OntologyVersioning.docx)

**Comment by marksem** [comment]
#292, demodularized gist. Is this issue still applicable in any way?

**Comment by rjyounes** [comment]
Let's leave this open in case there are worthwhile suggestions for versioning, even though the module management issue is now moot.

**Comment by uscholdm** [comment]
Given that any remaining issue is much different than this original one, perhaps better to close this one and refer back to it in  a new clearly articulated issue.  It is not clear what the new issue is. We already agree on semantic versioning.

**Comment by rjyounes** [comment]
@uscholdm If there is a new issue, then we can adopt your suggestion. Given that you don't know what the new issue would be, shall we just close this one? I haven't read the doc myself.

**Comment by uscholdm** [comment]
Lets see if @tedhills thinks there remains an issue.  He initially brought this up. There was disagreement on some of his suggestions, but there may be things we still want to look into.

**Comment by tedhills** [comment]
Thanks, Michael, for the mention. I think I would hold out on some points, but it's not that important to me. I bow to the wisdom of the crowd. :-)

**Comment by uscholdm** [comment]
The concern is whether you go one way at MS Research, and we go another way, which may be a different approach used by our other work at MS.  The difference between the approaches may matter less than not being aligned.

**Comment by tedhills** [comment]
I am quite willing to follow the approach you all settle on. But did I read correctly, by the way, that gist is being de-modularized? My head is whirling on that one. If true, the version IRI management becomes substantially easier.

**Comment by marksem** [comment]
@tedhills , yes. See #292

**Comment by uscholdm** [comment]
@tedhills We devoted a whole gist council meeting to this question. There very little discussion and no real objections -- to our surprise.  All yays and no nays.

**Comment by rjyounes** [comment]
Closing this issue because:
1. Strong internal disagreement with the proposal
2. gist is no longer modular
3. New versioning work being done at a client which can inform this issue.
