### ISSUE TITLE
Use .rdf or .ttl file extensions, not .owl

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#129]
TopBraid Composer will not load a .owl file.  A reasonable convention is:
- *.rdf for rdf-xml syntax
- *.ttl for turtel syntax

This is a trivial change, just rename all the files and update the catalog file

**Comment by rjyounes** [comment]
I would argue that it's preferable to run a postprocessor to change the extensions to rdf. As we discussed, I don't think we should change our preferred practice to conform to the quirks of specific tools.

**Comment by uscholdm** [comment]
OK - how about a tool-independent justification. It is convenient to be able to look at the extension and know what the syntax is w/o opening up the file.

**Comment by rjyounes** [comment]
rdf doesn't tell you what the format is, does it? Wouldn't it have to be "rdfxml" to do that? Is there a source that indicates an rdf extension means RDF/XML?

BTW Protege exports a file with .owl extension when you save as RDF/XML, if that makes any difference.

**Comment by Jamie-SA** [comment]
**Regarding .rdf** see [application/rdf+xml Media Type Registration](https://tools.ietf.org/html/rfc3870)

The media type is "application/rdf+xml" and the file extension is ".rdf".

**However** according to [this post](https://github.com/G-Node/neuro-ontology/issues/2) there is a difference between RDF/XML and OWL/XML.

Here is the definition of [OWL XML serialization](https://www.w3.org/TR/owl2-xml-serialization/).

> The Internet Media Type / MIME Type for the OWL XML Serialization is application/owl+xml.
> It is recommended that OWL XML Serialization files have the extension .owx (all lowercase) on all platforms. 

[This post](answers.semanticweb.com/questions/11286/owlxml-vs-rdfxml-serialization) looks interesting but isn't responding currently.

###  Summary
The evidence seems to support using .rdf if it is rdf/xml.
I couldn't find anything official about .owl for ontologies, it is used for other types of files.

**Comment by rjyounes** [comment]
OK, that answers that concern. I still have a preference for .owl because it distinguishes it from non-OWL RDF.

**Comment by uscholdm** [comment]
I think of "rdf" is short for rdf/xml.

**Comment by rjyounes** [comment]
We are switching to Turtle, so the extension will be .ttl.

Will be handled in #319
