### ISSUE TITLE
Expand or remove range on fromAgent and toAgent

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#131]
Current range is union of Person, Organization, and Address(?).

We may want to say a DigitalAgent or a Network sends or receives a message. Currently the range prevents us from doing so.

And an address doesn't _send_ a message, though a message may be sent _from_ (not _by_) an address.

Related to #132.

**Comment by uscholdm** [comment]
I agree, the range is too narrow. I'm not optimistic that anyone can confidently expand the range in a way that will not expand again for similar reasons. Can't think of everything.

**Comment by rjyounes** [comment]
I agree. So the proposal should be to remove it.

**Comment by uscholdm** [comment]
I am in favor of creating a class which means (roughly): "That which has the capacity to do something." It includes organizations, people, computer programs mainly. 

The obvious name for the class would be 'Agent', but that is a very ambiguous term and Dave has often rejected it on this count. There used to be a gist:Agent class (I think) which was the union of Person, Organization and ComputerProgram. Dave took it out for the same reason it took out SocialBeing, its an abstraction of more concrete things.

**Comment by rjyounes** [comment]
Yes, that ties in nicely with #132 - though as you state there ComputerProgram isn't the right term, it should be SoftwareAgent or the like. The definition should be refined to exclude objects that do something - ovens that cook, for example. 

I would not make this a closed class (i.e., with equivalent class union of X, Y, Z, or disjoint union) for the reasons we've stated about not being able to foresee all types of agents.

Is the point about abstraction that we would never instantiate an Agent, only one of its concrete subclasses? I.e., we would never say "there is this thing that has the capacity to do something, but other than that I don't know what it is."  Essentially we're creating the class as a convenience for stating domains, ranges, or restrictions.  That's an interesting criterion to distinguish when to create a named class vs using an anonymous class. On the other hand, if you find that anonymous class appearing in lots of different places, does that call for a named class?

**Comment by uscholdm** [comment]
> exclude objects that do something - ovens that cook, for example.

Yes, as well as rivers that flow.  The 'things that are done' need to be intended, though not necessarily by the doing entity.  E.g. a smart door lock is run by a program that opens/closes the latch. That is an lock doing the task in accordance with the intention of the programmer.

**Comment by rjyounes** [comment]
Is there a distinction between the smart lock and a web or other application, then? Your remark suggests that there is no such thing as a digital/software agent (or if there is we have entered the singularity).

**Comment by uscholdm** [comment]
> Your remark suggests that there is no such thing as a digital/software agent

I did not mean to suggest that. In the case of the lock, I suppose its the software running (digital agent) that does something by issuing the  'command' that results in the lock closing/opening.   Robotics folk have names for these things, usually ending in 'tor'.   E.g. https://en.wikipedia.org/wiki/Robot_end_effector

Its loose usage in English whether one thinks of the motor-controlled lock as the doer/agent or the program.

**Comment by rjyounes** [comment]
We do have other abstractions of more concrete things in gist: TemporalRelation is one that I think would never be instantiated. As I come across many cases that could be Person or Organization, I have to think there's a class lurking there. And now that I think about it, one could well say "Semantic Arts has a client named Louis Vitton, but I don't know whether that's a person or a company."

**Comment by uscholdm** [comment]
We had a concept for Person or Organization. It was called SocialBeing but Dave did not like it for years and eventually tossed it. Everywhere it occurred (in domains and ranges and such) it now has a blank node [Person or Organization]

**Comment by rjyounes** [comment]
Dave has agreed to change to general to/from predicates. On 2/9/20 he wrote: In general I like economizing on properties.  I’m try to recall what ambiguity we were trying to prevent when we adopted those.  I’ll think on it tonight.  If I don’t come up with anything go ahead.

**Comment by rjyounes** [comment]
Consider in relation to #133 and #134.

**Comment by rjyounes** [comment]
Close as partial duplicate of #321
