### ISSUE TITLE
Add Agent and SoftwareAgent classes

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#132]
Add a SoftwareAgent class for chatbots, interactive websites, mobile apps, and other software systems that people can interact with.

Add an Agent class, subclassed by Person, Organization, and SoftwareAgent.

Related to #131.

**Comment by uscholdm** [comment]
There used to be a class called something like ComputerProgram that was meant to cover this case.  That was problemantic because a program is a set of instructions manifest as content, usually text. Only when it is running on a computer can it 'do' anything.  MorganStanley core has something called SoftwareAgent, which is closer to what we want.

**Comment by rjyounes** [comment]
I agree that ComputerProgram is not what we want.

**Comment by rjyounes** [comment]
I just noticed this definition of gist:Message: "A specific instance of content sent from an Organization, Person, or Application to at least one other Organization, Person, or Application."

It looks like there was an Application class at some point.

**Comment by uscholdm** [comment]
Yes, it should be SoftwareAgent (I'm thinking that is still a class in gist).

**Comment by rjyounes** [comment]
There is no such class, nor Application, in gist 9.

**Comment by rjyounes** [comment]
There are two senses of SoftwareAgent. One is the more general meaning of SoftwareApplication, which performs actions and interacts with humans. The other is the narrower sense of chatbot, digital agent, etc. This is the Wikipedia definition. So I would revise my proposal as follows:

Add Agent class, disjoint union of Person, Organization, SoftwareApplication.
Add SoftwareAgent subclass of SoftwareApplication, if we want it, otherwise leave to client ontologies.

**Comment by uscholdm** [comment]
I Presume that by "This is the Wikipedia" you mean "The latter is the Wikipedia"

**Comment by rjyounes** [comment]
Correct. I've updated the comment accordingly.

**Comment by rjyounes** [comment]
Consider with #131

**Comment by rjyounes** [comment]
Would Organization be a subclass of Agent? FIBO defines AutonomousAgent as: "An autonomous entity that can adapt to and interact with its environment." Depending on exactly what that means, it could encompass organizations.

On the other hand, organizations can act, but perhaps it's more accurate to say that people act on behalf of organizations, which would mean the organization itself does not act and therefore is not an agent.

FIBO's definition of Organization is "a unique framework of authority within which a person or persons act, or are designated to act, towards some purpose, such as to meet a need or pursue collective goals on a continuing basis". This reinforces the idea that organizations are not themselves agents, and in fact in FIBO it is not a subclass of Agent.

**Comment by uscholdm** [comment]
@rjyounes said:
> Would Organization be a subclass of Agent? 

Probably not, if you include special purpose vehicles which are like companies but exist for technical reasons and they don't do anything per se, other than be a structure for passing money through or some such.  Edge case.

> FIBO's definition of Organization ... reinforces the idea that organizations are not themselves agents, and in fact in FIBO it is not a subclass of Agent.

True, but its a matter of linguistic convenience what it is that has intentions or does things. Facebook bought Instagram is not technically true, any more than an asteroid 'wants' to keep going in a singluar direction by laws of physics. It acts as if it wants to do that. THe people who run FB made a purchasing decision and excecuted it.

**Comment by rjyounes** [comment]
I now think the general concept of Agent is too fraught with complications to define in gist. Different ontologies will need slightly different meanings - e.g., one might include Organization in Agent, another might not - which suggests that it should be left to client ontologies to define.

Since Dave is working on a gist software ontology, which more fully describes software and related concepts, we can leave it out of gist core.

**Comment by uscholdm** [comment]
Agreed - good call.
