### ISSUE TITLE
Expand definition of giver and getter

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#133]
The definition reads: "The active party, the one with the obligation or the one initiating the transfer."

I am using these predicates to point from an Employment resource to the employer and employee, which doesn't fit this definition. Either it's the wrong use of the predicates, or the definition needs to be expanded. Personally, it strikes me as a good use of these predicates. Can be generally useful to apply to complex relationship resources.

**Comment by DanCarey404** [comment]
The properties were constructed to relate to Agreements.  Employment is certainly a subclass of TemporalRelation.  It might be argued that it is also a subclass of Agreement.  But I would model it as a TemporalRelation :governedBy some EmploymentAgreement, since the agreement might be amended over the course of one's employment)

**Comment by rjyounes** [comment]
I've modeled it as a subclass of both TemporalRelation and Agreement (or maybe Contract, I'm not sure if employment relationships are legally enforceable or not). I see your point, that makes Employment a valid use case. We still need to clean up the definitions of the predicates though. In an Employment, neither party is more active than the other; both incur an obligation; and there is no transfer.

**Comment by DanCarey404** [comment]
One cannot accept employment without it being offered.  The employer initiates the transfer.

**Comment by rjyounes** [comment]
I realize that, but the offer is an event. I'm not interested in that.

**Comment by rjyounes** [comment]
I'm also not interested in the contractual agreement per se, only the state of a person being an employee of a legal entity. I do like your distinction between Employment and EmploymentAgreement, but I think I would not model the latter because it doesn't concern me.

**Comment by rjyounes** [comment]
I don't see how it's a transfer. Transfer of what?

**Comment by DanCarey404** [comment]
Transfer of the employment agreement, or from a different angle transfer of the employment (which makes them the giver).

**Comment by rjyounes** [comment]
Maybe there's a technical definition of "transfer" I'm not familiar with. "Transfer" in ordinary language means moving something or someone from one place, state, relationships, etc. to another. It's not accurate to say the employment agreement moves from the employer to the employee.

**Comment by DanCarey404** [comment]
But I can see the idea of making Employment a subclass of both TemporalRelation and Agreement.  But I fear you might wind up binding yourself in the future.  If you're not really interested in the contractual agreement per se, then I would again suggest two new properties and not using :giver and :getter.

**Comment by DanCarey404** [comment]
_Now_ I see the point of the original statement.  Introducing the concept of _transfer_ may be misleading.

**Comment by rjyounes** [comment]
Do you mean that if down the road I need to model the Agreement separate from the Employment, I will want giver and getter for the Agreement, and therefore should use two different predicates for the Employment?  That makes sense.

**Comment by rjyounes** [comment]
A smaller point: strictly in terms of the wording of the definitions, they both need to be rewritten because they refer to the definition of the superproperty, hasParty. The definition of getter is simply "The recipient," which is unclear unless you are familiar with the definition of hasParty. I think, in general, the definition of every term should be fully comprehensible on its own.

**Comment by DanCarey404** [comment]
I just opened issue #134 addressing that very issue.

**Comment by rjyounes** [comment]
I now understand these predicates are meant to relate strictly to Agreements, and the definitional issues are covered by #134, so closing this issue.

**Comment by uscholdm** [comment]
I like Rebecca's use of giver/getter for Employment, creative and I think accurate. I never thought of it.

**Comment by uscholdm** [comment]
I think Employment should be a TemporalRelation, which is separate from any agreement. It's a bit sleight of hand to say its both. Might get away with it, but it seems dubious to me.

**Comment by uscholdm** [comment]
Actually, there are two things going on with offers. One is a promise, like any product for offer. The other is the event of making that promise (giving a prospective employee the offer letter). The event part is not very interesting.

**Comment by rjyounes** [comment]
Yes, I like Dan's idea as well. Now here's another one: Engagement. Is an Engagement between two parties the same as the contract, or is it a relationship governed by a contract? For example, one of my projects was renegotiated with the client midway through and a new SOW signed. Is that a new Engagement (Engagement = Contract), or the same Engagement with a new Contract (Engagement != Contract)?

**Comment by rjyounes** [comment]
Dave wrote on 2/9/20: "Meanwhile on Giver / Getter I’d prefer to get rid of them.  They were meant to be a generalization of buyer and seller ( to include more kinds of contracts) but it was never very clear.  In gist acct they will be based on the specific obligations.  To me it’s a bit of a stretch to call that from and to.  ( giver and getter was already a stretch)"

So we will need to figure out what specific predicates we need to replace giver/getter.

**Comment by rjyounes** [comment]
Michael: have a general hasParticipant.

One proposal: Deprecate hasParty, giver, and getter. Define hasParticipant. Subproperties in client ontologies would be, e.g., lender and borrower. Too specific to include in an upper ontology.

Rebecca: participants should be agents, not things. E.g., doesn't include the package that is being sent or the house it is being sent to.
Boris: agrees. 
Michael: do we want another property for the objects involved in an event.
Jamie: In an electronic message, the sender and recipient are participants, but there's a location, etc.

Rebecca: do we want high level properties in gist to cover all senses of giving and getting?
Jamie: The relationships are really bidirectional. E.g., in a loan, each party acquires an obligation. 
Michael: In an agreement, there are two obligations. Each obligation has a giver and getter.
Michael: we should have directionality on obligation. Either use giver and getter or different terms. 

Michael: in a loan, there are two parties and two obligations. On the loan itself there is no giver and getter; they are on the obligations. 
Rebecca: hasGiver and hasGetter. 
Cheryl: there is a giver and a getter.
Peter: not always related to an obligation. Can't infer that there's a contract.
Rebecca: we have fromAgent and toAgent for giver and getter.
Michael: obligation has a restriction that it must have fromAgent and toAgent.
Rebecca: also not verbs. 
Michael: hasRecipient, ...
Jamie: hasProvider?
Michael: Let's use fromAgent and toAgent.

DECISION: 
- Deprecate giver and getter
- Deprecate hasParty and add hasParticipant. 
- fromAgent and toAgent become subproperties of hasParticipant.
- hasParticipant applies to various things like events, obligations etc.

**Comment by uscholdm** [comment]
UPDATED DECISION:
- Replace hasParty with hasParticipant with range of Person or Organization
- hasParticipate applies to various things includingt events, agreements, obligations
- Deprecate hasParty
- Do NOT have a broader property for other objects involved in events or agreements.
- Replace getter with toAgent, deprecating the former 
- Replace giver with fromAgent, deprecating the former
- toAgent and fromAgent are subproperties of hasParticipant
- Update skos:definitions for affected terms
Synch with gistAccounting

**Comment by rjyounes** [comment]
Needs more review based on comments on PR #404

**Comment by rjyounes** [comment]
Michael created a PR, but it got closed w/o implementation.  (ref. #404  )

Summary:   most of group: keep hasParty with its range of Person or Org, and make it a subprop of new hasParticipant. property.     to follow up.

**Comment by rjyounes** [comment]
**FINAL DECISION:**

- Replace names `giver` and `getter` with `hasGiver` and `hasGetter`, respectively.
- Deprecate `giver` and `getter`.
- `hasGiver` and `hasGetter` are not sub-properties of `hasParty`` (as were `giver` and `getter`.
- Add property `hasParticipant`:
  - No domain or range.
  - Has sub-properties: `hasGiver`, `hasGetter`, `hasParty`, `fromAgent`, `toAgent`.
- Add annotations on `fromAgent` and `hasParty`.

**Comment by uscholdm** [comment]
@rjyounes I Presume you copied this right out of the .md release notes file?  They should be identical.

**Comment by rjyounes** [comment]
Yes. I found the decision changes confusing so wanted to clarify the final decision here.

**Comment by uscholdm** [comment]
I made some more changes, responding to your suggestions.  If you approve, then we should swap those into here, replacing your comment above.
