### ISSUE TITLE
Refactor :hasParty, :giver, :getter

### ISSUE THREAD

**Issue by DanCarey404** [semanticarts/gist#134]
The definition of _:hasParty_ specifically mentions that it applies to an agreement, but there is no domain on the property.  I suggest adding _:Agreement_ as a domain.
Absent the context of being subproperties of _:hasParty_, the names of _:giver_ and _:getter_ are confusing.  For example, one might think that it makes sense to say **:_Joe :giver :_Agreement_x** .  I suggest refactoring the properties to be _:hasGiver_ and _:hasGetter_ .

**Comment by rjyounes** [comment]
+1. I have proposed the convention that object properties always start with verbs. 

As I point out in #133, the definitions are also inadequate because they cannot be understood without knowing the definition of the superproperty, especially in the case of getter which is simply defined as "the recipient."

**Comment by uscholdm** [comment]
I think this is likley to backfire. Before long, if not already, we will want to talk to parties of non-agreements.  People talk abouit 'interested parties', for example (just off the top of my head). Broader ranges are more future-proof, and should only be used when there is a logical necessity involved.

**Comment by uscholdm** [comment]
I agree to change names to hasGiver(Getter). Perhaps this should be done in one swell foop, a bunch of URI changes instead of peacemeal.

M

**Comment by uscholdm** [comment]
Back to overly narrow domains. In the first ontology I built for SA, I created a more general version of getter (which I called _getter to make the link clear).  The definition was/is: "Generic recipient in situations, events, activities, agreements that have one or more participants giving and one or more receiving. "  When you goto the doctor, you are the getter for that event, it is not an agreement. 
See: S:\ClientsAndPartners\Sentara\_Enterprise_Ontology\EntOnt2\SHEO1.1\OWL Files

There is an ontology called sheoUpper which has a lot of stuff independent from healthcare. I'd call it sheoGeneric these days. It has a property that is higher than party called participant.

**Comment by rjyounes** [comment]
I've often though we need general to and from predicates as Michael is describing. This would also encompass fromAgent and toAgent; see #131. I have a need to model engagements and opportunities (I.e., sales pursuits) with a common superclass, as they share important properties in the particular knowledge domain. An engagement is an agreement, while an opportunity is not, but it would be useful and sensible to have the same predicates linking vendor and (potential) customer in both cases. (On the other hand, are the roles actually reversed in the two? In an opportunity, the vendor is the giver - he makes an offer to the client. In the engagement, would we instead say that the client is the giver? Or perhaps the engagement is non-directional, in which case we would use the superproperty hasParty.)

**Comment by rjyounes** [comment]
Regarding Michael's point on name changes taking place all at once, I agree with that as well; there are a number of corrections of this sort throughout the ontology. Definitions require a complete review and overhaul. I'm still working on the conventions doc but we should discuss it sometime soon so that we can enact some of them. I'm sure some are going to generate a lot of controversy.

**Comment by DanCarey404** [comment]
I concur about the danger of too-narrow properties.  But as a business-oriented ontology, I think it is proper for gist to have some that are tailored to talking about agreements.  In msCore, we have the properties _mscore:hasParticipant_ and _mscore:participatesIn_.  These are more generic (but also not specifically related in any way to the concept of "party").
Would something like this address the concerns raised here?
![image](https://user-images.githubusercontent.com/4614948/72992432-bbfb1c00-3dc1-11ea-9587-b06fc9e0ddac.png)

**Comment by uscholdm** [comment]
Yes. I am a fan of hasParticipant - I reinvented/borrowed it from DOLCE years ago for sheoGeneric (which I mentioned in a prior comment).

**Comment by rjyounes** [comment]
From Dave: Meanwhile on Giver / Getter I’d prefer to get rid of them.  They were meant to be a generalization of butter and seller ( to include more kinds of contracts) but it was never very clear.  In gist acct they will be based on the specific obligations.  To me it’s a bit of a stretch to call that from and to.  ( giver and getter was already a stretch)

**Comment by uscholdm** [comment]
I think giver and getter were mainly for obligations, which could be called obligor and obligee.  All obligations have direction so giver/getter made sense. Not all agreements do have a from or a to direction.  If we get rid of giver/getter, had anyone proposed what to use to point to the obligee(or)s in an obligation?

**Comment by uscholdm** [comment]
DECISION: 
- Replace hasParty with hasParticipant
- Replace getter with toAgent, 
- Replace giver with fromAgent, 
- toAgent and fromAgent are subproperties of hasParticipant
- Update skos:definitions
Synch with gistAccounting

**Comment by uscholdm** [comment]
DECISION: this duplicates issue  #133
