### ISSUE TITLE
Why don't we use SKOS instead of gist Categories?

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#135]
Opening this issue to start a discussion.

**Comment by uscholdm** [comment]
SKOS did not exist at the time. So the better question is whether we should use skos:Concept instead of gist:Category.   I think the former is infinitely broad. Mathematicians say that there  different kind of infinity, and some are 'greater than' others. So while there are also indefinitely many uses for gist:Category, I'd say its narrower than skos:Concept.

**Comment by DougalW** [comment]
I strongly favour continuing with GIST:Category. I use it extensively in our ontology and it's a very natural fit for categorisation in general, and small taxonomic distinctions specifically.

**Comment by uscholdm** [comment]
> I strongly favour continuing with GIST:Category. I use it extensively in our ontology and it's a very natural fit for categorisation in general, and small taxonomic distinctions specifically.

Nobody seem to want to remove gist:Category.  Ontologicaly, it would seem that gist:Category is a subclass of skos:Concept, but that might bring a lot of baggage from skos itself. I propose we stay thecurrent course.

**Comment by rjyounes** [comment]
No one has answered the question, which is why gist invented its own category structure rather than using SKOS, and is distinct from the issue of keeping things as is to avoid disruption. I've reworded the title of the issue slightly to clarify that. Note that agreeing that new ontologies should use SKOS doesn't entail removing the current terms.

However, if we use gist:Category, I would prefer that, like SKOS, we define a superproperty of gist:hasSuperCategory which is transitive. (The ideal naming would be gist:hasSuperCategory as the transitive superproperty, and gist:hasDirectSuperCategory as the intransitive subproperty, but that would change the entailments in the current use of gist:hasSuperCategory, so not advisable.)

**Comment by rjyounes** [comment]
Offhand I don't see any undesirable entailments resulting from making gist:Category a subclass of skos:Concept; there is no requirement that the latter belong to a skos:ConceptScheme, for example. This would also allow us to use the SKOS predicates.

Frankly, I'm more interested in having a transitive predicate than I am in using SKOS

**Comment by rjyounes** [comment]
I like the use of the British spelling “favour”!

**Comment by uscholdm** [comment]
> However, if we use gist:Category, I would prefer that, like SKOS, we define a superproperty of gist:hasSuperCategory which is transitive. 

This would be re-creating skos braoder and broaderTransitive.  At Platts, we already use skos:broader. So maybe Category subclass of skos:Concept not such a bad idea.  

New proposal:
1. make gist:Category a subclass of skos:Concept
1. remove gist:hasSuper(Sub)Category and use skos:braoder(Transitive) instead.

Are there any good reasons to not do this?

**Comment by rjyounes** [comment]
I like this proposal, adding that we could also use skos:broader/narrower for the direct relationships.

**Comment by Jamie-SA** [comment]
I thought there have been several comments that the direction-ality of skos:broader/narrower is not clear and is confusing.

**Comment by uscholdm** [comment]
That is true. Fortunately, the label make is clear: "has broader". That makes it not as bad.

**Comment by rjyounes** [comment]
@Jamie-SA Yes, as Michael says, you're right, but in this case I believe it to be overridden by the functionality and the widespread use of the ontology. We are already moving in the direction of replacing RDFS annotations with SKOS annotations, so adopting these predicates represents some consistency in that regard.

**Comment by rjyounes** [comment]
Relates to broader issue of #161

**Comment by marksem** [comment]
I don't like gist:Category sub skos:Concept, b/c to me skos:Concept is almost like owl:Thing.   Isn't gist:Person also concept?  Wouldn't every class in gist also be a skos:Concept?   skos: is good for thesauri, but imo NOT for "good" ontologies that are NOT about "terms,"

**Comment by uscholdm** [comment]
> Wouldn't every class in gist also be a skos:Concept?

Conceptually, yes, but we generally would not want it to be both ways in the owl/rdf.   This is the flip side of the question: "Couldn 't every instance of gist:Category" be an owl:Class? The answer is, yes it could.  Our usual guideline for this is to make it a class only if there are specific things that you will be saying about it.

> skos: is good for thesauri, but imo NOT for "good" ontologies that are NOT about "terms,"

Exactly. That is why I'm proposing to use it for JUST the subclasses of gist:Category - which, because we say nothing about each category, they live in term world.


> Isn't gist:Person also [a] [skos:C]oncept?

If a folksonomy, one might create a tag for Person. In that context it would be a skos:Concept. If gist, we'd have that as an instance of gist:Category.

**Comment by rjyounes** [comment]
I am now convinced of the difference, so closing this issue.
