### ISSUE TITLE
Remove three specific invalid restrictions on gist:Person

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#136]
Has a name: not always, e.g., newborn before they are named.

Identified by some id: not always.

has birthdate: not necessarily (this gets us into the middle of a huge religious-social-political debate).

**Comment by uscholdm** [comment]
When life begins is debated. What the date of birth is, is legally unambiguous and well accepted: when the baby comes out of the womb.

**Comment by uscholdm** [comment]
While not untrue, the definition is circular.  It would hold for every thing from toads to toadstools and thus sheds no light at all on what a person is.

**Comment by rjyounes** [comment]
That's exactly what I mean. For those who believe human life begins before birth, there is no birthdate. 

There is already circularity in the definition, since part of it includes offspring of some gist:Person. That could well designate dogs, then (even toads, which have birthdates although they are unknown).

Granted the definition is less rich than it would otherwise be, but we can't just make stuff up that's not true to avoid vacuous definitions. If it comes down to it, there must be some identifying genetic or anatomical structure that would uniquely identify humans. Even though we don't know it in all cases - just as we may not know weight or volume even though they clearly exist --  it would still be identifying data.

**Comment by rjyounes** [comment]
Jamie: hard to reference something that doesn't have any identifying attributes.

Rebecca: if in some business contexts (e.g., HR) there is always a name, birthdate, and ID, then that should be expressed in SHACL. 

Mark: birthdate comes from `LivingThing`, so the restriction would have to be removed from `LivingThing`.

Boris: `hasBirthdDate` would still have `LivingThing` as domain.

Mark: Currently `hasBirthDate` is a subproperty of `actualStart`. If we push it up to be a direct subproperty of `start`, then we don't have to remove the`hasBirthDate` restriction from `Person`.

PROPOSAL:
- Make `hasBirthDate` a direct subproperty of `start`
- Remove restriction on `name` and `identifiedBy` for `Person`

**Comment by rjyounes** [comment]
The `gist:identifedBy` restriction has already been removed from `gist:Person` in prior work.

**Comment by rjyounes** [comment]
These changes were reverted due to postponement of the next major release till May. The changes will be restored for that release.
