### ISSUE TITLE
Remove birthdate restriction from LivingThing

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#137]
Trees don't have birthdates.

**Comment by uscholdm** [comment]
Agreed. They do come into existence over a period of time, but there is no accepted way to nail that down, and is unlikely to ever be nailed down to a 24 hour interval.

**Comment by sa-bpelakh** [comment]
OPTIONS:
* LivingThing equivalent (PhysicallyIdentifiableItem AND (hasBirthDate OR offspringOf(LivingThing))
* Simplify to 'subClassOf PhysicallyIdentifiableItem', document intent of class in skos:definition, let domain/range of properties handle inference of individuals into class.

**Comment by rjyounes** [comment]
The birthdate issue was resolved in the solution to #136. The issues under OPTIONS above should be removed to another issue.
