### ISSUE TITLE
Fix definition of basisFor

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#139]
Current definition: "Reason for an event."

I may want to use this predicate in other circumstances: e.g., a training course is the basis for expertise in a particular area. 

And in fact, the inverse basedOn has a broader definition: "pointer to the thing something was derived from"  This could also use some refinement, but it does allow application to a wider range of resources.

**Comment by uscholdm** [comment]
In a prior version of gist, the definition was "Reason, law, rule, etc. behind an action or decision.".  I agree that this is not very good. I think the idea here is that something was a foundational starting point for, gave rise to, or justifies something else. 


At one point, I had a property called 'justifies' which was a subproperty of basisFor. A agreement justifies an obligation, for example.   In a sense, it is also the basis for the obligation.

This is a tricky one to nail down. More example would help.

**Comment by JonathonGist** [comment]
I agree with the comments both of you have made. Here are my definition and example; if we are not yet using skos these could simply be comments.

skos:definition
Something that is a foundation for or a starting point for something else; something that gave rise to or justifies something else. (A pointer from the source to something that was derived from it.)

skos:example
The reason, law, rule, etc. behind an action or decision. The reason for an event: the desire to create a community around the data-centric revolution/movement was the basis for initiating the Data-Centric Architecture Summit in 2018. The unabridged dictionary was the basis for the abridged dictionary. A document (encoded as a file) is the basis for the page (with its text and objects) that is extracted from that document.

**Comment by uscholdm** [comment]
Nicely done, Jonathan.  We are not yet agreed on a standard grammatical style for all our properties, but I like to emphasize that a property relates one thing to another.  A variation of your definition would be: 
"The subject is a foundation for, a starting point for, gave rise to or justifies the object. "

**Comment by JonathonGist** [comment]
Michael, I like your rewrite; I account it as replacing my definition. Excellent.

**Comment by rjyounes** [comment]
Fixed by #484.
