### ISSUE TITLE
occuredAt should be occursAt

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#14]
I want to say where an event like the SuperBowl is planned to be played at. 
gist:occurredAt is wrong because it is in the past.  I think it is good practice to have all properties be tense-neutral verbs.

Suggest change to occursAt. 

ALSO: the restriction on PhysicalEvent says (occurredAt GeoRegion) which is logically true, but using Place would be better because one could then satisfy the restriction by saying it occurred at a Stadium, which is a building or landmark, or a PhysicalEvent can occurr in a Room too.

Suggest change restriction to (occursAt gist:Place)

**Comment by mkumba** [comment]
#14 in9.0.0
