### ISSUE TITLE
Release process & capturing actual release files

### ISSUE THREAD

**Issue by Jamie-SA** [semanticarts/gist#141]
I think it might be a good idea to capture the actual release directory with the exact state of what was released. We are not currently doing that but it was previously done as a dead ended branch.

I think this would also help anyone coming to github versus the download page.

Currently, to be able to reproduce the exact output would require additional steps that would have to be performed exactly as they were done to create the release.

**Comment by rjyounes** [comment]
We've decided we don't want to store generated release packages in GitHub. Jamie will figure out ahow to restructure the files on the server to enable download of previous versions from website.

**Comment by marksem** [comment]
But note that we probably *do* want to store generated releases *somewhere*.  That may be Nexus or some other place.  github.io was mentioned also (by @pwin).

**Comment by sa-bpelakh** [comment]
DECISION: Document attaching build artifact as Zip to GitHub release.

**Comment by sa-bpelakh** [comment]
Closed in #453
