### ISSUE TITLE
gist:memberOf should have Collection as the range, not the domain

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#142]
OrdinalMember upon reasoning ends up a subclass of Collection.   Does not make sense.  The offending axiom appears to be **gist:memberOf rdfs:domain gist:Collection**

![gistBut-OrdinalMember-1](https://user-images.githubusercontent.com/34490444/72441061-048a5800-3778-11ea-9071-09ed35245d5c.png)

![gistBut-OrdinalMember-2](https://user-images.githubusercontent.com/34490444/72441076-0bb16600-3778-11ea-8d2c-5ddb5e3d4abe.png)

**Comment by uscholdm** [comment]
Should be that the RANGE is Collection, not the domain. Funny how nobody noticed all these years (unless the bug slipped in somewhere afterwards).

**Comment by rjyounes** [comment]
The correction of range of of memberOf has also been noted by Phil Blackwood via email. If that if the only problem involved here, we can rename it.

**Comment by rjyounes** [comment]
Bumping this up to the May 2020 release because it's egregious and quick to fix.

**Comment by rjyounes** [comment]
@marksem Is this the same as #243, which has already been fixed?

**Comment by rjyounes** [comment]
@marksem I've assigned this to you so you can sort it out and close it if it's already been addressed.

**Comment by marksem** [comment]
This issue was covered and closed by #243
