### ISSUE TITLE
gist 9.0.0 ControllerType issues

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#143]
Controller type has no definitions, comments nor labels, top-level concept.  
Dave indicated this was part of gist IoT was meant to be a sub type of Category, and should have label and comment.

![gistBug-controllerType](https://user-images.githubusercontent.com/34490444/72460614-221ce900-379b-11ea-8d5d-3226bf5137ce.png)

**Comment by sa-bpelakh** [comment]
OBE.

**Comment by rjyounes** [comment]
@sa-bpelakh Assuming that "OBE" in this context does not mean Order of the British Empire, could you provide a note about why this issue was closed?

**Comment by sa-bpelakh** [comment]
OBE - Overcome By Events - the deficiencies documented in this issue have been addressed by a [previous edit](https://github.com/semanticarts/gist/commit/5c3593dea822e0b3c9ab861eda1ea6d5fe70d366).

**Comment by rjyounes** [comment]
Aha - we have a label for that, now added.
