### ISSUE TITLE
Clarify definition of CoherentRatioUnit or remove the class

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#146]
Current definition: "A ratio unit whose numerator and denominator reduce to 1."

Maybe I'm just ignorant here, but this doesn't mean anything to me. We should clarify it for the general population.

**Comment by uscholdm** [comment]
Yeah, it requires more explanation and might not be technically accurate. It means that none of the units need any conversions, after simplification.  

See: http://www.eim.gr/metrology/measurement-units/si-derived-units/coherent-derived-units/ which says coherent derived units are:
> products of powers of base units. Coherent derived units are products of powers of base units that include no numerical factor other than 1.

Examples:
- meter / second:  both meter and second have conversion to base of 1
- km / killo-second has  1000 conversion for numerator, and 1000 for denominator which reduces to 1. It is equiv to meter / sec
- km/sec.   km has conversion of 1000, sec has conversion of 1, so this does not reduce to 1

**Comment by sa-bpelakh** [comment]
DECISION: add `skos:example` (see above) that clarifies meaning of definition.

**Comment by rjyounes** [comment]
This is subsumed by #534 but I'm leaving it open so we make sure to consider the specific issues addressed here.

**Comment by rjyounes** [comment]
See discussion in #331.

**Comment by stevenchalem** [comment]
On hold until major measurement changes are implemented

**Comment by uscholdm** [comment]
This should be moot, as ProductUnit and RationUnit are ambigous and likely going away.

**Comment by uscholdm** [comment]
Defer until units work has been decided.

**Comment by philblackwood** [comment]
Will be addressed in new Units of Measure (concept not needed).
