### ISSUE TITLE
Change Percentage to Percent

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#149]
Percent is used with a specific number, meaning "per hundred." For example:

```
The attorney has a win rate of over 80%.
```
Percentage is used to refer to a general relationship rather than a specific measure:

```
The attorney has won a large percentage of cases.
```

See Merriam-Webster:
Percent: https://www.merriam-webster.com/dictionary/percent
Percentage: https://www.merriam-webster.com/dictionary/percentage

**Comment by uscholdm** [comment]
Interesting, but I'm not sure how useful this is for gist. Do you have a specific proposal?

**Comment by rjyounes** [comment]
The proposal is to change the name of the class from Percentage to Percent.

**Comment by uscholdm** [comment]
We want to be consistent with other Magnitude types and common English usage.  An instance of gist:Weight, for example, has a number an a unit whose base unit is kilogram and may or may not have a conversion.  An instance of gist:Percentage has a number also, say 70 it's base unit is gist:each and it should have a conversion of .01 (a separate matter).  So I can say the magnitude 37kg is a Weight.  Your proposal is to say that the magnitude that represents the number .7 as a percentage (i.e. 70%) is an instance of a percent?  Does not sound very natural to me, but maybe it is to others. In any event it might be too minor to bother with changing gist.  I'd like to change the conversion for the unit percent to be .01, but Dave prefers to use 1 for practical reasons.

**Comment by rjyounes** [comment]
OK, point taken

**Comment by rjyounes** [comment]
OK, point taken. My mistake.
