### ISSUE TITLE
Incorporate serializer, versionizer, and bundler into ontology-toolkit

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#150]
Ontology-toolkit is built in Python so cross-platform. Will consolidate all tools into a single script.

**Comment by rjyounes** [comment]
@sa-bpelakh Please assign labels as appropriate. It doesn't fit into a project since it is not part of a gist release, but it would be nice to have an ETA on completion.

**Comment by sa-bpelakh** [comment]
Will be covered in https://github.com/semanticarts/ontology-toolkit/pull/2
