### ISSUE TITLE
Add missing labels

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#153]
Was originally part of #20, now split out as separate issue. For this issue, just add labels, based on local names, to terms with no labels.

Mark has a script to automate this.

**Comment by rjyounes** [comment]
Copying discussion and decisions from issue #20, where this issue was split off from:

Proposal (ryounes):

Proposal:

My proposal involves correspondences between local names and labels, so I begin with my proposed orthographic (as opposed to structure/content) conventions for local names:

Classes: camelcase, initial uppercase. Acronyms also camel-cased so that word boundaries are unambiguous - e.g., AmaGuideline not AMAGuideline, UriScheme not URIScheme. Alphanumeric characters only - e.g., Isbn10, not Isbn-10 or ISBN-10.

Properties: camelcase, initial lowercase, acronyms as above.

Both: non-standard abbreviations should not be used: e.g., hasUoM should be hasUnitOfMeaure.

Labels:
Classes: Initial uppercase, remainder lowercase, normalized to natural language standards - I.e., hyphens inserted, acronyms in all caps, etc. Examples: AMA guideline, ISBN-10. I prefer only initial word capitalized because title case, while technically well-defined, can introduce inconsistencies when actually implemented by different people.

Properties: same as classes, with initial lowercase. Hypothetical examples: has unit of measure, has SSN. Initial lowercase follows the convention applied to local names.

Among other advantages, these conventions facilitate automated mapping between local names and labels. E.g., "hasUoM" and label "Has Unit of Measure" cannot be automatically mapped to one another. Labels with acronyms and hyphens can be automatically mapped to local names but not the reverse, but this is a general problem.



DISCUSSION: gist review meeting 2020-01-16

Treatment of acronyms:

Michael: Have used underscore to separate acronym from next word.
Options for acronyms:

AmaGuideline
AMAGuideline
AMA_Guideline
Dan: Using lowercase local property names but uppercase property labels at MS for better display as column headers in spreadsheets

Boris: Should in this case argue for alternative labels of some sort. Could create other annotations like hasOfficialName for special-purpose labels. URI and prefLabel should not be driven by display or other concerns.

Michael: Different clients can decide to do things differently.

Votes:
Michael: 2, 3, 1
Rebecca: 1, 3, 2
Dan: 1, 2, 3
Boris: 1, 3, 2
Steve: 1, 3, 2

Decision: Option 1
Rationale:

We use underscore for infixes in instance names. Convention 3 can thus create confusion.
Unambiguous word boundaries
Exception: Keep ID - NB its defined as word in Merriam-Webster in all-caps.

Boris: Likes entire proposal.

DECISIONS

Adopt entire proposal.
We will also fix local names, but will deprecate the current term to maintain backward-compatibility. Terms to be deleted on next major release. New terms will have local names and labels as described, deprecated terms will remain untouched.
Note: when we add a term with a corrected local name and deprecate the original, if there are other terms that reference the original - e.g., as domain, range, subclass, restriction - that term will need to remain untouched until the next major release. So when we remove deprecated terms, we need to check the rest of gist and update references. A deprecated term should contain a skos:editorialNote about what's replacing it so we don't have to retrace our steps to figure out the replacement.

**Comment by DanCarey404** [comment]
I don't recall agreeing to sentence case in the labels.  And a quick search for the word "sentence" in #20 doesn't show anything.

**Comment by rjyounes** [comment]
Moving this discussion to issue #20. Please discontinue discussion here.
