### ISSUE TITLE
Generalize the properties :numerator, :denominator, :multiplier, and :multiplicand

### ISSUE THREAD

**Issue by DanCarey404** [semanticarts/gist#160]
The domains and ranges applied to the properties :numerator, :denominator, :multiplier, and :multiplicand (i.e., :RatioUnit, :ProductUnit, and :UnitOfMeasure) leave them more constrained than they perhaps ought to be.
Also, :mutliplier and :multiplicand should be inverses.

**Comment by uscholdm** [comment]
>  :mutliplier and :multiplicand should be inverses.
I don't think so. Commutativity is present, but that about argument order, not direction of the link.  This is an easy mistake to make.

**Comment by uscholdm** [comment]
Can you give example of how the domains/ranges are too constrained?  What do we potentially need that they disallow?

**Comment by uscholdm** [comment]
DECISION: 
- Create separate issue for broadening the definition of Specification (See: https://github.com/semanticarts/gist/issues/405) 
- Reconsider the other points afterwards.

**Comment by philblackwood** [comment]
When the order is important, it would be easier to remember factor1 and factor2.

**Comment by rjyounes** [comment]
From issue review meeting 2021-07-22:

When would the distinction between `multiplier` and `multiplicand` be significant?

Why are they limited to `ProductUnit`s?

Similarly, why are `numerator` and `denominator` limited to units of measure?

Deferring discussion for feedback from @uscholdm.

**Comment by rjyounes** [comment]
`multiplier` and `multiplicand` are not inverses, as @uscholdm points out. Both predicates relate one of the multipliers to the product, not to one another. It's analogous to the relationship between `fromAgent` and `toAgent`.

**Comment by uscholdm** [comment]
> When would the distinction between `multiplier` and `multiplicand` be significant?

I don't know if it would ever matter, I presume this is just borrowed from mathematics which uses these (albeit rather obscure) terms. Factor1 and Factor2 would might be easier as Phil suggests. If we wanted to be analy consistently, we would use divndent and divisor rather than numerator and denominator, but lets forget that bad idea.

> Why are they limited to `ProductUnit`s?
Because they only make sense when you multiply two units which is what a ProductUnit is.

MORE IMPORTANTLY: Having spent untold hours painstakingly using multiplicand/multiplier/numerator/denominator to create many dozens of units, so far it has never paid any dividends. (so to speak).

**Comment by uscholdm** [comment]
> `multiplier` and `multiplicand` are not inverses, as @uscholdm points out. Both predicates relate one of the multipliers to the product, not to one another. It's analogous to the relationship between `fromAgent` and `toAgent`.

Excellent analogy

**Comment by rjyounes** [comment]
We have a client who is using numerators and denominators for ordinary fractions, and has to define them because the gist predicates are overly narrow.

**Comment by uscholdm** [comment]
> We have a client who is using numerators and denominators for ordinary fractions, and has to define them because the gist predicates are overly narrow.

I see..So relaxing the domain/range makes sense. You could add domain(range)Incldes annotations.   

We made formulas for one of our cients (@Boris do you recall whether we used numerator/denominator for that)

**Comment by rjyounes** [comment]
Boris: `numerator` and `denominator` are needed for complex units of measure. `owl:rational` can be used in other cases.

DECISION: Remove domain and range from all four predicates.
