### ISSUE TITLE
Remove Visio files, pngs, and PDFs since out of date

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#164]
Does this also apply to the PDFs and PNGs in the Documentation directory?

**Comment by sa-bpelakh** [comment]
@rjyounes I don't know how many users looked at the giant PDF rather than loading into Protege and poking around. Technically we have embedded docs, though logical grouping and smart layout is not inherent.

**Comment by rjyounes** [comment]
Need to remove.
