### ISSUE TITLE
Change XSD datatypes in definition of TimeInstant

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#166]
The relevant fragment of the definition of gist:TimeInstant is:

```
	<owl:Class rdf:about="&gist;TimeInstant">
		<rdfs:subClassOf>
			<owl:Restriction>
				<owl:onProperty rdf:resource="&gist;epoch"/>
				<owl:someValuesFrom rdf:resource="&xs;double"/>
			</owl:Restriction>
		</rdfs:subClassOf>
		<rdfs:subClassOf>
			<owl:Restriction>
				<owl:onProperty rdf:resource="&gist;hasPrecision"/>
				<owl:someValuesFrom rdf:resource="&gist;Duration"/>
			</owl:Restriction>
		</rdfs:subClassOf>
		<rdfs:subClassOf>
			<owl:Restriction>
				<owl:onProperty rdf:resource="&gist;localDate"/>
				<owl:someValuesFrom rdf:resource="&xs;string"/>
			</owl:Restriction>
		</rdfs:subClassOf>
		<rdfs:subClassOf>
			<owl:Restriction>
				<owl:onProperty rdf:resource="&gist;localDateTime"/>
				<owl:someValuesFrom rdf:resource="&xs;dateTime"/>
			</owl:Restriction>
		</rdfs:subClassOf>
		<rdfs:subClassOf>
			<owl:Restriction>
				<owl:onProperty rdf:resource="&gist;localTime"/>
				<owl:someValuesFrom rdf:resource="&xs;string"/>
			</owl:Restriction>
		</rdfs:subClassOf>
		<rdfs:subClassOf>
			<owl:Restriction>
				<owl:onProperty rdf:resource="&gist;universalDate"/>
				<owl:someValuesFrom rdf:resource="&xs;string"/>
			</owl:Restriction>
		</rdfs:subClassOf>
		<rdfs:subClassOf>
			<owl:Restriction>
				<owl:onProperty rdf:resource="&gist;universalDateTime"/>
				<owl:someValuesFrom rdf:resource="&xs;dateTime"/>
			</owl:Restriction>
		</rdfs:subClassOf>
		<rdfs:subClassOf>
			<owl:Restriction>
				<owl:onProperty rdf:resource="&gist;universalTime"/>
				<owl:someValuesFrom rdf:resource="&xs;string"/>
			</owl:Restriction>
		</rdfs:subClassOf>
	</owl:Class>
```

Why do properties universalDate, universalTime, localDate, and localTime have xsd:string values, while the others have xsd:dateTime values. Why not use xsd:date and xsd:time?

**Comment by Jamie-SA** [comment]
Is it because OWL does not support xsd:date and xsd:time?
See https://www.w3.org/TR/owl2-quick-reference/#Built-in_Datatypes

They are not included in the "OWL 2 datatype map, which lists the datatypes that can be used in OWL 2 ontologies".

I found it odd when I came across it that several useful RDF datatypes are not included.

**Comment by uscholdm** [comment]
Yeah - dates are a bit of a nuisance.

**Comment by rjyounes** [comment]
@Jamie-SA I hadn't seen your reference, and was basing my thought on this:

"The RDF and OWL Recommendations use the simple types from XML Schema"
https://www.w3.org/TR/swbp-xsch-datatypes/

Simple types are those that can't have child elements or attributes. So the two specs seem to be in conflict; the one I cite is from 2006 so maybe has been superceded by the other, from 2012. @uscholdm any thoughts?

**Comment by rjyounes** [comment]
Also,
