### ISSUE TITLE
Remove gist:decimalValue and replace with gist:numericValue

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#171]
If there is ever a need to connect a number to something else it cannot be a literal, it has to have a URI (it might be called NumberValue).  It makes sense to use the same property, decimalValue to point to the number.  Currently, this falsely implies that the NumberValue is an instance of gist:Magnitude. 

SUGGESTED FIX: remove the domain from gist:decimalValue.

This is a response to a current requirement for Platts, it is not a theoretical exercise.  It underscores the caution we need to take when using domain and range. 

See also:  https://github.com/semanticarts/gist/issues/172

**Comment by uscholdm** [comment]
This just bit us again for the IBB Project.  Peter and I wanted to reuse decimalValue for things that are not magnitudes. New proposal:
1. deprecate `gist:decimalValue` which is misleadingly named in the first place (See https://github.com/semanticarts/gist/issues/172)
1. add new property called `gist:numericalValue` with no domain and whose range is the union of all the datatypes that are numbers i.e. `(xsd:decimal or xsd:double or xsd:integer or owl:real or ...)`
1. as explained in https://github.com/semanticarts/gist/issues/172, if there are special cases requiring a specific range, then a new subproperty can be created such as gist:doubleValue, gist:integerValue. This is a bit of an ant-pattern though, better to use SHACL. If we did create a decimalValue then it definitely should not have any domain. To have a separate property for use only with Magnitudes whose value is always double is an even worse anti-pattern (antier pattern?).

**Comment by rjyounes** [comment]
I like your suggestion. There may be cases where semantics rather than just expected usage requires a specific numeric type, in which case it might be appropriate to mint some of those more specific properties. Hypothetically, hasNumberOfChildren is an integer, for example. We may well not define those in gist but leave them to client ontologies.

**Comment by uscholdm** [comment]
@rjyounes Yes, exactly!

**Comment by rjyounes** [comment]
Address with #172 - may be a duplicate.

**Comment by Jamie-SA** [comment]
Any interest in addressing this for v10 release?

I am wondering because we are about to start baking the current definitions into new shapes for SA internal systems. Would be nice (for us) to make any changes now rather than later.

This might be a bigger change than just removing the range (see #172). There are several terms in gist that have owl:restriction onProperty gist:decimalValue. But that also makes it a good candidate to go into a major release like v10.

**Comment by uscholdm** [comment]
I'm interested!

**Comment by rjyounes** [comment]
Let's sort out whether the correct term is "numeric" or "numerical." I'm unclear on the difference, or whether there is a difference. The answers I get from a search do not help to clarify it.

**Comment by rjyounes** [comment]
@Jamie-SA I've put this into the June project so we can consider it for that release.

**Comment by uscholdm** [comment]
> Let's sort out whether the correct term is "numeric" or "numerical." I'm unclear on the difference, or whether there is a difference. The answers I get from a search do not help to clarify it.

I think `numericValue` sounds better, the other one sounds al funny (so to speak).

**Comment by rjyounes** [comment]
DECISION: 
1. deprecate `gist:decimalValue` which is misleadingly named in the first place (See https://github.com/semanticarts/gist/issues/172)
1. add new property called `gist:numericValue` with no domain and whose range is the union of all the datatypes that are numbers i.e. `(xsd:decimal or xsd:double or xsd:integer or owl:real or ...)`
1. as explained in https://github.com/semanticarts/gist/issues/172, if there are special cases requiring a specific range, then a new subproperty can be created such as gist:doubleValue, gist:integerValue. This is a bit of an ant-pattern though, better to use SHACL. If we did create a decimalValue then it definitely should not have any domain. To have a separate property for use only with Magnitudes whose value is always double is an even worse anti-pattern (antier pattern?).
