### ISSUE TITLE
Make TaskTemplate a subclass of Specification

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#175]
This question was raised and got some provisional agreement (from Dave and Michael) at the gist Council meeting on Events on 02/13/2020.

**Comment by marksem** [comment]
I say no.  

As I commented on issue #60 , "I do not think Template is sub of Specification. Specification is a type of requirement. I do not see a Template as a type of Requirement. My Christmas cookie cutter is not in all cases a requirement. "  

Furthermore I do not think things like Recipes or How-Tos (which I think are subs of TaskTemplate) are always a "Requirement".

**Comment by rjyounes** [comment]
Closing this issue in any case because it's a duplicate of #60.
