### ISSUE TITLE
Planned events vs predicted events

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#176]
A PlannedEvent, at least based on name, suggests intentional planning by agents, as opposed to predicted natural events such as volcanic eruptions. Do we need a different class for these, or is it just a matter of clarifying the definition and examples of PlannedEvent? Or even changing the name, because it's misleading.

**Comment by uscholdm** [comment]
This is a valid distinction. I unless we think it will be commonly used in a typical enterprise, we might not want add it to gist.

**Comment by rjyounes** [comment]
I suggest the following: Event > Predicted/Forecast/ExpectedEvent > PlannedEvent.

Sample use cases:  prediction of outages in petchem plants (this is a real use case that was actually discussed); the financial/economic impact of predicted natural disasters.

**Comment by rjyounes** [comment]
See also #489 and #402.

**Comment by uscholdm** [comment]
> I suggest the following: Event > Predicted/Forecast/ExpectedEvent > PlannedEvent.

**Comment by uscholdm** [comment]
It says implementation specified, but I don't see a proposed solution.  I do see suggestions, but no DECISION. I lean towards not adding new classes to gist at this time - unless there is clear demand from more than one or two clients.

**Comment by rjyounes** [comment]
Fixed the status.

**Comment by rjyounes** [comment]
Planned events are instantiated when planned. Hypothetical events don't have datetimes attached.

Hypothetical events could be specifications. May be simulations, but not predicted.

Michael: Leave PredictedEvent out of gist? Hypothetical and predicted events are different. Predicted = Hurricane Andrew on Tuesday. Hypothetical = a hurricane is coming. Keep PlannedEvent. 

What do we need in gist?
* PlannedEvent - already exists

DECISION: Don't need hypothetical or predicted events.  No action required, issue can be closed.

To do: create annotations (e.g., `skos:scopeNote`s) to explain exact meaning of PlannedEvent and difference from predicted and hypothetical events.

Michael proposes a Markdown document of ways gist could be extended, in part based on our thought processes as we made decisions.

Peter: Could be an appendage to the primer.
