### ISSUE TITLE
Remove or loosen constraints on gist:requires

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#183]
Current domain: Intention
Current range: Behavior
Definition: An intention that sets out a state of satisfaction (you are required to drive on right side of the road)

We may want to say "Plants require good soil and rain to grow." The plant itself does not have an intention, though we might have an intention for the plant. Or maybe the subject of requires here is growth, but this too doesn't have an intention.

The Cambridge Dictionary defines several meanings for required:
1. To need something or to make something necessary.
2. To order or demand something, or to order someone to do something, especially because of a rule or law.
3. To make it officially necessary for someone to do something.

gist:requires encompasses only definitions 2 and 3.

**Comment by rjyounes** [comment]
DECISION: Remove domain and range.

**Comment by rjyounes** [comment]
Deferring until we know whether the next release will be a major one or not.

**Comment by bolerio** [comment]
Completely agree the domain and range should be removed and I also like the proposed definition "the object is necessary to the subject".

**Comment by rjyounes** [comment]
@uscholdm I'd like to get your input on this one. The current definition, with domain `gist:Intention` and range `gist:Behavior` is "An intention that sets out a state of satisfaction (you are required to drive on right side of the road)." Now that we are removing the domain and range constraints, I'm not sure how we should define this predicate, because there is one sense of the word in English. I see at least two broad buckets:

- Necessary: 
  - The patient requires a kidney transplant to survive.
  - Solar power requires sunlight.
- Mandatory/compulsory/obligatory: 
  - The law requires that you have a driver's license in order to drive on public roads.
  - The teacher required his class to complete the homework assignment by the next day.

Maybe you can think of others.

Should a single predicate encompass both these meanings? If so, what is a good definition that covers both, other than "... or ..."?

**Comment by uscholdm** [comment]
DECISION: remove domain and range constraints on the definition of `gist:requires`. #614  [#183](https://github.com/semanticarts/gist/issues/183)
