### ISSUE TITLE
Update rdfs:label to skos:prefLabel

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#185]
Can be automated through ontology-toolkit.

Will create as an option in ontology-toolkit.

We'll keep rdfs:label in version 9.x, with automated addition of skos:prefLabel. In version 10 we can remove rdfs:label.

See [issue in ontology-toolkit](https://github.com/semanticarts/ontology-toolkit/issues/4).

**Comment by Jamie-SA** [comment]
Should the generated skos:prefLabel have a language tag of @en instead of being xsd:string?

**Comment by rjyounes** [comment]
Encompassed by #85.
