### ISSUE TITLE
Create documentation of the contribution process - adding and implementing issues and submitting PRs

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#190]
Add guidelines for issue submission to documentation folder. 

E.g., be specific in titles (not "typo in label" but specifically which label).
Include gist version number in the description (not title).

To submit a PR:
- create issue first
- submit PR referencing issue (I.e. "fixes #xx")

**Comment by uscholdm** [comment]
Include in the recommendations suggestions for solutions, where possible.

**Comment by rjyounes** [comment]
Include issue and PR submission by non-SA contributors

**Comment by rjyounes** [comment]
I moved everything from the wiki page into GitHub. I think there may need to be some separation between internal and public documentation, so this needs some refinement.

**Comment by rjyounes** [comment]
Should move everything from wiki to GitHub to keep everything in one place, but remove references to, e.g., individual people. Use term "mergers" for those who have merge permission to develop.

**Comment by rjyounes** [comment]
See https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors. Should follow this model.

- Change doc directory to docs
- File is Contributing.md

**Comment by rjyounes** [comment]
@sa-bpelakh See preceding comment - there are benefits to follow GitHub in putting this file in a folder called docs rather than doc, so I'd like to rename the folder as part of this issue. Is there an ontology-toolkit config file that needs to be updated? I'm assuming now no changes are required to ontology-toolkit itself.

**Comment by sa-bpelakh** [comment]
@rjyounes I have not issue w/ renaming the folder. The bundle template that is part of https://github.com/semanticarts/gist/pull/225 (for which I have requested your review 😄 ) will need to modified, but that's all.

**Comment by rjyounes** [comment]
Aha, that explains it: I was looking for such a file but couldn't find one!

**Comment by rjyounes** [comment]
Scaled this issue back to refer just to Contributing.md. Other issues have been created for other documents: #232, #233.
