### ISSUE TITLE
Generalize definition of gist:respondsTo

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#191]
rdfs:comment: "The set of sensors that a controller is attached to"

Note that there are no domain or range restrictions on the property.

Proposal: make this into a general predicate defined as "The resource says or does something in response to something that has been said or done."

It seems highly doubtful that we would need a predicate with the current level of specificity in an upper enterprise ontology. It would be interesting to know the use case that drove this.

**Comment by rjyounes** [comment]
Labelling as patch since the original definition seems like a mistake, and there is no axiomatic change.

**Comment by uscholdm** [comment]
I agree this should be generalized.   When you say "The resource", which resource are you referring to? The subject of the triple?  We have a long way to go before settling on a style for definitions of properties.  Dan's preferred choice is more like this:
- the Subject says or does something in response to the Object"

**Comment by rjyounes** [comment]
This issue is not meant to address the stylistic issue, only the content.

FWIW, I find Dan's preferred style cumbersome and unidiomatic. Two other conventions I've played with:

1. Relates a set of sensors to the attached controller.
2. Relates this set of sensors to the attached controller.

"This" acts as a sort of keyword referencing the subject. At any rate, we will discuss the issue further as we drill down into stylistic conventions.

**Comment by uscholdm** [comment]
I find that depending on the property, a different style/pattern works better.

**Comment by rjyounes** [comment]
Perhaps the rdfs:comment is meant as an example rather than a definition. Another excellent reason to use the more specific skos annotations.

**Comment by rjyounes** [comment]
Closing: will be addressed in #323. IoT will likely be pulled out into a separate module.
