### ISSUE TITLE
Clean up documentation and tools

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#193]
- bundle.bat can be deleted - now replaced by ontology-toolkit. Instructions in README.md should be updated to reflect the use of ontology-toolkit.
- versionize scripts can be deleted
- serialize scripts can be deleted
- version.txt - delete
- curl_requests.txt - do we need this?
- Only rdf-toolkit is needed in tools directory

**Comment by marksem** [comment]
@sa-bpelakh , I think I'll need your help to know what tools are needed and no-longer-needed to do a release, since you did the most recent release.

**Comment by sa-bpelakh** [comment]
@marksem So, you should read https://github.com/semanticarts/ontology-toolkit/blob/develop/README.md, if you run `python ontology-toolkit.py bundle [version]` from the gist root directory, that gets you most of the way there. If you move the locations of any of the artifacts (like LICENSE.txt etc), the script will need to be adjusted, it makes some assumptions to simply the command line interface.

**Comment by marksem** [comment]
@sa-bpelakh , what is the recommended way to install the needed requirements for ontology-toolkit? E.g. pip install -r requirements.txt vs. pipenv vs virtualenv?   Also, what is the recommended way to get ontology-toolkit.py on your PATH so you can run it anywhere (such as in the gist folder)?

It would be helpful to add such direction to the ontology-toolkit readme. It probably makes more sense to have that there than in the gist readme.

**Comment by sa-bpelakh** [comment]
`pip install -r requirements.txt` will work for now. You can use `virtualenv` if you want to isolate the downloaded packages, but I don't tend to do that. I created https://github.com/semanticarts/ontology-toolkit/issues/16 to augment the documentation.

I will also look into [PyInstaller](http://pyinstaller.org) to see if we can get the script packaged as an executable.

**Comment by rjyounes** [comment]
@marksem You may want to follow the GitHub process for adding a license: https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

This involves keeping it at the root of the repo rather than in the doc folder, contrary to what I suggested above.
