### ISSUE TITLE
Definition of gist:Message is inconsistent with its axioms

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#194]
Definition: A specific instance of content sent from an Organization, Person, or Application to at least one other Organization, Person, or Application.

Axioms: 

```
<owl:intersectionOf rdf:parseType="Collection">
    <rdf:Description rdf:about="&gist;ContentExpression">
    </rdf:Description>
    <owl:Restriction>
        <owl:onProperty rdf:resource="&gist;fromAgent"/>
        <owl:someValuesFrom>
            <owl:Class>
                <owl:unionOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="&gist;Person">
                    </rdf:Description>
                    <rdf:Description rdf:about="&gist;Organization">
                    </rdf:Description>
                    <rdf:Description rdf:about="&gist;Address">
                    </rdf:Description>
                </owl:unionOf>
            </owl:Class>
        </owl:someValuesFrom>
    </owl:Restriction>
    <owl:Restriction>
        <owl:onProperty rdf:resource="&gist;toAgent"/>
        <owl:someValuesFrom>
            <owl:Class>
                <owl:unionOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="&gist;Person">
                    </rdf:Description>
                    <rdf:Description rdf:about="&gist;Organization">
                    </rdf:Description>
                    <rdf:Description rdf:about="&gist;Address">
                    </rdf:Description>
                </owl:unionOf>
            </owl:Class>
        </owl:someValuesFrom>
    </owl:Restriction>
</owl:intersectionOf>
```

**Comment by uscholdm** [comment]
I could be wrong, but I thought this issue already came up. I seem to recall commenting on it.

**Comment by rjyounes** [comment]
I did a search on Message and didn't come up with anything. 

This ties in to #132. I think we need an Agent class, with subclasses Person, Organization, and SoftwareApplication. A Message can be sent to and from an Agent. In the case of Address, IMO an Agent sends and receives a Message at an Address; the Address (Content) does not send or receive. How could Content do either?

In summary, I think the annotation is essentially correct but could be more concise if we have an Agent class. The axiom is IMO wrong.

**Comment by rjyounes** [comment]
`Address has been removed; now just `Person` or `Organization` in the axioms.

**Comment by rjyounes** [comment]
DECISION: For now, change `skos:definition` to match current formal definition.
