### ISSUE TITLE
Determine if there is a problem with disjointness axioms in gist 9.1.0

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#197]
See discussion in PR #192. 

@uscholdm Creating issue in response to your concerns.

**Comment by sa-bpelakh** [comment]
Compared (via Protege) a merged 9.0.0 gist to a merged 9.1.0 gist, found that only differences were spelling corrections in annotations and definitions, plus some removed invalid properties. All class definitions, including disjointness, were identical.
