### ISSUE TITLE
Refactor gistIoT to move general concepts to gistTop

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#198]
E.g., gist:respondsTo: "The set of sensors that a controller is attached to."

Questions:
- If all such terms that are useful in a general context are moved out of gistIoT, is there enough left to have a separate ontology module?
- Should an upper enterprise ontology model such specialized domains as sensors?

Relates to the larger question in #201.

**Comment by pwin** [comment]
[2020-03-24_ReviewOf_gist_IoT.docx](https://github.com/semanticarts/gist/files/4379686/2020-03-24_ReviewOf_gist_IoT.docx)
This is a doc with background and a list of classes and properties, helpful for the review.  Any comments?

**Comment by rjyounes** [comment]
This should be put on hold until we've determined whether to de-modularize gist. See #292.

**Comment by marksem** [comment]
Closed as part of #292, demodularize gist. No longer applicable.
