### ISSUE TITLE
Add merged gist to generated artifacts on gist releases

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#199]
It can be convenient to have all of gist in a single ontology. E.g. 

1. To compare two versions in Protégé
2. To have a quick look w/o fussing with lots of files.
3. To help prepare release notes - a final look through all the changes

Boris did such merge and compared two versions in Protégé last week. It was very handy.
Suggest to call the file something like allGistMerged.ttl(rdf)

**Comment by marksem** [comment]
Closed as part of #292, demodularize gist. No longer applies.
