### ISSUE TITLE
Use a tool that allows users to create modules for specific purposes

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#201]
Peter will investigate subsetting.

**Comment by pwin** [comment]
http://precedings.nature.com/documents/3574/version/1/files/npre20093574-1.pdf describes the Minimum Information to Reference an External Ontology Term (MIREOT) approach to ontology subsetting.  This is one of 3 ontoogy subsetting techniques that is available in the OBO ROBOT tool - http://robot.obolibrary.org/ .  See http://robot.obolibrary.org/extract

"The MIREOT method preserves the hierarchy of the input ontology (subclass and subproperty relationships), but does not try to preserve the full set of logical entailments."

**Comment by uscholdm** [comment]
This is very interesting. Would you like to give an overview presentation of sorts about this on some Friday?

**Comment by pwin** [comment]
Please can this be reviewed 
[Extracting Terms from Ontologies.pptx](https://github.com/semanticarts/gist/files/4439356/Extracting.Terms.from.Ontologies.pptx)

**Comment by rjyounes** [comment]
Dave is working on this - defer.

**Comment by uscholdm** [comment]
@pwin @rjyounes 
Peter - do you want to keep this active? If so, can you give a short presentation and outline proposal ideas? If not, I guess it could be closed.
