### ISSUE TITLE
Apply Markdown-to-HTML conversion to the 9.1.0 release package

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#202]
See [ontology-toolkit issue 12](https://github.com/semanticarts/ontology-toolkit/issues/12)

**Comment by sa-bpelakh** [comment]
Sent HTML doc to @Jamie-SA, @pwin added functionality to `bundle` for future releases.

**Comment by Jamie-SA** [comment]
It added a strange character to the <h1> tag contents. I edited it out so it doesn't show up but it would be nice if it didn't add that.
