### ISSUE TITLE
Deprecate _unitedNations

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#207]
Doesn't belong in an upper ontology, and if someone needs to reference the United Nations, an external URI can be used.

I'm calling this a patch because we could consider its inclusion an error, in a sense. It's a debatable point, however.

**Comment by rjyounes** [comment]
Impacts #71

**Comment by rjyounes** [comment]
Dave defined this entity in order to define CountryGovernment as having to be recognized by the UN.

Discussion:
- There are many different ways to define what a country is
- We don't want to take a political stance that the UN is the authoritative source of what a country is.
- Same comment about ISO-3166

**Comment by rjyounes** [comment]
We will run this by Dave before deleting. If we don't delete, then consider #71.

**Comment by rjyounes** [comment]
1. Remove class CountryGovernment and _unitedNations
2. Remove _unitedNations and keep class CountryGovernment without the existing recognizedBy restriction
3. Keep CountryGovernment and have a cardinality restriction of 1 on recognizedBy and recognizedBy some Organization. Remove _unitedNations. Client ontologies can subclass with their desired recognizing body.

**Decision: #3.**

**Comment by rjyounes** [comment]
@DanCarey404 I am putting the status back to in review because @uscholdm  had some comments that didn't get expressed at the meeting:

If we change the restriction to be recognizedBy some organization, then we cannot use equivalenceClass. That would mean any organization at all (for example Seattle City Council) could recognize an entity and it would be a Country.

Anyway, there is no semantics for recognizedBy, not even an annotation. So Dave wanting an unambiguous definition for CountryGovernment is not satisfied anyway, except superficially and misleadingly. It gives the impression of actual meaning w/o having actual meaning.

Also this will be circular anyway, since recognizedBy in this context really means recognized AS A COUNTRY.

**Comment by rjyounes** [comment]
recognizedBy does have a definition, it's recognizes that doesn't. That definition is nevertheless not very enlightening, but at a minimum we could reverse it and add it to recognizes.
```
	<owl:ObjectProperty rdf:about="&gist;recognizedBy">
		<rdfs:label rdf:datatype="&xsd;string">Recognized By</rdfs:label>
		<rdfs:comment rdf:datatype="&xsd;string">The entity that formally acknowledges the existence of, as the State recognizes the existence of a particular company</rdfs:comment>
		<rdfs:range>
			<owl:Class>
				<owl:unionOf rdf:parseType="Collection">
					<rdf:Description rdf:about="&gist;Person">
					</rdf:Description>
					<rdf:Description rdf:about="&gist;Organization">
					</rdf:Description>
				</owl:unionOf>
			</owl:Class>
		</rdfs:range>
		<owl:inverseOf rdf:resource="&gist;recognizes"/>
	</owl:ObjectProperty>
	
	<owl:ObjectProperty rdf:about="&gist;recognizes">
		<rdfs:label rdf:datatype="&xsd;string">Recognizes</rdfs:label>
		<rdfs:comment rdf:datatype="&xsd;string">Recognizes</rdfs:comment>
	</owl:ObjectProperty>

```

**Comment by uscholdm** [comment]
Oh yes. Do we have a style convention for whether we attach definitions to both the property and its inverse? Not a bad idea. Alternative is to have the definition on just one and for the othere have the definition just say "inverse of property P"

**Comment by rjyounes** [comment]
I think annotations should go on both. That's something we should consider in #253. Recall, we don't yet have any style conventions for anything other than the bare bones in the style guide, which includes just local names and labels at this point.

**Comment by rjyounes** [comment]
Proposal: make recognition a necessary but not sufficient restriction for something being a CountryGovernment. Remove _unitedNations.

**Comment by rjyounes** [comment]
Dan: Dave had no particular view. 

DECISION: Keep CountryGovernment and have a cardinality restriction of 1 on recognizedBy and recognizedBy some Organization. Remove _unitedNations. Client ontologies can subclass with their desired recognizing body.
