### ISSUE TITLE
Pare down object properties

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#209]
From Dan: Dave recently mentioned that he thought we could pare down the object properties in gist.  I agree with that assessment.  This would make a good topic for a future gist council.  In anticipation of that, I would like to request that SA ontologists (to the extent that you are able to do so) check what properties your clients are actually using in their ABoxes.  Once we integrate together our findings, we should have a reasonable picture of which gist properties are genuinely needed, and which require reexamination.

**Comment by rjyounes** [comment]
I propose that SA ontologists add their findings here while keeping clients anonymous.

Non-SA ontologists: it would be interesting for you to also add your usage data.

**Comment by rjyounes** [comment]
Removal of inverses in #506 is relevant here.

**Comment by pwin** [comment]
inverses removed.
