### ISSUE TITLE
Proposed new definitions and other annotations

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#217]
These are from Jonathan Storm. 

@daliadahleh  will review and attach an updated version of the spreadsheet with any edits, for review by the rest of the team. Or if you prefer, you can put it on Office 365 and we can review and make our own comments there.

[gist9Annotations - 1st batch 2020-01-29.txt](https://github.com/semanticarts/gist/files/4388653/gist9Annotations.-.1st.batch.2020-01-29.txt)
[gist9Annotations - 1st batch 2020-01-29.xlsx](https://github.com/semanticarts/gist/files/4388654/gist9Annotations.-.1st.batch.2020-01-29.xlsx)

**Comment by daliadahleh** [comment]
I suggested some edits where I found the proposed definitions either confusing or too restrictive. See comments in column I. 

[gist9Annotations.-.1st.batch.2020-01-29-comments.xlsx](https://github.com/semanticarts/gist/files/4399545/gist9Annotations.-.1st.batch.2020-01-29-comments.xlsx)

**Comment by rjyounes** [comment]
@daliadahleh I have created a new column J with my approved annotations. Since we have not officially decided to use skos predicates, although we are headed in that direction, these would all be rdfs:comments and I have indicated this in my notes. These can be converted to skos annnotations if and when we make that decision. These definitions need to be reviewed by the group, which we do not have time for for the April release, and I have thus moved the issue to May.

[gist9Annotations.-.1st.batch.2020-01-29-comments-RY.xlsx](https://github.com/semanticarts/gist/files/4540692/gist9Annotations.-.1st.batch.2020-01-29-comments-RY.xlsx)

**Comment by rjyounes** [comment]
Deferred until we decide on skos annotations to use - issue #85.

**Comment by rjyounes** [comment]
Relates to #534.

**Comment by uscholdm** [comment]
@daliadahleh @rjyounes

> We may want to simply close this issue without further action and do a complete overhaul of definitions at some future date.

I agree, we have made a bunch of changes in the 3 years since this proposal came out, we are now using skos annotations.
