### ISSUE TITLE
Networkd Link

### ISSUE THREAD

**Issue by DougalW** [semanticarts/gist#224]
Hi, the class:
https://ontologies.semanticarts.com/gist/NetworkLink

has a few spelling mistakes:
- in the rdfs:label annotation it reads: 'Networkd Link'
- in the rtfs:comment annotation is misspells abstraction as: 'abstractino'

Cheers
Dougal

**Comment by ungricht** [comment]
This issue appears to have been resolved during the process of updating to de-modularized version. I no longer see the error.  I recommend we close the issue.
