### ISSUE TITLE
Document use of pre-commit hook to run serializer in the gist style guide

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#226]
Is this the pre-commit hook we recommend using? https://github.com/edmcouncil/rdf-toolkit/blob/master/etc/git-hook/pre-commit

It's a bit heavy-weight but perhaps that's necessary for robustness.

**Comment by rjyounes** [comment]
See #222

**Comment by rjyounes** [comment]
Closing - will discuss under #222

**Comment by uscholdm** [comment]
There is a pre-commit file in this folder:   ...\Offerings\gist\git4gist\ which, I think, was a reworked one from edmc changed by Ted.  Have a look.
