### ISSUE TITLE
gist:memberOf incorrect rdfs:domain

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#243]
Currently (gist 9.1.0) has

gist:memberOf  rdfs:domain   gist:Collection.

This means that if X memberOf Y, then X is a collection.
But clearly this is incorrect.  Could say that if X memberOf Y, then Y a collection, but not X.
E.g.,  _PersonX memberOf _OrgY does not make _PersonX a collection. 

Note that gist:hasMember (the inverse of gist:memberOf) already has   rdfs:domain  of  gist:Collection.

Suggest just remove the rdfs:domain restriction from gist:memberOf.
Alternatively change it to an rdfs:range restriction.

**Comment by uscholdm** [comment]
Cleary an unintended bug. I would go further and recommend to get rid of the domain/range constraint.  If you want someone to be a member of an organization, then the organization is forced to be a collection. Bad idea, forces introducing extra properties that only differ in domain or range.

**Comment by rjyounes** [comment]
@uscholdm I agree.
