### ISSUE TITLE
Upgrade to Creative Commons 4.0 license

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#244]
We are using version 3.0. We should consider upgrading to 4.0: https://creativecommons.org/licenses/by-sa/4.0/legalcode

This involves changing license.txt and updating the release announcement.

We will need Dave's input on this one.

**Comment by uscholdm** [comment]
*   We are using [Creative Commons] version 3.0. We should upgrade to 4.0
Are they backwards compatible 😊

M.

**Comment by rjyounes** [comment]
Good question. I've modified the issue to "consider upgrade." I was assuming that since they replaced 3.0 with 4.0, that is the one that should be used, but I could be wrong. Needs further investigation.

**Comment by Jamie-SA** [comment]
Yes, the changes should be reviewed. Sometimes you might not agree with the changes. That happened when the GNU Public License went from v2 to v3 (I think), many people balked and refused to update to it.

**Comment by rjyounes** [comment]
See https://doctorow.medium.com/a-bug-in-early-creative-commons-licenses-has-enabled-a-new-breed-of-superpredator-5f6360713299, which makes this more urgent.

**Comment by rjyounes** [comment]
Steps involved:

1. Select license using CC's [license chooser](https://chooser-beta.creativecommons.org/) and based on other information on the site.
2. Update LICENSE.txt in repository
3. Update `gist:license` value in `gistCore`
4. Update gist page on website. Note: some of the current language is unclear and contradictory; this needs to be reviewed and modified with care. E.g., at the top of the page it is claimed that "You can use gist as you see fit for any purpose, just give us attribution." This is not the case, as indicated further down the page, which adds "Any concepts used from gist are to remain in the gist namespace." The language needs to be updated based on careful review of the CC 4.0 license selected.

**Comment by rjyounes** [comment]
Details on this license are found at https://creativecommons.org/licenses/by/4.0/

The issue I see with this license is that it allows users to “remix, transform, and build upon…” which doesn’t include our restriction against making changes within the gist namespace. I wonder how to handle that – I know currently we just have a note on the website to that effect. I assume the CC licenses are not specialized enough to include that sort of clause. The best thing to do would be to consult a lawyer but we probably don't want to incur the expense.

**Comment by rjyounes** [comment]
Email discussion:

Peter 2022-03-11:

 asked colleagues in W3C about our challenge regarding the namespace. 
 
 Hi Peter,

I talked about this with Wendy and Ralph and here is what I understand.

It is considered best practice that namespaces be dereferenceable.

Since the user has no control over the domain of the namespace, they
can't really put anything useful there (and worst, they are at the mercy
of the domain owner).

Legally speaking, there is nothing that would prevent the user from
using something like https://google.com/ns/#Person , except for
trademark infringement at most.

Rebecca:

What they say is correct, but not applicable outside of the semantic web (aka LOD). Within an enterprise you can make any assertions you want, since the URIs are not being dereferenced.

Peter:

What they say is correct, but not applicable outside of the semantic web (aka LOD). Within an enterprise you can make any assertions you want, since the URIs are not being dereferenced.

**Comment by rjyounes** [comment]
DECISION:

Upgrade to Attribution 4.0 International (CC BY 4.0) https://creativecommons.org/licenses/by/4.0/ with a disclaimer about not defining terms in the gist namespace.

Website: state first our disclaimer, then link to the license.
`gist:license` do the same thing (this is an annotation property so we can put an arbitrary string into it.)
LICENSE.txt in repo - same thing

**Comment by semartsofficemanager** [comment]
Spoke to Dave - he is inclined to move forward with conversion to 4.0. He saw somewhere there is a legal flaw with version 3 that means we should upgrade. 

The license states that attribution is required, and our form of attribution is the namespace request, so this is consistent with the license not in opposition.

No need to involve a lawyer or discuss further but can go ahead and update documentation accordingly. @rjyounes can you either take it from there or assign to someone who knows how to take this forward? Happy to answer any additional questions.

**Comment by rjyounes** [comment]
Thanks, JT. I will move this forward.
