### ISSUE TITLE
Apply or remove axiomatic redundancy related to Symmetric properties (disjoints and inverses) consistently

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#254]
See discussion on PR #247. That PR was closed because it has not gone through the triage process.

**Comment by marksem** [comment]
As discussed on Teams regarding my work on issue #243 there are redundant disjoints that could be removed.

Suggestion: Remove redundant disjoints in gistTop, i.e. state the distjoint on just one side. Ususally the one that occurs 1st alphabetically.

Here's the teams discussion transcript:

[9:18 AM] Mark Wallace
sa-gist, I have an issue where when I run the serializer, it removes a bunch of disjointness axioms, even though I didn't touch anything there. Is anyone else seeing this?
​[9:43 AM] Dalia Dahleh
I believe that's protege, not the serializer. When you save an ontology in protege it only writes one side of a symmetric property.
​[9:48 AM] Mark Wallace
Ah, ok Wonder how many of us are using Protege? More importantly, is it OK to "agree with " protege and let these come out (under a different atomic commit), or to keep having to "unstage that hunk" after I serialize from Protege?
​[10:19 AM] Dalia Dahleh
Good question. I'm thinking it might be better to remove them. Not only to make it easier to save with protege, but also to make it more consistent. Most disjoints are only stated on one class in our gist files (even UnitOfMeasure has a few more that are only stated on the other class)
​[10:21 AM] Mark Wallace
ok, sounds goodl. I'll take them out as another atomic commit
Edited​[10:46 AM] Boris Pelakh
Is Protege consistent about which half of the symmetrical disjoint it drops? Should there be a standard?
​[10:48 AM] Dalia Dahleh
It looks like it keeps the first, sorted alphabetically
(2 liked)

**Comment by rjyounes** [comment]
Larger issue of axiomatic redundancy: do we want redundancy or not? If yes, they should be added across the board. gist leans toward lack of redundancy.

Note: Protégé removes certain redundancies, such as disjoints, inverses. But not all, such as doesn't infer InverseFunctional on the inverse of a Functional property.

Those who don't use Protégé for editing may add redundancies, so we wouldn't be consistent. 

Without reasoning, Allegrograph does not find the redundancies.

Dan: separate ontology file for just disjoints?

Peter: difference between RDF/XML and OWL/XML?

Dave: materialize all redundant assertions and put them in the appropriate files. 

Peter: we need a test case to determine what the cost-benefit of the consistency is.

**Decision: limit this issue to disjoints, and remove the redundant ones.**
