### ISSUE TITLE
`gist:identifiedBy` unintentionally made an owl:FunctionalProperty ?

### ISSUE THREAD

**Issue by skwlilac** [semanticarts/gist#255]
In `gistTop9.2.0`  the definition for `gist:identifiedBy` states:

    This is like a URI: a thing can have more than one ID, but each of the IDs must refer to a unique thing.

However, its inverse relation, `gist:identifies`, is defined as being an `owl:InverseFunctionalProperty`, i.e. the that the inverse of `gist:identifies`, namely `gist:identifiedBy` is also an  `owl:FunctionalProperty` i.e. that some thing can only be identified by a single ID.

I think that this inference is unintended. It makes sense of `gist:identifies` to be functional - which arises from the two axioms on `gist:identifiedBy`. 

I think the simple 'fix' is to remove the `owl:InverseFunctionalProperty` assertion on `gist:identifies`, and possible replace it with a redundant `owl:FunctionalProperty` assertion, though I don't think the latter is necessary given the other axioms.

Apologies if I have missed something subtle or failed to understand the intention of these to properties and `gist:ID`.

**Comment by uscholdm** [comment]
Good catch. Your suggested fix is correct.  To repeat:
> Remove the `owl:InverseFunctionalProperty` assertion on `gist:identifies`.

I suggest to NOT replace it with a redundant `owl:FunctionalProperty` assertion.

**Comment by rjyounes** [comment]
In gist9.2.0 both identifies and identifiedBy are inverse functional properties, clearly an error. This has been identified in #180. Closing this issue.
