### ISSUE TITLE
Release Notes - correcting issue number

### ISSUE THREAD

**Issue by pwin** [semanticarts/gist#256]
In the release notes the link and number for the issue of "Include direct imports of all gist modules in gistCore. Fixes issue 90." should be issue 80

**Comment by rjyounes** [comment]
@pwin I've assigned myself because I have a running branch open to make documentation updates. Might as well roll this in rather than having a new PR, if you agree.

**Comment by rjyounes** [comment]
@pwin go ahead

**Comment by rjyounes** [comment]
Has been fixed.
