### ISSUE TITLE
Document Approach to Importing Ontologies

### ISSUE THREAD

**Issue by tedhills** [semanticarts/gist#260]
At the Gist Council on May7, 2020, there was a discussion in support of the idea that an ontology should directly import all its dependent modules rather than rely on the transitive closure of imports, and there was a statement that gist is being modified to do this. This issue is a reminder to document this approach in the gist Style Guide that is being developed.

**Comment by rjyounes** [comment]
@tedhills Good point, thanks for raising it. Will do.

**Comment by rjyounes** [comment]
Directly relates to #292; if we do #292 then we can close this.

**Comment by marksem** [comment]
Closed as part of #292, demodularize gist.
