### ISSUE TITLE
gist:orderedMemberOf should not be Inverse Functional

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#262]
In gist 9.2.0, gist:orderedMemberOf is defined as Inverse Functional.  

This means that the inverse property, if it exists, is functional. [1] The inverse property does in fact exist, and it is gist:hasOrderedMember, which should clearly **not** be functional.  If it were functional, each OrderedCollection could only have 1 member. 

Suggestion: 
Define gist:orderedMemberOf as Functional instead of Inverse Functional

Refs.
[1] http://protegeproject.github.io/protege/views/object-property-characteristics/

**Comment by uscholdm** [comment]
Good catch, a clear mistake.  I have no idea how this got in...
