### ISSUE TITLE
Adding SHACL to gist?

### ISSUE THREAD

**Issue by Jamie-SA** [semanticarts/gist#263]
Anyone else think that adding some SHACL **for use with** gist would be a good idea?

For instance, Mark's recent suggestion about making gist:orderedMemberOf a functional property (#262) got me thinking about it again. Making the gist:orderedMemberOf property Functional doesn't prevent you from having two of them on an individual. If you want to prevent that you should use SHACL.

If you really want to allow two of them and then infer that the objects are the same, then you wouldn't want the SHACL. But my guess is that would more often be a mistake and I'd rather prevent that from happening in most cases.

**Comment by rjyounes** [comment]
I'm in favor of leaving the semantics in the ontology and letting different applications define the SHACL according to the particular constraints they want to impose on their data. The OWL should speak for itself. While OWL inferencing may not be particularly rich, I don't think we should subvert it.

**Comment by uscholdm** [comment]
I agree with Rebecca in most cases. But I also think there maybe some cases where some SHACL with gist might be desirable.  I'd need to think of examples though  - I might be wrong.  On the other hand, it might be nice to provide some starter SHACL for anyone who can then edit it up or down as they see fit.

**Comment by rjyounes** [comment]
If by "starter SHACL" you mean sort of a tutorial, then I don't think that's the role of gist. There are plenty of SHACL tutorials out there.

**Comment by uscholdm** [comment]
> if by "starter SHACL" you mean sort of a tutorial,

Not at all. I mean if one want to have SHACL for a triple store using an ontology based on gist, we could have some SHACL ready to go generated from gist automatically and that could be a starter for the SHACL that is needed. We did this for MS in NYC.   Each restriction in OWL has an 'echo' in SHACL that looks more or less identical.  Those are easy to generate. Then they can be pruned or added to to suit a particular application.

**Comment by DougalW** [comment]
I think there would need to be a very compelling reason to add SHACL to GIST, maybe to very tightly specify the meaning of something? But in terms of architectural separation of concerns, my experience is that different users will craft wildly different constraints based on applications/usage scenarios, so it's best left up to end users. 

Here's an example use case. At Meaningful, if we integrate between two different end points we include subtly different SHACL shapes for each end point, and a generic central shape for the ontologically 'complete' data they integrate to.

**Comment by dhurlburtusa** [comment]
I think it would prove useful to add some annotations about some example SHACL that fits well with the gist concept. This will help those learning Gist that the SHACL should be separate and implies that the SHACL may vary from application to application. Hence the reason an `owl:Restriction` "equivalent" is not provided with Gist.

**Comment by uscholdm** [comment]
> I think it would prove useful to add some annotations about some example SHACL that fits well with the gist concept.

I don't think adding annotation is the right way to achieve the goal of illustrating example SHACL to use with gist. That should be done in an separate file in an examples folder.

**Comment by uscholdm** [comment]
> I think there would need to be a very compelling reason to add SHACL to GIST, maybe to very tightly specify the meaning of something?

Actually, there are numerous things that cannot be said in OWL, e.g. rules. Over the years, I have often put in an annotation to state a truth about a concept, and to say "but it cannot be said in OWL". Many of those things CAN be said in SHACL.   

We use domainIncludes and rangeIncludes correspond to SHACL with a *, meaning 0 or more.

I briefly looked for more interesting examples and did not find any.

**Comment by uscholdm** [comment]
PROPOSAL
- this opens up a can of worms. 
- if it's useful, why don't we do in internally?
- close this issue now
- if we start using something like it internally and want to share it more widely, we can re-open this issue

**Comment by rjyounes** [comment]
We've determined that, because SHACL is not an OWL ontology, using SHACL in gist would make gist non-OWL DL compliant. See issue #934. Closing.
