### ISSUE TITLE
Create a gist handbook of examples or "recipes"

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#286]
Is this something we want to do (it's a bit time-consuming)? Users have trouble implementing some of the more complex or unfamiliar models, such as categories and units & measures.

Could include two parts, the first an overall introduction to gist, the second a cookbook-style - e.g., how to model dates, temporal relations, etc.

**Comment by uscholdm** [comment]
@rjyounes 
I am strongly in favor of having examples, It's a giant task, this issue is perhaps too broad.  Can we close it and say we'll do it later? Should we break it up into sub-tasks?

**Comment by rjyounes** [comment]
I'll close it. We are beginning an internal list of best practices but a concerted effort is beyond anyone's bandwidth.
