### ISSUE TITLE
gist:categorizedBy should not be a subproperty of gist:hasSubCategory

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#287]
gist:hasSubCategory relates Category to Category. gist:categorizedBy relates an object of some sort to a Category.

Putting  this on the May 2020 project because it is egregious and quick to fix.

**Comment by uscholdm** [comment]
You probably mean subProperty, but its moot in any case. There are no such axioms regarding gist:hasSubCategory in the 9.2.0 release that I just downloaded. It shows up in 3 places:
1. as a restriction on Taxonomy class
2. the definition of the property, it only has a label and a comment
3. it's the inverse of hasSuperCategory

Suggest to close the issue.

**Comment by rjyounes** [comment]
Looking at the files, you're right. I wonder how the Protégé version can be explained. See attached image.
![categorizedBy](https://user-images.githubusercontent.com/1693668/82252641-5eb14a80-991d-11ea-92a7-3cc393631d4a.png)

Also, off topic: categorizedBy, as well as Category, is defined in gistTop, while the other two are in gistCategory, which makes more sense. I suppose there's a chain of references that requires it, but I wonder if it can be cleaned up. Or perhaps this supports the argument that gist isn't structured for real modularity.

**Comment by rjyounes** [comment]
I closed Protégé and reopened it and the subproperty assertion disappeared.

**Comment by uscholdm** [comment]
That is super odd. Maybe Protege imported things incorrectly? You can tell exactly what was loaded by looking at imports, but it can be a tad time-consuming.
