### ISSUE TITLE
Inconsistency for reliance on transitivity of import

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#288]
Issue https://github.com/semanticarts/gist/issues/80 added explicit imports to gistCore so as not to rely on transitivity. However, all the other ontologies still DO rely on transitivity of imports. Is there any justification for this inconsistency?

I propose that we either:
1. have all ontologies have all explicit imports, just like gistCore does
1. have a clear rational for why it makes sensed to do so ONLY for gistCore.

**Comment by rjyounes** [comment]
Discuss in the context of #292.

**Comment by marksem** [comment]
Closed as part of #292, demodularize gist.
