### ISSUE TITLE
The gist:CurrencyUnit works with some changing conversion rates

### ISSUE THREAD

**Issue by Livier13** [semanticarts/gist#289]
This issue aims at solving the uncertainty around the gist:CurrencyUnit class = A unit of money:
- Why a currency unit shouldn't be regarded as a regular unit of measure?  Even though it is used to express a monetary magnitude.
Note: this is the only unit whose conversion factors include time (i.e., the conversion rates change on a daily basis).
- Moreover, all currencies are exchangeable into one another with changing conversion rates.
- Actually, a conversion rate is only fixed at the moment of a transaction, that's all.

Therefore, a need arises for more clarity in common; especially when a changing conversion rate affects the derived magnitude from gist:Accounting.

**Comment by rjyounes** [comment]
WON'T FIX: Duplicates #125, which we decided not to fix.
