### ISSUE TITLE
gist:categorizedBy and gist:Category are defined in gistTop rather than gistCategory

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#291]
gist:hasSubCategory and gist:hasSuperCategory are defined in gistCategory, as they should be. gist:categorizedBy and gist:Category are defined in gistTop. The latter is used in the union range of governs, but this range includes so many classes that I wonder if it could be removed. gist:categorizedBy is used in, for example, gistAgreement, which imports gistIntention, which imports gistTop. Similarly for other references to gist:categorizedBy.

This tangle of references supports the idea that modularity doesn't work for gist because there are too many cross-references; that may be the best approach because there are likely many problems of this sort.

**Comment by marksem** [comment]
Closed as part of #292, demodularize gist.
