### ISSUE TITLE
Do away with modularity in gist

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#292]
Put everything into one file. See #291 for rationale - there may be other issues raising the same point.

I'm starting to come around to the idea that modularity doesn't work in gist - while still supporting it in theory. I believe there are many examples like this one: gist:categorizedBy and gist:Category are not defined in gistCategory, but rather gistTop, because they are referenced either in gistTop or files that import gistTop. Rather than trying to untangle this web of references, perhaps it is best to dump everything into the same file and forget about modularity. gist:hasSubCategory and gist:hasSuperCategory are defined in gistCategory as you would expect.

**Comment by rjyounes** [comment]
We say this on our website: "Gist is extremely modular. There are several modules that can be used collectively or in subsets if you don't need all the concepts in gist." Needs to be removed if we make this change. In any case it's an overstatement.

**Comment by uscholdm** [comment]
>  In any case it's an overstatement.

Another way to put it is to say it was aspirational – IMHO, it was only ever a little true some of the time, and it got less so over time as more stuff migrated to gistTop. Hence the learning.

**Comment by rjyounes** [comment]
Relates to #260 and #288; all three can be addressed together.

**Comment by rjyounes** [comment]
Adding to June 2020 project; let's discuss whether we can get this done for the June release.

**Comment by marksem** [comment]
AC)

1. No more catalog-v001.xml will be needed.
2. Just gistDeprecated.owl and gistCore.owl needed (top level)
3. Update bundling/packaging to still inject proper version number and create good folder shape.

**Comment by rjyounes** [comment]
Other tickets need to be closed out, Mark will implement this and notify others to continue working on other issues.

Meika will finish #93, the PR will be merged, then all other modifications will be postponed till Mark's work is finished. Whoever merges the PR, please send out notification to the group to stop work.
