### ISSUE TITLE
Guidance for adding inverse properties

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#294]
As noted in issue https://github.com/semanticarts/gist/issues/106, we generally refrain from defining inverse properties. However, they are often needed in client ontologies. I suggest that we give guidance on what such a property should be called, if needed. That reduces the chances of creating two different inverses for the same property.  

If SA folk are creating these inverses, we can use the gist namespace, but not others.  Also, it will be a tad awkward to be using a non-gist namespace for the inverse of a gist property.  I don't know the right answer for this. Just putting it out there.

This is coming up now because I want to use the property ownedBy.

**Comment by DanCarey404** [comment]
I don't think there's any way to _not_ use a non-gist namespace for such an inverse.  To do otherwise is namespace-squatting.

**Comment by uscholdm** [comment]
I suppose that's true. Another  alternative is for us to provide all of these inverses in a separate file that is optional - like we have done for deprecated things.

**Comment by rjyounes** [comment]
There are many other cases, e.g., 
A and B are inverses, A has range r, we don't explicitly assert B has domain r.
C is a subproperty of A, A is the inverse of B, 

Another option is to provide a file with materialized inferences that people can use or not.
Need to configure reasoner to not include empty inferences such as every class being a subclass of itself.

**Comment by rjyounes** [comment]
At the gist issue review meeting today, we decided in general _not_ to define inverses, and at some point clean up the inverses we currently have. Therefore closing this issue and adding new issue to implement.
