### ISSUE TITLE
Remove redundant owl:Thing assertions and add strict option to bundle.yaml

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#297]
For example:

```
	<gist:BaseUnit rdf:about="&gist;_USDollar">
		<rdf:type rdf:resource="&owl;NamedIndividual"/>
		<rdf:type rdf:resource="&owl;Thing"/>
		<gist:convertToBase rdf:datatype="&xsd;double">1.0</gist:convertToBase>
		<gist:hasBaseUnit rdf:resource="&gist;_USDollar"/>
	</gist:BaseUnit>
	
	<gist:BaseUnit rdf:about="&gist;_ampere">
		<rdf:type rdf:resource="&owl;NamedIndividual"/>
		<rdf:type rdf:resource="&owl;Thing"/>
		<gist:convertToBase rdf:datatype="&xsd;double">1.0</gist:convertToBase>
		<gist:hasBaseUnit rdf:resource="&gist;_ampere"/>
	</gist:BaseUnit>

	<gist:Duration rdf:about="&gist;_one_minute">
		<rdf:type rdf:resource="&owl;Thing"/>
		<gist:decimalValue rdf:datatype="&xsd;double">1.0</gist:decimalValue>
		<gist:hasUoM rdf:resource="&gist;_minute"/>
	</gist:Duration>
```

The owl:Thing assertion is redundant. We should review the files to see if there are any others. In the third case we could add the NamedIndividual assertion.

**Comment by uscholdm** [comment]
Perhaps this check can go into the bundling software before bundling and release are allowed?

**Comment by rjyounes** [comment]
I don't think the bundling tool should take care of bad ontology-writing. We should just remove them. The bundling tool can remove the stub declarations Protégé inserts, but that's a different matter.

**Comment by uscholdm** [comment]
IMHO, the bundling tool should not bundle bad ontologies and send then out the door. It should do lots of checks, this being one of them.  Or maybe a separate q/a tool that is run before the bundling tool. That's up to the developers, how to manage that pipeline.

Come to think of it, it should be convenient for any ontologist to run such checks, and maybe we should encourage this before any 'major' PR is approved.

**Comment by rjyounes** [comment]
I see your point, and those are good suggestions. We can have it both ways: we ought still to remove assertions that have been identified as bad from the ontology, while also having QA tools that will catch errors we haven't caught.

**Comment by rjyounes** [comment]
I believe the `:x a owl:NamedIndividual` assertion is also redundant. Does this impart any additional meaning?

**Comment by uscholdm** [comment]
`owl:NamedIndividual` is something that Protege adds, I don't thing we need it.

**Comment by robertloo** [comment]
Regarding removing `owl:NamedIndividual`, how does user identify a set of individuals? By filtering names that start with underscore?

**Comment by rjyounes** [comment]
It's not reliable to depend on the IRI naming convention, which is just a mechanism for human understandability and does not carry any semantic weight. In fact, not all `gist` individuals follow this convention: the units of measure, such as `gist:_second`, do not (though we plan to bring them into conformance in the future.) You would look for the type of the resource. E.g., while ontology classes and properties are typed as `owl:Class`, `owl:ObjectProperty`, and `owl:DatatypeProperty`, and individual would be types as `gist:Person`, `gist:Magnitude`, etc.

**Comment by uscholdm** [comment]
@rjyounes The `NamedIndividual` issue has been resolved by a new option in the serializer to remove them. 

There are still a bunch of individuals that are explicit instances of `owl:Thing`. They are all instances of UnitOfMeasure.  I ran a test by loading into Protege, removing all and saving out the file to see if they were re-introduced. They were not.

Options for moving forward:
1. just close the issue because the units are being refactored, and `owl:Thing` will not be re-introduced.
2. add a SHACL check to catch any that might get introduced later on.

**Comment by rjyounes** [comment]
Let's close this for now. Maybe add an issue to add a SHACL check with a warning.

**Comment by uscholdm** [comment]
@rjyounes  From 12.0.1 release notes:
- Added missing `owl:Thing` assertions to gist instances to ensure that `rdfs:isDefinedBy` assertions are generated during the release bundling process. Issue [#775](https://github.com/semanticarts/gist/issues/775).

But we could strip them off again after generating `rdfs:isDefinedBy` assertions. What do you think? They are unsightly.

**Comment by rjyounes** [comment]
The onto_tool behavior has been [fixed](https://github.com/semanticarts/ontology-toolkit/pull/113). We need to modify the gist `bundle.yaml` file to apply the new option `strict` that is not dependent on `owl:Thing` assertions. We can then remove the `owl:Thing` assertions.

**Comment by rjyounes** [comment]
Closing - this is an old issue and there are no longer any `owl:Thing` assertions in the ontology.
