### ISSUE TITLE
Remove hasMember and memberOf domain/range axioms

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#299]
Currently these are gist:Collection.

Aside from the simple error in #142, which has a straightforward fix, there's a bigger question of whether things like organizations, families, clubs, teams, etc should be considered collections. The class Organization is not defined as a subclass of Collections.

The definition of Organization also comments that it may not have members; is that correct? It may not have current members, but does it by definition have the potential to have members? Without members it's an empty Collection. Can we have empty Collections? 

Note: I thought this question had been raised in a different issue, but am unable to find it. If found they should be collapsed.

**Comment by rjyounes** [comment]
Yes, I agree.

**Comment by DougalW** [comment]
> The definition of Organization also comments that it may not have members; is that correct? 

There's an interesting new form of organization called Decentralized autonomous organization - it essentially has no physical members, just blockchain rules.

**Comment by rjyounes** [comment]
That's intriguing. I had a simpler case in mind, a newly-formed organization that as yet has no members, but yours is an excellent example as well.

**Comment by uscholdm** [comment]
While true, this is about cardinality, NOT the issue at hand, which is domain & range.

**Comment by rjyounes** [comment]
You're right, I shouldn't have gone down that detour.

**Comment by rjyounes** [comment]
Has been fixed somewhere along the line.
