### ISSUE TITLE
Change the definition of 'precedes' to exclude same order

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#300]
From Phil Blackwell via email.

Definition of gist:precedes is "A generic ordering relation indicating that the Subject has the same order as or comes before the Object. The 'greater than or equal to' symbol is often used for this relation."

Phil notes that the relevant symbol is <= rather than >=.

I am now wondering whether it shouldn't be simply < rather than <=. The former aligns better with our common sense understanding. Then the first part of the definition must also change.

**Comment by rjyounes** [comment]
Michael commented on #550 on Sept 3, 2021. The comment seems to have gone missing.  

"This is now moot, but just for some background. In mathematics there is a standard convention to have a ordering relation R and  version that is strictlyR .E.g. precedes and strictlyPrecedes. That is the convention that I adopted. "

**Comment by uscholdm** [comment]
Thanks - I guess you can close this now...

**Comment by rjyounes** [comment]
@uscholdm Why do you propose closing this? It should not be assumed that we are going to follow the mathematical definition rather than the common sense one. (See similar comment on #570.)

**Comment by rjyounes** [comment]
Add scope note on how to indicate items in the same position (they directly precede or directly follow the same item, or have the same sequence number).

**Comment by philblackwood** [comment]
If A precedes B, we could write A <= B.
 
The current definition uses the wrong sign:
 
skos:definition "A generic ordering relation indicating that the subject has the same order as or comes before the object. The '**greater** than or equal to' symbol is often used for this relation."
 
It should be changed to:
 
skos:definition "A generic ordering relation indicating that the subject has the same order as or comes before the object. The '**less** than or equal to' symbol is often used for this relation."

**Comment by rjyounes** [comment]
I also added the predicate `gist:follows`, alongside `gist:precedes`, `gist:precedesDirectly`, and `gist:followsDirectly`. It appears to be an unintentional omission.

**Comment by uscholdm** [comment]
This has been implemented by #737
