### ISSUE TITLE
Add Magnitude as domain of hasPrecision

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#302]
From Phil Blackwood via email.

On the other hand, the comment reads: "NOTE:  Most frequently apples to Magnitude(s) and TimeInstant. Could also apply to a measurement."

The question would thus be, define a union domain or leave it open, as currently.

**Comment by uscholdm** [comment]
Keep it simple, leave it open. Murphy says that the minute we close it is exactly when the need arises for a broader interpretation.

**Comment by rjyounes** [comment]
+1. I'm only the messenger.

**Comment by uscholdm** [comment]
> I didn't suggest making a change, only pointed out where hasPrecision is most commonly used.

This is the sort of thing that we could use the  suggestion about an   annotation property for indicating intended domains and ranges.  See: issues: https://github.com/semanticarts/gist/issues/389 and https://github.com/semanticarts/gist/issues/472

**Comment by uscholdm** [comment]
DEFERRED: until there is a revision to units and magnitudes in a future major release. #697
