### ISSUE TITLE
Should we convert gist to use our standard namespace conventions?

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#305]
We have 3 namespaces for our client ontologies. 
1. for the TBox  (e.g. pleo)
2. for the CBox (e.g. pleox)
3. for the ABox (e.g. pleod) where d is for data. should have been called the DBox.

I propose that we use this convention for gist, introducing a gistx namespace for the handful of individuals we have, e.g. units of measure etc.  We probably do not need a gistd.

**Comment by rjyounes** [comment]
Including comment from #522: gist media types is a taxonomy, so URI should be https://taxonomies.semanticarts.com/t/gistMediaTypes, which is being closed as a duplicate.

**Comment by rjyounes** [comment]
Defer until #61 is implemented so we don't change the names more than once.

**Comment by dylan-sa** [comment]
I believe the initial thought was that it would affect reasoning, given that units of measure appear in class definitions. For example, given the definition of `gist:DataSizeUnit`, an instance of this class (e.g., `:_gigabyte`) would be inferred to have a base unit of `gist:_bit`. After the change, the same instance would be inferred to have a base unit of `gistx:_bit`. Even so, I can see how this kind of effect might not rise to the level of a major change.

**Comment by rjyounes** [comment]
It doesn't matter, since they'd be owl:sameAs'd to one another.

**Comment by rjyounes** [comment]
Relates to reference data issues: #1036, #1037

**Comment by rjyounes** [comment]
@uscholdm I believe this is already assumed by the use of the `gistd:` namespace for units of measure. Can we close this issue?

**Comment by uscholdm** [comment]
> @uscholdm I believe this is already assumed by the use of the `gistd:` namespace for units of measure. Can we close this issue?

@rjyounes The original proposal was to have units be in a gistx namespace.  A unit such as mm can correctly be construed as being a category for Magnitudes that use mm as its unit. Because gist is an ontology for the enterprise, it was never intended to include enterprise data.  Units are part of the subject matter vocabulary that is used in enterprise data.

We may disagree on this point, which is fine, however it is appropriate to bring in other opinions and get consensus or vote.

**Comment by rjyounes** [comment]
Yes, we will have to disagree. IMO a unit of measure has a number of properties that make it an instance rather than a category. I also noticed that @philblackwood assumed the use of a data namespace, `gistd:`. However, you're right that it's worth a discussion.

**Comment by uscholdm** [comment]
> Yes, we will have to disagree. IMO a unit of measure has a number of properties that make it an instance rather than a category. 

It's a general guideline, not necessarily a hard and fast rule that a category has no properties.   
It's also a general guideline that enterprise ontologies do not have data in them, they have classes, properties, a few special instances and categories, but no data. Gist is the basis for enterprise ontologies, so it should not have data.

So one guideline says a unit cannot be a category.
Another guideline says a unit should not be enterprise data.

I think that one of those guidelines will have to be relaxed.

**Comment by rjyounes** [comment]
> It's a general guideline, not necessarily a hard and fast rule that a category has no properties.

I do occasionally attach properties to categories, e.g., ranking. However, a uom doesn't feel like a "bucket" or label.

> It's also a general guideline that enterprise ontologies do not have data in them, they have classes, properties, a few special instances and categories, but no data. Gist is the basis for enterprise ontologies, so it should not have data.

Why wouldn't uoms qualify as "a few special instances"?

> So one guideline says a unit cannot be a category.
Another guideline says a unit should not be enterprise data.

I think the primary task is to figure out what a uom is, then decide where it goes.

Finally: doesn't the plan to put uoms in a separate ontology of reference data (#1036) obviate the issue of putting data into the ontology?

**Comment by uscholdm** [comment]
So, we are ok in principle with putting properties on categories in appropriate circumstances. 
Is there an argument that says gist units should be enterprise data, as opposed to representing the subject matter, which is what our categories do?

Units are not slam-dunk categories, but is is semantically coherent to view a unit as categorizing Magnitudes. 5mm, 240mm and .5 mm are all in the category of magnitudes that have mm as their unit.

Fortunately the choice we make may have zero practical implications, so it's is more a matter of taste.
