### ISSUE TITLE
PhysicalIdentifiableItem should not have an identifiedBy restriction

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#306]
As I understand it, a PhysicalIdentifiableItem is any discrete thing, like a table, a book, a plant, as opposed to a PhysicalSubstance like water, sugar, oil - essentially these capture the distinction between count and mass nouns in English. Surely not all of these are expected to have an ID.

**Comment by rjyounes** [comment]
As an aside, because the range of identifiedBy is ID, you don't need to state a someValuesFrom ID restriction - it would be (if it were correct) more concisely expressed as a min cardinality constraint. Ditto for madeUpOf.

**Comment by uscholdm** [comment]
I agree that the identifiedBy restriction is incorrect. What is closer to correct is that in principle it would be possible for something to have an identifier, not that it does in fact have one.

**Comment by rjyounes** [comment]
Closing: fixed in PR #676.
