### ISSUE TITLE
Consider syntactic variants of multiple subclass assertions in gist style guide

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#307]
The following are syntactically/stylistically different, semantically identical variants:

```
<owl:Class rdf:about="&gist;PhysicalIdentifiableItem">
        <rdfs:subClassOf>
                <owl:Restriction>
                        <owl:onProperty rdf:resource="&gist;hasMagnitude"/>
                        <owl:someValuesFrom rdf:resource="&gist;Volume"/>
                </owl:Restriction>
        </rdfs:subClassOf>
        <rdfs:subClassOf>
                <owl:Restriction>
                        <owl:onProperty rdf:resource="&gist;hasMagnitude"/>
                        <owl:someValuesFrom rdf:resource="&gist;Weight"/>
                </owl:Restriction>
        </rdfs:subClassOf>
<owl:Class>
```

```
<owl:Class rdf:about="&gist;PhysicalIdentifiableItem">
        <rdfs:subClassOf>
                <owl:Class>
                        <owl:intersectionOf rdf:parseType="Collection">
                                <owl:Restriction>
                                        <owl:onProperty rdf:resource="&gist;hasMagnitude"/>
                                        <owl:someValuesFrom rdf:resource="&gist;Volume"/>
                                </owl:Restriction>
                                <owl:Restriction>
                                        <owl:onProperty rdf:resource="&gist;hasMagnitude"/>
                                        <owl:someValuesFrom rdf:resource="&gist;Weight"/>
                                </owl:Restriction>
                        </owl:intersectionOf>
                </owl:Class>
        </rdfs:subClassOf>
</owl:Class>

```
Adopt one of these styles and document in style guide.

(I personally prefer the second variant, but consensus is required.)

**Comment by uscholdm** [comment]
This may be a tool thing. Hardly anybody will type in such axioms. They will use a tool (e.g. PRotege) which will decide how to write the triples. A different tool may make a different choice. Two version of 100% correct OWL. Many people creating ontologies will never need to look at nor know about such differences.  

Does the same difference also show up in Turtle syntax? I'm guessing yes. 

There is a potential argument for post processor to make sure the same conventions is used across the board.  Ideally the rdf serializer would do that, but my guess is that it does not.  Rather it will faithfully represent triples in one style or the other, depending on what the input is.

**Comment by uscholdm** [comment]
@rjyounes 
We are now using Turtle, so if we still care about this distinction, the two styles should be redone.  With luck, the serializer will render them both the same and this becomes a non-issue, so to speak.

My guess is the serializer will not have them be the same. This is something that is so minor that I don't think we should have a preferred style. They both mean exactly the same thing.
