### ISSUE TITLE
New subclass of Event: Determination

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#317]
There are many examples of events whose central purpose is to determine some kind of  result, value or outcome.  Determinations will always have:
1. Method what was done to make the determination - (e.g. manual process, algorithm)
2. Result: usually a value or a category or some sort
3. Performer: of the determination (a person, a program/application)
4. Date performed (inherited from Event)

The most common  examples in my experience are:
- Measurement
    - the sulphur content of Brent crude
    - blood pressure
- Evaluation - based on quality.  
    - loan approval (from FIBO)
    - how good of a modeler is an interviewee?
- Assessment [quality-neutral]
    - What will the price of Brent crude be next month?
- Classification: what category does something belong in?
    - is a person short, medium height or tall?

There is a a bit of overlap here.  
- Sometimes categories will be in some kind of notional order, which makes it more like (e.g. bad, neutral, good).  
- the word Assessment often is used in the context of quality.

**Comment by uscholdm** [comment]
@rjyounes I'd like for this to be addressed by the group.

**Comment by rjyounes** [comment]
Added to 12.1.0 project for review.

**Comment by rjyounes** [comment]
Also includes an approval decision - I.e., the act of approving.

**Comment by uscholdm** [comment]
A `Determination` need not be historical, it may be planned but unscheduled, or scheduled, in the process of happening, or already happened. Thus it should be a subclass of `gist:Event`.
