### ISSUE TITLE
Support content negotiation for direct HTTP access of Gist

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#318]
Even if gist is edited in turtle (#223), it should be accessible on the web in multiple formats, with some default format. 

Propose: the default format is RDF/XML (most universally acceptable).  
Propose: we support Accept requests for rdf/xml, turtle, ntriples, JSON-LD.  

Ref. https://www.w3.org/TR/swbp-vocab-pub/#negotiation

**Comment by uscholdm** [comment]
I like this suggestion. Note that Widoco output has a place for clicking which format you want. Very handy.

**Comment by JonathonGist** [comment]
I like it! I think this will improve access to gist for the world.

**Comment by rjyounes** [comment]
Relates to #130

**Comment by rjyounes** [comment]
Currently this works for ttl, rdf/xml, and json-ld (those generated in release package).

**Comment by rjyounes** [comment]
Closing since three formats are already supported.
