### ISSUE TITLE
Support multiple formats in gist bundling

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#319]
When we bundle gist as a ZIP file to put on our website, should we only provide the Turtle serialization (#223), or should we also provide other formats?

Propose: we provide 3 formats, Turtle, JSON-LD, and RDF/XML.  

This may somewhat overlap with the issue about Widoco (#170)

**Comment by Jamie-SA** [comment]
The document you mentioned in #318 and other things I've read lead me to the conclusion that RDF/XML needs to be provided as the default type. Other formats should be in addition to that.

**Comment by sa-bpelakh** [comment]
We can modify bundle.yaml to generate all 3 for the zip file, then nginx mapping can handle the rest.

**Comment by rjyounes** [comment]
.owl extension shouldn't be used because it specifies content rather than format.

**Comment by rjyounes** [comment]
Release notes should mention that scripts etc might be impacted.

**Comment by marksem** [comment]
Use these suffixes, respectively for the bundled serializations:   **.ttl, .jsonld .rdf**
