### ISSUE TITLE
Remove gist:characterizedAs and use gist:categorizedBy

### ISSUE THREAD

**Issue by Jamie-SA** [semanticarts/gist#320]
This came from a discussion with @uscholdm. I was using gist:Transaction which is a gist:Event which has:
`(characterizedAs some Behavior)`.

gist:Behavior is a subClassOf gist:Category.

I think Michael said that he thought we don't need both characterizedAs and categorizedBy. And some other stuff but I won't try to remember exactly what he said.

**Comment by uscholdm** [comment]
A bit of history here.  `gist:characterizedAs` was  a way to indicate what kind of event something was based on the kind of thing that was done (cutting, extruding etc).  Initially, Behavior was not a subclass of `gist:Category`, so a separate property was used. Later on we realized that `gist:Behavior` was best modeled as a subclass of `gist:Category` which was done a few years ago.  

Only today, thanks to Jamie, did I realize that the property `gist:characterizedAs` in in fact superfluous.  The property is only used once, in the definition of `Event` which is `equivalentClass` to 
- `(gist:characterizedAs some gist:Behavior) and 
(gist:end some gist:TimeInstant) and 
(gist:start some gist:TimeInstant)`

This says every event is `gist:characterizedAs`  some `gist:Behavior`. I think this is incorrect. Some events happen, and nothing much is done, per se.  Characterizing the nature of what is done, if needed, is a job for SHACL.

I 'used' Behavior and characterized extensively in my first ontolgoy at SA, Sentara. But what I did was not useful, it was just an echo of an event hierarchy.  After that, I never used it.  It's unlikely to be missed. I was explaining to Jamie that some of the restrictions we have are there mostly to communicate meaning to humans, and that in practice, they never give rise to triples.  Another example of this is the `affectedBy` property connecting a `Transaction` to an `Account`. One affect of a payment transaction is to decrease a balance. That is an affect, but there is no point for making an `affectedBy` triple for that. A more specific property would be used.

PROPOSAL
1. deprecate the property gist:characterizedBy
2. remove the equivalentClass axiom and replace it with two subclass restrictions. 
3. optional: in a skos:note, suggest that one way to characterize events is by a behavior.

Given it was rarely/never used, I am against the 3rd point. Better perhaps to say that there are all kinds of events having different properties. Some but not all have place, some but not all have an agent doing something. etc.

**Comment by Livier13** [comment]
Insightful part of history.

**Comment by rjyounes** [comment]
+1 for deprecating/deleting it.

**Comment by uscholdm** [comment]
@rjyounes This should be closed. The `isCharacterizedAs` was deprecated in PR #951 relating to issue #820

**Comment by rjyounes** [comment]
Closing as per preceding comment.
