### ISSUE TITLE
Review union class equivalence assertions for accuracy

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#322]
Issue #110 started as the general issue of union class equivalence constraining use, and gave gist:Artifact as an example. Because we noted other problems with the definition of gist:Artifact, the original issue was morphed into one dealing solely with that class definition, and the general issue is now re-created here. The original description of #110 reads as below. This issue now proposes reviewing each of these union class equivalences for possible removal on these grounds.

When a class is defined as the union of a set of other classes, it is not possible to define additional subclasses that are not also subclasses of one of the members of the union. Is this by intention? It makes extension difficult. 

For example:

```
	<owl:Class rdf:about="&gist;Artifact">
		<rdfs:label rdf:datatype="&xs;string">Artifact</rdfs:label>
		<rdfs:comment rdf:datatype="&xs;string">An intentional person made thing, could be physical or content</rdfs:comment>
		<owl:intersectionOf rdf:parseType="Collection">
			<owl:Class>
				<owl:unionOf rdf:parseType="Collection">
					<rdf:Description rdf:about="&gist;Content">
					</rdf:Description>
					<rdf:Description rdf:about="&gist;IntellectualProperty">
					</rdf:Description>
					<rdf:Description rdf:about="&gist;Equipment">
					</rdf:Description>
					<rdf:Description rdf:about="&gist;Building">
					</rdf:Description>
					<rdf:Description rdf:about="&gist;PhysicalSubstance">
					</rdf:Description>
				</owl:unionOf>
			</owl:Class>
			<owl:Restriction>
				<owl:onProperty rdf:resource="&gist;goal"/>
				<owl:someValuesFrom rdf:resource="&gist;Function"/>
			</owl:Restriction>
		</owl:intersectionOf>
	</owl:Class>
```
Because this is a closed list, an ontology importing gist cannot define another direct subclass of Artifact.

In fact, we see already this problem within gist itself. System is a subclass of Artifact, but it is not asserted to subclass any of the unioned classes. Do we really want to say that System is a direct subclass of one of these, but we don't know which? Seems odd. And none of the unioned classes seem like appropriate superclasses of System.

**Comment by rjyounes** [comment]
Mark is having problems with this in MS SeatLocation - wants to make it a subset of Place but can't. 

This is a major change, unless we call it a bug.

Michael: though technically this affects inferencing, we shouldn't have to call this major because it doesn't have a significant impact on anything.
Need to revisit definition of major/minor/patch?

MarK doesn't want to find all the cases, but volunteers to take care of Place.

MarC will find all the cases and make an issue for each. Assign the Place issue to MarK. (Search for unionOf)

**Comment by rjyounes** [comment]
Rebecca: update our notes on versioning to indicate guidelines vs hard-and-fast rules.

**Comment by rjyounes** [comment]
It now seems to me that the problem is even broader - _any_ reference to a union class, whether it be a superclass, domain, range, or allValuesFrom is _potentially_ problematic in the same way. For example:

```
	<owl:ObjectProperty rdf:about="&gist;governs">
		<rdfs:label rdf:datatype="&xsd;string">Governs</rdfs:label>
		<rdfs:comment rdf:datatype="&xsd;string">The subject controls or inhibits the object in some way</rdfs:comment>
		<rdfs:domain>
			<owl:Class>
				<owl:unionOf rdf:parseType="Collection">
					<rdf:Description rdf:about="&gist;Intention">
					</rdf:Description>
					<rdf:Description rdf:about="&gist;Organization">
					</rdf:Description>
					<rdf:Description rdf:about="&gist;Person">
					</rdf:Description>
					<rdf:Description rdf:about="&gist;Template">
					</rdf:Description>
				</owl:unionOf>
			</owl:Class>
		</rdfs:domain>
          etc.
	</owl:ObjectProperty>
```

**Comment by rjyounes** [comment]
I'm now thinking we don't want to tackle these cases here: it gets us into the larger issue of domain and range constraints. So let's just stick to the original issue of equivalentClass here.

**Comment by rjyounes** [comment]
Note that in some cases these equivalences are definitional and therefore valid; e.g., CoherentUnit.

**Comment by mdfeickert** [comment]
Created "Cannot create subclasses of **Place** since it is a Unioned class #343" for Place class.

**Comment by rjyounes** [comment]
This issue itself does not involve any changes, so has no impact.
