### ISSUE TITLE
Should some parts of gist be re-modularized?

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#323]
Were we overzealous in de-modularizing all of gist? Perhaps there are some truly separable modules.

Caution: in many cases, modularization was not viable because, due to dependencies, one of the terms had to be in gistTop. This was true of gistNetwork and also, I believe, gistIoT. We should study the history pre-modularization to avoid recreating the same problem.

**Comment by rjyounes** [comment]
An ontology versioning ontology (Michael and Boris are working on one) is a good candidate for a separate module.

**Comment by rjyounes** [comment]
Dave is also working on a software ontology.

**Comment by rjyounes** [comment]
We should consider whether these modules should have different namespaces, so that there is real modularity rather than just the intention of modularity. One of the reasons given for using a single namespace was for refactoring - moving terms from one module to another - but I see this as just a signal that these were not truly separable modules. If something is clearly separable as a module then it should have its own namespace.

**Comment by rjyounes** [comment]
From Dave: IoT should be taken out of core.

**Comment by marksem** [comment]
See #66 re adding to gistIoT

**Comment by rjyounes** [comment]
Candidates:
- IoT - sensor, actuator, etc. but not network because it has a more general usage)

**Comment by rjyounes** [comment]
Units and magnitudes are a good candidate for modularization, so we'll add it to that bucket.

What about IoT? This should arguably be a separate gist ontology (like accounting, HR, etc.).

**Comment by rjyounes** [comment]
DECISION: We will create a new ontology file for IoT.
