### ISSUE TITLE
remove gist:geoDirectlyContains and gist:geoDirectlyContainedIn

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#328]
gist:geoDirectlyContains and gist:geoDirectlyContainedIn should be removed, because "direct containment" in the geographic area is problemmatic.  See #115 which discusses the geo direct containment issue at length.

**Comment by rjyounes** [comment]
@marksem Do we need this issue, since it's wholly subsumed in #115?

**Comment by marksem** [comment]
#115 seems to broad to move.  Trying to make this small and atomic.

**Comment by uscholdm** [comment]
> That one was about hasDirectPart, not geoDirectlyContains.
https://github.com/semanticarts/gist/issues/115 is about the whole hasX/hasDirectX pattern.

**Comment by rjyounes** [comment]
If we want to move on #115, we should break it up into individual tasks for each predicate, as you've done here, since, as I comment there, I do not expect a single, blanket solution for all cases.

**Comment by sa-bpelakh** [comment]
Deprecate as minor change, remove in next major version.
