### ISSUE TITLE
Values restrictions shouldn't duplicate property range

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#341]
It is not necessary to restate the range of a property in a property restriction. For example:

```
	<owl:Class rdf:about="&gist;Message">
		<rdfs:label rdf:datatype="&xsd;string">Message</rdfs:label>
		<rdfs:comment rdf:datatype="&xsd;string">A specific instance of content sent from an Organization, Person, or Application to at least one other Organization, Person, or Application.</rdfs:comment>
		<rdfs:comment rdf:datatype="&xsd;string">EXAMPLES: An email message, a phone call, a voice message, or a Web Service message.</rdfs:comment>
		<owl:equivalentClass>
			<owl:Class>
				<owl:intersectionOf rdf:parseType="Collection">
					<rdf:Description rdf:about="&gist;ContentExpression">
					</rdf:Description>
					<owl:Restriction>
						<owl:onProperty rdf:resource="&gist;fromAgent"/>
						<owl:someValuesFrom>
							<owl:Class>
								<owl:unionOf rdf:parseType="Collection">
									<rdf:Description rdf:about="&gist;Address">
									</rdf:Description>
									<rdf:Description rdf:about="&gist;Organization">
									</rdf:Description>
									<rdf:Description rdf:about="&gist;Person">
									</rdf:Description>
								</owl:unionOf>
							</owl:Class>
						</owl:someValuesFrom>
					</owl:Restriction>
                                   ...
				</owl:intersectionOf>
			</owl:Class>
		</owl:equivalentClass>
	</owl:Class>
```
The range of fromAgent is the union of Address, Organization, and Person. IMO it's preferable to state this as a minCardinality restriction, or at least someValuesFrom owl:Thing, in order to avoid logical redundancy and giving the false impression that we are saying something new. In most contexts we strictly avoid redundant axioms - e.g., in stating an inverse, domain, and range on only one of two inverse properties.

A similar example is the hasParty restriction on Agreement.

**Comment by uscholdm** [comment]
As it stands, it is logically redundant.  And in a static world that would be the end of it. But as a modeler in a changing world, I know that a range may change, but I want to make sure that my restriction has the same filter.  Sometimes redundancy serves a purpose.   Having explicit imports instead of relying on transitivity is also strictly redundayt, but serves a purpose.

So my vote is to not just willy nilly remove all these w/o some thoughtfulness.

M>

**Comment by rjyounes** [comment]
Interesting point - I hadn't thought of looking at it that way. But since we control both the property and class definitions, I would imagine that before changing the range of a property we would check to see what that might affect. Then the restriction could be added if necessary. We don't have to guard against what we ourselves might do. What you say makes sense in the context of a client-defined class with a restriction on a gist property.

**Comment by uscholdm** [comment]
I don't mind either way.

**Comment by uscholdm** [comment]
@rjyounes This has been ongoing for a long time. Did we not address this recently?

**Comment by uscholdm** [comment]
@rjyounes 

> It's part of our internal cardinality discussion, so we can close the issue. It's not gist-specific in any case.

No, but the decision about cardinality could directly impact gist, and this issue would be alive again. I guess any cardinality decision would mean walk through all of gist to see what changes are warranted.
