### ISSUE TITLE
Cannot create subclasses of Place since it is a Unioned class

### ISSUE THREAD

**Issue by mdfeickert** [semanticarts/gist#343]
When a class is defined as the union of a set of other classes, it is not possible to define additional subclasses that are not also subclasses of one of the members of the union. Is this by intention? It makes extension difficult.

Specific example for Place:

	<owl:Class rdf:about="&gist;Place">
		<rdfs:label rdf:datatype="&xs;string">Place</rdfs:label>
		<rdfs:comment rdf:datatype="&xs;string">Union of all the geo classes</rdfs:comment>
		<rdfs:isDefinedBy rdf:resource="https://ontologies.semanticarts.com/o/gistCore"/>
		<owl:equivalentClass>
			<owl:Class>
				<owl:unionOf rdf:parseType="Collection">
					<rdf:Description rdf:about="&gist;GeoPoint">
					</rdf:Description>
					<rdf:Description rdf:about="&gist;GeoRegion">
					</rdf:Description>
					<rdf:Description rdf:about="&gist;GeoRoute">
					</rdf:Description>
					<rdf:Description rdf:about="&gist;GeoSegment">
					</rdf:Description>
					<rdf:Description rdf:about="&gist;GeoVolume">
					</rdf:Description>
					<rdf:Description rdf:about="&gist;Landmark">
					</rdf:Description>
					<rdf:Description rdf:about="&gist;Room">
					</rdf:Description>
				</owl:unionOf>
			</owl:Class>
		</owl:equivalentClass>
	</owl:Class>
	
Because this is a closed list, an ontology importing gist cannot define another direct subclass of Place.

**Comment by uscholdm** [comment]
This is true for all practical purposes.  For the pedants in our midst, strictly speaking, you can create new subclasses, e.g. LandMarkOrRoom .  But it cannot bring any new instances to the table - hence the original objection.
