### ISSUE TITLE
Rewrite website gist page

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#369]
@pwin has pointed out, and I agree, that the gist page on the website is inadequate: it should contain an overview of gist and what it's good for, a visualization. Should be in a less chatty style. The detailed release notes don't belong there, rather there should be a pointer to the release notes, as well as individual pointers to the other documentation in the repository (contributions, release management, style guide). Ditto for a handbook/cookbook type of document as envisioned in issue #286.

This could be the same or similar to the repository readme in issue #87. We may want to assign both issues to a couple of people to collaborate on.

This is not tied to a particular release, but I'll add it to the next release project so we can keep an eye on it.

**Comment by rjyounes** [comment]
Provisionally assigning this issue to @pwin and myself, at least to organize it.

**Comment by uscholdm** [comment]
@rjyounes 
What is the status of this?

**Comment by rjyounes** [comment]
Done.
