### ISSUE TITLE
Gist instances have no labels. 

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#370]
None of the 17 gist 9.4 individuals have a label (nor a comment).  

Propose we add labels and comments to these, per good practice.

**Comment by uscholdm** [comment]
Good idea.  This could be done in conjunction with moving gist to our standard namespace convention, per issue https://github.com/semanticarts/gist/issues/305

**Comment by rjyounes** [comment]
Submit one PR for #370, #526, and #556.

**Comment by rjyounes** [comment]
They also have no unitSymbols. Shouldn't those be added as well?
