### ISSUE TITLE
Add scopeNote to gist:Category referencing skos:Concept

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#374]
I think it is semantically correct to say that `gist:Category` is a subclass of `skos:Concept`. It is more specific in that instances are meant to categorize things, which is not true of all `skos:Concepts`, which can be anything.  Two options:

1. make that explicit in an axiom (perhaps by importing skos itself)
2. say so in an annotation

See also, issue https://github.com/semanticarts/gist/issues/373

**Comment by rjyounes** [comment]
We would need to import SKOS in any case if we want the broader(narrower)/broaderTransitive(narrowerTransitive) inferences, as in #373, which I think we would have to have, given that we just introduced transitivity and the direct/indirect distinction to the gist predicates for good reason. See #107 and #104.

**Comment by uscholdm** [comment]
@rjyounes I think we should not add it as a subclass. I am in favor of adding a scopeNote in the definition of `gist:Category`.  We do not want to be in the business of comparing gist with external ontologies in general, but it makes sense to do so for pervasively used concepts like, `skos:Concept`, so to speak.

**Comment by rjyounes** [comment]
@uscholdm Agree and have changed the issue name accordingly. Added to 12.1.0 project.

**Comment by rjyounes** [comment]
Closing. We've decided in the past that as a general practice we don't want to include such references in gist.
