### ISSUE TITLE
insufficient gist:recognizes comment

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#375]
The comment on gist:recognizes is the same as its label.  Insufficient textual definition.  Noticed in gist9.4.0.

**Comment by rjyounes** [comment]
This is subsumed by #534 but I'm leaving it open so we make sure to consider the specific issues addressed here.

**Comment by uscholdm** [comment]
SUGGESTION: close, no longer relevant.  What we now have is:
```
gist:isRecognizedBy
	a owl:ObjectProperty ;
	rdfs:range [
		a owl:Class ;
		owl:unionOf (
			gist:Organization
			gist:Person
		) ;
	] ;
	skos:definition "The entity that formally acknowledges the existence of, as the State recognizes the existence of a particular company"^^xsd:string ;
	skos:prefLabel "is recognized by"^^xsd:string ;
	.
```

**Comment by rjyounes** [comment]
Closing - no longer relevant.
