### ISSUE TITLE
Add rdfs:comment and rdfs:labels into a separate file in case anyone wants them.

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#379]
After Issue https://github.com/semanticarts/gist/issues/351 is implemented, I think we agreed to have the file around as an optiona import. Not sure if it should go into the deprecated file, or a new file called, say deprecatedAnnotations.

This way, we can keep the conversion to skos as a change of lesser significance. 

Michael

**Comment by rjyounes** [comment]
We discussed this and agreed that Boris would automate that process. It should not go into gistDeprecated because you don't deprecate a triple.

**Comment by rjyounes** [comment]
Fixed in PR #380

**Comment by rjyounes** [comment]
@sa-bpelakh @uscholdm I'm assuming we will NOT regenerate this file in subsequent releases. I.e., only existing RDFS annotations are supported moving forward. Is that your understanding?
