### ISSUE TITLE
Magnitude and Unit IRIs are not named consistently 

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#381]
Follows consistent pattern:
- Area/AreaUnit
- Duration/DurationUnit
- ElectricCurrent/ElectricCurrentUnit
- LuminousIntensity/LuminousIntensityUnit
- Mass/MassUnit

Does not follow consistent pattern:
- Count/CountingUnit
- Extent/DistanceUnit
- InformationQuantity/DataSizeUnit
- MolarQuantity/MoleUnit
- Monetary/CurrencyUnit

Some of these are no-brainers, others not so obvious if there is a good alternative. Here are some ideas. Boldface indicates a change.

- Count/**CountUnit**
- **Distance**/DistanceUnit
- **DataSize**/DataSizeUnit
- **MoleCount**/**MoleCountUnit**  WIkipedia says a mole is a "count of particles"
- **Currency/CurrencyUnit**

**Comment by uscholdm** [comment]
DEFERRED: until there is a revision to units and magnitudes in a future major release. #697

**Comment by philblackwood** [comment]
Will be addressed in new Units of Measure (which will not use these subclasses).

**Comment by uscholdm** [comment]
CLosing as not planned
