### ISSUE TITLE
Make uniqueText a subproperty of containedText

### ISSUE THREAD

**Issue by stewardont** [semanticarts/gist#387]
I'm guess that's what uniqueText is intended to be. If not that should be clarified.

**Comment by rjyounes** [comment]
@stewardont Currently containedText defines a domain of Text (in the human-readable definition, but not formally), so there are additional repercussions to this change. There is discussion of the various text properties, along with your suggestion, in #372, so I'm going to close out this issue.

**Comment by rjyounes** [comment]
Subsumed by #372.
