### ISSUE TITLE
Add annotation properties to indicate intended usage of properties AND 'min 0' begone. 

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#389]
A common problem is over-constraining the domain or range of a property.  One can err on the side of adaptability by having no domain or range, but then there is no information about its likely use. 

For example, the property `formerlyPartOf` is being used at Platts to indicate that Ukraine was part of the Soviet Union. For the foreseeable future this will only be used when the subject and object are both instances of `pleo:Region`.  I want to indicate this w/o having it be the domain and range, because lots of things can be former parts of other things.  I propse doing the followign:

```
pleo:domainIncludes rdfs:subPropertyOf skos:scopeNote .
pleo:rangeIncludes  rdfs:subPropertyOf skos:scopeNote .
pleo:formerlyPartOf pleo:domainIncludes pleo:Region .
pleo:formerlyPartOf pleo:rangeIncludes pleo:Region .
```

This also eliminates the temptation to add a min 0 - restriction on the class `pleo:Region`.

**Comment by uscholdm** [comment]
> Where does 'min 0' come into play here?

If the restriction on the class Mammal (hasTusk min 0). I'm hinting that some mammals have tusks. 
I can put that information in the property, hasTusk by saying domainIncludes Mammal.

**Comment by rjyounes** [comment]
Agreed - definitely better to use an annotation to annotate rather than an axiom.

**Comment by uscholdm** [comment]
Here are the schema.org versions. They are pure rdf and rdfs, not owl.

```
schema:domainIncludes a rdf:Property ;
    rdfs:label "domainIncludes" ;
    rdfs:comment "Relates a property to a class that is (one of) the type(s) the property is expected to be used on." ;
    schema:domainIncludes schema:Property ;
    schema:isPartOf <https://meta.schema.org> ;
    schema:rangeIncludes schema:Class .

schema:rangeIncludes a rdf:Property ;
    rdfs:label "rangeIncludes" ;
    rdfs:comment "Relates a property to a class that constitutes (one of) the expected type(s) for values of the property." ;
    schema:domainIncludes schema:Property ;
    schema:isPartOf <https://meta.schema.org> ;
    schema:rangeIncludes schema:Class .
```

**Comment by rjyounes** [comment]
Re-opening this issue: see discussion thread on #487. I'm inclined to delete the annotation properties we defined and use schema's instead.

**Comment by rjyounes** [comment]
Why didn't we want to use the schema properties? We will use these as annotation properties and don't affect reasoning.
Jamie: nice to keep gist self-contained.
Michael: but we already use skos annotations.
Michael: if we refer to a schema property in gist, and we save out the file from Protege, Protege declares the property in the gist. 
Mark uses Protege to write files.
Serializer apparently removes the stubs.

DECISION: Stick with earlier decision to define our own properties. The implications of using RDF properties in an OWL ontology are unclear.
