### ISSUE TITLE
Add Address as range of toPlace/fromPlace

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#392]
Assigned to MarkW to explore and bring back next time.

**Comment by uscholdm** [comment]
Any enterprise that ships anything from tankers full of oil to post cards will have core class which is the event of sending something from somewhere to somewhere else.    So we need an answer to the two questions: 
1. where is the item coming from?
2. where is the item going to? 

That is exactly what toPlace and fromPlace are for. What are different ways to answer this question?
- A postal or shipping service would typically use addresses for both.
- An oil tanker would come from a port to another port (e.g. in Platts)
- Interoffice delivery in  large enterprise might deliver from warehouses or possibley individual rooms.

We do not want lots of properties such as: toAddress/fromAddress and toPort/fromPort and toRoomNumber and fromRoomNumber. One property should suffice.  A room number could be considered an address, where the room is the place.

This is easily handled by extending the range of toPlace and fromPlace to include Address. I cannot think of anything else that it might be.  This does not seem controversial. Can anyone who objects to this explain the problem that this solution is likely to causes in a practical enterprise context?

If I was extending gist for this purpose, I would be annoyed by having to create a new property so I could answer the 'where do I sent this package to' question with an address, I would have to add a new property. That is bad.

A fall back option is to remove the range entirely.

**Comment by rjyounes** [comment]
I'm definitely opposed to removing the range altogether. I still have to ponder the main issue.

**Comment by rjyounes** [comment]
DECISION: Implement this change.

**Comment by marksem** [comment]
So the implementation will be to declare the range of toPlace to be (Address or Place)?  Same for fromPlace?

**Comment by rjyounes** [comment]
Yes

**Comment by marksem** [comment]
Is this major, since it changes reasoning? @rjyounes @uscholdm @pwin

**Comment by rjyounes** [comment]
Yes, it is. We can move it to May since April is no longer a major release. I don't think you were present for that decision.
