### ISSUE TITLE
Is there a good reason for gist:name to be a data property rather than an annotation property?

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#394]
Attn: @sa-bpelakh 

We are representing regions for one of our clients, and they are paying particular attention to prefLabels and altLabels, as well as creating a way to resolve  ambiguous labels like "New York" that could refer to a port, a city or a state.   Often a country has a common name that is used for most purposes and is the prefLabel, but also has an official name which is often longer, but not used very often.

The question arises: why are names not labels?  We have a property for hasOfficialName that is a subproperty of gist:name. The question arose as to whether any kind of name should also be an altLabel. It stands to reason to do so.  That could be accomplished by having gist:name be a subproperty of skos:altLabel. 

Is there a good reason to not do this?

**Comment by rjyounes** [comment]
Interesting that I have the opposite take on this in #427. In addition, our decision to make `gist:description` a datatype rather than annotation property has relevance here.

**Comment by uscholdm** [comment]
@rjyounes 
I now think this is not worth worrying about.  Even if we found a coherent argument that it might have made more sense back in the day, I cannot think of any advantages of making the change at the moment. I recommend we close this issue.
