### ISSUE TITLE
Definition of gist:Message is out of sync with the formal definition

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#396]
Human-readable definition (before update to SKOS annotations):

```
	rdfs:comment
		"A specific instance of content sent from an Organization, Person, or Application to at least one other Organization, Person, or Application."^^xsd:string ,
		"EXAMPLES: An email message, a phone call, a voice message, or a Web Service message."^^xsd:string
		;
```

Formal definition: 

```

	owl:equivalentClass [
		a owl:Class ;
		owl:intersectionOf (
			gist:ContentExpression
			[
				a owl:Restriction ;
				owl:onProperty gist:fromAgent ;
				owl:minCardinality "1"^^xsd:nonNegativeInteger ;
			]
			[
				a owl:Restriction ;
				owl:onProperty gist:toAgent ;
				owl:minCardinality "1"^^xsd:nonNegativeInteger ;
			]
		) ;
	] ;
	.
```

NOTE: This formal definition has been modified in PR #395. See notes there on rationale. Previously it was 

```
	owl:equivalentClass [
		a owl:Class ;
		owl:intersectionOf (
			gist:ContentExpression
			[
				a owl:Restriction ;
				owl:onProperty gist:fromAgent ;
				owl:someValuesFrom [
					a owl:Class ;
					owl:unionOf (
						gist:Address
						gist:Organization
						gist:Person
					) ;
				] ;
			]
			[
				a owl:Restriction ;
				owl:onProperty gist:toAgent ;
				owl:someValuesFrom [
					a owl:Class ;
					owl:unionOf (
						gist:Address
						gist:Organization
						gist:Person
					) ;
				] ;
			]
		) ;
	] ;

	.
```
We removed `Address` from the ranges of `toAgent` and `fromAgent` in issue #391. In coming across the definition of `Message`, rather than remove `Address` there as well, I replaced the `someValuesFrom` restriction with a `minCardinality` restriction, since the `unionOf` simply restates the property ranges.

This re-raises the issue of defining a `SoftwareAgent` or `SoftwareApplication` class. This is not the only time it is referenced in conjunction with `Person` and `Organization`. See, for example, the definition of `Event`:

```
Something happening over some period of time, often characterized as some kind of activity being carried out by some person, organization, or software application.
```

Should we have a class `SoftwareAgent` or `SoftwareApplication` to be added to the ranges of `fromAgent` and `toAgent`? 

This question was raised previously in the closed issue #132, where the addition of an `Agent` class was rejected. But we did not deal in depth with the issue of software agents. We should either revisit this or adjust the human-readable definitions of `Message`, `Event`, and any others, accordingly.

**Comment by uscholdm** [comment]
> Should we have a class SoftwareAgent or SoftwareApplication to be added to the ranges of fromAgent and toAgent?

I'm inclined to say yes; if we do, we should use whatever is in the software ontology. 

BTW, as of 23-Oct-23, the restrictions on Message again explicitly refer to Organization and Person. See below.

```
gist:Message
	a owl:Class ;
	rdfs:isDefinedBy <https://w3id.org/semanticarts/ontology/gistCore> ;
	owl:equivalentClass [
		a owl:Class ;
		owl:intersectionOf (
			gist:ContentExpression
			[
				a owl:Restriction ;
				owl:onProperty gist:comesFromAgent ;
				owl:someValuesFrom [
					a owl:Class ;
					owl:unionOf (
						gist:Organization
						gist:Person
					) ;
				] ;
			]
			[
				a owl:Restriction ;
				owl:onProperty gist:goesToAgent ;
				owl:someValuesFrom [
					a owl:Class ;
					owl:unionOf (
						gist:Organization
						gist:Person
					) ;
				] ;
			]
		) ;
	] ;
	.
```

**Comment by sa-bpelakh** [comment]
DECISION: Remove type references from definition, e.g
```
	rdfs:comment
		"A specific instance of content sent from a sender to at least one other recipient."^^xsd:string ,
		"EXAMPLES: An email message, a phone call, a voice message, or a Web Service message."^^xsd:string
		;
```
