### ISSUE TITLE
Should ContingentEvents be PlannedEvents?

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#402]
From Teams:

MarkW: 
Just noticed this: gist:ContingentEvent gets inferred under gist:PlannedEvent. (though not asserted there). It does so because it has a planned start and end.   Does it seem right that contingent events are planned? 

Rebecca Younes:
    Good point. There are naturally occurring contingent events, such as if a hurricane hits Florida, there is a high probability that certain buildings will be damaged (sorry, Mark!). I can see three ways of addressing this: (1) add a ContingentPlannedEvent referring to human contingencies;  (2) individual event could be typed both PlannedEvent and ContingentEvent without an additional class (I.e., no change to the ontology; (3) ContingentEvent is meant to refer to a human-defined contingency, and needs a new text definition. 
​
Boris Pelakh:
    If ContingentEvent is meant to refer to things like hurricane forecasts, then plannedStart/plannedEnd seems wrong, since those types of events aren't really planned. I guess we can discuss this as part of the issue 

Dan Carey:
    In some sense, ContingentEvent isn't actually an event; it's a specification.

**Comment by rjyounes** [comment]
@DanCarey404 It could be considered the specification of an event. A planned event is also a specification, before it occurs, that is. I think you missed the discussion on whether Specification should be extended to include processes; it could be extended in the same way to include events. In fact, it might be worth going the other way and figuring out what can NOT have a specification.

**Comment by uscholdm** [comment]
> Dan Carey: In some sense, ContingentEvent isn't actually an event; it's a specification.

At MS, the risk ontology has a class that means a bad event that might happen. I forget what it is called. I think it is a subclass of HypotheticalEvent.  In common sense terms, it can reasonably be thought of as a specification of a possible future event.  It is analogous to a PlannedEvent, which is also a specification of a possible future event.  But we have always, for convenience, been a subclass of Event.  I never thought to make it a specification, though it is not unreasonable.  

I think its easier to just have all these possible future events all be subclasses of Event and not of Specification.  This also came up at P&G where we modeled bad events like tanker spilling shampoo into local streams. They ran simulations, and we might have had a class for simulated event.

**Comment by uscholdm** [comment]
> Does it seem right that contingent events are planned?

I don't think so, it jars with common intuition.

**Comment by marksem** [comment]
At MS, it is PotentialRiskEvent, and as you say it is sub of HypotheticalEvent, which actually *is* sub Specification, and not sub Event. 

![image](https://user-images.githubusercontent.com/34490444/101048879-00faed80-3551-11eb-9b06-ddf26915ef75.png)

**Comment by rjyounes** [comment]
I agree that ContingentEvents are not necessarily planned, and I like the EventSpecification classes as well.

This raises the question of whether a PlannedEvent should be an EventSpecification, rather than an Event. This introduces complexity: my planned birthday party is a specification before it happens, and an event after it happens. We'd have two objects with most of the same properties except whether they occur in the past, present, or future. However, since not every event works as planned, perhaps they are more different than that: the planned party has an invitee list, but not attendees. It has a birthday cake order (another specification) but the actual event may have no birthday cake because it was dropped and smashed before it arrived. So it's not really that the PlannedEvent morphs into an actual Event, but that there actually are two objects. I can talk about how my actual birthday party did not live up to expectations (i.e., did not meet the spec).

@marksem An unrelated question related to your class hierarchy above: you argued in #406 that a process specification  or TaskTemplate should not be a subclass of Specification, but you have ActionPlan as a subclass of Specification. What is the crucial difference between ActionPlan and TaskTemplate that makes one but not the other a type of Specification?

**Comment by marksem** [comment]
^^ *I* don't have it, the MS ontology does. :)   That was modeled in there before I starting working MS.   I'm still pondering if I think of Hypothetical Events as Specifications.    I think I prefer the gist way as more workable/intuitive, where all kinds of events, planned, hypothetical, actual/historical are still under the umbrella concept of events.

**Comment by rjyounes** [comment]
See also #489 and #176.

**Comment by rjyounes** [comment]
Can this be closed by the planned action on issue #176?

**Comment by uscholdm** [comment]
> Can this be closed by the planned action on issue #176?

I cannot see any planned action on #176, so  cannot answer this question.

**Comment by uscholdm** [comment]
@rjyounes, this is now moot. `PlannedEvent` no longer exists.  But there was lots of nice discussion!

**Comment by rjyounes** [comment]
Closing.
