### ISSUE TITLE
Broaden meaning of Specification to include how to do things

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#405]
Spawned from issue https://github.com/semanticarts/gist/issues/60

**Comment by uscholdm** [comment]
The current intended meaning for `gist:Specification` is as a set of acceptance criteria for something, e.g. a product or service.  The criteria can be used to determine whether something is in compliance. If you bought something, did you get what you thought you paid for.  Another example is a formal specification of a program, in software engineering.

In the enterprise it is common to (formally or informally) document how to do things, e.g. recipe, method or process.  There was never a home in gist for such things, so they were either added as orphan classes, or put under `Specification`, which was not strictly correct.  This issue is about broadening the definition of `Specification` to include specifications of **how to do** something as well as specifying **what** it means to be a given thing.

**Comment by uscholdm** [comment]
DECISION: 
- Broaden the definition.
- For now, do not create two main subclasses for the two kinds of specification. It may or may not prove to be useful.

**Comment by uscholdm** [comment]
Commend from @mkumba 

> Admittedly the word specification is ambiguous in English in this regard, but what are we gaining by also becoming ambiguous. I think the issue is as it was if something was a specification we would know what it was, now we're not going to be sure if it is evaluative, or generative.

> There are behaviors that we can imagine implementing on instances of these classes. If the instance is template, then saying something like "new()" should create something. If something is a specification saying something like "conformsTo" we should get a boolean. But if we mix them all together we won't know which ones conform to which behaviors.

Response from @uscholdm 

> So maybe that's a good reason to have two major subclasses, which could be called EvaluativeSpecificaton and GenerativeSpecification (or maybe HowToSpecification). We decided to not do that till there was a good reason to. There are some things that I model as Specification that I would not make subclasses of either, so I'd not want them to be a disjoint union. For example, in Platts there is a class called TimeOfDayInTimeZone which means 'the time of day on a 24 hour clock in a given time zone, ignoring daylight savings time.' It is informational, part of the description of an assessment, when it takes place. Having a disjoint union would nudge one into thinking one had to choose. I would not want to be forced to think about whether TimeOfDayInTimeZone or SpecEntry or various other things necessarily go into one place or the other. Unhelpful.

**Comment by uscholdm** [comment]
Comment from @marksem 

> I concur with the merit of Dave's concerns. I'm sorry to have missed the issue review yesterday where the DECISION was made. Because I still think a Specification is a "what" but not a "how" (process) for the reasons Dave brings up. Furthermore, Specification is sub of Requirement. That again makes me think it is a "what" but not a "how". I think processes fit under Task Template. I thought that's what Task Template was pretty much about.
As for "EvaluativeSpecificaton and GenerativeSpecification", my initial reaction is to strongly object. These are starting to sound like BFO classes, i.e., not natural, common concepts, and I think that would start to undermine Gist's appeal.

**Comment by uscholdm** [comment]
I had a chat with @marksem and have updated my understanding and views.
1. Allowing specifications of how to do something to be a subclass of `Specification` makes it also a subclass of `Requirement`, which is incorrect. A 'how to' (e.g. recipe, or plan or method) amounts to a set of instructions.  
   1. The set of instructions need not (collectively) **be** a requirement, they could just be a guideline
   1. There may or may not be a requirement to **follow** the instructions. There would be for manufacturing shampoo, but not for baking cookies at home, you can do whatever you like. In a business context, set of instructions can also be suggestive rather than required.
1. The sense of `Specification`as a set of evaluation criteria, does seem  a better fit under `Requirement` at first blush. *** 
1. I am in favor of having a class under which all 'how to' characterizations go.  `TaskTemplate` is a viable candidate for this. The meaning is quite close.
1. I am happy for Template to remain not a subclass of `Specification` (per @rjyounes view).
1. There is an open question as to whether `TaskTemplate` is a Template. @rjyounes raised some objections. If it is not, then it should have a different name.

ONE CANDIDATE PROPOSAL: 
- Leave `Specification` where it is with its current meaning being a set of criteria to evaluate 'what' something is
- Put all classes whose instances specify how to do something (plan, process, recipe, method...) under `TaskTemplate`
- Tweak the definition of `TaskTemplate` to make thiss more clear.
- **Close this issue as a 'won't do' and continue the conversation at issue #60** 

*** But perhaps not necessarily. Something can be a specification which at the time of creation is aspirational, beyond the current capability. It is not a requirement, it is just a characterization of what is desired.  There are degrees to which specifications and how-tos are to be followed from weak to strong. e.g.
- MAY: suggestion (here's an idea to consider)
- SHOULD: guideline (good idea to follow, unless you have a reason not to)
- MUST: requirement: 
These gradations are analogous to `what is going on with `DegreeOfCommitment` and could probably be merged.

**Comment by rjyounes** [comment]
Closing by the same rationale as #60.
