### ISSUE TITLE
TaskTemplate label is wrong

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#407]
In gist 9.4.0, class TaskTemplate has label "Template Task".

Propose we change label to "Task Template".

**Comment by uscholdm** [comment]
@marksem @sa-bpelakh 
Boris just wrote a SPARQL query to catch this sort of error.  It has been added to our suite of ontology quality queries in the ontology-quality repo and will be added to the ontology release process.
- `...\github\ontology-quality\queries\verify_matched_prefLabel*.rq`

**Comment by rjyounes** [comment]
No wonder it had me so confused. TaskTemplate makes sense but Template Task does not.

**Comment by rjyounes** [comment]
See also #408, which are larger issues.
