### ISSUE TITLE
TaskTemplate definition

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#408]
Definition of TaskTemplate: An outline of [sic] task of a particular type, that will, when instantiated, generate an actual (unscheduled) task.

1. Why must the resulting task be unscheduled? I have a recipe for muffins that I plan to execute at 3pm today. 

2. I am concerned about the name TaskTemplate. Perhaps the reason it has generated to much confusion (e.g., #60 and related issues) is that the name is not very intuitive. We don't tend to describe things like recipes and instructions for assembling furniture as "templates." I don't have a great suggestion at the moment. TaskInstructions is better understood but awkward. TaskOutline?

**Comment by rjyounes** [comment]
Ignore label issue - subsumed by #590. There is a legitimate point about the definition, copied here:

Definition of TaskTemplate: An outline of [sic] task of a particular type, that will, when instantiated, generate an actual (unscheduled) task.

Why must the resulting task be unscheduled? I have a recipe for muffins that I plan to execute at 3pm today.

**Comment by rjyounes** [comment]
Proposed definition: An outline of a particular task that the execution of a task is based on.

Revised definition of `Template`: "Something used to make objects in its own image."
Move to skos:example (but keep existing example): "In manufacturing this would be specialized as a die to make stamped parts, cookie cutters are templates for cookies, and forms are templates for data."

**Comment by rjyounes** [comment]
Roll into PR for #590.

**Comment by uscholdm** [comment]
This has been done and merged #691
