### ISSUE TITLE
Don't generate legacy RDFS annotations in next major/minor release after 9.5.0

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#415]
IMO we should not keep regenerating RDFS annotations for terms introduced after 9.5.0; the idea was only to support implementations reliant on existing RDFS annotations.

This would require keeping the 9.5.0 rdfsAnnotations.ttl file for future releases but not regenerating it in new release packages except in patch releases that occur before the next major/minor release. bundle.yaml would change to prevent regeneration of the file.

**Comment by sa-bpelakh** [comment]
I would expect to keep this around until 10.0.0, using the same policy as deprecated classes/properties - deprecate on minor release, remove on major release.

**Comment by rjyounes** [comment]
@sa-bpelakh Agreed, for existing terms. In case I wasn't clear, I was referring to new terms introduced post-9.5.0. Technically there's nothing to deprecate since the terms didn't exist before we made the annotation change. Or do you want to fully support queries on rdfs:label, both in old and new terms?

**Comment by sa-bpelakh** [comment]
Well, unless we introduce a `@since` annotation of some sort, it's much easier for me to generate the `rdfs:label` for all terms. It's not like we are manually curating these.

**Comment by Jamie-SA** [comment]
I thought the reason to do this was to give time for users of gist to switch to the new annotations. I think the likely case is that some users may have hard coded queries, etc., to use the old annotation properties in their system and that would apply to new terms and updated annotations on terms; less likely that they have hard coded the use of specific annotations on specific terms and that they would use new annotations on new terms.

And, as Boris says, there is no extra work to keep doing this. I don't see a reason to limit it to only old terms.

**Comment by rjyounes** [comment]
OK, I'm convinced.
