### ISSUE TITLE
Use version IRI in rdfs:isDefinedBy annotations

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#417]
We decided to add these based on the discussion I initiated last year arguing for versioned IRIs for all ontology terms. We rejected that proposal, but decided to use rdfs:isDefinedBy as a mechanism for recording the ontology _version_ each term belongs to. By using the unversioned ontology IRI we are not addressing that issue. I therefore propose using versioned IRIs in these annotations.

If this is not already an option in ontology-toolkit, it would have to be added, as well as modifying the gist bundle.yaml file.

**Comment by uscholdm** [comment]
This makes sense, are there and downsides/tradeoffs?  None come immediately to mind.

**Comment by rjyounes** [comment]
Discussion from triage meeting:
- Generally gist is used either in a triple store or local file storage: dereferenceable URIs are not a critical use case
- Even in the context of the linked data cloud, the value of `rdfs:isDefinedBy` as proposed here would only provide the _most recent_ ontology the term is defined in, which would not help users trying to retrieve an older version of the ontology. `rdfs:isDefinedBy` does not substitute for versioned IRIs in the linked data context.

Therefore, the issue is being closed.

**Comment by Jamie-SA** [comment]
>     * [...] the value of `rdfs:isDefinedBy` as proposed here would only provide the _most recent_ ontology the term is defined in

I am having a hard time understanding your assertion, I don't think that is a correct statement. Using version IRIs would link to the version of the ontology that is being used. That was the point of the original issue. How can you assert that a version IRI "would only provide the _most recent_ ontology"?

**Comment by rjyounes** [comment]
@Jamie-SA I mis-phrased the previous comment. `rdfs:isDefinedBy` would show only the most recent version of the ontology that defines a given term -- unless, of course, you want to have multiple assertions, adding a new one for every new release. In other words, if you retrieve a term that asserts `rdfs:isDefinedBy <https://ontologies. semanticarts.com/o/gistCore9.5.0>`, you don't know whether the term was also defined in version 9.4.0, unless, as I said, you _add_ a new assertion rather than replacing the old one on each release.

If terms had versioned IRIs, you would be able to retrieve the version you wanted by IRI rather than `rdfs:isDefinedBy` - all published versions would be floating around in the linked data cloud.
