### ISSUE TITLE
change gist:Specification textual description

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#431]
Proposal:   change gist:Specification textual description to say "A _requirement or_ set of requirements to be satisfied by a material, design, product, or service."

Rationale:

Currently (through v9.5.0), gist:Specification is a subClassOf gist:Requriement.  But its textual definition is:  "A _set of requirements_ to be satisfied by a material, design, product, or service."   As such, it would most naturally seem to be a sub of Collection.
 
If we change to say it is "a requirement or set of requirements," we could be OK since Requirement and Collection are not disjoint.  This allows us to keep our textual definition part about "… to be satisfied by a material, design, product, or service", which I like because it distinguishes it from a more general Requirement.   

(@mkumba supports this change)

**Comment by rjyounes** [comment]
To be legalistic, a set may have one member. Or none - perhaps we should say "...a _non-empty_ set of requirements..."

That being said, the proposal seems fine to me given ordinary English usage.

**Comment by uscholdm** [comment]
Or getting rid of the geek-speak altogether:  `One or more requirements`.   Simpler, if a tad less precise.

**Comment by rjyounes** [comment]
This is subsumed by #534 but I'm leaving it open so we make sure to consider the specific issues addressed here.

**Comment by uscholdm** [comment]
SUGGESTION: change the definition to be:
- "_One or more requirements_ to be satisfied by a material, design, product, or service."

**Comment by rjyounes** [comment]
I agree with @uscholdm's suggestion.
