### ISSUE TITLE
gist:ID -- relax restriction

### ISSUE THREAD

**Issue by DanCarey404** [semanticarts/gist#433]
The current definition/restriction for gist:ID includes the clause _(gist:uniqueText some xsd:string)_.  But we cannot assume/guarantee that a particular ID string is unique.  For example, the string "13579" might be the ID text for a person in one data source and the ID text for an Organization in a different source.
This formulation also precludes the possibility of the identifier data being an integer natively, if that was necessary for some reason.

I tentatively suggest we replace the _(gist:uniqueText some xsd:string)_ clause with something like _((gist:containedText some xsd:string) OR (gist:decimalValue some xsd:double))_.  Alternatively, the clause could be deleted with no replacement.

**Comment by rjyounes** [comment]
I agree about the non-uniqueness of the text. The intent is that within a particular identifier scheme the text is unique, but we can't claim universal uniqueness. E.g., someone's SSN could be someone else's driver's license number somewhere in the world.

I'm not so sure about the integer issue. When numbers are used as identifiers, are they really still numbers or do they "become" strings in that the numeric value has been stripped?

**Comment by DanCarey404** [comment]
The integer thing just occurred to me as I was writing up the issue.  It may be a red herring of my own devising.

**Comment by uscholdm** [comment]
> The integer thing just occurred to me as I was writing up the issue. It may be a red herring of my own devising.

When you see numbers used as IDs their numberness is usually not very relevant, and they are best represented as strings.

**Comment by uscholdm** [comment]
> The current definition/restriction for gist:ID includes the clause (gist:uniqueText some xsd:string). But we cannot assume/guarantee that a particular ID string is unique.

The `uniqueText` property is functional. That just means that MY social security number instnce of `gist:ID` only points to a single string. It does not mean that no other ID/SSN points to the same string. The latter constraint is ensured by the inverse functionality of `gist:identifiedBy`, I think everything is correct as it is.

**Comment by rjyounes** [comment]
@uscholdm You're right. Dan, are you in agreement with closing this issue?

Interesting about the functional property, though. Doesn't my SSN identifier point to "123-45-6789", "123456789", "123 45 6789", and "123\t456\t789"?

**Comment by uscholdm** [comment]
@rjyounes 
> Doesn't my SSN identifier point to "123-45-6789", "123456789", "123 45 6789", and "123\t456\t789"?

That would be perverse.  Good point though, given the world as it is.

**Comment by rjyounes** [comment]
From https://www.ssa.gov/:

The SSN must be nine (9) numerical characters only.
Spaces, alphabetic characters, hyphens, slashes or any other special characters are not allowed.

But maybe this is just confusing form entry in a UI with the actual ID string.

**Comment by DanCarey404** [comment]
Okay, having walked through @uscholdm's explanation, I'm satisfied this is a non-issue.
**However...**
WRT gist:identifiedBy being Inverse Fuctional...  I noticed gist:identifies is also Inverse Functional.  Shouldn't the latter be Functional?  (In which case, we need a new ticket.)

**Comment by uscholdm** [comment]
> WRT gist:identifiedBy being Inverse Fuctional... I noticed gist:identifies is also Inverse Functional. Shouldn't the latter be Functional?

Hah - yes, good catch. `gist:identifies`  is absolutely NOT inverse functional because a person can be `gist:identifiedBy` more than one ID.

**Comment by rjyounes** [comment]
See https://github.com/semanticarts/gist/issues/180

**Comment by rjyounes** [comment]
I'm adding #180 to the March release because it's quite an egregious error.
