### ISSUE TITLE
gist:Group leaves a lot to be desired

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#440]
The `skos:definition` for `gist:Group`  is:

> A collection of People. The group may or may not be an Organization.  Many organizations consist of groups of people, but that is not a defining characteristic.

Here is the code (minus the above definition):

```
gist:Group
	a owl:Class ;
	owl:equivalentClass [
		a owl:Class ;
		owl:intersectionOf (
			gist:Collection
			[
				a owl:Restriction ;
				owl:onProperty gist:hasMember ;
				owl:someValuesFrom gist:Person ;
			]
		) ;
	] ;
	skos:prefLabel "Group"^^xsd:string ;
	.
```

This is overly narrow, given the usual meaning for the English word, 'group'. Calling the class `GroupOfPeople` would address this concern.

Its also overly broad in that it can include anything as a member. To fix that would require an `allValuesFrom` restriction so that only Persons can be members. Dave does not like using `allValuesFrom` because you cannot infer class membership. I think its better to give that up than to allow wrong inferences. For example, currently, an instance of `gist:Collection` that consisted of one person, one pickle and the planet Venus would be inferred to be a member of `gist:Group`, which we are told is a group of people.

Maybe best to just get rid of `gist:Group` entirely.  I don't think it gets enough use to justify its being in gist.  I've never used it.

**Comment by rjyounes** [comment]
I have no particular feelings about `gist:Group` one way or another, but can you further clarify why Dave doesn't like `allValuesFrom`? I don't understand "because you cannot infer class membership." It seems to me it's very valuable in cases like this to specify what type of members the collection can have. What's wrong with that?

**Comment by uscholdm** [comment]
@rjyounes 
> I don't understand "because you cannot infer class membership."

Pity you came after we stopped doing the DBBO class, we have slides on this. It's the open world.  You can have 43  members of an instance of `Collection` and have all 43 be instances of type: `Person`.  You might be tempted to infer this collection into the `Group` class because all the members are `Person`s. But, the open world says things could be true that you don't know about.  The collection might actually have a member that is a building. The moment that triple is added, the reasoner has enough information to infer that the collection is NOT an instance of `Group` because not all members are `Person`s. This is why you can never infer that an individual IS an instance of `Group`.  You can only infer that it is not.  The same is true for max and exact cardinality restrictions (exact is just a shorthand for min and max together).  The reason is the same: the open world. 

> can you further clarify why Dave doesn't like `allValuesFrom`

He likes to be able to infer individuals into classes.

**Comment by rjyounes** [comment]
Thanks for the clarification.

**Comment by rjyounes** [comment]
This class has been removed from the ontology.
