### ISSUE TITLE
Suggestion: Create class gist:TextId as the intersection of gist:ID and gist:Text

### ISSUE THREAD

**Issue by tedhills** [semanticarts/gist#441]
gist:ID is a subclass of gist:Content, which includes multimedia content. While it's true that an ID could be multimedia--for example, a static or animated logo that identifies a company--in the vast majority of cases in practice, an ID is textual. However, the ontology does not constrain an :ID to being textual. Systems that in fact can handle multimedia content would have to look further into gist:ID instances to determine whether they are text or something else.

To close this little ontological gap, I recommend that a class be added to gist, gist:TextId, as the intersection of gist:ID and gist:Text. gist:TextId would be used exactly as all of the examples show in the Gist Council presentation of 2021 March 4, but would ontologically eliminate the possibility that the ID might be multimedia.

**Comment by uscholdm** [comment]
@tedhills @rjyounes This is a legitimate point, however it is not likely to be needed in most organizations; users can create such a class on their own as needed. 
I propose to close this issue.

**Comment by rjyounes** [comment]
Another problem with this proposal is that it creates asymmetry: you would be able to assert that something is a text ID, but not that it is a non-text ID; you'd need a second subclass to do that. 

I agree with @uscholdm  that this doesn't belong in gist. Note that you could also create more specific subclasses without needing an intermediate `TextID` or `NonTextID` class. E.g., a BarCode can be defined as an ID expressed in an image media type.

**Comment by tedhills** [comment]
Hi,

I’ve been on vacation and haven’t had the chance to reply to this. I agree with closing this issue. I had noticed some time ago that the equivalence class for gist:ID includes “and (gist:uniqueText some xsd:string”. So, gist:ID is already tied to text IDs only.

However, the idea of a barcode image as an ID is a very good one—and now it can’t be an instance of gist:ID! :-)

All the best,
Ted Hills
Concepts and Objects LLC
+1 908 200 8713
***@***.***

￼
