### ISSUE TITLE
No Real Difference between gist:Magnitude and gist:UnitOfMeasure

### ISSUE THREAD

**Issue by tedhills** [semanticarts/gist#443]
According to http://physics.nist.gov/cuu/Units/introduction.html:

"A **unit** is _a particular physical quantity_, defined and adopted by convention, with which other particular quantities of the same kind are compared to express their value."

The **value of a physical quantity** is _the quantitative expression of a particular physical quantity_ as the product of a number and a unit, the number being its numerical value. Thus, the numerical value of a particular physical quantity depends on the unit in which it is expressed."

It can be seen that there is some circularity here, in that _the value of a physical quantity_ expresses a physical quantity. In fact, the value of a physical quantity _is a_ physical quantity. The only difference is in the form of expression. A unit is given as one of something, so that the "one" can be dropped, since 1x = x.

I see that gist has a parallel structure, where gist:UnitOfMeasure is (one of) a unit, and gist:Magnitude enables the expression of a quantity as any number times a unit (including of course one times a unit).

Thus, what a gist:UnitOfMeasure expresses is exactly the same as what a gist:Magnitude expresses, except that the expression of gist:UnitOfMeasure is restricted to expressing "exactly one of".

But gist:UnitOfMeasure and gist:Magnitude are disjoint top-level classes. In fact, gist:UnitOfMeasure should be a subclass of gist:Magnitude, since every unit of measure is just one particular quantity, which is what gist:Magnitude expresses.

It then becomes questionable whether we really need to have subclasses of gist:Magnitude just to say "one of" the particular kind of quantity the gist:Magnitude subclass identifies. In fact, all we need is an individual of gist:Magnitude, such as gist:_one_millisecond.

This became real for me when I had to decide how to mark up natural language text containing words like "millisecond" and "kilogram". Should I use the units gist:_millisecond and gist:_kilogram, or the magnitudes gist:_one_millisecond and gist:_one_kilogram? But wait, why are there definitions for gist:_millisecond, gist:_one_millisecond, and gist:_kilogram, but not gist:_one_kilogram? The choice seems arbitrary. What am I missing?

Furthermore, if one digs into the International System of Units (SI) (https://www.nist.gov/pml/special-publication-330), one realizes that even basic units are in fact multiples of smaller units or fractions of larger units. For instance, a second is the duration of 9,192,631,770 oscillations of a cesium atom; a meter is the distance traveled by light in vacuum in 1/299792458 second; etc., etc. This emphasizes that a unit is an arbitrary physical quantity, chosen by convention, and not really a special class of thing--other than the recognition that it was chosen by convention.

In light of this, I propose the elimination of class gist:UnitOfMeasure as superfluous (and thereby eliminating the incorrect disjoint axiom referencing :Magnitude), and the replacement of all of the gist:BaseUnit individuals with corresponding gist:Magnitude individuals.

**Comment by rjyounes** [comment]
This resurrects #61.
