### ISSUE TITLE
parentOf property: definition needs work

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#444]
The current definition for `gist:parentOf` is: 
```
gist:parentOf
	a owl:ObjectProperty ;
	skos:definition "Biological Parent"^^xsd:string ;
	skos:prefLabel "parent of"^^xsd:string ;
	.
```

The term parent is used much more broadly in a hierarchy. For example:
- directSubTaskOf is defined to be an immedate parent task
-  we have a property called `gist:hasNavigationalParent`

SUGGESTION: rename to `biologicalParentOf` (or use the inverse `hasBiologicalParent`

**Comment by rjyounes** [comment]
Not just that, but more to the point, there are adoptive parents who have legal responsibility for the child. I don't know if step-parent would ever be important in an enterprise context without legal adoption.

Anyway, I heartily agree with the suggestion.

**Comment by Jamie-SA** [comment]
Related to the discussion is gist:offspringOf which sounds like it would be the inverse of the the current gist:parentOf (and the proposed gist:biologicalParentOf). Neither existing properties have owl:inverseOf declared.

Not relevant to the proposal but I am curious how often gist:parentOf got used in a non-biological hierarchies. :)

**Comment by rjyounes** [comment]
This is subsumed by #534 but I'm leaving it open so we make sure to consider the specific issues addressed here.

**Comment by uscholdm** [comment]
@rjyounes This has been addressed, suggest to close. 
Here is the current implementation:
```
gist:hasBiologicalParent
	a owl:ObjectProperty ;
	rdfs:domain gist:LivingThing ;
	rdfs:range gist:LivingThing ;
	skos:definition "Relates a living thing to its biological parent."^^xsd:string ;
	skos:prefLabel "has biological parent"^^xsd:string ;
	.
```
