### ISSUE TITLE
Include materialized gist inferences with our release

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#446]
For those who wish to load gist into a triple store, it would be handy to have a file included with the release the included materialized inferences.  It is especially handy for all of us who use Slow Reveal. Saves going to the trouble of doing it manually.

**Comment by philblackwood** [comment]
Like.   (I don't see a like button ... but I like it. Answers a question I had about inferences for inverses.)

**Comment by uscholdm** [comment]
@rjyounes 
OUTCOME: we now do this for all releases.
