### ISSUE TITLE
simplify Magnitude and Unit of Measure

### ISSUE THREAD

**Issue by philblackwood** [semanticarts/gist#451]
Updated May 5 with more complete description and comparison with gist 9.6.0
Also includes a spreadsheet with examples.
Change the .txt suffix to .owl to open the owl file.

Updated May 24 to include annotations in owl file, change unitSymbol to symbol, and include 200+ business metrics in spreadsheet. The WORD document includes the example of adding a new unit (watt hours per mile) and minor editorial changes to WORD document.

[gist issue 451.docx](https://github.com/semanticarts/gist/files/6532611/gist.issue.451.docx)

[abox unit of measure.xlsx](https://github.com/semanticarts/gist/files/6532546/abox.unit.of.measure.xlsx)

[magnitude_pdb.txt](https://github.com/semanticarts/gist/files/6532574/magnitude_pdb.txt)

An agile approach to evaluating this would be to get a high level sense of whether it makes sense to consider it, then understand the proposal and tweak it until it does everything it needs to, and then figure out how to get "from here to there".  Point-by-point comparison of old vs. new is a larger effort and prone to forgetting things like changing hasUoM to hasUnitOfMeaure.  My 2 cents.

**Comment by philblackwood** [comment]
Probably subsumes the following:

#146 CoherentRatioUnit
#160 numerator, denominator, multiplier, multiplicand
#302 add Magnitude as domain of hasPrecision (I agree with Michael's suggestion to close)
#381 terms for Magnitude and Unit IRIs

I incorporated the proposed solution for #171 and #172: introduce numericalValue

**Comment by philblackwood** [comment]
For Enterprise customers, it would be more natural to use the term "standard unit" rather than "coherent unit".

**Comment by rjyounes** [comment]
Dave's thoughts in the attached PowerPoint.
[notes on UoM.pptx](https://github.com/semanticarts/gist/files/6292522/notes.on.UoM.pptx)

**Comment by philblackwood** [comment]
some background info about dimensions and units, with an opinion that units are a better concrete abstraction.

[dimensions and units.pptx](https://github.com/semanticarts/gist/files/6313503/dimensions.and.units.pptx)

**Comment by philblackwood** [comment]
Unit conversion options:

1. directly convert any non-standard units to SI coherent units
2. derive the conversion from other conversions, using ProductUnit and ExponentUnit (following SI definition)
3. use multiplication and division to represent exponents, as in gist 9.6.0

For a simple domain, it might work fine to use an online unit conversion tool to figure out the one-time conversions.
See:https://www.calculator.net/conversion-calculator.html

The attached 3 slides sketch out the options.

[unit conversion options.pptx](https://github.com/semanticarts/gist/files/6320866/unit.conversion.options.pptx)

**Comment by philblackwood** [comment]
Some statements to help define "what needs to be said" about magnitudes and units of measure. 
Please add more if you see something missing.

Will the cabinet or table top fit through the door?    (variety of dimension names in real world)
If you sign today, we will finish the job within 3 months.    (unit that does not map to SI)
The unemployment rate is 40%, but exactly what is 40% of what?  (relative magnitudes, best practice for labels)
What is the average in feet of: 3 meters, 192 inches, and 3 yards?  (conversions to and from standard units)
If I want an average temperature, does it matter if I work in Fahrenheit vs. Kelvin?  (degF / degK handling)
Do air traffic at LaGuardia meet the noise abatement standard?  (decibels)
What is the climate model's equilibrium temperature for the current CO2 level?  (logarithm scales)
I know F=ma. Can I put that in gist?  (dimensional analysis)
How can I check for consistency when I add a new unit of measure to gist?  (dimensional analysis)
What should I use Joules for?  (convention to create 1-1 mapping between SI units and SI dimensions)

**Comment by uscholdm** [comment]
@philblackwood 
I'm struggling to get the essence of the idea so I can evaluate it.  I want to be able to look at some definitions and immediately see what it would look like in gist 9.6.  I cannot see how to do that yet.  
- You say to use `Aspect` to capture the idea of dimension, but there was no class for dimension in gist.  
- It is not clear what is to be used for the broader notion of unit, other than the coherent ones. 

The turtle has the following: 

```
:_distance
	a
		owl:NamedIndividual ,
		:Aspect
		;
	skos:definition "The spatial aspect that is measured in meters (coherent unit)."^^xsd:string ;
	skos:scopeNote 'The term "distance" is used instead of the term "length" as in the International System of Units. This allows the term "length" to be used along with "width" and "height" to describe physical objects.'^^xsd:string ;
	.

:_distance_above_sea_level
	a
		owl:NamedIndividual ,
		:Aspect
		;
	skos:definition "An aspect that is measured in meters (coherent unit)."^^xsd:string ;
	skos:scopeNote "The term can be used for the elevation of a geo point or for the altitude of an object."^^xsd:string ;
	.
```

I cannot easily determine what is similar or different about these two.  There is no semantic link to indicate that both have the same coherent unit.  The text definitions say how they are similar, but say nothing about how they differ.
- The spatial aspect that is measured in meters (coherent unit).
- An aspect that is measured in meters (coherent unit).

**Comment by philblackwood** [comment]
Michael, yes, in a loose implementation, the client might not feel the need to associate aspects with units.

They certainly can; I currently have that included as an option. They would make the association by using statements that say what coherent unit an aspect is associated with. See hasCoherentUnit.

"Dimension" is just the term frequently used in the literature that appears as Aspect in gist, if anybody reading this is curious.

**Comment by uscholdm** [comment]
There is no class in gist for dimension, on purpose.   Each coherent unit corresponds to exactly one dimension, so the latter is unnecessary.

**Comment by philblackwood** [comment]
Here is some quantitative information to help decide if doing direct conversions from all non-SI units to SI units, as described in the original write-up, is a good approach. (attached slide)

The analysis is based on the units described in the SI brochure at https://www.bipm.org/en/publications/si-brochure

Many of the direct conversions could be anticipated and done off-line once, and an offline routine could do any new conversions needed to calculate it for inclusion in the data set.  (e.g. identify all units you use such as newton-meters, inches, etc., and the types of things you want to have units for such as elevations, thermal conductivity, etc.) 

So there are two reasonable options. The original proposal includes only the direct conversions, but if the decision is to also support indirect conversions, I believe that adds 2 or 3 concepts to the original 15.

See attached slide.
[landscape of units.pptx](https://github.com/semanticarts/gist/files/6331515/landscape.of.units.pptx)

**Comment by philblackwood** [comment]
to be added to WORD document:

categorizedBy is used to categorize Magnitudes any way a client needs to or wants to.

It can be used to refer to an off-line taxonomy, for example.

A specialized domain can use its specialized terminology: fluid mechanics can use terms like "depth in open channel", for example.

The values of categorizedBy can be used to do some guiding of what makes physical sense. For example, a rule for a kitchen design application could raise a warning if you try to add 3 cabinet depths (if it's just 2, they would need to be back-to-back to make sense). It could question whether you really want to add the depth of one cabinet to another. Rules like this are expected to be very domain-specific. See next comment for rules of the road for units.

**Comment by philblackwood** [comment]
to be added to WORD document:

gist 9.6.0 alludes to rules that allow quantities to be compared using greater-than and less-than. More can be said.

The rules for what mathematical operations and comparisons can be done with the numericalValue of a Magnitude look more like the following:

1. addition, subtraction, greater-than, less-than, equal-to, max, min, average, standard deviation all can be done if the units of measure are the same.

2. multiplication and division can be done in many more cases (not sure if any constraints are possible). For example, cost per widget might be calculated for a collection of widgets, where each widget has a magnitude for cost. Cost per widget is found by dividing the total cost by the total number of widgets. The units for cost and for the count are different, but the division yields an answer that makes sense.

These are desirable rules but require a narrower definition of coherent unit than the International System of Units provides. Two modifications are needed (one is a recommendation in the SI brochure):

1. eliminate cases where multiple units measure the same type of thing. For example, degree Celsius and degree Kelvin should not both be coherent units. Make sure only one of them is considered to be a coherent unit in gist. (one could easily read the SI Brochure as saying they both are)

2. eliminate cases where a single coherent unit measures several different types of thing. The SI has 19 cases in which the product of powers of base units is ambiguous. While SI "fixed" 3 of these that had implications for public health, the others need to be given separate names in gist to allow simple math rules above to work.

See SI Brochure, section 2.3.4 following table 6.

SI Brochure:https://www.bipm.org/en/publications/si-brochure/

**Comment by philblackwood** [comment]
to be added to WORD document:

diagrams comparing the simpler version of Magnitudes and Units of Measure with gist 9.6.0 as I understand it.

(attached)

[before and after.pptx](https://github.com/semanticarts/gist/files/6407333/before.and.after.pptx)

**Comment by philblackwood** [comment]
all my comments from this thread have been folded into the updated WORD document in the first comment (box)

**Comment by philblackwood** [comment]
Attached is a hopefully realistic scenario of an Enterprise that needs to introduce a new unit of measure.

It illustrates the kind of guidelines needed for manual calculation of conversion factors and identifies some obstacles to automation of the conversion factors.

This example will be added to the WORD document. The Excel file will be updated with a list of 248 common business metrics and what some of them would look like if the aspect were folded into the unit itself.

[Simple example of new units.docx](https://github.com/semanticarts/gist/files/6467503/Simple.example.of.new.units.docx)

**Comment by rjyounes** [comment]
Consider pulling magnitudes and units of measure out of gist core into a separate module as a first step. Not sure if there's a clean breaking point.

**Comment by philblackwood** [comment]
Interesting idea, Rebecca. 

Maybe get some more experience and start to add things back in to the core as they prove themselves (kind of the opposite of removing things that are not being used; add things that are being used).

**Comment by uscholdm** [comment]
I'd have to have a look, but I think there are a few places where Magnitudes are used to define other things, but even if so, there won't be many.

**Comment by philblackwood** [comment]
The original entry has been modified to include updates to WORD document (example of watt hours per mile, plus editorial changes).

The .txt file (owl content) has been updated with annotations and to change unitSymbol to symbol.

The excel sheet now includes 200+ examples of business metrics.

**Comment by philblackwood** [comment]
Here is some data from the QUDT ontology (Quantities, Units, Dimensions, and Types) at http://qudt.org

QUDT units, quantity kinds, quantity kind dimension vectors (with SI terms added), and disciplines.

QUDT has many, many properties, not always used consistently, so I did not include them.

QUDT documentation talks about systems of units other than SI, but their vectors seem to represent SI units (not entirely clear ... that's a topic for a different post).

[qudtUnits.txt](https://github.com/semanticarts/gist/files/6941546/qudtUnits.txt)
[qudtQuantityKinds.txt](https://github.com/semanticarts/gist/files/6941549/qudtQuantityKinds.txt)
[qudtVectorsWithSITerms.txt](https://github.com/semanticarts/gist/files/6941554/qudtVectorsWithSITerms.txt)
[qudtDisciplines.txt](https://github.com/semanticarts/gist/files/6941555/qudtDisciplines.txt)

**Comment by philblackwood** [comment]
To better understand QUDT data for Quantities, Units, Dimensions, and Types, consider the following questions and answers:

      What does the unit MicroGRAY measure?   Absorbed Dose

      What disciplines deal with Absorbed Dose? Radiology and Atomic Physics

You can answer similar questions with the attached data set derived from QUDT (change the .txt suffix to .owl)
           
[qudtValues.txt](https://github.com/semanticarts/gist/files/6946058/qudtValues.txt)

**Comment by philblackwood** [comment]
Here are a few slides to give concrete examples that span a good range of use cases and identifies some desirable characteristics of any solution. It includes a sketch of how SI and QUDT are different, and some references (I doubt if we need to go deep into Gaussian or Planck systems).

[unit of measure jumpstart.pptx](https://github.com/semanticarts/gist/files/7197575/unit.of.measure.jumpstart.pptx)

**Comment by uscholdm** [comment]
**The following notes were the basis for a discussion on 13-Oct-22.**

The points below are based on feedback from @philblackwood 

- Existing terminology is pretty geeky, assuming more math and physics familiarity than may be warranted for our clients. For example, CoherentUnit. There is also an verbiage inconsistency we have a property called hasStandardUnit that has range CoherentUnit. 

- When one wishes to introduce a new kind of unit, gist is designed with the expectation that the user will create new Magnitude and UnitOfMeasure subclasses, and specify detailed composition of units from other units using numerator, denominator, multiplier and multiplicand.  This expectation and the work involved is considerable. The benefits are not clearly worth the effort.

- There is an alternative way to express the units in SI terms, which is an option to consider should the need arise. 

- ProductUnit and RatioUnit are ambiguous concepts. The exact same unit can be expressed as a product or a ratio.  

- We do not now have a consistent way in gist to represent a wide variety of business units and metrics, including statistical measures such as average or maximum.   We have modeled statistics such as this in client work, but it is not currently exposed in gist. It is adequate, but there might be better ways to do this. It is an open question whether to keep this separate from gist proper, given it is pretty niche.

- We do not now have a way in gist to express the fact that two different physical measures that cannot meaningfully be added nevertheless have the same unit. An example from Schneider Electric is  reactive power and real power. Both have the same SI base unit exponents: [kg](https://en.wikipedia.org/wiki/Kilogram)⋅[m](https://en.wikipedia.org/wiki/Metre)2⋅[s](https://en.wikipedia.org/wiki/Second)−3   Other units that have the same base units are: [watt](https://en.wikipedia.org/wiki/Watt), [volt-ampere-reactive](https://en.wikipedia.org/wiki/Volt-ampere#Reactive) and [volt-ampere](https://en.wikipedia.org/wiki/Volt-ampere) (not to mention our good friend joules-per-second). Again, from our prior client work, we did have a mechanism for expressing this linkage between units, which is not exposed in gist.

If I were King, I would be inclined to:
- Rename CoherentUnit to StandardUnit (have Coherent Unit be an altlabel)
- Remove Aspect from being a subclass of Category.  Aspects such as like length, or inner diameter or cycle time are not categorizing anything that I can think of.  
- UnitOfMeasure is a subclass of Magnitude
- Define StandardUnit to be a UnitOfMeasure that
  - has conversion = 1
  - has itself as a standard unit
  - has a scopeNote indicating that this captures the idea of dimension.
- Get rid of RatioUnit, RatioMagnitude, ProductUnit and ProductMagnutide
- Make it clear that there is a simple way to create new units.  This is currently supported in gist, no need to change anything.
  - Create the unit as a new instance of UnitOfMeasure
  - Make sure it has a standard unit
  - Make sure it has a conversion
- If there is a need to represent the internal structure of a unit, that can be done in two ways. 
  - The current method: hard to create, easier to understand once created, hard for computer to do recursive computation.
    - Create new subclass of Magnitude
    - Create new subclass of UnitOfMeasure
    - Use numerator, denominator, multiplier and multiplicand to show how to construct the new unit
  - The current method (simplified): 
    - Create new subclass of Magnitude
    - Create new subclass of UnitOfMeasure
    - Specify a direct conversion to the standard unit
    - Do NOT bother with numerator, denominator, multiplier and multiplicand
  - The vector exponent method: this is used by QUDT. It is easier to create, harder for humans to understand but easier computationally 

Open questions: 
- How to handle things that have same units but mean different things and cannot be added.
- Underlying meaning of percentages, rather then pure number unit
- Unless it falls in our lap for free, defer creating a special mechanism for statistics like average and maximum that apply to collections. It is pretty niche.
- Business units like unemployment rate, average cost to acquire a customer
- How include characteristics and specifications

**Comment by rjyounes** [comment]
Closing this issue as the proposals are now out of date. See current discussion and proposals in issue #759.
