### ISSUE TITLE
Decide whether we should retain directSubTaskOf, hasDirectSubTask

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#454]
This is a spinoff of issue #115 

Problems were identified with using the hasX / hasDirectX pattern.
Decide whether to keep `directSubTaskOf` and `hasDirectSubTask` and if so, whether we should issue guidelines about best practice.

**Comment by rjyounes** [comment]
I don't see why we shouldn't offer the option to use this if it's appropriate in a given use case. For example, when modeling a project one may want to know how each task breaks down into direct subtasks.

**Comment by uscholdm** [comment]
This is now moot, they were removed in response to #733
