### ISSUE TITLE
Decide whether we should keep hasDirectSubCategory and  hasDirectSuperCategory

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#455]
This is a spinoff of issue #115

Problems were identified with using the hasX / hasDirectX pattern.
Decide whether to keep `hasDirectSubCategory` and `hasDirectSuperCategory` and if so, whether we should issue guidelines about best practice.  

Consider this in the context of issue https://github.com/semanticarts/gist/issues/373 which suggests getting rid of these properties because `skos:broader` is fine as it is.

**Comment by rjyounes** [comment]
We should keep these to enable building a taxonomy tree.

**Comment by rjyounes** [comment]
Subsumed in #373.
