### ISSUE TITLE
gist:Artifact versus gist:PhysicalIdentifiableItem

### ISSUE THREAD

**Issue by tedhills** [semanticarts/gist#457]
I wanted to add class :Painting to my ontology, and went looking for a root class. I found gist:Artifact and gist:PhysicalIdentifiableItem as candidates. They both seem like reasonable choices.

The definition of gist:Artifact is "An intentional, person-made thing, which could be physical or content."

There is no definition of gist:PhysicalIdentifiableItem. We are given two examples of gist:PhysicalIdentifiableItem ("a computer, a book"), plus a negative example which I won't quote.

These definitions make me think that gist:PhysicalIdentifiableItem should be a subclass of gist:Artifact.

Thoughts?

**Comment by rivettp** [comment]
I'd say no, since a unique, and named, naturally formed rock would be a PhysicalIdentifiableItem but not an Artifact. See for example https://www.salardeuyuni.com/arbol-de-piedra/

**Comment by uscholdm** [comment]
> I'd say no,

I agree with Pete.

**Comment by tedhills** [comment]
@rivettp Hi Pete! Your rationale makes perfect sense. However, given such an interpretation, the examples given for Physical Identifiable Item--"a computer, a book"--are not correct.

I suggest that :PhysicalIdentifiableItem be given a proper skos:definition, and the examples be made to match that definition.

Thanks,
Ted

**Comment by rjyounes** [comment]
We can either submit a new issue for improving the annotations on `gist:PhysicalIdentifiableItem`, or wait until we do a complete revision of annotation properties. In any case, this issue is being closed.

**Comment by rjyounes** [comment]
Re-opening with new title. The issue is now to improve the definition, examples, and possibly scopeNote.
