### ISSUE TITLE
Transferable styles

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#469]
I have my presentation separated into small chunks because it loses data when it gets too large. This means I have to recreate all the styles. Could there be a way to either (1) copy the styles from one presentation to another, or (2) have an option to assign the styles to the presentation workspace rather than the presentation? The latter seems preferable, but I can live with either, or any other solution you come up with.

**Comment by uscholdm** [comment]
@rjyounes 
I cannot work out how this is related to gist.  Does gist have styles or presentations? Can you give an example?

**Comment by rjyounes** [comment]
Sorry - this was meant for the ontology-presenter repo.
