### ISSUE TITLE
Add a set of "atDateTime" data properties

### ISSUE THREAD

**Issue by DanCarey404** [semanticarts/gist#470]
As currently constituted (v9.7), gist provides no way to assert a start or stop time directly.  It all relies on the use of TimeInstant instances, which can be cumbersome, hard to mint in a standard fashion, and not always necessary.
We should provide a standard set of datatype properties with an xsd:dateTime range.  Provisionally, this could be something like:
```
gist:atDateTime
     gist:occurAtDateTime
     gist:startAtDateTime
     gist:endAtDateTime
     gist:createAtDateTime
     gist:changeAtDateTime
     gist:lastModifyAtDateTime
```

If adopted, some class restrictions should be rewritten to include the use of these in addition to the TimeInstant-dependent properties.

**Comment by rjyounes** [comment]
This will be addressed in #499.
