### ISSUE TITLE
Create subclasses for types of locations

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#471]
Proposal:

- Add class `gist:Location`
- Rename `gist:Place` (a physical place) to `gist:PhysicalLocation` and make it a subclass of `gist:Location`
- Add `gist:VirtualLocation`, also a subclass of `gist:Location` 
- Same predicate used for all three - `gist:hasLocation`.
- Physical place located by a street address, geo points, etc.
- Virtual location located by URL, file path, etc.

**Comment by uscholdm** [comment]
In English, place and location are virtually identical in meaning.   We already use `gist:Place` as the generic "any possible answer to a 'where' question", but if there is a good reason we could rename it to be `gist:Location`. Whatever we choose, the two subclasses should be prefixed by 'Physical' and 'Virtual'.

> same predicate for all three 

There lots of predicates that can point to a place.  I have a birth place and I have a residence and I have where I am sitting right now, which I wish was on a mountain top watching a sunset.

> Physical place identified by a street address, geo points, etc
Virtual location identified by URL, etc

`identifiedBy` has range of ID, not Content.  Its a bit tricky relating a building address to a physical location.  You can think of web address or a zoom adddress as virtual places that you go to.  I don't know the best way to do that.

**Comment by rjyounes** [comment]
@uscholdm 

_In English, place and location are virtually identical in meaning. We already use gist:Place as the generic "any possible answer to a 'where' question", but if there is a good reason we could rename it to be gist:Location. Whatever we choose, the two subclasses should be prefixed by 'Physical' and 'Virtual'._

Agreed.

_There lots of predicates that can point to a place. I have a birth place and I have a residence and I have where I am sitting right now, which I wish was on a mountain top watching a sunset._

What I meant here is that for a generic 'located at' predicate, the same can be used for both virtual and physical locations.

_identifiedBy has range of ID, not Content._ 

I did not mean `identifiedBy`, I meant "identified by" in the loose sense. The predicate could be `hasAddress` or whatever, I was not specifically addressing this point. However, `gist:hasCommunicationAddress` doesn't seem to work for virtual locations. Maybe we could create `hasAddress` and make it a superproperty of `hasCommunicationAddress`. The address of some virtual locations, like websites, would be a URL.

**Comment by uscholdm** [comment]
> I did not mean `identifiedBy`, I meant "identified by"
> However, gist:hasCommunicationAddress doesn't seem to work for virtual locations. 

Oh, how silly of me :-).
Someone might say only communicate to me via email or phone. Those are both virtual.

> What I meant here is that for a generic 'located at' predicate, the same can be used for both virtual and physical locations.

Agreed.

**Comment by rjyounes** [comment]
Jamie's use case: where can I find the data that I want to point to? E.g., this named graph in this dataset. This use case is solved by the resolution of #483, so we will leave it in review.

**Comment by rjyounes** [comment]
Won't fix. Distinction between VirtualLocation and its address isn't clear, and there are no urgent use cases.

**Comment by uscholdm** [comment]
This keeps coming up. It came up again today: #1009

**Comment by rjyounes** [comment]
Closing - the address working group has not found a need to model different types of locations.
