### ISSUE TITLE
Move all instances out of gistCore into individual files

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#474]
E.g., move all units into a gistUnits file, mime types into gistMimeTypes, etc. Users will have to import the files they need.

**Comment by rjyounes** [comment]
Relates tangentially to #463.

**Comment by uscholdm** [comment]
IRelates directly (by subsumption?) to #305 . We might want to introduce a gistx namespace.

**Comment by rjyounes** [comment]
Will not fix. There are classes referring to the instances, so they should not be moved out into a separate file - would create a circular import.
