### ISSUE TITLE
Policy for major releases

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#475]
A major release will generally have a number of things that would not require a major release, in addition to the things that do.  Lets call the former changes A and the latter changes B.

A user may wish to have all of A, but not want to deal with the major impacts of B. If A and B were rolled into a single major release, such users will suffer. This problem could be solved by making two releases at the same time.  
1. one more point release with only changes A (e.g. 9.8.0)
2. a major release with only changes B (e.g. 10.0.0)

Is this something worth considering, given the extra work?  Is this sort of twofer release approach ever done for ordinary software releases?

**Comment by rjyounes** [comment]
Interesting idea. I've put it into the June project so we can consider it before the release of 10.0.0.

**Comment by rjyounes** [comment]
Boris: Too much overhead. Would need two release branches and continuous merge from the minor release branch to the major one.

DECISION: Don't do this.
