### ISSUE TITLE
Create a method to automatically generate gist documentation as part of the release process

### ISSUE THREAD

**Issue by sa-bpelakh** [semanticarts/gist#476]
There are several alternatives that should be explored:

1. The Markdown/e-Book approach developed by @pwin , and
2. The query-generated tabular view created by @uscholdm

**Comment by pwin** [comment]
The Markdown approach is to create the core book in markdown then to use [Pandoc](https://pandoc.org/) to convert that to epub format and then to use the [Amazon Kindle Previewer 3](https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765261) to convert to the Kindle format.  Both can be run from the command line, so there is scope for developing a fully scripted pipeline

**Comment by pwin** [comment]
Part of the gist-doc and ontology-documentation repos
