### ISSUE TITLE
Rename TemporalRelation to TemporalRelationship

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#478]
An instance of `gist:TemporalRelation` is a relationship between two things, it is not a relation. So the class should be renamed to `TemporalRelationship`

See also #188

**Comment by rjyounes** [comment]
What's the difference between a relation and a relationship? Relation: "the way in which two or more concepts, objects, or people are connected..." Why is this not appropriate?

**Comment by uscholdm** [comment]
The **way** I am related to you is the same **way** that Dave is related to you (being a work colleague of)  `isColleagueOf`.  OWL calls that a property, in math/logic it is called a relation.  There is just one relation, but many relationships. Here are two:
- Michael is colleague of Dave
- Rebecca is colleague of Dave

These are relathionSHIPs, not relaSHINS.  The time stamps are different for each of these two instances of (what should be called) `TemporalRelationship`.    Or more likely, a subclass of `TemporalRelationship` whose skos:definition might be "collegial relationship between two people that holds for  a period of time."

**Comment by rjyounes** [comment]
I see. That makes sense.

**Comment by uscholdm** [comment]
@rjyounes 
We should revisit this, and if we keep it, it should ideally be along with other name changes.  It's minor and could be tempered with a scope note.

**Comment by rjyounes** [comment]
I've added it to the 12.1.0 project for review.

**Comment by rjyounes** [comment]
Closing - not significant enough to change.
