### ISSUE TITLE
Reconsider Event class hierarchy

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#489]
Questions:
- Why do we have `ContemporaneousEvent`, `HistoricalEvent`, but no future event? Note that this is not the same thing as a planned event, which could be past, present, or future.
- Do we even want classes that define the time of an event relative to the current time at all? While a historical event will always be a historical event, for the others we have to change the class assignment over the course of time. E.g., when an end date for a `ContemporaneousEvent` is recorded, and that date is in the past rather than the future, we have to change the class assignment of the event. 
- `Task` is a subclass of `Event`. While I suppose a task is in some sense an event, that doesn't strike me as its salient characteristic. It also doesn't have to have either a start or end date - and not just in the open world sense of not knowing what those are, but actually _not having them_. E.g., I have a task on my to-do list but no specific time I plan to accomplish it. I have a work task but it has not been scheduled yet.

Relates to #174 - we may want to consider some of these questions in tandem.

**Comment by uscholdm** [comment]
> Why do we have ContemporaneousEvent, HistoricalEvent, but no future event?

We do have it, but like the proverbial rose, it has a different name: `PlannedEvent`. It means: "An event which, at the time it is created, is to occur in the future."

**Comment by uscholdm** [comment]
> Task is a subclass of Event. While I suppose a task is in some sense an event, that doesn't strike me as its salient characteristic.

'Task' is generally used not to be the doing of the thing, but the thing to be done (e.g.  I have a list of tasks). So I disagree with having a class called `Task` be a subclass of `Event`. The closest thing in gist we have for 'the thing to do' is `Behavior`.

**Comment by rjyounes** [comment]
@uschold Re `Task` - you are echoing my point. `Task` is currently a subclass of `Event`, but I was arguing that it should not be.

Re future event: this is different from a planned event. We may predict the occurrence of a future event such as a hurricane, but it is not planned. See also related issues #176 and #402.

**Comment by uscholdm** [comment]
> Re `Task` - you are echoing my point.

That was my intent.

**Comment by uscholdm** [comment]
> Re future event: this is different from a planned event. We may predict the occurrence of a future event such as a hurricane, but it is not planned. See also related issues #176 and #402.

That's interesting - many distinctions. We have often used a class called `HypotheticalEvent`, in the context of bad things that might happen. Simulated toxic spills, houses burning down etc.  They are specifications / characterizations of events that _might_ happen. They may never happen, so calling them future or planned events is wrong.  

How would you create an instance of a future hurricane? How would you distinguish one future hurricane from another? You know that **A** hurricane will happen in the future in some region (but there could be two at the same time). To talk about a **particular** hurricane would, perhaps better be viewed as a hypothetical event.

**Comment by rjyounes** [comment]
Partially duplicates #176
