### ISSUE TITLE
gist 8.2.0 and gist 9.0.0 are not using git branching

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#49]
I see some issues being closed as "resolved" in "gist 8.2.0" and/or "gist 9.0.0" but there are no branches for such revisions. 

I strongly urge that we use this branching/workflow scheme for gist changes: 
     https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow 
This approach uses feature branches off the master and pull requests to make changes.

**Comment by mkumba** [comment]
I'm trying #49
