### ISSUE TITLE
Add examples to show how things are used.

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#496]
Put in a separate examples folder.

**Comment by uscholdm** [comment]
I am working on this.

**Comment by rjyounes** [comment]
I'd like to consider moving these to the `gist-doc` repository so they are not tied to our release schedule. If they are distributed with a release, it creates a lot of additional work to update the examples accordingly. Even if not distributed in a release, I think the implication would be that they are being kept up-to-date with the develop branch, surely to onerous a task when making changes to gist. The `gist-doc` repo can get out of sync with the current state of gist, either released or in development, without creating confusion as long as it's made clear in the readme. @pwin's documentation in that repo, for example, is not updated on the same schedule as gist.

**Comment by uscholdm** [comment]
This is an excellent point.

**Comment by rjyounes** [comment]
Closing - examples will reside in gist-doc repo, @uscholdm to create new issue there.

**Comment by uscholdm** [comment]
> Closing - examples will reside in gist-doc repo, @uscholdm to create new issue there.

Issue created: https://github.com/semanticarts/gist-doc/issues/7

**Comment by JonathonGist** [comment]
Thank you team for doing this--I can hardly wait to read it, when I get some time.
