### ISSUE TITLE
Referring to ontology terms in annotations

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#497]
If a skos:definition refers to OrderedCollection how should it appear?  should it show up as the ontology term or in regular Engliseh words.  For example:
- skos:definition "An ordered collection that is wonderful"^^xsd:string ; 
- skos:definition "An OrderedCollection that is wonderful"^^xsd:string ;

**Comment by rjyounes** [comment]
Put another way, the question is are we trying to refer to the _concept_ or to the term in the ontology? Most often if it's clearly a real-world thing, like person, I would use the ordinary English, but `OrderedMember` is not something that exists in the real world, it's a modeling construct, so it's unclear what to do in this case.

**Comment by uscholdm** [comment]
@ryounes 
This is worth bringing up with the group to get opinions.

**Comment by jtdelany58** [comment]
It seems to me that OrderedCollection should be included in the description, even if it added to the English wording.  For example, An ordered collection (OrderedCollection) that is wonderful".

**Comment by rjyounes** [comment]
I've developed a personal rule-of-thumb, which is that in definitions and scope notes I use ordinary English, whereas when referring to terms in an editorial note, I use the term name. For example:

```
skos:definition "An ordered collection that is wonderful." ;
skos:editorialNote "Consider whether this should be a subclass of OrderedCollection." ;
```

**Comment by rjyounes** [comment]
Closing - duplicates #966.
