### ISSUE TITLE
gist imports should use version numbers

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#50]
Currently, all the owl:imports statements in the gist files specify the non-numeric version numbers, e.g.:

     `<owl:imports rdf:resource="http://ontologies.semanticarts.com/o/gistAddress"/>`

To avoid possibly importing the wrong versions of files, they should really import by version number, e.g.:

     `<owl:imports rdf:resource="http://ontologies.semanticarts.com/o/gistAddress8.0.0"/>`

**Comment by mkumba** [comment]
I think this will be fixed if I can get my git process to work 9.0.0 #50

**Comment by mkumba** [comment]
I think this will be fixed if I can get my git process to work 9.0.0 #50
