### ISSUE TITLE
Remove inverses unless there's a compelling reason

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#506]
As per the decision in #294, we should purge gist of inverse properties that don't have a compelling reason to exist. In general, the guidance is that if there's a tree-like structure, keep the property that goes up rather than down the tree, since cardinality generally will be greater going downward. If there's no tree-like structure, it's dependent on individual context.

This will be a minor change if we deprecate the inverses. 

[Added]
From Issue #551 
`precedesDirectly` has inverse `followsDirectly`, but `precedes` has no inverse `follows`. Should be consistent one way or another.

**Comment by rjyounes** [comment]
We currently define 17 inverses. 

We have to decide which ones to keep. @uscholdm and @mdfeickert will take a pass at a proposal and present.

Rebecca: use directionality guidelines in style guide.

Peter: If we don't provide inverses, people will be rolling their own. We should put recommendations in place for when it's appropriate. 

Peter: could also have an optional import of the inverses.

Michael: or add an annotation with suggestions of how to name the inverses.

Rebecca: Why do we care what other people name properties in their own namespaces?

Rebecca: We don't need both the annotation and the import. The latter seems better.

Borislav: Remove all inverses from gist and put in a separate file.

Michael: There are some inverses I use all the time that I would like to keep, but I wouldn't want to use the whole file. So each person would have to pick and choose the ones they want. This is inconvenient, and argues for keeping the commonly used ones in gistCore.

Michael: May also propose bringing a few back.

**Comment by rjyounes** [comment]
Consider in conjunction with #551.

**Comment by JonathonGist** [comment]
Glad for these decisions--especially that all of them are to be available in an imports file. And I'm glad that the special ones, used often, are being preserved in gistCore.

**Comment by JonathonGist** [comment]
It seems that with the availability of inverse paths in SPARQL and SHACL, there is limited or no need for adding inverse predicates to an ontology. My argument for keeping them in a separate file has evaporated.

**Comment by rjyounes** [comment]
I've now come across a case or two where the inverse appears to be necessary. For example, if we have a `gist:ControlledVocabulary`, we probably want to assert `<term> gist:isMemberOf <term>` rather than using a value restriction on `gist:hasMember` on the vocabulary itself. This results in duplication and therefore maintenance problems.

Having thought of this case, I now think we have to proceed with some caution, though at the moment I haven't thought of any others.

**Comment by rjyounes** [comment]
@marksem will provide a candidate list of removals and run it by the group.

**Comment by uscholdm** [comment]
The inverse issue: what is the rationale for choosing which direction to keep?  I wrote this up in  a blog and in my book.  [Whitepaper: Quantum Entanglement, Flipping Out and Inverse Properties (semanticarts.com)](https://www.semanticarts.com/whitepaper-quantum-entanglement-flipping-out-and-inverse-properties-in-owl/) Look for "preferred persepctive"
Whitepaper: Quantum Entanglement, Flipping Out and Inverse Properties
In this whitepaper, we take a deep dive into the pragmatic issues regarding the use of inverse properties when creating OWL ontologies.

**Comment by rjyounes** [comment]
@marksem Please note that issue #551 should be considered in tandem.

**Comment by Jamie-SA** [comment]
Choosing `gist:hasAspect`, and other similar directionalilty (`gist:isCategorizedBy` & `gist:isCharacterizedBy`) also aligns with the reduced cardinality preference.

Similarly, I think that would suggest use of `gist:isPartOf` and `gist:isDirectPartOf` over their inverses.

Now, if you really want to reduce triple explosion, get rid of those transitive/non-transitive pairs. Mostly kidding. But I do wonder how important others find them to be in their work. (warning... completely separate issue)

**Comment by rjyounes** [comment]
Proposal:
* Select one of a pair of inverses to remain in `gistCore, the other to be moved to a separate file `gistInverses.ttl` that can optionally be imported by users.
* General consideration for which predicate to keep in `gistCore` is cardinality, for query performance. For example, we are generally expect fewer relationships in the `isBasedOn` direction than `isBasisFor`, or `isPartOf` than `hasPart` (a template is the basis for many instantiations, but the instantiation is typically based on a single template; an engine is part of only one car, but a car has many parts).
* Some cases will not be clear, such as `isAbout` and `isDescribedBy`. Choose your favorite.

**Comment by rjyounes** [comment]
Another motivation for removing inverses: I'm seeing clients generating RDF sometimes using one inverse, sometimes another. You could say this is just bad practice, but the existence of the inverse sets us up for that practice. Then if inferencing is _not_ being run, you have to know which predicate to query for in which cases.

**Comment by rjyounes** [comment]
Addition to above proposal: In some cases the way we think about and use concepts is in the opposite direction. `isIdentifiedBy` is a good example: We generally ask "What is X's SSN?" rather than "Whose SSN is this?" So we should keep `isIdentifiedBy` in gistCore.

**Comment by marksem** [comment]
I like the idea of no inverses to avoid confusion.   I also applaud the pragmatism of letting overwhelming use modify the general consideration.

**Comment by Jamie-SA** [comment]
@philblackwood offered to take a look at this.

**Comment by philblackwood** [comment]
There are many good reasons to eliminate inverses; see Michael Uschold's document for a good discussion. His comment above is from Sep 8, and the link is: 
https://www.semanticarts.com/wp-content/uploads/2018/10/QuantumEntanglementInverseProps041516MFUnewtemplate.pdf

Attached is a straw proposal for which ones to keep. The three main criteria are:

1. Ease of understanding, e.g. hasSuperCategory is contrary to common usage (subClass, subTask, sub...)
2. Does the property usually describe the subject? (e.g. isIdentifiedBy)
3. Is it usually many-to-one, or functional vs. inverse functional? (isPartOf)

In the attached, each property on the "keep" list has highlights to show which of these 3 criteria is met in most cases of expected usage. Some of these might be debatable, so let's pool our experiences to refine the attached view.

[inverses.xlsx](https://github.com/semanticarts/gist/files/10520688/inverses.xlsx)

**Comment by rjyounes** [comment]
@philblackwood We have defined a rule of thumb that the retained properties should go from "child" to "parent" for query performance and also to express the dependency relationship. These both contradict your first conclusion: (1) a subcategory generally has only one supercategory (except in polyhierarchies, which we don't often use), while a supercategory may have many subcategories. (2) The subcategory is dependent on the supercategory but not the reverse. Also, in this particular case I don't see any issue of ease of understanding. `hasSubTask` should be reversed to `hasSuperTask`, in fact, by the reasoning I've given. Though independently I've suggested we don't need it since we can use `isPartOf`; see [issue #733](https://github.com/semanticarts/gist/issues/733).

**Comment by rjyounes** [comment]
Result of gist dev team meeting discussion:

Problems with inverses:
* They increase cognitive load, during ontology development, querying (have to query with both predicates), and ETL.
* They blow up inferencing engines like RDFox and Stardog. 

Agreed on:
* Remove *all* inverses from gistCore.
* For some of the inverses in Phil's spreadsheet, agreed on which inverse to keep.
* Define as best practice, to include in documentation, a white paper, etc.

Still open:
* Provide a file of the inverses removed from gistCore? Some argue no, on the grounds that it doesn't make sense to document a best practice and at the same time provide a means to avoid it.
* For some predicates, still need to agree on which to keep. Some argue that providing a separate file of the removed inverses would make it easier to agree on.

Attached is the in-progress spreadsheet with column C indicating decisions that have been made.

[inverses.xlsx](https://github.com/semanticarts/gist/files/10700621/inverses.xlsx)

**Comment by rivettp** [comment]
Firstly, I agree with the decision. 
But I'm wondering if you considered adding an annotation property to retain the name to be used (e.g. in user interfaces, or SHACL shapes) for the inverse direction. I recall that a few other ontologies have done this (but cannot recall which ones!). 
Another potential annotation property might be the expected cardinality of the inverse direction.

**Comment by rjyounes** [comment]
Form working group to handle "still open" items from Feb 9. Spreadsheet from that meeting is the up-to-date version of what we've agreed on.

Volunteers:
* Michael
* Dylan
* Rebecca

Rebecca to call meeting.

**Comment by marksem** [comment]
^^ @dylan-sa , can you put me as optional on that meeting.  I'd like to weigh-in if I have time.

**Comment by rjyounes** [comment]
> Decision on keeping inverses in a separate file: Inverses to be removed and not maintained in a separate file

I was under the impression that this was still an open question. @dylan-sa , are you still abstaining?

**Comment by dylan-sa** [comment]
@rjyounes I'll go ahead and cast my vote in favor of complete removal so we've got a proper majority.

**Comment by dylan-sa** [comment]
Putting back into draft mode until more revisions are made.
