### ISSUE TITLE
Taxonomy class has incorrect restrictions

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#51]

**Comment by mkumba** [comment]
#51 changed to gist:hasMember soem gist:Category in gist 9.0.0

**Comment by mkumba** [comment]
#51 changed to gist:hasMember soem gist:Category in gist 9.0.0

**Comment by uscholdm** [comment]
If this is an equivalence, and you use some vs. all, you have an definition that incorrectly allows a vocabulary to have members that are non-categories, e.g. laptops, contracts and buildings.  If it is subclass, then it is correct.

**Comment by mkumba** [comment]
When I made this change Taxonomy == Controlled Vocabulary.  Do we need Taxonomy

I added this
![image](https://user-images.githubusercontent.com/25790/55118012-6dea8e80-50b2-11e9-9364-dbe88d35429d.png)

**Comment by mkumba** [comment]
Adding the all values makes the subclassing work out but it does it by not adding anything.  Yes you're right you could add shoes and ships and ceiling was to the taxonomy, but by saying that is the distinction you're allowing the shoes in the ControlledVocabulary.  But really allValues isn't adding to the definition of the class you put it on.  It's adding to the definition of its completment, and its adding to the definition of the filter class.  But really its trying to be a constraint, and Id rather have SHACL manage the constraints.

**Comment by uscholdm** [comment]
I don't think of the allValues axiom as a constraint.  I think of it as a true statement that helps to clarify the meaning of the concept.  Meaning can be used in different ways. Being a constraint is just one. 

Its always a judgment call whether to put true statements in the model that clarify meaning, and whether to have those statements be in annotations or in formal axioms.

**Comment by uscholdm** [comment]
Regarding the inferred equivalence of Taxonomy and ControlledVocabulary and whether we need the former.   They are only equivalent because not enough meaning has been added to Taxonomy.  The definition is Taxon is a bit clunky, it is really just the role of a member of a ControlledVocabulary, and we generally avoid defining Role classes.  Its odd that this is not just easy to do.   It seems useful to have a class for Taxonomy meaning that its members are arranged in a hierarchy. It is less obvious that specifying axioms that make that distinction is useful.

**Comment by uscholdm** [comment]
Can we define Taxonomy this way, per one of the above diagrams, but ignoring the navigational parent part.
ControlledVocabulary and 
(hasMember some ( (hasSuperCategory some Category) OR
                                 (hasSubCategory some Category) 
                                  )
 )

**Comment by mkumba** [comment]
Clever, good idea

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by uscholdm** [comment]
Its more fully described above with a question about whether we want to include navigational links too. Maybe not, since a taxonomy categorizes, but a so called navigational taxonomy is not really a taxonomy, in that the nodes are not categorizing anything, or if they are, in a very different looser way.

Might we get rid of our own superCategory and use skos:broader for simplicity's sake?
