### ISSUE TITLE
Add best practice for negative examples to style guide

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#511]
E.g., for `StreetAddress`:

```
gist:negativeExample "A PO box address or FPO code."
```

Evolved from the discussion of PR #508.

@uscholdm I don't see a similar issue from you, but if you have submitted one we can close this as a duplicate.

**Comment by uscholdm** [comment]
Its not a stretch to think of a negative example as an example, so we could get away with jsue using skos:example and highlight the fact that it is a negative example. e.g.
```
skos:example "Negative example: A fictional character is NOT a person."^^xsd:string ;
```

I don't feel strongly about it either  way.

**Comment by rjyounes** [comment]
I don't like relying on magic sequences of characters to convey the meaning - I.e., "Negative example." That reminds me of when, before we used `skos:example`, we had `rdfs:comment`s in the definition prefixed by "EXAMPLE:". This seems to be to defeat the purpose of having specific annotations. That being said, in this particular case it's not such a big deal either way.

**Comment by uscholdm** [comment]
Aside from the fact that there is nothing magical about negativity, I'm ok with having a separate annotation, but we might as well gather more opinions in case there is a clear preference.

**Comment by uscholdm** [comment]
@rjyounes Let's bring this to the group. I think it is a reasonable idea.

**Comment by rjyounes** [comment]
DECISION: 
 * Don't add an annotation property
 * Add to style guide - can add in scope note as "Negative example:"
 * E.g., "Negative example: PO Box, FPO code"

**Comment by rjyounes** [comment]
@uscholdm You give two wording examples above:
1. Negative example: A fictional character is NOT a person.
2. Negative example: PO Box
The are fundamentally different. Which do you prefer?

**Comment by uscholdm** [comment]
> @uscholdm You give two wording examples above:
> 
> 1. Negative example: A fictional character is NOT a person.
> 2. Negative example: PO Box
>    They are fundamentally different. Which do you prefer?

I don't think it matters much, the former is more explicit but sort of redundant/verbose since it should be obvious from context. If guess I mildly prefer the former.

**Comment by rjyounes** [comment]
Combine into a single PR with issue #966.
