### ISSUE TITLE
Migration script: Refactored ordered collection model

### ISSUE THREAD

**Issue by Jamie-SA** [semanticarts/gist#516]
Migration script: Refactored ordered collection model. Issue #112.
Added predicate gist:providesOrderFor. Deleted classes gist:OrdinalCollection and gist:OrdinalMember.

Things to do (needs review/agreement before implementing):

I am not sure. Anyone more familiar with this change is welcome to edit this comment to flesh out the requirements.

**Comment by rjyounes** [comment]
Issue warning, maybe provide suggestion.

**Comment by Jamie-SA** [comment]
I think this is old and no longer needed.
