### ISSUE TITLE
Change definition of gist:Transaction

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#521]
"An event which has an effect on at least one accumulator."

"Accumulator" is not a generally understood term. 

Suggestion: "An exchange or transfer of goods, services, or funds."

**Comment by DougalW** [comment]
Sounds much better. Value is also often used in modern contexts for transactions e.g. we might exchange precious metals. Most often value is denominated in funds (currency, tokens e.g. Etherium etc).

**Comment by uscholdm** [comment]
> Suggestion: "An exchange or transfer of goods, services, or funds."

I think this is pretty good, but misses what Dave wanted to emphasize about an accumulator. The idea is that the transaction is tracked in some way. But, I can scratch your back if you scratch mine, and that is a transaction w/o any record.  If a business context, this may not be that relevant.  Maybe add a scope note that transactions are recorded in some way?

M.

**Comment by Jamie-SA** [comment]
After Dave's recent work on accounting he might have some newer/additional thoughts on Transactions.

**Comment by DougalW** [comment]
This is a very interesting one to define. I can think of at least three categories of transaction (two are economic, the third  technological): 
1. formal value-exchange based (in the accounting sense i.e. I account for each side of the ledger via some form of token for value exchange and recording of the transaction and value exchange)
2. informal value-exchange based (as in gifting/reciprocity networks where the transaction itself is implicit i.e. accounted for in people's heads but still there nonetheless, and value exchange is often via direct mechanisms such as labour, favours etc)
3. non-value based transactions (the most obvious being transaction control systems in technology systems like CICS, ACID transactions for database updates etc)

**Comment by rjyounes** [comment]
This is subsumed by #534 but I'm leaving it open so we make sure to consider the specific issues addressed here.

**Comment by rjyounes** [comment]
For reference: definition of "accumulator" in finance: https://en.wikipedia.org/wiki/Accumulator_(structured_product).

This is a highly specialized sense of transaction, so the underlying question is whether to broaden it.

**Comment by uscholdm** [comment]
@rjyounes The current version of gist:Transaction has no restriction:
```
gist:Transaction
	a owl:Class ;
	rdfs:subClassOf gist:Event ;
	skos:definition "An event which has an effect on at least one accumulator."^^xsd:string ;
	skos:prefLabel "Transaction"^^xsd:string ;
	.
```

I like the annotations proposed by @rjyounes above.  The new proposal is:
```
gist:Transaction
	a owl:Class ;
	rdfs:subClassOf gist:Event ;
	skos:definition "An exchange or transfer of goods, services, or funds."^^xsd:string ;
	skos:prefLabel "Transaction"^^xsd:string ;
        skos:scopeNote "Different sorts of transactions would have different datetime precisions. For example, an electronic transaction would have a gist:actualEndMicrosecond." ;
	.
```

Should we make it a subclass of `HistoricalEvent`? My feeling is NO.  Although it would be consistent with the original restriction, it would not allow a Transaction to have a planned future start time.

**Comment by rjyounes** [comment]
I agree that it should not be a subclass of `HistoricalEvent`, for the reason you state. I like your proposed definition, and would make one small change to the scope note ("would have" sounds odd in the first sentence).

```
skos:scopeNote "Different sorts of transactions can have different datetime precisions. For example, an electronic transaction would have a gist:actualEndMicrosecond." ;
```

I'm fast-tracking this one and assigning it to @uscholdm.
