### ISSUE TITLE
Define predicate gist:offers to use with Offer in place of hasDirectPart

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#528]
The relevant restriction on `gist:Offer`:

```
  a owl:Restriction ;
  owl:onProperty gist:hasDirectPart ;
  owl:someValuesFrom gist:CatalogItem ;
```

`hasDirectPart` is not specific enough, IMO, to represent the relationship between an offer and the thing being offered. I propose `isOfferOf`.

**Comment by uscholdm** [comment]
Is this solving an existing problem or a possible future problem?

**Comment by rjyounes** [comment]
I'd like to keep it. I've come across this in client work.

**Comment by uscholdm** [comment]
isOfferOf is clunky. Here are other options:

1. This offer **is an offer of** an iPhone 15 Pro
2. This offer **offers** an iPhone 15 Pro
3. This offer **is offering** an iPhone 15 Pro

But I still am not inclined to add a predicate that has such limited scope for use which does not disambiguate anything, it mostly only sounds nicer.

**Comment by rjyounes** [comment]
What are we offering? A specification? A thing conforming to the specification?
Rebecca: I can offer a specific item for sale - e.g., my house
Dave: There's still a specification about what must be delivered. When you sell something, there's an obligation to deliver and an obligation to  pay. At the time of the offer, the thing being delivered doesn't exist. When you sell a house, you're delivering a title. 

Jamie: Agree that there should be a different predicate, but not convinced `isOfferOf` is the right one. Something more general would be better.


Offer consists of:
* Dates (start and end dates)
* Monetary amount (hasMagnitude Magnitude with aspect price)
* Thing offered - predicate??
* Optionally: who it's offered to - hasRecipient

Proposals:
1. Change predicate in the restriction from `hasDirectPart` to `isOfferOf`
2. Keep `hasDirectPart` in the restriction - voted down

Proposed restriction:
```
  a owl:Restriction ;
  owl:onProperty gist:isOfferOf ;
  owl:someValuesFrom owl:Thing ;
```
Add scope note to give examples of types of things offered.

For next meeting: either accept `isOfferOf` or bring another proposal.

**Comment by philblackwood** [comment]
What does the proposed predicate isOfferOf mean? Not sure why we would consider approving something that hasn't been defined yet.

To make it work, I think the object needs to be a specification, and isOfferOf really means "is offer of a thing meeting the specification".

We need to have a clear definition before approving.

**Comment by uscholdm** [comment]
> What does the proposed predicate isOfferOf mean? 

Something like this::

**definition**: Relates an offer to the thing being offered.
**example**: A used car ad is an offer of a specific car.  An offer for an iPhone is for any phone that meets the appropriate specification

**Comment by Jamie-SA** [comment]
I kind of like `gist:isAbout` as it would be more generic, except that it's domain is `gist:Content` which makes it not very general. If we add `gist:isOfferOf` it will also be fairly specific to only `gist:Offer`. I guess it depends on how many Class specific properties we want to have in gist.

**Comment by uscholdm** [comment]
> I guess it depends on how many Class specific properties we want to have in gist.
Generally fewer is better, but sometimes it is hard to think of good alternatives.

**Comment by uscholdm** [comment]
> I kind of like `gist:isAbout` as it would be more generic, except that it's domain is `gist:Content` which makes it not very general.

If we broadened domain of isAbout to include Offers, then it's definition might be too broad to use with Offer. An offer could be about the item for sale, but it might also be about a 10 year anniversary sale. Thus Offer isAbout X would be ambiguous.

**Comment by marksem** [comment]
Sorry late to this party.  'isOfferOf' sounds really contrived to me.  Would 'offers' be a more general predicate?

**Comment by rjyounes** [comment]
@marksem @uscholdm I still feel queasy about the double use of `offers`. If `Offer` is a reification of this predicate, then it is odd for it also to use this predicate. This is the issue Michael and I raised yesterday. I realize the reification is not expressed formally, so there are no formal logical consequences, but conceptually it seems wrong to me.

**Comment by stevenchalem** [comment]
If we are to avoid the double use of `offers` and just specify a predicate that connects a `gist:Offer` to the thing being offered, then  `gist:isAbout` might work, except that it applies to `gist:Document` and a `gist:Offer` is not a `gist:Document`. Could we loosen that restriction on `gist:isAbout`? Introduce something similar like `gist:covers`?

**Comment by rjyounes** [comment]
I think it's important to have a predicate for aboutness limited to content. Any other aboutness is a stretch, in my opinion. (FYI the domain of isAbout is Content.)

**Comment by rjyounes** [comment]
Just throwing out `isBasedOn` as a possibility, though I don't love it.

**Comment by rjyounes** [comment]
I am now inclined to postpone this to 13.1 and bring it back to the group, for the following reasons:

* We had lengthy discussion of this issue over a couple of meetings and came to a decision. From a procedural point of view, we should not undo that decision either in a group of 4 after the meeting or in a comment thread.
* This is just one predicate but there are a couple of larger issues at stake:
  * Predicates for specific resources: this is not ideal but we do have quite a number of them already in gist. We would not be setting a new precedent with `isOfferOf`. 
  * Use of a predicate both with and without a reified relationship or other object (or turning it around, both as a shortcut and a non-shortcut).

@stevenchalem What do you think?

**Comment by stevenchalem** [comment]
@rjyounes I agree. But does the restriction change in gist:Offer make this a major change that would need to wait for 14.0?

**Comment by uscholdm** [comment]
If we are considering isBasedOn and isAbout, we might as well go back to hasDirectPart. The whole idea was to make it more specific.

**Comment by stevenchalem** [comment]
@uscholdm wrote > If we are considering isBasedOn and isAbout, we might as well go back to hasDirectPart. The whole idea was to make it more specific.

@marksem's objection was that `gist:hasDirectPart` is *too* specific -- that it is "bespoke". Although @rjyounes's original statement was that `hasDirectPart` is too specific, what came out in discussion was that people found it not a good fit; that `hasDirectPart` doesn't correctly denote the relationship between an offer and the thing being offered. So my interpretation of the goal is to find a predicate that correctly describes that relationship yet is general enough to have broader application. But maybe that's just my interpretation.

**Comment by Jamie-SA** [comment]
> @marksem's objection was that `gist:hasDirectPart` is _too_ specific -- that it is "bespoke".

@stevenchalem did you mean to say "`gist:isOfferOf` is _too_ specfic"?

**Comment by stevenchalem** [comment]
> > @marksem's objection was that `gist:hasDirectPart` is _too_ specific -- that it is "bespoke".
> 
> @stevenchalem did you mean to say "`gist:isOfferOf` is _too_ specfic"?

Yes. Thank you. Corrected.
