### ISSUE TITLE
Add domain Aspect to gist:isAspectOf

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#529]
Judging from the definition of `aspectOf` as "What this aspect is referring to," the intent seems to be to apply specifically to `gist:Aspect`. If so, formalize that with a domain of `Aspect`.

**Comment by uscholdm** [comment]
This sort of things usually come back to bite us. I suggest leave it as it is.  Maybe change the definition?

M.

**Comment by uscholdm** [comment]
Subsumed by #697
