### ISSUE TITLE
Broaden text definition of gist:isAllocatedBy

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#530]
The definition is: "Connection between an ID and the thing that minted the ID.  It may be a person or organization, or could be an algorithm (next available or random number generator)."

The domain is not specified.

There are other things that can be allocated - e.g., certifications, ratings, default units of measure for an aspect, etc.

**Comment by rjyounes** [comment]
This is subsumed by #534 but I'm leaving it open so we make sure to consider the specific issues addressed here.

**Comment by marksem** [comment]
> There are other things that can be allocated

in fact, we use this property in the axioms of gist:Category, so clearly its Domain is beyond just IDs, even in internal gist usage.

**Comment by rjyounes** [comment]
Decision: update `skos:definition` to include other types of entities, as suggested above.

Add `domainIncludes gist:ID`.
