### ISSUE TITLE
Annotations for conversion ratio properties

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#533]
`standardConversionFactor` (formerly `convertToStandard`): The definition provided is more like a scopeNote plus an example: ""Note this kind of conversion will only work with temperatures if they are in Kelvin or Rankine (with a true 0).  You multiply to get to the base, divide to go from the base. mph to mps is .44704.  The multiple from kph to mps is .277778 .  To convert 60 mph to kph is (60 * .44704 / .277778 or 96.56056 kph"
Proposal: Break this up into a scopeNote and example, and add an actual definition.

`baseConversionFactor` (formerly `convertToBase`): Definition is ""The conversion factor used to get to the base unit.  E.g., multiplying by 0.0254 gets you from inches to meters. Divide by this number to go the other way. Used in conjunction with conversionOffset to convert from one unit to another. Degrees K =  (Degrees F - conversionOffset) * convertToBase. Or K = (F-(-469.67)) * (5/9.  To go the other way: F = (K * 9/5) -469.67.  Try it on Google."
Proposal: Break up into definition and example, and remove "Try it on Google."

**Comment by uscholdm** [comment]
I think the local names should be 
- `standardConversionFactor` 
- `baseConversionFactor` 

The are conversion factors, not ratios.

**Comment by rjyounes** [comment]
@uscholdm I've now fixed this in PR #535.

**Comment by uscholdm** [comment]
@rjyounes There is just one property in gist 12.0.0: `conversionFactor`. Examples are already split out. The definition is much better. I propose to close this issue.
```
gist:conversionFactor
	a owl:DatatypeProperty ;
	rdfs:domain gist:UnitOfMeasure ;
	rdfs:isDefinedBy <https://w3id.org/semanticarts/ontology/gistCore> ;
	rdfs:range xsd:double ;
	skos:definition "The conversion factor used to convert a unit to its standard (i.e., coherent) unit (which could be a base unit.)"^^xsd:string ;
	skos:example
		"A value expressed in inches is multiplied by a conversion factor of 0.0254 to express the value in the base unit, meter."^^xsd:string ,
		"An area expressed as 7 square kilometers is multiplied by a conversion factor of one million which results in 7 million square meters."^^xsd:string
		;
	skos:prefLabel "conversion factor"^^xsd:string ;
	skos:scopeNote "Sometimes this property must be used in conjunction with conversionOffset. Kelvin =  (Degrees F - conversionOffset) * conversionFactor. Or K = (F-(-469.67)) * (5/9)."^^xsd:string ;
	.
```

**Comment by rjyounes** [comment]
Yes, the issue is outdated.
