### ISSUE TITLE
Define a property to indicate how the items in an OrderedCollection are ordered

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#545]
Example follows. Please read the editorial note and examples.

```
gist:isOrderedBy 
	a owl:ObjectProperty ;
	rdfs:domain gist:OrderedCollection ;
	rdfs:range [
                 a owl:Class ;
		owl:unionOf (
			owl:ObjectProperty
			owl:DatatypeProperty
		);
	] ;
	skos:scopelNote "Two collections of the same individuals ordered in two different ways are two different ordered collections." ;
	skos:definition "Relates an ordered collection to the property by which the members are ordered." ;
	skos:example "The runners in a race could be ordered by finishing time, race number, national ranking, etc." ;
	skos:prefLabel "is ordered by" ;
	.
```

I wasn't sure about defining a range as above but Protege, Pellet, and HermiT accept it.

I would not insist on the domain of `OrderedCollection`.

This would of course be optional, not required.

**Comment by uscholdm** [comment]
OWL2-DL does not permit the object of a triple using a user-defined predicate (such as gist:isOrderedBy) to be a class or property. This would have to be an annotation property. Also, sometimes metrics such as finishing time are instances of a class such as Metric or MeasurableConcept or Characteristic.  So it might be better to use intendedRange rather than rdfs:range

**Comment by rjyounes** [comment]
Yes, I wasn't sure about using the property this way. Does this mean that Pellet and HermiT support OWL Full rather than just OWL DL?

I think now the best solution would use `Category` as the object of `allValuesFrom`.

**Comment by uscholdm** [comment]
> Does this mean that Pellet and HermiT support OWL Full rather than just OWL DL?

I don't think so, but I do find it a bit surprising.

> I think now the best solution would use Category as the object of allValuesFrom

This seems to be conflating rdfs:range with restrictions.  Rather than `Category`, maybe use `gist:Aspect`?

**Comment by uscholdm** [comment]
Indicating the basis for ordering is often useful. However, in some cases there is no ordering principle per se, so it should not be a necessary restriction. For example, if there are 3 degrees of importance, low, medium and high.  I can't think of anything useful to say about the basis for ordering. It is by edict, not by measurement.

**Comment by rjyounes** [comment]
The proposal is to make this optional.

**Comment by uscholdm** [comment]
OK - optional is good.

**Comment by uscholdm** [comment]
@rjyounes @jtdelany58  First, I'm surprised that the reasoners accepted that range. Even so, you cannot have properties as objects of triples with user-defined properties -- that would take you out of OWL 2 DL. You could have the range be `gist:Aspect` if you wanted `isOrderedBy`

BUT: this can be handled in a different way, whereby there is just one ordered collection which has the same members in the same order, but they are connected to different things.  Let's say there are two 100-meter races and we care about who finished 1st and 2nd both for the finish time and for the first 10 meters time.  There are four finishing orders as that we want to know about. Let's say these are the results:
Race 1: John comes in first and Jane comes in second for both aspects (finish and 1st 10m)
Race 2: For the finish time, again it is John first and Jane 2nd.  But the order is reversed  for the first 10m time.  

We can do the following using only two ordered collections.

![image](https://github.com/semanticarts/gist/assets/10777545/981f4316-8f42-45b7-a2da-4dfb7ab79787)

PUNCH LINE: 
- We do not need to add a property or a restriction, let users do things as they see fit.
- If anyone did want an `isOrderedBy` property, they should use Aspects, not owl properties.

**Comment by rjyounes** [comment]
Makes sense. Closing.
