### ISSUE TITLE
Open World makes first thing in an OrderedCollection indeterminate

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#549]
Given the open world assumption, it is not possible to tell which is the first thing in an OrderedCollection just by looking for the absence of a predecessor.   We may want an explicit `hasFirstMember` type property to remove this ambiguity and make it easy to find the first member of an OrderedCollection.

**Comment by rjyounes** [comment]
Excellent point from @stewardont. I'm in favor of this.

**Comment by rjyounes** [comment]
DECISION: Add `hasFirstMember` predicate - subproperty of `hasMember`, domain is `OrderedCollection`, range is `OrderedMember`. Not a functional  property since ordered collections are not necessarily strictly ordered.

**Comment by rjyounes** [comment]
Fixed in PR #667.
