### ISSUE TITLE
Consistency in inverses of precedes and precedes directly

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#551]
`precedesDirectly` has inverse `followsDirectly`, but `precedes` has no inverse `follows`. Should be consistent one way or another.

Relates to the general issue of inverses: #506.

**Comment by Jamie-SA** [comment]
Added to #506 and closing this one.

**Comment by philblackwood** [comment]
Actually, gist:follows is included in gist11.1.0 so this issue can be closed.
