### ISSUE TITLE
Migration: Refactored the way network connections are modeled per issue 126

### ISSUE THREAD

**Issue by Jamie-SA** [semanticarts/gist#557]
Tasks for migration - write queries to do the following:

- [x] `networkConnection` renamed to `links`
- [x] `hasFromNode` renamed to `linksFrom`
- [x] `hasToNode` renamed to `linksTo`
- [ ] Verify/warn if new restriction (on NetworkLink that it must have exactly 2 links) fails
- [ ] Verify/warn if new restrictions (on NetworkLink and NetworkNode that they must be memberOf a Network) fail

**Comment by uscholdm** [comment]
@Jamie-SA @rjyounes Can this be closed now?

**Comment by rjyounes** [comment]
Out-of-date.
