### ISSUE TITLE
Migration: Modified classes and properties related to street addresses

### ISSUE THREAD

**Issue by Jamie-SA** [semanticarts/gist#558]
- [x] Removed BuildingAddress. TODO: warn if exists
- [x] Added StreetAddress as subclass of PostalAddress. TODO: nothing
- [x] Replaced hasStreetAddress with the more general hasAddress TODO: suggest renaming existing properties
- [x] Removed streetAddressOf. TODO: warn if exists
- [x] Removed communicationAddressOf in a general effort to trim unused inverse properties. TODO: warn if used
- [x] Clarified the definition of hasCommunicationAddress (which is now a subproperty of hasAddress) TODO: nothing
- [ ] added domain (Person U Organization) on hasCommunicationAddress. TODO: warn if fails

**Comment by uscholdm** [comment]
@Jamie-SA @rjyounes Can this be closed now?

**Comment by rjyounes** [comment]
Seems to be out-of-date.
