### ISSUE TITLE
trouble with gist:geoOccupies and gist:GeoPoint

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#56]
I'm having a little trouble determining how we describe something as being located at a lat/long point using gist8.0.0.  Here's why:

1.	gist:latitude has domain of gist:GeoPoint (same for gist:longitude)
2.	The only object property I could find that seems to tie something to its location is gist:geoOccupies 
3.	gist:geoOccupies has range  gist:GeoRegion or gist:GeoVolume (not gist:GeoPoint)

So if I wanted to say a certain landmark is at a lat/long, how would I say it in triples?

Sample construct that seems reasonable:

```
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix gist:    <http://ontologies.semanticarts.com/gist/> .
@prefix :        <http://example/> .

:_WashingtonMonument a gist:Landmark 
  ; gist:geoOccupies :_GeoPoint_38.88-77.03
  .

:_GeoPoint_38.88-77.03 a :GeoPoint
  ; gist:latitude 38.889467
  ; gist:longitude -77.035251
  .
```

But is uses gist:geoOccupies to point at a point. Is this correct way to model?   (yes, could have maybe used gist:permanentGeoOccupies)

Suggestion: Change range of gist:geoOccupies to gist:Place?  (note: geo:Place is the inferred range)

_(This may be related to #14 )_

**Comment by mkumba** [comment]
#56 in gist(.0.0
