### ISSUE TITLE
gist:OrderedMember bug in 10.0.0?

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#571]
gist:OrderedMembe in 10.0.0 appears to me to have a bug in its axiomatic definition.

The current definition is this:
`
((followsDirectly some owl:Thing) or (precedesDirectly some owl:Thing) or (sequence some xsd:integer))
 and (followsDirectly some OrderedMember)
 and (precedesDirectly some OrderedMember)
`

But this appears to say that every ordered member must have something before it, and after it, and clearly this would not hold true for the first item, and the last item, in the collection

**Comment by daliadahleh** [comment]
This was just fixed in https://github.com/semanticarts/gist/pull/569
