### ISSUE TITLE
Broaden gist:uniqueText definition

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#577]
Definition is: "This is used for the actual value of a key or ID where you don't want the possibility of having more than one."

There is no domain.

Proposal:
- add `gist:domainIncludes gist:ID`
- Change definition to something like: 'The unique string value of some text object."
- Add `skos:example`: "The string value of an identifier object; the three-segment number associated with a materialized version number."

**Comment by uscholdm** [comment]
Right idea, but the example could be simpler. How about: 
- `skos:example "The unique string for a vehicle identification number."^^xsd:string .`

**Comment by uscholdm** [comment]
This has already been implemented. 
```
gist:uniqueText
	a
		owl:DatatypeProperty ,
		owl:FunctionalProperty
		;
	rdfs:isDefinedBy <https://w3id.org/semanticarts/ontology/gistCore> ;
	rdfs:range xsd:string ;
	skos:definition "The unique string value of some content object; i.e., there is no possibility of having more than one value."^^xsd:string ;
	skos:example "The unique string for a vehicle identification number."^^xsd:string ;
	skos:prefLabel "unique text"^^xsd:string ;
	gist:domainIncludes
		gist:ID ,
		gist:Text
		;
	.
```

**Comment by uscholdm** [comment]
Completed
