### ISSUE TITLE
gist unit of measure instances have no unit symbols

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#579]
Submit one PR for #370, #526, and #579.

**Comment by uscholdm** [comment]
Do we want the full meal deal, as in: 
```
gist:_kilogram_per_cubic_meter
	a
		owl:Thing ,
		gist:DensityUnit
		;
	skos:prefLabel "Kilogram per cubic meter"^^xsd:string ;
	gist:convertToStandard "1.0"^^xsd:double ;
	gist:denominator gist:_cubic_meter ;
	gist:hasStandardUnit gist:_kilogram_per_cubic_meter ;
	gist:numerator gist:_kilogram ;
	gist:unitSymbol "kg/m^3"^^xsd:string ;
	gist:unitSymbolHTML "kg/m&sup3;"^^xsd:string ;
	gist:unitSymbolUnicode "kg/m?"^^xsd:string ;
	.
```
The difference is nicely showing sub/superscripts for exponents, or showing the small circle degrees symbol for temperature.  Come to think of it, it virtually all the gist units will be simple, no need for any special characters.

**Comment by rjyounes** [comment]
I vote no.

**Comment by rjyounes** [comment]
Would `gist:unitSymbolHtml` and `gist:unitSymbolUnicode` be good candidates for removal?

**Comment by uscholdm** [comment]
More a case of not adding them.  I don't think they exist in gist now, just in special add-on units ontologies for various clients.  

I think we should not add them at this time.  Maybe an editorial comment on `gist:UnitOfMeasure` to suggest doing this.
