### ISSUE TITLE
question: gist:hasDirectPart scope note

### ISSUE THREAD

**Issue by justin2004** [semanticarts/gist#591]
"For example, a spark plug is a direct part of an engine block; there cannot be any intermediate parts."
https://github.com/semanticarts/gist/blob/7513770f22780edfeef17789d826daeed3d7d7b7/gistCore.ttl#L3166

I think this example relies on the close proximity between a spark plug and an engine block.
There are no intervening parts. They are directly adjacent.
But there are many parts of an engine that directly touch (and are mounted onto) the engine block that aren't direct parts of the engine block (including spark plug).
e.g
An exhaust manifold is a component in the exhaust system.
An oil pump is a component in the lubrication system and also the cooling system.
And a spark plug is a component in the ignition system.

An engine block is an assemblage of machined pieces of metal. It might have direct parts but spark plug isn't one of them.

I think gist:hasDirectPart is tricky because we can often find a sub-system that slips in between directly adjacent (physically) components.

Can we find some better examples of direct parts?

**Comment by uscholdm** [comment]
SUGGESTION: close this issue as there is no proposal on the table and the importance is minor.
