### ISSUE TITLE
question: relationship between gist:hasPart and gist:isMadeUpOf

### ISSUE THREAD

**Issue by justin2004** [semanticarts/gist#592]
It seems like gist should assert that:
```
gist:isMadeUpOf rdfs:subPropertyOf gist:hasPart .
```

Being made up of something is a specialization of being a part of something.
Water is made up of hydrogen and hydrogen is part of water.

If we don't think gist should assert that then that might mean gist intends `gist:hasPart` to be a relationship between gist:Artifacts only -- since water and hydrogen are not gist:Artifacts.
But I don't think that is necessary because it is easy to find that out in a query:
```
select * where {
?s gist:hasPart ?o .
?o a gist:Artifact .
?s a gist:Artifact .
}
```

A bit of background here...
I am working on getting water quality data into Wikidata (my example entity is [here](https://www.wikidata.org/wiki/Q108226511)). I am using [wdt:hasPart](https://www.wikidata.org/wiki/Property:P527) to relate drinking water to things in it (such as copper, lead, etc.).
And eventually I'd like to put more effort into aligning Wikidata with Gist.

**Comment by justin2004** [comment]
Hi @rjyounes ,

>  in that the latter retains its independent identity whereas the former don't, becoming absorbed into the whole.

If the definition of "retention of independent identity" is something like: "the part can be extracted from the whole without destroying the part" then the relationship of hydrogen to water meets the same criteria as the engine block to a spark plug.

I can remove the spark plug from the engine block with a torsional force and the spark plug is still a spark plug.
I can remove the hydrogen from the water with electrolysis and the hydrogen is still hydrogen.

(Though that does make me think a useful test for direct parts might be whether or not you can remove them from the whole and the whole still exists.)

The torsional force is macroscopic chemistry and the electrolysis is microscopic chemistry.
But the macro/micro distinction there is an example of what Dennett calls "scale chauvinism."


If instead the definition of "retention of independent identity" isn't about the ability to extract the parts but more about the absorption into the whole... I still don't think I still much difference between an engine doings its thing with all of its parts and water doing its thing with all of its parts... other than the role of `gist:Artifact`. But maybe my [world hypothesis is mechanism](https://en.wikipedia.org/wiki/World_Hypotheses) and gist's is another.  


(I'm treating spark plug as a direct part of an engine block just for this discussion but I think it isn't.)

**Comment by uscholdm** [comment]
@rjyounes 
PROPOSAL: close this issue, it is subsumed by #152

**Comment by rjyounes** [comment]
Closing - subsumed by #152.
