### ISSUE TITLE
Broaden the range of containedText to include xsd:anyURI for representing web addresses.

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#594]
I want to create a class, WebAddress as follows:

```
ibbeo:WebAddress
    a owl:Class ;
    skos:prefLabel "Web Address"^^xsd:string ;
    skos:definition "A URL"^^xsd:string ;
    rdfs:subClassOf
      gist:Address ,
      [
        a owl:Restriction ;
        owl:onProperty gist:containedText ;
        owl:someValuesFrom xsd:anyURI ;
      ]
      ;
      .
```

But the property containedText has range `xsd:string`
```
gist:containedText
	a owl:DatatypeProperty ;
	rdfs:range xsd:string ;
	skos:definition "Links to the string corresponding to Text"^^xsd:string ;
	skos:prefLabel "contained text"^^xsd:string ;
	.
```

Althought `gist:containedText` was created specifically for use with `gist:Text`, it has no domain, so it should be usable with anything that corresponds to text, which is the case for a WebAddress.

SUGGESTION: make the range of `containedText` be the union of `xsd:string` and `xsd:anyURI`

**Comment by rjyounes** [comment]
Closing - will not fix. Web addresses require different modeling.
