### ISSUE TITLE
Define gist:controls to use with governments instead of gist:governs

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#598]
Spinoff from issue #215. This was included in the original proposal but we are breaking it off into a separate issue.

**Comment by turingtest37** [comment]
It feels to me like "governs" could subclass "controls". An entity can control a territory militarily without governing it. Governs -- to me -- implies a proper government, no matter how tiny. What do others think?

**Comment by rjyounes** [comment]
This makes sense to me. Then it seems we don't need to introduce `controls` as part of the geo/government model (issue #215). The word "controls" in ordinary language has a really broad spectrum of meaning and use, and I don't see that introducing that into the ontology provides any useful semantics.

**Comment by uscholdm** [comment]
> This makes sense to me. Then it seems we don't need to introduce `controls` as part of the geo/government model (issue #215). The word "controls" in ordinary language has a really broad spectrum of meaning and use, and I don't see that introducing that into the ontology provides any useful semantics.

I agree. I was uncomfortable about using 'controls' in a highly specific geo political context.

**Comment by uscholdm** [comment]
This is now moot, there is no longer a `controls` property. We use `isGovernedBy`
