### ISSUE TITLE
Deprecate isAspectOf, add hasAspect

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#603]
Normally the assertion and queries would go the other way: you don't want to know all the things that have a length aspect, you want to know what aspects a thing has. The former involves making assertions on a taxonomic term, which is odd. 

Also make range of `hasAspect` `gist:Aspect`.

**Comment by uscholdm** [comment]
> Also make range of `hasAspect` `gist:Aspect`.

Makes sense at first glance, but this sort of thing tends to backfire as often as not.  It might be we wans to say something hasAspect where the aspect is an aspect in everyday terms, but is strictly speaking not exactly what we mean by gist:Aspect.  That can be done with SHACL.

**Comment by rjyounes** [comment]
Your point is a good one. I retract the range proposal.

**Comment by uscholdm** [comment]
@rjyounes 
PROPOSAL:
- Deprecate `isAspectOf`, add `hasAspect`
- Don't have a domain or a range for  `hasAspect`

This is timely, as the refactored units proposal (#697) will likely want to use `hasAspect`.

**Comment by rjyounes** [comment]
@uscholdm I agreem with this proposal. Should this issue be rolled into the units and measures model, or can we address it independently?

**Comment by uscholdm** [comment]
> Should this issue be rolled into the units and measures model, or can we address it independently?

Probably does not matter much - if somone want to do it now, not a bad idea. One less thing to document when UoM changes.

**Comment by rjyounes** [comment]
@philblackwood Is this in accord with the new units and measures model?

**Comment by philblackwood** [comment]
will be included in new Units of Measure.
