### ISSUE TITLE
Modify guidance on category infixes in style guide

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#604]
There are cases where it may not be appropriate or optimal to use the most specific category.

**Comment by uscholdm** [comment]
Can you give some examples. Also, maybe quote the relevant part of the style guide? I don't have enough to know whether I agree or not to this proposal.

**Comment by uscholdm** [comment]
@rjyounes Do we want to keep this open? If so, do you have specific examples?

**Comment by rjyounes** [comment]
I've already added a comment to the style guide to this effect.
