### ISSUE TITLE
Adjust skos:definition of isRecognizedBy

### ISSUE THREAD

**Issue by turingtest37** [semanticarts/gist#607]
The current skos:definition of isRecognizedBy states "The entity that formally acknowledges the existence of, as the State recognizes the existence of a particular company"

This apparently describes the Object of the assertion, without mentioning the Subject, which is confusing.

I would suggest: "The Object entity formally acknowledges the existence of the Subject, as the State recognizes the existence of a particular company".

**Comment by rjyounes** [comment]
Your proposal is a definite improvement; I hate definitions of object properties that fail to indicate directionality, and in fact our style guide recommends against this, but we may want to tighten it up a bit, something along the lines of "formally acknowledges the existence and right to exist of..." or (following my favorite tool, the dictionary) "formally acknowledges the existence, validity, or legality of..."

I would put everything after the comma in a `skos:example`. "State" should not be capitalized. Arguably Subject and Object should not be either, though some will disagree.

**Comment by uscholdm** [comment]
There is also a property called `isRecognizedDirectlyBy` whose definition has a similar problem.  But I don't think we need this property anyway. If we did want it, then the non-direct version should be transitive.

```
gist:isRecognizedDirectlyBy
	a owl:ObjectProperty ;
	rdfs:subPropertyOf gist:isRecognizedBy ;
	skos:definition "The party doing the recognition"^^xsd:string ;
	skos:prefLabel "is recognized directly by"^^xsd:string ;
	.
```

**Comment by uscholdm** [comment]
@rjyounes PROPOSAL: 
- change the definition of `isRecognizedBy` to: 
`"Relates something to a party that formally acknowledges its existence, validity, or legality."`
- add skos example: 
`"The state recognizes the existence of a particular company."`
- get rid of the property, `isRecognizedDirectlyBy`

**Comment by rjyounes** [comment]
> But I don't think we need this property anyway.

Agreed. Recognition doesn't seem like a transitive property, nor is it defined as such; meaning there's no value in having two predicates.

> add skos example:
"The state recognizes the existence of a particular company."

Would it be better to have the example mirror the direction of the predicate? - I.e., "The existence of a particular company is recognized by the state." I generally prefer to do this to avoid confusion.

> get rid of the property, isRecognizedDirectlyBy
Agreed.

Again, could you submit a PR for this and we'll (hopefully) quickly review it at the meeting. Shouldn't be much controversy here.
