### ISSUE TITLE
Do we need a mechanism to provide a version of gist without extensive annotations?

### ISSUE THREAD

**Issue by pwin** [semanticarts/gist#609]
Extensive documentation within the ontology is a double-edged sword - it provides scope for additional clarification of intention within the ontology, including examples etc., but it also provides greater bulk for situations where the only purpose of the ontology is to provide material for computation over the OWL and where the annotations are not going to be seen.  In this latter the bulk of the file with annotations is unnecessary and could be done better with a thinner file.

**Comment by rjyounes** [comment]
I feel quite strongly that we should _not_ do this. If onto-tool provides the means to remove annotations, users can do so themselves. I see no obligation on our part to provide a "gist lite" with human semantics stripped out, and I can see how this could cause a good deal of confusion.

**Comment by DougalW** [comment]
Programmatic manipulation of an OWL ontology via e.g. OwlAPI allows you to strip out annotations you don't want/need anyway, so this issue is unnecessary.

**Comment by uscholdm** [comment]
@rjyounes, @pwin PROPOSAL: to close due to lack of demand. Anyone who needs this functionality can do it themselves.

**Comment by rjyounes** [comment]
Closing. For the record, I think this is an awful idea.
