### ISSUE TITLE
Clarify meaning of Planned Event

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#610]
Spin-off of #176: "To do: create annotations (e.g., `skos:scopeNote`s) to explain exact meaning of PlannedEvent and difference from predicted and hypothetical events."

**Comment by uscholdm** [comment]
@rjyounes  `PlannedEvent` is no longer a class. We now have `ScheduledEvent`.

For hypothetical events, see #831 #30

**Comment by rjyounes** [comment]
Closing per preceding comment.
