### ISSUE TITLE
gist:links should be symmetric

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#612]
since gist:links property is defined as 

> Relates a NetworkLink to a NetworkNode that it connects to another node. Used when the connections are undirected, or the direction is not known.

shouldn't it be declared as symmetric, i.e. an owl:SymmetricProperty?

**Comment by rjyounes** [comment]
No. The subject is a `NetworkLink`, the object is a `NetworkNode`. The model looks as follows:

![network](https://user-images.githubusercontent.com/1693668/148546401-db0ac102-073f-45fd-bd28-0fcf0dcf6870.png)

`links` is used when the link is undirected, or direction is unknown. `linksFrom` and `linksTo` are used to indirect direction of the link.
