### ISSUE TITLE
Add/modify terms to model a Tree

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#617]
While technically it is possible to model a tree as an `OrderedCollection`, intuitively it represents a different set of relationships. A Teams discussion is copied below:

=======

_Rebecca: Is a tree just a specialized version of an `OrderedCollection` in which elements may directly precede more than one element? In fact, technically that's not excluded by the definition of `OrderedCollection`, so perhaps it's not even a specialization._

_Jamie: I don't think the meaning of directlyPrecedes is the same as hierarchy in a tree, even if it could be used that way. Interestingly, I think we create hierarchies (trees) fairly frequently in Ontologies (hasParent, hasSupervisor, hasSubTask, hasDirectPart, subClassOf, etc) but the concept itself is not part of the Ontology. This just made me wonder what is different about a OrderedCollection that makes it appropriate for inclusion. A Tree, an OrderedCollection, an Array, a List, etc., are all data structures but we don't explicitly model most data structures in gist. I guess the main difference is that it isn't obvious how to create an OrderedCollection in RDF so therefore we need to provide a "pattern" as to how to do it. From a logical consistency point of view, it seems odd._

_Rebecca: The programming data structure analogy only goes so far: a collection is a set of relationships in an ontology, rather than a data structure, so I don't think that the mechanic that set of relationship it would be implemented in software are not relevant. In that sense aren't array, list, and ordered collection all the same? As you say, technically the `gist:precedesDirectly` relationship could work to create a tree: if A is the parent of B and C in a tree, then perhaps we could say it directly precedes them. (It's more obvious if you lay the tree on its side.) Note the gist definition of `precedesDirectly` is "a generic ordering relation..." The difference is essentially that the branching structure created when one node "precedes" or is the parent of more than one other node is typical in a tree, but atypical in what we think of as an ordered collection; but our definition of the latter does not preclude it. Having said all of that, intuitively it does seem that a `Tree` represents a different set of relationships than an `OrderedCollection`, as you say, so I could define a new predicate for that. However, the `Tree` requires the same proxy mechanism that an `OrderedCollection` does, so it's unfortunate that given the way we've named those terms they don't carry over well to a tree. It would be better if we'd used something like `Proxy` or `PositionalMember` instead of `OrderedMember`, and `isProxyFor` or `providesPositionFor` instead of `providesOrderFor`._

======

My proposal is:
- Define a class `Tree` as a subclass of `gist:Collection` to represent hierarchies of non-categorial items (`gist:Taxonomy` pertains only to controlled vocabularies rather than instance data). 
- Define new predicates to represent the relationship between a tree element and its children. (`hasNavigationalParent` and related predicates are also for controlled vocabularies).
  - Question: would these be subproperties of `gist:precedes` and `gist:precedesDirectly`?
- Rename the following terms so they can apply to `Tree`s as well as `OrderedCollection`s, and modify formal and textual definitions as needed:
  - `OrderedMember` => `PositionalMember` or `ProxyMember`
  - `providesOrderFor` => `providesPositionFor` or `isProxyFor`

**Comment by uscholdm** [comment]
1. I agree that we generally don't want to be in the business of defining data structures 
2. I don't see a tree as being a collection, though one might view it that way through a particular technical lens
3. A prior version of gist catered for partially ordered collections vs. fully ordered collections and Dave got rid of it - I don't think it was missed. 
4. This seems over-complicated to me. Are there any compelling use cases?
5.

**Comment by Jamie-SA** [comment]
I am thinking that the interesting distinction here is the need for a Proxy instance. Maybe it is the Proxy concept that is useful for gist. Though, when I think about what a Proxy is, it seems to be a reified relationship (so maybe there is a more generic name or a super class). Maybe also a super class of TemporialRelation.

**Comment by rjyounes** [comment]
What I'm trying to say is that we have the proxy concept already in gist - but it's called `OrderedMember` - and I would like to rename it if we do implement trees to generalize it, if we're not thinking of trees as ordered collections.

I don't see how `TemporalRelation` fits in. Maybe "proxy" isn't a good name, but what we're talking about is an object that serves to position something in an ordered collection (or tree). It is defined to relate an `OrderedCollection` to a `Thing`, and is not an ordinary reified relationship. 

I also don't see what you mean when you say that the _distinction_ is in the Proxy. We need a proxy for both. Something can be a member of two trees just as two ordered collections; thus the need for a proxy.

**Comment by uscholdm** [comment]
`TemporalRelation` is only indirectly relevant at most.  It is relevant to the extent that reification is relevant and a `TemporalRelation` is a specific kind of reification. But trees and collections generally have nothing to do with time.

**Comment by uscholdm** [comment]
@rjyounes, @Jamie-SA PROPOSAL: to close this because
- We don't want to be in the business of defining data structures, generally speaking
- No obvious general-purpose demand, if users need it they can define it themselves.
- It's a bit subtle and confusing (to me, anyway)

**Comment by rjyounes** [comment]
Agreed - closing.
