### ISSUE TITLE
Missing and redundant elements in generated JSON-LD file

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#618]
One of our partners noticed that:

1. The `xsd` namespace is used but never declared in a `@context`. 
2. The same `@context`s are defined for each node, but it is more concise to define them for the entire document.

These are the result of the `rdf-toolkit.jar` serialization. The solution would be to use a different Turtle-to-JSON-LD converter.

**Comment by uscholdm** [comment]
@rjyounes Do we want to do anything about this?

**Comment by rjyounes** [comment]
No. Closing.
