### ISSUE TITLE
Define policy regarding use of minCardinality and minQualifiedCardinality 0

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#620]
Spinoff of #582.

Discussion:

Policy moving forward needs to be defined. Possibilities are:
- Use a `scopeNote`; since `min 0` has no inferencing power a `scopeNote` is equivalent. Use SHACL for data validation if needed.
- Continue to use `min 0`.

@Jamie-SA: it's useful because we don't have SHACL for gist.

**Comment by uscholdm** [comment]
@rjyounes What is the status of this?

**Comment by rjyounes** [comment]
This has been done. We have agreed to use `someValuesFrom` rather than `min(Qualified)Cardinality`. Closing the issue.
