### ISSUE TITLE
Move gist instances to a separate file?

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#623]
Consider in conjunction with #305 and #556.

**Comment by rjyounes** [comment]
My current thinking is that we should not do this because they are referenced in the ontology. E..g., `CurrencyUnit`: 

```
gist:CurrencyUnit
	owl:equivalentClass [
		a owl:Class ;
		owl:intersectionOf (
			gist:SimpleUnitOfMeasure
			[
				a owl:Restriction ;
				owl:onProperty gist:hasBaseUnit ;
				owl:hasValue gist:_USDollar ;
			]
		) ;
	] ;
```

What implications does this have then for namespacing - issue #305? Would we mix namespaces in a single file? 

We could still implement #556 without either #305 or this.

**Comment by uscholdm** [comment]
It is common practice to use multiple namespaces in the same file, 
- gist:, 
- pleo:, pleox: 
- skos: etc.  

I don't see this as a problem.

**Comment by rjyounes** [comment]
That is different: you are referring to _using_ different namespaces in an ontology (file), whereas I am referring to _defining_ terms in different namespaces in an ontology (file). My comment was unclear.

**Comment by uscholdm** [comment]
OK - that is an important distinction.  Even so, I think it is ok to use gistx namespace to define things in gistCore. If we really did not like it, then we could have them in a separate file and import them.  NOrmally the taxonomy fiel imports the ontology file, so it would be a bit backwards.  There are pros and cons.

**Comment by rjyounes** [comment]
Dan - it's ok to put the uoms etc in a separate file and reference them from the ontology without doing an import.

Delete `gist:_greenwichTimeZone` since no longer used.
The magnitudes one_X are no longer used either - they were used to define precisions of `TimeInstant`s.
So the remaining instances are all uoms.

Dan - with pared down list, let's leave them in the ontology file.

Proposal - keep all units referenced in the ontology file (e.g., _second referenced by DurationUnit) and have a separate file for others (non-base units) - _day and others Michael has proposed adding (issue #460).

Rebecca - if we were to define Area using standard units (meter x meter) - which we don't currently but should - then we would also put the standard units in the gist file. 

DECISION:
- Keep units referenced in the ontology (these are base units) in the ontology file.
- Also keep the existing derived units in the ontology file as exemplars of how to define derived units.
- Put the big list from Michael into a separate file.

NO ACTION REQUIRED
