### ISSUE TITLE
Correct axioms related to baseConversionFactor and standardConversionFactor, and clarify definitions

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#624]
@uschold and I think the following changes should be made, based on discussion related to issue #582:

* Make `baseConversionFactor` a subproperty of `standardConversionFactor` instead of the other way around (we got this right in making `hasBaseUnit` a subproperty of `hasStandardUnit`, interestingly enough.
* The class `UnitOfMeasure` should have cardinality restrictions of 1 for both `standardConversionFactor` and `hasStandardUnit`. Such restrictions should then be removed from the subclasses.
* In addition, the definitions need to be cleaned up and clarified:

The current definition of `standardConversionFactor` is a scope note and provides no clarification of the difference between it and `baseConversionFactor`. The language in the latter's definition could also be cleaned up and split into a definition, example, and scope note.

`baseConversionFactor`: The conversion factor used to get to the base unit.  E.g., multiplying by 0.0254 gets you from inches to meters. Divide by this number to go the other way. Used in conjunction with conversionOffset to convert from one unit to another. Degrees K =  (Degrees F - conversionOffset) * convertToBase. Or K = (F-(-469.67)) * (5/9.  To go the other way: F = (K * 9/5) -469.67.  Try it on Google.

`standardConversionFactor`: Note this kind of conversion will only work with temperatures if they are in Kelvin or Rankine (with a true 0).  You multiply to get to the base, divide to go from the base. mph to mps is .44704.  The multiple from kph to mps is .277778 .  To convert 60 mph to kph is (60 * .44704 / .277778 or 96.56056 kph

**Comment by rjyounes** [comment]
@wslooney Thanks for articulating this. I've copied your comment here because this is where the discussion will continue.

We may decide to shelve this and wait for the larger overhaul of units and magnitudes, or to go ahead with these smaller changes in advance.

**Comment by wslooney** [comment]
```
gist:hasBaseUnit
	a owl:ObjectProperty ;
	rdfs:subPropertyOf gist:hasStandardUnit ;
	rdfs:domain gist:UnitOfMeasure ;
	rdfs:range gist:BaseUnit ;
	skos:definition "Relates a UnitOfMeasure to its BaseUnit.  This indicates what kind of Unit something is."^^xsd:string ;
	skos:example "Saying that a furlong hasBaseUnit  meter says it is a DistanceUnit."^^xsd:string ;
	skos:prefLabel "has base unit"^^xsd:string ;
	.
```

Should the domain for :hasBaseUnit be :SimpleUnitOfMeasure (and the definition updated)? Members of :UnitOfMeasure that aren't a member of :SimpleUnitOfMeasure never have a base unit, they have a standard unit.
