### ISSUE TITLE
Non-conforming label property disappeared

### ISSUE THREAD

**Issue by dylan-sa** [semanticarts/gist#628]
In issue #428 there is a suggestion to introduce the annotation property `gist:nonConformingLabel`. It is mentioned in the release notes for version 9.5 but it is not in the current version of gist (10.0). And there is no mention in release notes that it went away. Was it ever there?

**Comment by Jamie-SA** [comment]
Searching the downloads for `nonConform` found:
- found nothing in the 9.5.0 download
- in the 9.6.0 download found several matches in `ontologyShapes9.6.0.*`, `gistValidationAnnotations9.6.0.*`, and `rdfsAnnotations.ttl`.
- found nothing in the 9.7.0 download
-  found nothing in the 10.0.0 download

**Comment by uscholdm** [comment]
So the fix is to remove that mention from the release notes - unless we want to put it in there for real - Im not in favor of that.

**Comment by rjyounes** [comment]
The purpose of the annotation is to flag annotations that violate the SHACL rules run by onto_tool. It is defined in the file gistValidationAnnotations.ttl.

**Comment by uscholdm** [comment]
I see. Intersting.
