### ISSUE TITLE
A GeoPoliticalRegion is a GeoRegion, not a Collection

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#63]
Gist now says that a GeoPoliticalRegion is a gist:Collection of GeoRegions linked by gist:hasMember, but not itself a GeoRegion.  I think it more accurate to say that GeoPoliticalRegion is a GeoRegion that has various other GeoRegions as parts.

**Comment by rjyounes** [comment]
Will be addressed in larger discussion of georegions presented by Ted. (Add an issue and add a link.)

**Comment by uscholdm** [comment]
> Will be addressed in larger discussion of georegions presented by Ted. See #151.

 I do not recall anything in @tedhills proposal that required a `GeoPoliticalEntity` to be a `Collection`. This is fine in principle, but there may be delays. In the mean time, I am forced to create a new version of `GeoPoliticalEntity` for a client that is not a `Collection`, but a `GeoRegion`.  

Ted: can you comment?

**Comment by tedhills** [comment]
In fact, I do not define a :GeoPoliticalEntity to be a :Collection; rather, it is a composite entity with two direct parts: gist:GeoRegion and gist:GovernmentOrganization. Issue #151 has the three slide presentations I prepared uploaded to it. Part 3, slide 12 has this solution; the section from slide 9 through 17 fleshes it out. Please pay attention to the notes accompanying each slide.

In Part 2 I propose a class with a somewhat awkward name, gist:GeoRegionOrCollection, which is either a gist:GeoRegion or a collection of gist:GeoRegions. Slide 16 shows the solution; slides 7-15 make the argument. There's a lot here and talking through it might be better than just reading the slides.

@careydan has distilled all of this into a set of proposed classes that might be easier to absorb than my slides.
