### ISSUE TITLE
There is no way to know what the unique text of a MediaType means.

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#631]
MediaType all seem to have some unique text, e.g
```
media-app:n-triples
	a gist:MediaType ;
	skos:prefLabel "N-Triples"^^xsd:string ;
	gist:uniqueText "application/n-triples"^^xsd:string ;
	.

<https://www.iana.org/assignments/media-types/application/sparql-results+xml>
	a gist:MediaType ;
	skos:prefLabel "SPARQL 1.1 Query Results XML"^^xsd:string ;
	gist:uniqueText "application/sparql-results+xml"^^xsd:string ;
	.
```
 I wonder what that meant, had a look and found nothing. Some ways to address this include one of more of:
1. Create a new property (maybe a subproperty of `uniqueText`) that has a definition.
2. Add a scope note on the definition of the `MediaType` class saying that each has a unique text and what it means
3. Add a a restriction on MediaType that requires a `uniqueText` string, if they all need it.

**Comment by rjyounes** [comment]
Why not just add a `skos:definition`?

**Comment by Jamie-SA** [comment]
The uniqueText is to be the concatenation of the "Type name", a slash "/", and the "Subtype name" as provided on the page displayed when you resolve the URI of the MediaType.

**Comment by uscholdm** [comment]
PROPOSAL:
1. Add a a restriction on MediaType that requires a `uniqueText` string
2. Add a scope note to MediaType saying that `uniqueText` is the concatenation of the "Type name", a slash "/", and the "Subtype name" as provided on the page displayed when you resolve the URI of the MediaType.
3. Add `domainIncludes` `MediaType` to `uniqueText`

**Comment by rjyounes** [comment]
I like the proposal. 1 makes this a major change, so it will need to be deferred to 13.0.0.

**Comment by rjyounes** [comment]
@uscholdm I hope you don't mind, I've assigned this to you.
