### ISSUE TITLE
Should the top-level split in the new time model be actual/planned rather than start/end?

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#634]
See lengthy discussion on PR #630, which I will not repeat here. We need to consider this before releasing the new time model.

**Comment by dylan-sa** [comment]
@rjyounes This is a tough one. I think one way of deciding is to ask whether planned times, for instance, tend to have more in common with one another than start times. That is, are start times a more heterogeneous bunch than planned times? If the answer is yes, then actual/planned may be the better division to have at the top level. My gut intuition is that planned times and start times are equally miscellaneous in character, so it may be that we could go with either division at the top. (For this reason, I would also gravitate towards the model that you have suggested in #630, where `gist:startDateTime`, `gist:endDateTime`, `gist:plannedDateTime`, and `gist:actualDateTime` are all at the top level. But I can see the downsides to that approach as well.)

**Comment by rjyounes** [comment]
Thanks for your thoughts, @dylan-sa. I realized when looking at the current model again that all the `*DateTime` predicates are meant to be abstract, and not actually used. In that case it doesn't matter how you organize the hierarchy, you still end up with the same properties at the bottom. So I'm going to close this.
