### ISSUE TITLE
Fix range and typo in definition of geoOccupies

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#64]
The range of geoOccupies is the union of a single class (gist:Place). Should just be that class, directly. 
Interestingly, this is not the case for the file gistPlace9.0.0 in the internally released gist folder.  It has the range as the union of GeoRegion and GeoVolume.  This may or may not be intended, but in any event, the gist on git is different from what is in the internally released gist folder for 9.0.0

**Comment by rjyounes** [comment]
Fix together with #334.
