### ISSUE TITLE
Fix definition of `PhysicalSubstance`

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#644]
Current definition and examples:

```
skos:definition "Non corporeal material, i.e. 'stuff' which can be divided into parts where each part retains its essence."
skos:example "An amount of water, of penicillin, of sand, of gold. An actual piece of gold, not gold the concept."
```

@mkumba notes that 'non-corporeal' is incorrect, and should be changed to 'physical.'

`piece of gold ` is not correct as an example, it should be `some amount of gold`.

The distinction between `PhysicalSubstance` and `PhysicalIdentifiableItem` mirrors English mass and count nouns. One could also use the term `discrete` as in `DiscretePhysicalItem`, but I don't know what the opposite is.

However, it doesn't seem correct to say that count nouns like persons and a grain of sand lose their identity when divided. A person can have all his/her limbs amputated and still be a person. This needs clarification. There's a question of the granularity of the division - if a person is split into distinct atoms, then it is no longer a person.

**Comment by rjyounes** [comment]
I also propose defining a class such as `PhysicalObject` as a superclass of `PhysicalSubstance` and `PhysicalIdentifiableItem`.

**Comment by uscholdm** [comment]
> However, it doesn't seem correct to say that count nouns like persons and a grain of sand lose their identity when divided. A person can have all his/her limbs amputated and still be a person. This needs clarification. There's a question of the granularity of the division - if a person is split into distinct atoms, then it is no longer a person.

I think its relevant here that if you amputate or otherwise dismember a person, at most one of the 'pieces' could be said to have retained its identify.

**Comment by rjyounes** [comment]
I just realized that as I was rereading the definition. So you're right, my point is irrelevant.

**Comment by rjyounes** [comment]
Though I could be really nitpicky and mention earthworms.

**Comment by uscholdm** [comment]
Interesting edge case

**Comment by mkumba** [comment]
How about Eric the Half a Bee? 

https://m.youtube.com/watch?v=ftomw87g61Y

**Comment by dylan-sa** [comment]
> Current definition and examples:
> 
> ```
> skos:definition "Non corporeal material, i.e. 'stuff' which can be divided into parts where each part retains its essence."
> skos:example "An amount of water, of penicillin, of sand, of gold. An actual piece of gold, not gold the concept."
> ```

In addition to the division idea, there is an "additive" way of thinking about it too: If you've got two amounts of water, you can add them together and you've still got water. If you've got two oranges, their mereological sum is not an orange. 

The additive version may be preferable for this reason: It seems like we'd call a water molecule an amount of water, but it's not possible to divide it and still end up with water.

**Comment by rjyounes** [comment]
Interesting point. I wonder, though, if it suggests instead that a water molecule is _not_ a `PhysicalSubstance` but a `PhysicalIdentifiableItem`. I.e., when we talk about _one molecule_ of water (grain of sand, brick of gold, etc.) we're now in the realm of discrete objects.

**Comment by dylan-sa** [comment]
@rjyounes Good point--that must be what is going on in this case. So probably the division and addition tests are equally good markers of the distinction between `PhysicalSubstance` and `PhysicalIdentifiableItem`.

Related to this point: I wonder if our `skos:example` should say "A **non-discrete** amount of water..." That would help to clarify that we aren't talking about the molecules of water, bricks/pieces of gold, etc.

**Comment by uscholdm** [comment]
> If you've got two amounts of water, you can add them together and you've still got water. If you've got two oranges, their mereological sum is not an orange.

That's fine with things like sand and water that seamlessly merge. Two pieces of gold are still two pieces of gold, unless you melt them into one.

**Comment by uscholdm** [comment]
> Interesting point. I wonder, though, if it suggests instead that a water molecule is _not_ a `PhysicalSubstance` but a `PhysicalIdentifiableItem`. I.e., when we talk about _one molecule_ of water (grain of sand, brick of gold, etc.) we're now in the realm of discrete objects.

That's correct for sand, and in maybe in principle for water, but I don't know if it is technologically possible to identify a single molecule of water.

**Comment by uscholdm** [comment]
> Related to this point: I wonder if our `skos:example` should say "A **non-discrete** amount of water..." That would help to clarify that we aren't talking about molecules of water, bricks/pieces of gold, etc.

Nobody will know what we mean by "A **non-discrete** amount of water...". Just say water, and if you want to bring up that that the idea that if you divide enough you get to discrete somethigns, use sand not water as an example. Easy to undrestand.

**Comment by rjyounes** [comment]
> That's fine with things like sand and water that seamlessly merge. Two pieces of gold are still two pieces of gold, unless you melt them into one.

But we've said that _pieces_ of gold are `PhysicalIdentifiableItem`s, not `PhysicalSubstance`s, so that is not a counterexample to Dylan's point. Grains of sand, pieces of gold, and molecules of water are `PhysicalIdentifiableItem`s, while sand, gold, and water are `PhysicalSubstance`s.  As I commented above, only the latter pass the additivity (Dylan) or retention of identity under division (original definition) tests.

**Comment by uscholdm** [comment]
Is there a revised proposal on the table to evaluate?

**Comment by rjyounes** [comment]
I'll make the following proposal so we at least have something concrete to work with:


Current:


> gist:PhysicalSubstance 
    skos:definition "Non-corporeal material, i.e. 'stuff' which can be divided into parts where each part retains its essence." ;
    skos:example "An amount of water, of penicillin, of sand, of gold: an actual piece of gold, not the concept of gold." ;
    skos:scopeNote "An instance of this class must be a physical thing, and not just a categorical description." ;
.

> gist:PhysicalIdentifiableItem
	skos:definition "You could, at least in principle, put an RFID tag on members of this class. Physical things are made of something.  E.g., statues are made of bronze."^^xsd:string ;
	skos:example
		"A computer, a book."^^xsd:string ,
		"Negative example: A discontinuous thing like a manufacturing line cannot reasonably have an RFID attached to it, even though its parts are not the same kind of thing as the whole."^^xsd:string
		;
	skos:scopeNote "In practice, this always means that the parts are not the same kind of thing as the whole."^^xsd:string ;
.


I don't like "essence" in  "'stuff' which can be divided into parts where each part retains its essence," and there are many cases where it's unclear what this means or where it doesn't provide a good distinguishing criterion. If we divide an amount of water (say, 1 cup) into two parts (say, 2 half cups) we have two amounts of water - but not the same amounts. By "retaining its essence" I suppose we mean both are still amounts of water. 

On this view, it seems that a piece of gold would be a `PhysicalSubstance` after all, contrary to my previous comment: if we divide one piece of gold into two, we still have two pieces of gold. Yet a piece of gold seems more like a grain of sand than an amount of water.

What about a statue? We might say if we cut a statue in half we (perhaps) still have two statues - but a status is definitely a `PhysicalIdentifiableItem`. That is where "essence" comes into play, I guess, but we need to find a clearer way to state it.

If we just use the English count/mass distinction, we have a simple and clear definition of the difference, but it depends on where we want a piece of gold to fall. "Piece" is a count noun, so if we want a piece of gold it to be a `PhysicalSubstance` this doesn't work.

So here are my attempts. The definitions in particular are weak and need suggestions from others. These are more or less here to give us a concrete starting point.


Proposed:


> gist:PhysicalSubstance
    skos:definition "An undifferentiated, unbounded amount of physical material." ; 
    skos:example "An amount of water, flour, sand, gold." ;
   skos:scopeNote "This generally corresponds to mass nouns in English, as opposed to count nouns, which are PhysicalIdentifiableItems, such as a water molecule, a grain of sand, a brick of gold. PhysicalIdentifiableItems are made up of PhysicalSubstances; e.g., a cake is made up of butter, flour, and sugar, a statue is made of bronze. If you divide a PhysicalSubstance such as an amount of water into parts, you have two amounts of water; if you divide a PhysicalIdentifiableItem such as a computer into two parts, you have at most one computer, perhaps none.  A PhysicalSubstance may have externally-defined boundaries - e.g., an amount of water in a cup is bounded by the cup, a lake is bounded by the surrounding land - but it does not provide its own boundaries, as a PhysicalIdentifiableItem does." ,
"An instance of this class must be a physical thing, and not just a categorical description or concept." , "A" ;
.

> gist:PhysicalIdentifiableItem
	skos:definition "A countable physical object with identifiable boundaries." ; 
	skos:example "A computer, a book, a grain of sand." ;
	skos:scopeNote "This concept generally corresponds to count nouns in English, as opposed to mass nouns, which are PhysicalSubstances, such as an amount of water, sand, or gold. PhysicalIdentifiableItems are made up of PhysicalSubstances; e.g., a cake is made up of butter, flour, and sugar; a statue is made of bronze. If you divide a PhysicalSubstance such as an amount of water into parts, you have two amounts of water; if you divide a PhysicalIdentifiableItem such as a computer into two parts, you have at most one computer, perhaps none. A PhysicalSubstance may have externally-defined boundaries - e.g., an amount of water in a cup is bounded by the cup, a lake is bounded by the surrounding land - but it does not provide its own boundaries, as a PhysicalIdentifiableItem does." " ,  "You could, at least in principle, put an RFID tag on members of this class." ;
.

Note that by the boundary criterion a piece of gold is a `PhysicalIdentifiableItem`.

Further proposals:

* Rename `PhysicalIdentifiableItem`. Suggestions: `DiscretePhysicalObject`, `BoundedPhysicalObject`, `CountablePhysicalObject`.
* Create a superclass of both, such as `PhysicalThing` (I know this won't fly, but adding for the record).

Final note: I have the uneasy feeling that BFO might actually be able to _help_ us here.

**Comment by uscholdm** [comment]
A solid proposal - thank you.

**PhysicalSubstance** 

- I agree to not use 'essence'
- There is a spurious "A" in the scopeNote
- 'unbounded' is confusing. Every amount of stuff that you could identify with an IRI will have some bounds. Suggest skip mentioning this, or clarifying what you mean by it, if you think it's important. I think it's a bit confusing, not clarifying, even if it's true (or maybe I just don't get it) 
- I think using gold as an example is a bad idea, as it is so easily confused with a discrete piece of gold.
- Instead of 'brick of gold' I suggest 'gold bar', more common (I think).
- I propose a definition more like: `An undifferentiated amount of physical material which when subdivided, results in each part being the same kind of thing as the whole was`
- I propose add scopeNote: `Like a PhysicalIdentifiableItem, a PhysicalSubstance has mass and takes up space.


 **PhysicalIdentifiableItem** 

- 'Countable' is linguistic geek-speak. I propose a definition more like: `A discrete physical object which if subdivided, will generally result in parts that are very different in kind to the whole object.`
- I propose add scopeNote: `Like a PhysicalSubstance, a PhysicalIdentifiableItem has mass and takes up space.
- I suggest don't mention that a part could in principle be the same type of thing as the whole, it's not useful and will cause confusion.  You can tell the difference between a computer with and with out  part missing.  You can tell the difference between a person with a missing arm and a person with both arms. By contrast, there is nothing whatever different about two amounts of water after being split from the original amount.
- I Think the RFID tag comment is confusing, and not adding anything.

Here is a variation of your proposal:

```
gist:PhysicalSubstance
    skos:definition "An undifferentiated amount of physical material which when subdivided, results in each part being indistinguishable in nature from the whole and from each other part." ; 
    skos:example "An amount of water, flour, sand." ;
   skos:scopeNote "This generally corresponds to mass nouns in English. By contrast,  PhysicalIdentifiableItemsas such as a computer, a book, or a car, are count nouns. PhysicalIdentifiableItems are made up of PhysicalSubstances; e.g., a cake is made up of butter, flour, and sugar;  a ring is made of gold. If you divide a PhysicalSubstance such as an amount of water into parts, you have different amounts of identical water; if you divide a PhysicalIdentifiableItem such as a computer into parts, each part will be distinguishable from the original whole.  A PhysicalSubstance may have externally-defined boundaries - e.g., an amount of water in a cup is bounded by the cup, a lake is bounded by the surrounding land - but it does not provide its own boundaries, as a PhysicalIdentifiableItem does." ,
"An instance of this class has weight and takes up space. We mean the gold in a ring, not the concept of gold that shows up in the periodic table." ;
.

gist:PhysicalIdentifiableItem
	skos:definition "A discrete physical object which if subdivided, will result in parts that are distinguishable in nature from the whole and in general also distinguishable from the other parts" ; 
	skos:example "A computer, a book, a car." ;
	skos:scopeNote "This concept generally corresponds to count nouns in English, as opposed to mass nouns, which are PhysicalSubstances, such as an amount of water, sand, or gold. PhysicalIdentifiableItems are made up of PhysicalSubstances; e.g., a cake is made up of butter, flour, and sugar; a statue is made of bronze. If you divide a PhysicalSubstance such as an amount of water into parts, you have two amounts of water; if you divide a PhysicalIdentifiableItem such as a computer into two parts, you have at most one computer, perhaps none. A PhysicalSubstance may have externally-defined boundaries - e.g., an amount of water in a cup is bounded by the cup, a lake is bounded by the surrounding land - but it does not provide its own boundaries, as a PhysicalIdentifiableItem does." " ,  "You could, at least in principle, put an RFID tag on members of this class." ;
.

```

**Comment by rjyounes** [comment]
I like your changes, but am still puzzled by the gold/bronze case. Ruling out the concept of gold, gold comes in chunks, and a  chunk of gold has its own boundaries and according to our definitions above would be a `PhysicalIdentifiableItem`. This is not the result we want: gold is a mass noun just like water. Now I think maybe the bounded criterion is a red herring - it applies to gases, liquids, and particles, but not solids. That gives us this:

```
gist:PhysicalSubstance
    skos:definition "An undifferentiated amount of physical material which, when subdivided, results in each part being indistinguishable in nature from the whole and from each other part." ; 
    skos:example "An amount of water, flour, sand." ;
   skos:scopeNote "This generally corresponds to mass nouns in English. By contrast,  PhysicalIdentifiableItem such as a computer, a book, or a car, are count nouns. PhysicalIdentifiableItems are made up of PhysicalSubstances; e.g., a cake is made up of butter, flour, and sugar;  a ring is made of gold. If you divide a PhysicalSubstance such as an amount of water into parts, you have different amounts of identical water; if you divide a PhysicalIdentifiableItem such as a computer into parts, each part will be distinguishable from the original whole." ;
"An instance of this class has weight and takes up space. We mean the gold in a ring, not the concept of gold that shows up in the periodic table." ;
.

gist:PhysicalIdentifiableItem
	skos:definition "A discrete physical object which if subdivided, will result in parts that are distinguishable in nature from the whole and in general also distinguishable from the other parts" ; 
	skos:example "A computer, a book, a car." ;
	skos:scopeNote "This concept generally corresponds to count nouns in English, as opposed to mass nouns, which are PhysicalSubstances, such as an amount of water, flour, or sand. PhysicalIdentifiableItems are made up of PhysicalSubstances; e.g., a cake is made up of butter, flour, and sugar; a statue is made of bronze. If you divide a PhysicalSubstance such as an amount of water into parts, you have two amounts of water; if you divide a PhysicalIdentifiableItem such as a computer into two parts, you have at most one computer, perhaps none."  ,  "You could, at least in principle, put an RFID tag on members of this class." ;
.
```

**Comment by rjyounes** [comment]
@dylan-sa and I have been talking about this issue further. There's a difference between stone as a count noun (where you can have a pile of stones, I can throw a stone) and stone as a mass noun, as in the gold example, with no plural. In either case, if you subdivide them, you end up with the same kind of thing. How can we define the difference between them?

BFO has the interesting distinction between things that, if you move them, the whole thing moves together as a unit (I can't remember their term, "causal" something, but this is our PhysicalIdentifiableItem), vs. substances, which fail that test: you can take a handful of water out of a lake and not take the whole lake with you. But this still has the same problem, that gold or stone, which only come in chunks, do not get categorized as substances.

**Comment by uscholdm** [comment]
Do you really want to keep the reference to RFID?
The comment about a computer should match in both definitions.  I suggest focus on part similarity to whole and don't say 'at most one computer' which is confusing and maybe irrelevant.
We also might not want to have outright duplication of text in both definitions, though in this case it could be justified. An alternative, which is a bit more work, is to suppress detail of the 'other' concept in the definition of 'the' concept.

**Comment by uscholdm** [comment]
> @dylan-sa and I have been talking about this issue further. There's a difference between stone as a count noun (where you can have a pile of stones, I can throw a stone) and stone as a mass noun, as in the gold example, with no plural. In either case, if you subdivide them, you end up with the same kind of thing. How can we define the difference between them?

We probably don't have to go that deep - just say what we are sure of (parts are (or are not) indistinguishable in nature from the whole) with simple, clear examples and don't call attention to more subtle things we don't even understand yet. It won't likely matter.

**Comment by DougalW** [comment]
> > Interesting point. I wonder, though, if it suggests instead that a water molecule is _not_ a `PhysicalSubstance` but a `PhysicalIdentifiableItem`. I.e., when we talk about _one molecule_ of water (grain of sand, brick of gold, etc.) we're now in the realm of discrete objects.
> 
> That's correct for sand, and in maybe in principle for water, but I don't know if it is technologically possible to identify a single molecule of water.

Interestingly, this is actually possible. Various forms of scanning / force electron microscopes and x-ray microscopes can now image individual atoms and molecules.

**Comment by Jamie-SA** [comment]
I think this conversation has tried to identify a fundamental or philosophical difference between 2 things that are actually the same thing. This is probably not going to sit well with some ontologists, but the difference (in many cases, but not all) is in how we intend to use it, and therefore, how we want to track it.

If I buy gold bars as an investment I want to track the bar as a thing (a PhysicallyIdentifiableObject), it probably even has a serial number to identify it. If I buy gold (bars or otherwise) to melt and deposit onto electronic components (a PhysicalSubstance), I want to track it as an amount of a material that I will subdivide (or possibly add to), whether it came with a serial number or not. Gold is not inherently one or the other, it is how we use it that makes the distinction. And how we use it changes how we want to track it.

As gist is a business ontology, I think the important thing is to be able to easily handle the needs of a business for either case above and make it easy to identify where it fits in the model.

And if a gold bar that was bought as an investment ends up getting sent to be melted, there is a transaction (or business event) recording its change from PhysicallyIdentifiableObject to PhysicalSubstance.

RANDOM COMMENT: my attempt to create a counter example of an unbounded physically identifiable object -- a nebula might be identified by a URI but is arguably unbounded.

**Comment by DougalW** [comment]
Good comment Jamie. Re nebula - all members are bound gravitationally to the nebula. Nebulae may also themselves be gravitationally bound as an entity to other nebula or galaxies. E.g. our galaxy has several nebula in tow but they are themselves unique and distinct. To follow your example somewhat, new elements of a nebula may accrete to the nebula via gravitational capture (e.g. interstellar hydrogen the nebula passes through), or be pulled off by passage through a stronger gravitational field.

**Comment by rjyounes** [comment]
@Jamie-SA You've solved the problem of gold, which I didn't because I forgot that gold can be melted and doesn't have to come in chunks. Therefore, as you say, a brick or lump of gold is a `PhysicalIdentifiableObject`, whereas the molten gold is a `PhysicalSubstance`.

I am good with this proposal (a combination of mine and Michael's above):

```
``
gist:PhysicalSubstance
    skos:definition "An undifferentiated amount of physical material which, when subdivided, results in each part being indistinguishable in nature from the whole and from each other part." ; 
    skos:example "An amount of water, flour, sand, molten gold." ;
   skos:scopeNote "This generally corresponds to mass nouns in English. By contrast,  PhysicalIdentifiableItem such as a computer, book, or car, are count nouns. PhysicalIdentifiableItems are made up of PhysicalSubstances; e.g., a cake is made up of butter, flour, and sugar;  a ring is made of gold. If you divide a PhysicalSubstance such as an amount of water into parts, you have different amounts of identical water; if you divide a PhysicalIdentifiableItem such as a computer into parts, each part will be distinguishable from the original whole." ;
"An instance of this class has weight and takes up space. We mean the physical gold in a ring, not the concept of gold that shows up in the periodic table." ;
.

gist:PhysicalIdentifiableItem
	skos:definition "A discrete physical object which if subdivided, will result in parts that are distinguishable in nature from the whole and in general also distinguishable from the other parts." ; 
	skos:example "A computer, book, car." ;
	skos:scopeNote "This concept generally corresponds to count nouns in English, as opposed to mass nouns, which are PhysicalSubstances, such as an amount of water, flour, or sand. PhysicalIdentifiableItems are made up of PhysicalSubstances; e.g., a cake is made up of butter, flour, and sugar; a statue is made of bronze. If you divide a PhysicalSubstance such as an amount of water into parts, you have two amounts of water; if you divide a PhysicalIdentifiableItem such as a computer into two parts, neither one resembles the original object."  ,  "You could, at least in principle, put an RFID tag on members of this class." ;
.
```

The only issue I have is with the wording of "if you divide a PhysicalIdentifiableItem such as a computer into two parts, neither one resembles the original object." If possible, I'd like to state more precisely what "neither one resembles the original object" means.

**Comment by Jamie-SA** [comment]
Solid gold [[unrelated](https://en.wikipedia.org/wiki/Solid_Gold_(TV_series))] is also a PhysicalSubstance when it's intended use is as a substance (and not as a thing in itself). It always comes in the door as a solid (also referred to as "chunks" above). It only gets melted in processing steps. It is the intended use, not the state of existence of the material, that makes it one or the other.

**Comment by uscholdm** [comment]
Jamie raises legitimate concerns, but we don't need to solve a philosophical conundrum, just keep things simple.

The main distinction that is fairly clean and clear (minus the ever present edge cases) is as follows:
- **PII**: parts are distinguishable in nature from the whole -- e.g wheels, engine, battery for a car
- **Substance**: parts are indistinguishable in nature from the whole -- e.g. crude oil from a tanker

Let's have some clear examples w/o calling attention to edge cases that we don't even understand yet.

**Comment by uscholdm** [comment]
> "neither one resembles the original object"
I find these words confusing, the laptop minus the screen looks a lot like (i.e resembles) the laptop.

**Comment by rjyounes** [comment]
Final proposal:

```
gist:PhysicalSubstance
    skos:definition "An undifferentiated amount of physical material which, when subdivided, results in each part being indistinguishable in nature from the whole and from each other part." ; 
    skos:example "An amount of water, flour, sand, molten gold." ;
   skos:scopeNote "This generally corresponds to mass nouns in English. By contrast,  PhysicalIdentifiableItem such as a computer, book, or car, are count nouns. PhysicalIdentifiableItems are made up of PhysicalSubstances; e.g., a cake is made up of butter, flour, and sugar;  a ring is made of gold. If you divide a PhysicalSubstance such as an amount of water into parts, you have different amounts of identical water; if you divide a PhysicalIdentifiableItem such as a computer into parts, each part will be distinguishable from the original whole." ;
"An instance of this class has weight and takes up space. We mean the physical gold in a ring, not the concept of gold that shows up in the periodic table." ;
.

gist:PhysicalIdentifiableItem
	skos:definition "A discrete physical object which if subdivided, will result in parts that are distinguishable in nature from the whole and in general also distinguishable from the other parts." ; 
	skos:example "A computer, book, car." ;
	skos:scopeNote "This concept generally corresponds to count nouns in English, as opposed to mass nouns, which are PhysicalSubstances, such as an amount of water, flour, or sand. PhysicalIdentifiableItems are made up of PhysicalSubstances; e.g., a cake is made up of butter, flour, and sugar; a statue is made of bronze. If you divide a PhysicalSubstance such as an amount of water into parts, you have two amounts of water; if you divide a PhysicalIdentifiableItem such as a computer into parts, each part is different from the whole."  ,  "You could, at least in principle, put an RFID tag on members of this class." ;
.
```

**Comment by uscholdm** [comment]
For grammar's sake, add 'instances of' after 'By contrast'.

Also, I suggest removing or changing the RFID comment, it's confusing because not every PII could possibly have an RFID. It might be true that anything that you CAN attach an RFID to is a PII -- but I'm not even 100% sure of that.

Here is the latest crack at a final proposal with just those two changes:

```
gist:PhysicalSubstance
    skos:definition "An undifferentiated amount of physical material which, when subdivided, results in each part being indistinguishable in nature from the whole and from every other part." ; 
    skos:example "An amount of water, flour, sand, molten gold." ;
   skos:scopeNote "This generally corresponds to mass nouns in English. By contrast, instances of PhysicalIdentifiableItem such as a computer, book, or car, are count nouns. PhysicalIdentifiableItems are made up of PhysicalSubstances; e.g., a cake is made up of butter, flour, and sugar;  a ring is made of gold. If you divide a PhysicalSubstance such as an amount of water into parts, you have different amounts of identical water; if you divide a PhysicalIdentifiableItem such as a computer into parts, each part will be distinguishable from the original whole." ;
"An instance of this class has weight and takes up space. We mean the physical gold in a ring, not the concept of gold that shows up in the periodic table." ;
.

gist:PhysicalIdentifiableItem
    skos:definition "A discrete physical object which if subdivided, will result in parts that are distinguishable in nature from the whole and in general also distinguishable from the other parts." ; 
    skos:example "A computer, book, car." ;
    skos:scopeNote "This concept generally corresponds to count nouns in English, as opposed to mass nouns, which are PhysicalSubstances, such as an amount of water, flour, or sand. PhysicalIdentifiableItems are made up of PhysicalSubstances; e.g., a cake is made up of butter, flour, and sugar; a statue is made of bronze. If you divide a PhysicalSubstance such as an amount of water into parts, you have two amounts of water; if you divide a PhysicalIdentifiableItem such as a computer into parts, each part is different from the whole."  ,  "Generally, if you can put an RFID on something, then it is a member of this class." ;
.
```
