### ISSUE TITLE
Geo Region = has-magnitude some Area

### ISSUE THREAD

**Issue by cmungall** [semanticarts/gist#656]
> 'Geo Region' EquivalentTo ('has magnitude' some Area)

I think this is only true if one specializes Area or generalized Geo Region beyond what is intuitive. A region of a surface of a biological cell may have an area but it's not a geo region

A generally consider genusless logical definitions to be an antipattern, following genus-differentia form leads to fewer errors in my opinion

see S3 in https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/

**Comment by rjyounes** [comment]
I agree that this definition overstates the case.

In terms of clear textual definitions, gist is a bit spotty. We are overhauling them bit by bit, and plan a full overhaul at some point in the (hopefully) near future. We've also gotten more disciplined about differentiating definitions from other annotations such as scope notes and examples.

Do you have a proposal for the axiomatic definition?

**Comment by uscholdm** [comment]
@rjyounes, @cmungall, @mkumba
There is a general preference for having full definitions using equivalentClass rather than the weaker, subClassOf. This sometimes results in overstating the case.  I think that for GeoRegion,  it would be more accurate to use subClassOf instead of equivalentClass. In principle, it could avoid incorrect inferences. In practice, it may not matter. If it turned out to matter, we could weaken the definition at that time.

Here is a proposal. Replace:
```
	owl:equivalentClass [
		a owl:Class ;
		owl:intersectionOf (
			gist:Place
			[
				a owl:Restriction ;
				owl:onProperty gist:hasMagnitude ;
				owl:someValuesFrom gist:Area ;
			]
		) ;
	] ;
```

with 
```
	rdfs:subClassOf 
			gist:Place ,
			[
				a owl:Restriction ;
				owl:onProperty gist:hasMagnitude ;
				owl:someValuesFrom gist:Area ;
			]
			;

**Comment by rjyounes** [comment]
@philblackwood Impacted by new units and measures model - is this still relevant?

**Comment by uscholdm** [comment]
This is another decision point that not everyone agreed with. One proposal is to remove all subclasses of gist:Magnitude which means it is impossible to have a restriction of the sort:

```
	rdfs:subClassOf 
			gist:Place ,
			[
				a owl:Restriction ;
				owl:onProperty gist:hasMagnitude ;
				owl:someValuesFrom gist:Area ;
			]
			;
```

One proposal is to just lose the semantics. Another is to have a chained restriction that means Magnitude that has the unit of standard unit for the unit group for area, but come to think of it, there is no one unit group for area nor is there a standard unit anymore.  So I cannot think of a way to put that semantics back.  IMHO, having unit group is a good idea, throwing out standard units, not so much.  This reflects my current understanding of the proposal we are moving forward with.

**Comment by rjyounes** [comment]
@philblackwood Please integrate this into your unit and magnitude PRs in whatever way that makes sense, and this issue can be closed. Thanks.

**Comment by philblackwood** [comment]
Resolved as suggest by Michael Uschold, changing from owl:equivalentClass to rdfs:subClassOf 
Subsumed by pull request #1064
