### ISSUE TITLE
Deprecate gist:Group

### ISSUE THREAD

**Issue by wslooney** [semanticarts/gist#663]
from @uscholdm (https://github.com/semanticarts/gist/issues/570#issuecomment-1104428832) where we were looking at `gist:Collection` and subclasses:

"The use of the word 'grouping' in the definition conflicts with gist:Group. I propose to get rid of gist:Group. I have never used it. If we did want it, it should have a more specific name, such as GroupOfPersons. It would be defined as a subclass of gist:Collection and have an allValuesFRom restirciton with gist:Person as the filter class. But I cannot see any reason to keep it."

Should Group be deprecated at next minor release?

**Comment by turingtest37** [comment]
I like Group and I'm sure I will use it someday. But your suggestion to make it a subclass of Collection are worth debating. It's presently Equivalent to Collection and hasMember some Person.

Do we want to limit Group membership to ONLY Persons, or merely require one or more to infer the class?

**Comment by rjyounes** [comment]
Completed.
