### ISSUE TITLE
gist:Landmark as a subclass of gist:Place

### ISSUE THREAD

**Issue by dylan-sa** [semanticarts/gist#664]
Currently `gist:Landmark` is a subclass of `gist:Place`. The sibling classes under `gist:Place` are geospatial regions like `gist:GeoPoint`, `gist:GeoRegion`, and `gist:GeoVolume`. It seems right that an instance of `gist:Landmark` must occupy some `gist:GeoRegion` or `gist:GeoVolume`, but it doesn't seem like a landmark or a building is a place in the same way a geospatial region is a place. 

My proposal would be to remove this subclass axiom from the definition of `gist:Landmark` and leave its equivalent class axiom.

Current definition:
```
gist:Landmark
	a owl:Class ;
	rdfs:subClassOf gist:Place ;
	owl:equivalentClass [
		a owl:Class ;
		owl:intersectionOf (
			gist:PhysicalIdentifiableItem
			[
				a owl:Restriction ;
				owl:onProperty gist:occupiesGeographicallyPermanently ;
				owl:someValuesFrom [
					a owl:Class ;
					owl:unionOf (
						gist:GeoRegion
						gist:GeoVolume
					) ;
				] ;
			]
		) ;
	] ;
	skos:definition "Something permanently attached to the Earth."^^xsd:string ;
	skos:prefLabel "Landmark"^^xsd:string ;
	.
```

Proposed definition:

```
gist:Landmark
	a owl:Class ;
	owl:equivalentClass [
		a owl:Class ;
		owl:intersectionOf (
			gist:PhysicalIdentifiableItem
			[
				a owl:Restriction ;
				owl:onProperty gist:occupiesGeographicallyPermanently ;
				owl:someValuesFrom [
					a owl:Class ;
					owl:unionOf (
						gist:GeoRegion
						gist:GeoVolume
					) ;
				] ;
			]
		) ;
	] ;
	skos:definition "Something permanently attached to the Earth."^^xsd:string ;
	skos:prefLabel "Landmark"^^xsd:string ;
	.
```

**Comment by uscholdm** [comment]
> it doesn't seem like a landmark or a building is a place in the same way a geospatial region is a place.

I agree.  I also agree that the axiom about a landmark occupying geographically a region or volume is ontologically correct.  Im open to whether we do or do not add a `occupiesGeographicallyPermanently` property just for this class definition. 

Also, my understanding of `gist:Place` is that it is meant to encompass a variety of ways of being a place, so I am not inclined to remove the subclass relationship.

**Comment by dylan-sa** [comment]
> Also, my understanding of gist:Place is that it is meant to encompass a variety of ways of being a place, so I am not inclined to remove the subclass relationship.

Fair point!

**Comment by rjyounes** [comment]
Closing.
