### ISSUE TITLE
Add note to documentation about Protege sorting issue

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#665]
See #646. Both Contributing.md and the style guide should note that Protege editors need to:
- Do a serialization and commit before editing.
- Remove stub definitions added by Protege (skos annotation properties, etc.)

**Comment by rjyounes** [comment]
Closing: moved to issue #567.

**Comment by uscholdm** [comment]
@rjyounes Is this still open for a reason? The last comment says its being closed.
