### ISSUE TITLE
Replace skos:note with skos:scopeNote?

### ISSUE THREAD

**Issue by Jamie-SA** [semanticarts/gist#666]
There is only one use of skos:note in gist v11. Was that a mistake that should have been a skos:scopeNote?

```
gist:CountryGovernment
    skos:note "While a country government may enter into treaties with other country governments, that does not mean it is 'governed by' the others."^^xsd:string ;
```

**Comment by uscholdm** [comment]
It should be scopeNote - skos:note is a superproperty for varoius annotation properaties including, scopeNote

**Comment by rjyounes** [comment]
Perhaps arguable. A `scopeNote` is "A note that helps to clarify the meaning and/or the use of a concept." I'm not sure this does. The style guide does allow the use of `skos:note`, although discourages it in favor of a more specific annotation.

**Comment by rjyounes** [comment]
OK.
