### ISSUE TITLE
Disjointness axioms are in some cases arbitrary; use AllDisjointClasses instead?

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#671]
For example:

```
gist:PhysicalIdentifiableItem 
	owl:disjointWith
		gist:SchemaMetaData ,
		gist:UnitOfMeasure
		;
.

gist:PhysicalSubstance
	owl:disjointWith gist:UnitOfMeasure ;
.
```
Why are these different, and why do they not include other classes?

This is just one example. Perhaps we should use `owl:AllDisjointClasses` to subsume all the disjointness assertions (similar to what we do with the `owl:allDifferent` assertion for gist individuals).

**Comment by rjyounes** [comment]
I'm not saying everything is disjoint with everything else. I'm proposing that instead of the scattershot approach, we add an `owl:AllDisjointClasses` to cover those that are all pairwise disjoint.

**Comment by uscholdm** [comment]
I see.  It would be a fair amount of work to examine every pair and determine how to refactor it, and easy to make a mistake.  If you do this, I am 99.99% sure you will find things you disagree with, some of which all will agree are errors.   Not a bad idea to have a fresh set of eyes look into it.

**Comment by uscholdm** [comment]
@rjyounes Is this still worth considering? It's a small matter of style and could be a good chunk of work to get there.

**Comment by rjyounes** [comment]
Agreed. Closing.
