### ISSUE TITLE
Add reference to schema.org AdministrativeArea

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#681]
`gist:GovernedGeoRegion` is essentially identical in neaming to `AdministrativeArea` from schema.org. Compare the following definitions; can you tell which is which? 
- "A geographical region, typically under the jurisdiction of a particular government."
- "A defined geographic area or areas governed by at least one government organization."

To be good Semantic Web citizens, I propose that we add an additional altLabel as well as point to the URL:  `https://schema.org/AdministrativeArea` in a note (not sure which skos annotation is best)

**Comment by rjyounes** [comment]
Re `altLabel`: I'm not in favor of the term "administrative area," and I think the Schema name choice is poor. Because administration does not necessary imply governance, an administrative area can be, say, a service area defined by Verizon or UPS, or the ICU wing of a hospital. There are edge cases that aren't so straightforward: is a school district "governed by" a school board? So while the schema term may be aiming at the same thing we are, the word choice is misleading.

Re being good semantic web citizens: taken to its logical extension, this implies a full review of gist to add pointers to similar terms in well-known ontologies. This is a _lot_ of work: the devil is in the details, and to figure out whether two terms really mean the same thing can be time-consuming. For example, schema:Person is "A person (alive, dead, undead, or fictional)." gist:Person includes only the first two of these. Would we want to point to the schema term in this case? That's an easy one, but many will be more complex.

**Comment by uscholdm** [comment]
There are two questions here. First, the name, second, pointers to other IRIs.

I have always thought the name AdministrativeArea  was perfect - I wish I had thought of it myself. To administer is "to manage and be responsible for the running of". So we disagree on that point.

As to whether we wish to point to other commonly used IRIs at all, I am not sure. You raise a good point. If we start, where do we stop.

**Comment by JonathonGist** [comment]
In principle, I think it a good customer-service and good-citizen thing to add pointers to well-known ontology items in other ontologies. Indeed such is a very large task that isn't justified, financially. I recommend adding them where they are able to be done as a part of other work, so the burden is minimal and the connections accumulate over time with little pain. Hopefully customers and others, maybe me someday, will help with this. I suspect there will be limited direct matches; and many close matches. Both would have value, but the former the most value.

**Comment by uscholdm** [comment]
> I recommend adding them where they are able to be done as a part of other work, so the burden is minimal and the connections accumulate over time with little pain.

This has merit, and addresses my question about if we start, where do we stop. We can add them piecemeal when it seems to make sense, and make no attempt to have completeness.

**Comment by justin2004** [comment]
And we could use `rdfs:seeAlso` to make the minimal commitment initially when referencing resources in other ontologies (as discussed in #720).

**Comment by rjyounes** [comment]
I don't see why we need an altLabel if we have the seeAlso. There's only so far I'm willing to go to adjust to other ontologies. 

I still don't see the point of all of this. Schema has very different uses and users from gist (the web vs the enterprise). We are not Semantic Web citizens, much less good ones. And to me it introduces an uncomfortable sort of subordinate-superordinate relationship: we are going to cite Schema, but they are not going to cite gist. I'd like a full discussion of this and especially @mkumba's input as well. It strikes me as a policy decision of some significance.

**Comment by uscholdm** [comment]
> I still don't see the point of all of this. Schema has very different uses and users from gist (the web vs the enterprise). We are not Semantic Web citizens, much less good ones.

Fair point. I am biased because I happen to think AdministrativeArea is a  much better term, but that is not the point. I'm ok if we don't take much effort to link to other ontologies.  Maybe seeAlso, but altLabel may be going too far.

**Comment by uscholdm** [comment]
@rjyounes We cannot hope to relate gist to all commonly used ontology terms out there, if we start, where do we stop?  If there are compelling reasons to link to other ontology terms, then we should use` rdfs:seeAlso` (#720). There is no compelling reason to link to `schema:AdministrativeArea`.

I propose to close this issue.

**Comment by uscholdm** [comment]
> Agreed. I voiced this concern in regard to an issue involving a seeAlso to a schema property (can't find it now).

Same question arose relating to gist:domainIncludes and the schema version. #720

**Comment by JonathonGist** [comment]
Contrary to what I wrote earlier, I think your final decision is best. I love seeing how you all think and work to come to the best decision.
