### ISSUE TITLE
Should `gist` add explicit English language tags to all its existing SKOS annotation values?

### ISSUE THREAD

**Issue by pmcb55** [semanticarts/gist#685]
Currently the `skos:prefLabel` and `skos:definition` (and `skos:scopeNote` and `skos:example`, etc.) values for all terms in gist are only provided in English, yet they are not explicitly language tagged with `@en`.

To help promote more international reuse of gist, and to more clearly and explicitly denote the intended use of these values (i.e., I assume for human users to read and interpret), I would strongly advocate **_always_** adding explicit language tags for such predicates (and to leave strings of type `xsd:string` for predicates whose literal values would never make sense to translate across human languages (e.g., values for social security numbers (that may contain hyphens), or alphanumeric passport numbers, etc.))

**Comment by Jamie-SA** [comment]
This request has come up several times. I am not sure why we haven't done this yet.

#311 
#228 
#185 
#85

**Comment by rjyounes** [comment]
It's worth reading the discussion thread on #311 to get some insight into why we haven't done this in the past.

If we do want to do it, rdf-toolkit has this option:

```
 -osl,--override-string-language <arg> 
 sets an override language that is applied to all strings
```

We could add this argument in the pre-commit hook. 

However, this will over-generate in a couple of cases: 
* `gist:license` value - though it has been suggested that this be an object rather than datatype property - see #682.
* If we use `vann:hasPreferredPrefix` and `hasPreferredNamespaceUri` as suggested in #684.

Perhaps it's better placed in the bundler, where we can specify exactly the properties we want it to apply to (annotation properties).

**Comment by Jamie-SA** [comment]
Should it be a post processing step? Why not just change the source files and then only verify correctness in the bundling step? Similar to some of the queries Boris wrote for validating style.

Also think through how we'd want to handle having multiple languages in/for gist.

**Comment by rjyounes** [comment]
That works too, but I do think we should use the bundler to verify it in case people forget.

**Comment by JonathonGist** [comment]
Excellent. I was hoping you all would add @en where appropriate.

**Comment by rjyounes** [comment]
Considerations:
* `@en` tags could be added by bundler.
* This is a breaking change, not in terms of inferences, but it will break SPARQL queries.
* The bundler could add non-tagged versions of the annotations to `rdfs:Annotations`, for users who don't want to update their queries.
* Alternatively, Jamie suggests keeping the non-tagged files in `gistCore.ttl`, at least as a transitional device, so users don't have to add an additional import.

Needs further discussion, so moving to December release.

**Comment by Jamie-SA** [comment]
Rebecca is correct, this likely will break someone's queries or code. But I think we should do it. I'll volunteer to do the PR.

I think we should schedule it for the next major release (probably the Units Of Measure changes release).

But there is another problem, if we only have one language, adding a second would also break queries/code. It seems we have 2 options, 1) keep translations in a separate file, or 2) add at least one more language at the same time so people would need to address the issue of multiple languages at the same time as the switch to language tags.

Dealing with multiple languages might be harder for most of us who haven't had to deal with it yet, than just the change of literal type. So part of my likes the idea of keeping other languages in separate files. But I also think it might be a good idea to push us to start preparing for it, and therefore should put them into the main file. Of course, we could release multiple versions and let people choose.

See also these discussions about dealing with multiple languages:
- https://github.com/w3c/sparql-12/issues/13
- https://github.com/w3c/sparql-12/blob/main/SEP/SEP-0005/sep-0005.md

**Comment by rjyounes** [comment]
I don't consider myself anglocentric, but I don't think ontology terms need to have language versions until we have a specific use case for that. Instances are a different issue. In the Treasury of Lives project, for example, data properties like names and pref labels in taxonomies have different versions for different languages and transliterations. But ontology terms are not user-facing and I see no reason to provide alternate language versions for maintainers of the ontology - again, until we have a use case, which would have to be a gist developer who knows little or no English - arguably extremely unlikely.

**Comment by rjyounes** [comment]
We have to acknowledge that English is the de facto lingua franca in the worlds of business, finance, tech, industry, and academia. I bet every professional ontologist has read the English texts on the subject. 

Your final point is convincing, though, so I'll retract my disagreement.

**Comment by rjyounes** [comment]
Do we want to add `@en` or `@en-us`, so that our colleagues in the UK can use "Organisation"@en-gb"?

**Comment by JonathonGist** [comment]
I think that it would be good to use @en-us, so that @en-gb can be used where needed.

**Comment by uscholdm** [comment]
I wonder what FIBO does.

Sent from an input-challenged device.

On Jan 27, 2023, at 07:15, Rebecca Younes ***@***.***> wrote:

﻿

Do we want to add @en or @en-us, so that our colleagues in the UK can use ***@***.***<https://github.com/en-GB>"?

**Comment by rjyounes** [comment]
If someone wants to add a language, they can submit a PR and continue to maintain it.

Should we have a version of each annotation without a language tag?

Should we require a complete implementation of all annotations, or should we allow someone to implement piecemeal?
Steven: Then we would have to maintain it with every update.
Rebecca: We can suggest it.

Michael: Another option is to ask people to create files with their translations.
Jamie: Or put them in a separate file in our repo.

Suggestion: Canonical version doesn't have a tag. All tagged versions go in separate files.
We'll implement the English one as a starter.
Also a partial (or complete) French version.

Jamie: Automate English version and add to pre-commit hook (dev team)

**Comment by rjyounes** [comment]
TBD: File naming conventions, file and directory structure

- One directory for each language or a shared directory for all languages?
- One file per language, or mirroring the canonical files with 5 separate files? If the latter, there should be a directory per language to avoid clutter.
- The release package generates multiple serializations of each file, so having one directory per sub-language seems cleaner and more manageable.
- Adding status "under review" until these questions are answered.

Setting status to "under review" until these questions are answered.

**Comment by rjyounes** [comment]
Added individual issues:

#840 - Automated generation of en version
#841 - Sample French version
#842 - Documentation

This issue will be closed once the file and directory structure questions have been resolved.

**Comment by pmcb55** [comment]
Just a very quick comment - in all my US-based customer engagements, the first (and so far only!) additional language they've all requested has been Spanish. (I just mention this as I see you're leaning towards French, but I would have thought most current gist users are probably US-based, and therefore wouldn't Spanish perhaps be a more 'useful' 2nd language for that user-base...?)

**Comment by pmcb55** [comment]
>  If you are able to provide a Spanish version instead...

@rjyounes yeah, you've got a deal! Since this is just some examples, why don't we just add both French and Spanish

**Comment by Jamie-SA** [comment]
@pmcb55 thanks for the comments. I agree with adding 4 letter tags, it basically starts everyone on the path of being able to handle it from the beginning.

But I have a clarifying question: would you use 2 letter language tags when there is no difference? Or do you duplicate everything even when there is no difference between the 4 letter language tag versions?

**Comment by rjyounes** [comment]
@pmcb55 You've convinced me of the four-letter language tags. @Jamie-SA You would use the same tags throughout, even if the languages coincide. That would certainly decrease the burden on querying.

**Comment by rjyounes** [comment]
I would like to get @mkumba's input on the 4-letter tags before moving forward. He expressed a preference for 2-letter tags.

**Comment by mkumba** [comment]
Yeah the 4 letter tag comes into play about 1% of time, and even when it’s a fail is a soft fail.  Most Americans know that colour is really color and most Brit’s know color is really colour so there isn’t much lost.

The real debate is whether or when to allow un languished strings

Sent from my iPhone

On May 17, 2023, at 12:14, Rebecca Younes ***@***.***> wrote:

﻿

I would like to get @mkumba<https://github.com/mkumba>'s input on the 4-letter tags before moving forward. He expressed a preference for 2-letter tags.

**Comment by uscholdm** [comment]
> The real debate is whether or when to allow un languished strings

Yes that is the question - perhaps gist strings have languished in their un-languaged form for long enough!  :-)

**Comment by johnwcowan** [comment]
It's important to be flexible about the length of a language tag.  

For Japanese, the appropriate tag is simply "@ja", because there is no country other than Japan where Japanese is an important language.  We do not need to tag anything "@ja-JP", for example, because there is no contrast with "@ja-US" or "@ja-EU" or what have you. 

On the other hand, not all languages have 2-letter tags.  One of the official languages of the Cook Islands, for example, is Cook Islands Maori (not the same as New Zealand Maori), whose tag is "@rar".  Across the entire range of languages (about 7000), most have 3-letter tags, though most of the commercially important ones have 2-letter tags. 

On the gripping hand, the important distinction for written Chinese is traditional vs. simplified characters, which are tagged "@zh-Hant" and "@zh-Hans" respectively, and by the same token for Azerbaijani what matters is the script: Latin (@az-Latn), Cyrillic (@az-Cyrl), or Arabic (@az-Arab), as most literate Azeris only know one script.'

Links:

[Language Subtag Registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry)

[BCP 47](https://www.ietf.org/rfc/bcp/bcp47.txt).  See RFC 5646 (first part of BCP 47), section 4.1 for guidelines for constructing language tags from subtags.

**Comment by rjyounes** [comment]
@johnwcowan  Thanks, this is good information. W3C has a [helpful discussion](https://www.w3.org/International/articles/language-tags/) of tags and subtags which confirms what you are saying. We've been referring over-simplistically to "two" and "four" letter tags: the correct distinctions are between language tag, region sub-tag, and script tags. 

I think you're right that we need not prescribe a certain level of tagging. If someone wants to provide a specifically Canadian French version as opposed to a generic French version, they can do so. On the other hand, we may choose not to accept a PR that uses "jp-JP" tags and request that they be re-written as simply "jp." The primary open implementation question for us is whether our auto-generated English tags should be "en" or "en-US."

**Comment by johnwcowan** [comment]
Minor correction:  Japanese is 'ja', whereas Japan is 'JP'.

I recommend the use of 'en-US', since the existing text is written in U.S. English.

In general, anything meant to be linguistic data (descriptions, etc.) as opposed to codes, should be language-tagged.  So unless it's a requirement for backward compatibility, I recommend tagging all the linguistic data rather than providing an untagged form.  Untagged text should be confined to codes of various sorts.

**Comment by rjyounes** [comment]
It's a requirement for backward compatibility.

**Comment by rjyounes** [comment]
Closing: all to-do items moved to other issues.

**Comment by rjyounes** [comment]
Team discussion on 2023-05-25 led to the following conclusions:


	  * Related issues: 
		  * [Automated generation of en version](https://github.com/semanticarts/gist/issues/685)
		  * [Sample French version](https://github.com/semanticarts/gist/issues/841)
		  * [Sample Spanish version](https://github.com/semanticarts/gist/issues/851) (Pat McBennett to submit PR)
		  * [Documentation](https://github.com/semanticarts/gist/issues/842)
    * Open discussion points
	    * Language or language+subtag? Subtag could be region or script. E.g., in Chinese the script is of primary significance in written text, not the region. From John Cowan.
	      * Maybe language only if there are no significant regional distinctions, otherwise language+region? (Note, for accuracy the subtags are not always 2 letters). 
	      * Don't need to prescribe, just let people submit what they want to? We could reject a region tag where there are no regional distinctions.
	      * What do we want to do for our versions?
		      * English - use language only, may change in future
		      * French - use language only, may change in future
	     * How do we review PRs in language we have no expertise in? 
	         * Trust factor
	         * In-house expertise
		     * Test in Google translate (to English), if they look OK accept them. If not, reject the whole batch.
		     * Add disclaimer for those we haven't been able to review, and also that they may not be up-to-date as gist evolves.
		     * SA in-house expertise:
			     * French: Doug, Jess
			     * German: Rebecca
			     * Arabic: Dalia
			     * Simplified and Traditional Chinese: Katie (some)
			     * Japanese: Katie (some)
			     * Russian: Irina
			     * Italian: Irina
	    * No default untagged version - our default should be `en-US`. From John Cowan.
	      * Then this is a major change.
	      * Decision: keep untagged versions as defaults in ontology files. Can change later in a major release. 
	    *  File names and directory structure. 
		    * Only release in Turtle. 
		    * Most likely only gistCore, not supplementary ontologies, will be translated.
		    * There might be a translation of the readme if someone wants to do it.
		    * So, we'll only have one ontology file per language. Naming conventions:
			    * `gistCore.en.ttl`
			    * `README.en.md`
		    * So use one directory. [We didn't decide on a directory name, I propose `language_tagged_annotations` or similar.]

**Comment by rjyounes** [comment]
See additional discussion and final conclusion on #840.
