### ISSUE TITLE
Let’s not have street address be a sub of postal address

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#686]
From Dave

Let’s not have street address be a sub of postal address, see below from https://www.smarty.com/articles/autocomplete#po-boxes-apo-fpo-dpos

Consideration 6: Includes Non-Postal Addresses
A "non-postal" address in the United States is a real street address that is not included in the USPS address database. Non-postals include but are not limited to:
•  Rural areas where mail delivery isn't financially feasible for the USPS.
•  locations where inclement weather doesn't permit USPS delivery.
•  New construction that has not yet been added to the USPS database.While USPS doesn't deliver to these addresses, shippers like FedEx and UPS are happy to pick up the slack. There are currently millions of valid addresses that are "non-postals" by the USPS standards.

**Comment by rjyounes** [comment]
Dave also suggests renaming `StreetAddress` to `PhysicalAddress`.

**Comment by JonathonGist** [comment]
Thumbs up to all these changes, by me.

**Comment by uscholdm** [comment]
PROPOSAL:
- remove subclass relationship between `StreetAddress` and `PostalAddress`
- rename `StreetAddress` to `PhysicalAddress`
- add scopenote to `PhysicalAddress` saying that some street addresses are not postal addresses and pointing to the link: https://www.smarty.com/articles/autocomplete#po-boxes-apo-fpo-dpos

**Comment by rjyounes** [comment]
What about a class `DeliveryAddress`, which would include addresses used by USPS, UPS, FedEx, etc. rather than being limited to USPS, like `PostalAddress`? This is still not the same as a street (physical) address, for the same reason that PO boxes addresses are not street addresses.

**Comment by rjyounes** [comment]
I don't think we need to model the ins and outs of USPS addresses in an upper ontology.

Perhaps the distinction shouldn't be represented by subclasses of `Address`, but by the relationships to people. E.g., I have a PO box as my USPS delivery address, an address of the house I live in and another of the building I work in. A PO box address is still the address of a physical thing (the box).

**Comment by rjyounes** [comment]
Done in 13.0.0
