### ISSUE TITLE
reconsider gist:Category being a subclass of isAllocatedBy() in the context of BFO crosswalk work

### ISSUE THREAD

**Issue by pwin** [semanticarts/gist#687]
Anthony P raised the following in discussion:
"BFO documentation uses the term ‘category’ in an Aristotelian sense, which is to say it means a domain-neutral universal. In other words a BFO ‘category’ generalizes a specific universal type (e.g., Object, Object Aggregate, Role, Disposition, Process, Temporal Instant). A GIST ‘category’ has a different meaning because GIST categories are not required to be universals. “A concept or label used to categorize other instances informally. Things that can be thought of as types are usually Categories.” [source: GIST v10.0] Also, a GIST category is defined in a very specific context as is evidenced by this sub class axiom:

isAllocatedBy some (IntellectualProperty or Organization or Person)
"
So, if this is an issue that colleagues think is relevant to the direction of gist and the ongoing discussion regarding alignment to BFO, one possibility might be to have a gist:UniversalCategory as a superclass, and then re-define gist:Category in the specific way it is currently specified.

**Comment by rjyounes** [comment]
We are not interested in pushing gist up to this level of abstraction. In a gist-to-BFO mapping we could consider making `gist:Category` a subclass of the BFO class.

**Comment by uscholdm** [comment]
> We are not interested in pushing gist up to this level of abstraction. In a gist-to-BFO mapping we could consider making `gist:Category` a subclass of the BFO class.

Anthony does make a good point. As far as how we approach it, I agree with Rebecca's suggestion.
