### ISSUE TITLE
No need for instances of time magnitudes any  more 

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#692]
This new issue is moot if go with the suggestion in #61 

We used to use `gist:_one_day`, `gist:_one_millisecond` and `gist:_one_second` for precision on TimeInstants. These vestigial instances are no longer needed.

**Comment by rjyounes** [comment]
Why do we have this issue? It duplicates #61. Can we close it?

**Comment by uscholdm** [comment]
#61 has a large amount of content, this small fact could get lost.  Maybe just reference #692 from #61

**Comment by rjyounes** [comment]
Decision: we will deprecate these because they are no longer relevant  - they were used to define precisions of no longer existing `TimeInstant`.
We will also deprecate greenwichTimeZone as it's also no longer used.

**Comment by uscholdm** [comment]
If we had been more observant, we would have gotten rid of these instances when we published major version with new Time properties.  We would NOT have deprecated them then, given it was a major release, so it seems quite silly to deprecate them now.  I suggest just get rid of them with  a comment in tahe release notes explaining why not to deprecate, as we usually do.

**Comment by rjyounes** [comment]
I would prefer to follow the best practice of deprecating them for a non-major release, just in case someone is using them somewhere. I think this _is_ a case where it's best to stick to the rules. And there's no harm in deprecating them.

**Comment by uscholdm** [comment]
In the extremely unlikely situation where anyone IS using them, they are almost certainly MIS-using them, and that should be brought to their attention, in my opinion.  However, this is not worth a lot of discussion. Following the rules is great, until doing so has unintended negative consequences.  As an extreme example, I'd run a red light if I was driving someone with an urgent need to the hospital.  

However, this is not worth much discussion. I'll just deprecate and maybe mitigate damage by putting a comment saying you should not be using these.
