### ISSUE TITLE
ContemporaryEvent should use actualStartDateTime instead of startDateTime

### ISSUE THREAD

**Issue by blin** [semanticarts/gist#696]
Hello,

As per `skos:definition "An event that has started but has not yet ended."^^xsd:string ;`, ContemporaryEvent must have actualStartDateTime , otherwise we can't assert that it has started.

Please either change ContemporaryEvent to have actualStartDateTime or provide examples/counter-examples/notes that would clarify why having startDateTime is sufficient to infer that an event is a ContemporaryEvent .

**Comment by rjyounes** [comment]
Valid point. We will make this fix.

**Comment by dylan-sa** [comment]
Fixed in #717.
