### ISSUE TITLE
Shorten cumbersome property names

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#698]
@marksem I agree that the current versions using "geographically" are cumbersome and should be changed back to "geo."  We might want to check for other cumbersome property names as well.

**Comment by uscholdm** [comment]
This opens pandora's box.  We have a policy for not abbreviating. If we allow abbreviations sometimes, but not others, what are the guidelines?

**Comment by rjyounes** [comment]
@uscholdm  You're right. No backpedaling.
