### ISSUE TITLE
Should `gist:isConnectedTo` be symmetric?

### ISSUE THREAD

**Issue by dylan-sa** [semanticarts/gist#699]
Intuitively, if x is connected to y, then y is connected to x. Does this hold for `gist:isConnectedTo`?

**Comment by rjyounes** [comment]
No. This property can be used to connect a temporal relation to the two (or more things it's connected to. So you can have, say, a Marriage relationship that is connected to each of the people in the marriage. They are not necessarily connected to one another by the predicate.

**Comment by dylan-sa** [comment]
With the marriage relationship, I can see how `:_Person_A gist:isConnectedTo :_Person_B` might not hold. I was suggesting something different: that if `:_Marriage_between_A_and_B gist:isConnectedTo :_Person_A`, then `:_Person_A gist:isConnectedTo :_Marriage_between_A_and_B`. But maybe that's still not necessarily the case!

**Comment by rjyounes** [comment]
I think that's probably right. There's a nuance that should be discussed by the group.

**Comment by uscholdm** [comment]
Rebecca's description is accurate. The problem is the naming of  the predicate. There used to be an inverse property called hasConnection (which is equally unhelpful, other rthan implying that the property is not symmetric. Those two predicate names give no hint of what direction means what.  I made up my own convention to always use connectedTo FROM the 'main' entity (e.g. a Marriage) to some aspect or part of it (one of the spouses).  That's how it is used in TemporalRelation.

We are unlikely to come up with a better name for the property, but we might want to tweak the definition if we can make it more clear.

**Comment by dylan-sa** [comment]
An additional thought after our 8/11 meeting: `isSiblingOf` is symmetric and `isOlderSiblingOf` isn't, but `isOlderSiblingOf` is still a subproperty of `isSiblingOf`. So even if we decided to make `gist:isConnectedTo` symmetric, it wouldn't preclude us from building asymmetric or antisymmetric subproperties.

**Comment by rjyounes** [comment]
Dan: usually creates subproperties, which are not always symmetric, so it should not be symmetric.
E..g., `supercedes`. 

Michael: Historically, `isConnectedTo` was used for temporal relationships.

Do we need this property? Do we need to rename it?

Current definition: "A non-owning, non-causal, non-subordinate (i.e., peer-to-peer) relationship."
Dan: seems OK other than "peer-to-peer."

Can also be used directly - mechanical or physical connection between objects. ("Foot bone connected to the ankle bone.")
Rebecca: This isn't the same relationship as the temporal relationship one. Should have another predicate for this case.

Michael suggests using `hasParticipant` instead.
Rebecca: suggests agency, so doesn't cover all cases.

Proposal
- Leave `isConnectedTo` as is, except remove "peer-to-peer" in the definition
- Expand the restriction on `TemporalRelation` to allow `hasParticipant` OR `isConnectedTo`
- Add `isConnectedTo domainIncludes TemporalRelation`

We all agree to:
- Whatever predicate (predicate X) links a `TemporalRelation` to the two or more things it's connected to is not symmetric

Open questions:
- Do we want predicate X to also apply to the foot bone/ankle bone case?
  - Rebecca: No, these are completely different relationships. The marriage partners are analagous foot and ankle bone, not the Marriage to each of the partners.
- In that case, do we want to define a new predicate for this physical/mechanical connection?
  - Rebecca: No, let's not define anything new until we have a use case that can guide the definition (e.g., is it symmetric?).
- Do we want predicate X to be used for network connections?
  - Rebecca: No, we already have a network model for these (`NetworkNode`, `NetworkLink`, and `links`)
  - Scott: we don't use those in mscore
  - Rebecca: We can let mscore do whatever it does, it shoudn't determine gist usage.
- Do we want predicate X to be _limited_ to temporal relationships?
 - Rebecca: No,

**Comment by rjyounes** [comment]
@dylan-sa is absolutely right. So now we have nothing that we all agree on, sadly. We'll revisit in two weeks.

**Comment by DanCarey404** [comment]
I may have muddied the waters with an incorrect understanding.  I found a blog post that says "We can’t assume that property characteristics are inherited – some are (e.g. functionality), some aren’t (e.g. transitivity and symmetry)."  That would confirm Dylan's point.  In which case, maybe we _can_ and _should_ make :isConnectedTo symmetric.

**Comment by justin2004** [comment]
I think you were right the first time, @DanCarey404  .

If `:isX` is a subProperty of `gist:isConnectedTo` and `gist:isConnectedTo` is symmetric
then
if I assert
`:bob :isX :fred`
the reasoner will emit
`:bob gist:connectedTo :fred` 
and then it will emit
`:fred gist:connectedTo :bob`

So making `gist:isConnectedTo` symmetric would constrain uses (including sub props) of it.

I think my vote here is to delete `gist:connectedTo` and make a migration to transform usages of it to use `owl:topObjectProperty` instead.

**Comment by rjyounes** [comment]
@justin2004 That was my initial reasoning as well. The fallacy is that the reasoner will infer `fred :isConnectedTo :bob` _only_ when the sub-property is symmetric. Given another, non-symmetric, sub-property, that inference would not be made. Therefore, the super-property is not symmetric. I think @dylan-sa's example is pretty incontravertible.

We do not assert `owl:topObjectProperty` in our RDF and I have never seen this done. According to the OWL 2 spec:

The object property with IRI owl:topObjectProperty connects all possible pairs of individuals.

It would therefore be both redundant and meaningless to assert this relationship between two individuals.

What we are looking for is a predicate specifically designed to connect reified relationships to the objects that partake in that relationship. I.e., we are looking for a predicate with some semantics, not something vacuous. We are trying to constrain the semantics by excluding many of the other cases where we would use English "connected to" (this was the foot/ankle bone discussion) but which are semantically quite different. I use `isConnectedBy` in my client ontologies where I have no need for a more specific super-property, and do not want to lose it, though I would prefer a clearer name.

**Comment by justin2004** [comment]
> What we are looking for is a predicate specifically designed to connect reified relationships to the objects that partake in that relationship

That sounds like we just need `gist:hasParticipant`.

```turtle
:someNAryThing gist:hasParticipant :bob .
:someNAryThing gist:hasParticipant :fred .
```

I don't think the comments on `gist:hasParticipant` require that the participants be aware they are participating. 
And on that topic I think the proposal in #695 is relevant.

I think this:
```turtle
:someNAryThing gist:hasParticipant :bob .
:someNAryThing gist:hasParticipant :fred .
```
is really shorthand for this:
```turtle
[ a :someNAryThing ;                                                                                                                     
  :hasRole [ :playedBy :fred ] ;                                                                                                        
  :hasRole [ :playedBy :bob ] ]  
```

**Comment by uscholdm** [comment]
> > What we are looking for is a predicate specifically designed to connect reified relationships to the objects that partake in that relationship
> 
> That sounds like we just need to use `gist:hasParticipant`.
> 
> ```turtle
> :someNAryThing gist:hasParticipant :bob .
> :someNAryThing gist:hasParticipant :fred .
> ```
> 
> I don't think the comments on `gist:hasParticipant` require that the participants be aware they are participating. And on that topic I think the proposal in #695 is relevant.
> 
> I think this:
> 
> ```turtle
> :someNAryThing gist:hasParticipant :bob .
> :someNAryThing gist:hasParticipant :fred .
> ```
> 
> is really shorthand for something like this:
> 
> ```turtle
> :someNAryThing :hasRole [ :playedBy :fred ] ;
>                             :hasRole [ :playedBy :bob ] .  
> ```

I agree with this. I have seen hasParticipant in other upper ontologies used in a neutral non-agentive fashion.  In chemistary, a reactant is what particpates in a chemical reaction. They are not agentive. This is common usage. https://byjus.com/chemistry/precipitation-reaction/

**Comment by rjyounes** [comment]
I looked at the definition `hasParticipant` and see that it does not imply agency: "Relates something (e.g. an agreement) to things that play a role, or take part or are otherwise involved in some way." "Participant" would still not be my choice of word for this, but given this definition I agree that we can eliminate `isConnectedTo`.

**Comment by rjyounes** [comment]
Mark: agrees that `hasParticipant` can be used for `TemporalRelation`. Wants to keep `isConnectedTo` for network connections, also good parent property and should be symmetric.

Rebecca: It would be the superproperty of all properties, so vacuous.

Dan: Property is only used in a restriction on `TemporalRelation`. Doesn't like `hasParticipant` in the restriction.

Mark: Two issues:
1. What should be the property for temporal relations?
2. Should `isConnectedTo` be symmetric? 
Wants to keep it and make symmetric. Has been shortcut property for network nodes and links. 

Rebecca: If symmetric, it's no longer the right property for `TemporalRelation`s. 

Dan: Nothing else is generic enough. `hasParticipant` implies agents.

Rebecca: `hasParticipant` is not limited to agents according to the gist definition.

Making new issue to deal with temporal relations first. Then deal with symmetricity of `isConnectedTo` second.

**Comment by marksem** [comment]
Yes, this should be symmetric, and I'd like to keep it in gist.  
I agree TemporalRelation should use a different property in its axioms.
