### ISSUE TITLE
Consider Whether to Add a Way to Model Significant Figures

### ISSUE THREAD

**Issue by dhurlburtusa** [semanticarts/gist#702]
As I started to do more with the input data than just persisting it, it occurred to me that `gist` doesn't have a way, afaik, to model the [significant figures](https://en.wikipedia.org/wiki/Significant_figures) of some numeric value. I believe scientific notation is the only numeric format that has sig figs built into the syntax, i.e., 1.20e2 indicates 3 sig figs. And I believe xsd:double and xsd:float are the only standard datatypes that allow, but don't require, sci not in its lexical form. Things like `"1000000"^^xsd:decimal` or `"1.20"^^xsd:double` don't indicate the number of sig figs.

Why are sig figs important?

After performing calculations (addition, subtractions, multiplication, etc) on several numbers, the final number should be rounded/truncated to the number of sig figs as found in the input number with the least sig figs.

 I'm thinking is can be helpful to have an optional property on a `gist:Magnitude` that indicates the sig figs. So, a gist:Magnitude has a unit of measure, a value, and optional sig figs.

The sig figs could be an `xsd:nonNegativeInteger` of 1 or greater. The property could be called `gist:hasSigFigs`, `gist:hasSignificantFigures`, or others.

**Comment by uscholdm** [comment]
This is an interesting idea, and could be valuable in some situations.  Do you have an immediate requirement for this?

Even if you do, I suspect this need will not arise very often - hence it does not belong in gist core. 

The solution you propose is interesting, and might work. There is a question of when two Magnitude IRIs can be regarded as the same.  Normally if the number and the unit are identical, then both IRIs point to the same referent.  If we introduce significant digits on a Magnitude, then identity would involve that third thing.  So the following would arguably be different:
1. 2 meters with 2 significant digits
2. 2 meters with 3 significant digits

Getting inference correct could be a bit tricky, since some magnitudes will have significant digits and some will not.

**Comment by dhurlburtusa** [comment]
> Do you have an immediate requirement for this?

Not an actual requirement. I'm just doing like most of the world and blindly making calculations (e.g., multiplying, adding, etc) on numbers without knowing their precision. That is, just using floats or doubles and using the final result. (In some cases, decimals are being used for currency and proper steps are being taken to not lose fractions of a cent.)

I don't want to display stuff like 1.33333333333 just because that's what a calculation came out to. I'd rather display 4/3 if there is 100% accuracy (I only know of one case with 100% accuracy and that's with counts, might be others). If I knew the sig figs of all the values used in the calculation, then I can find the least sig fig and format the final value accordingly.

Unfortunately, most, if not all, of the incoming data is not in scientific notation. So, the number of sig figs is not explicit. I can take a guess that it's good enough to treat as 2, 3, or 4 sig figs.

I first learned about sig figs in chemistry class and later in engineering courses. It frustrates me to see data and not know how accurate the data is. It was recommended to either round to the least sig fig (LSF) after each calculation before continuing with the next calculation or to carry out all calculations and at the end round to LSF. Most engineers, I presume, including myself, to the latter.

But a question arises. Do I save the calculated value rounded to LSF or save the calculated value and note the LSF so far? The latter will allow further calculations to be performed on the saved value.

Related to sig figs are measurement tolerances.

I know there is a suppose to be a difference between [precision and accuracy](https://www.google.com/search?q=accuracy+vs+precision). I'm not sure how they relate to sig figs and measurement tolerances. Initially, I think sig figs is more about accuracy and measurement tolerances is more about precision.

So, what I'm getting at is maybe it would be best to model both accuracy and precision of some magnitude (assuming there is a real need).

**Comment by uscholdm** [comment]
You raise many excellent points, others have too, hence the existence of a whole field of mathematics which covers this: numerical analysis. It's very complex and even if we did have a client requirement to handle it, doing it in OWL/RDF/SPARQL may or may not be the best approach. 

My recommendation is to not do anything in gist for this and close the issue.

**Comment by dhurlburtusa** [comment]
Yeah, after thinking it through, this would add much more complexity, especially relative to the benefit it could provide.

One benefit came out of the research involved which was a better term for `precision` and that is `resolution`.

BTW, `gist:hasSignificantFigures` would be somewhat similar to `gist:hasPrecision`.
