### ISSUE TITLE
Add gist:BooleanCategory

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#705]
I have used this in a couple of projects and think it may be useful to add to gist.

```
gist:BooleanCategory 
	a owl:Class ;
	owl:equivalentClass [
		owl:intersectionOf (
			gist:Category
			gist:ControlledVocabulary
			[
				a owl:Restriction ;
				owl:onProperty gist:hasMember ;
				owl:cardinality "2"^^xsd:nonNegativeInteger ;
			]
		) ;

	] ;
	skos:prefLabel "Boolean Category" ;
	skos:definition "A category with exactly two values." ;
	skos:example "FLSA value can be either exempt or non-exempt." ;
	.

**Comment by rjyounes** [comment]
Decided to retract this.

**Comment by uscholdm** [comment]
I've thought about this, and the idea has some merit, sor the same reason as I sometime have Status as a subclass of gist:Category.  One wording problem with proposed model, the instance is a single category which means yes or now. A category is ONE value. You mean a subclass of gist:Category that has exactly two instances, one meanign yes and one meaning no.

**Comment by rjyounes** [comment]
Yeah, there were some issues the way I wrote it up, and then I decided it wasn't worth the bother, so I closed it.
