### ISSUE TITLE
Use different property from isConnectedTo in restriction on TemporalRelation

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#706]
Outgrowth of #699. See discussion thread there.

**Comment by rjyounes** [comment]
Proposal to use `hasParticipant` in this restriction.

**Comment by marksem** [comment]
I think hasParticipant, as defined in gist, would work for TemporalRelationships.  It could be sub-propertied for more meaning.

**Comment by rjyounes** [comment]
DECISION: Change the restriction to use `hasParticipant`.
