### ISSUE TITLE
Should TemporalRelation be a modeling pattern rather than a class?

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#707]
@DanCarey404 raised the question of whether `gist:TemporalRelation` should be a modeling pattern instead of a class. We came to this conclusion in discussing a possible superclass `ComplexRelation`; see #424.

**Comment by uscholdm** [comment]
@DanCarey404 @rjyounes 
After a careful read of #424, I don't see there is anything more to consider.  

I recommend we close this issue.

**Comment by rjyounes** [comment]
Agreed - closing.
