### ISSUE TITLE
Simplify gist:Address structure

### ISSUE THREAD

**Issue by DanCarey404** [semanticarts/gist#709]
I propose replacing the current gist:Address decomposition with the following:
**gist:Address**
     **gist:PhysicalAddress  (gist:isConnectedTo some mscore:Place) (gist:isCategorizedBy some gist:AddressType)** [postal, street, etc.]
     **gist:VirtualAddress  (gist:isCategorizedBy some gist:AddressType)** [email, telephoneNumber, website, etc.]

**Comment by uscholdm** [comment]
@DanCarey404 
This is an interesting idea. How about bringing in up in an internal meeting.  But first, take a look at #686.

**Comment by rjyounes** [comment]
Done in 13.0.0
