### ISSUE TITLE
downgrade gist:_unitedNations to just be a gist:Organization

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#71]
We should downgrade our gist:_unitedNations instance to be just an “organization”.  Currently in gist it is a gist:GovernmentOrganization

If you research it, you’ll find that the UN is not a government organization but is an instance of an inter-governmental organization. See https://en.wikipedia.org/wiki/Intergovernmental_organization. Other instances include NATO and the World Bank. 

Client ontology files could add the “inter-governmental org” type if needed.  It is probably too specific for gist.

**Comment by rjyounes** [comment]
See #207 - recommends deleting the entity

**Comment by rjyounes** [comment]
If #207 rejected, consider this.

**Comment by rjyounes** [comment]
We are removing _unitedNations in issue #207.
