### ISSUE TITLE
Reference the IRI `schema:rangeIncludes`

### ISSUE THREAD

**Issue by justin2004** [semanticarts/gist#720]
The `skos:scopeNote` on [gist:rangeIncludes](https://github.com/semanticarts/gist/blob/develop/gistCore.ttl#L3940-L3950) indirectly mentions `schema:rangeIncludes` but shouldn't Gist also explicitly reference it with its IRI?

Can we do the following?
`gist:rangeIncludes owl:equivalentProperty schema:rangeIncludes`
If we can't because of an OWL profile constraint that is fine but it seems we should do some form of
`gist:rangeIncludes ?p schema:rangeIncludes` to be a team player in LOD and to be thingy rather than stringy.

Oh, this also applies to `gist:domainIncludes`.

**Comment by rjyounes** [comment]
`gist:rangeIncludes` is an OWL annotation property. Schema predicates are RDFS properties, therefore it would be incorrect to assert equivalence. An `rdfs:seeAlso` would be a good idea.

**Comment by justin2004** [comment]
> An rdfs:seeAlso would be a good idea.

I agree. That seems like the minimal way be to thingy rather than just stringy.

> I don't know why the scope note on a single property would reference the schema predicates; that seems arbitrary.

My guess is because `schema:rangeIncludes` came first. Also I think the skope note is still useful albeit stringy:
"This property means the same thing as the Schema.org version, which is an rdf:Property and not compliant with OWL-DL."

So we are saying we'll add the following if we get consensus:
```turtle
gist:rangeIncludes rdfs:seeAlso schema:rangeIncludes .
```

**Comment by justin2004** [comment]
Oh, @rjyounes, there is also `skos:closeMatch` that might be even more to the point.

**Comment by rjyounes** [comment]
@justin2004 I disagree. The skos predicates are meant to relate concepts, not RWOs.

**Comment by rjyounes** [comment]
> gist:rangeIncludes rdfs:seeAlso schema:rangeIncludes .
gist:domainIncludes rdfs:seeAlso schema:domainIncludes .

I am in agreement with adding these triples, and would like to remove individual references to the schema predicates within specific term definitions.

**Comment by uscholdm** [comment]
PROPOSAL:

Add schema namespace prefix
`@prefix schema: <https://schema.org/>`

**Replace**
```
gist:domainIncludes
     skos:scopeNote
		"This property means the same thing as the Schema.org version, which is an rdf:Property and not compliant with OWL-DL."^^xsd:string
		;
	.
```
**with** 
```
gist:domainIncludes rdfs:seeAlso schema:domainIncludes ;
	.
```


and **Replace**
```
gist:rangeIncludes
     skos:scopeNote
		"This property means the same thing as the Schema.org version, which is an rdf:Property and not compliant with OWL-DL."^^xsd:string
		;
	.
```
**with** 
```
gist:domainIncludes rdfs:seeAlso schema:rangeIncludes ;
	.
```

Alternatively, leave the scope note intact and just add the seeAlso triple.

**Comment by pmcb55** [comment]
I'd suggest editing the `skos:scopeNode` slightly to say it also 'means the same' as `dcam:rangeIncludes` (where `prefix dcam: <http://purl.org/dc/dcam/>`) and add an `rdfs:seeAlso dcam:rangeIncludes` triple too (just to emphasise that the notion of domain/rangeIncludes is not **_just_** a Schema.org notion!).

And the fundamental reason I'd support keeping the scope note is for the explanation that "an rdf:Property is not compliant with OWL-DL" (and maybe also an `rdfs:seeAlso <HTML page that explains gist's intent to maintain OWL-DL compliance, and therefore the need to avoid rdfs:Class and rdf:Property>` triple!).

**Comment by rjyounes** [comment]
My current view is that asserting `rdfs:seeAlso` to other ontologies initiates a bad practice. I recommend closing this issue.

**Comment by uscholdm** [comment]
> My current view is that asserting `rdfs:seeAlso` to other ontologies initiates a bad practice. I recommend closing this issue.

I'm good with this. It raises the question of when else do we refer to external ontologies?
