### ISSUE TITLE
Restructure Address classes

### ISSUE THREAD

**Issue by DanCarey404** [semanticarts/gist#721]
I propose the following changes to simplify the Address class structure, provide more semantic clarity, and provide clear properties for usage.

- Deprecate/delete all current subclasses of gist:Address
- Add gist:PhysicalAddressType (:_streetAddress, :_postalAddress)
- Add gist:VirtualAddressType (:_emailAddress, :_telephoneNumber, :_webAddress)
- Add gist:PhysicalAddress (gist:Address and (gist:isAbout some gist:Place) and (mscore:categorizedBy some gist:PhysicalAddressType))
- Add gist:VirtualAddress (gist:Address and (mscore:categorizedBy some gist:VirtualAddressType))
- Add gist:addressText   (domain gist:Address)
     - OPTIONAL: Add gist:emailAddressText, gist:telephoneNumberText as subproperties
- Add restriction to gist:Address  (gist:Content and (gist:addressText some xsd:string))

Optionally, we could come up with a new object property for linking an Address to a Place.  Using gist:isAbout is expedient, but not elegant.

**Comment by DanCarey404** [comment]
Based on some of the discussion under #722 , we should perhaps reconsider whether Address is properly a subclass of Content.

**Comment by rjyounes** [comment]
REFER TO DISCUSSION OF gist:Address on issue #722.

**Comment by rjyounes** [comment]
I'd argue against `gist:addressText`:

1. It's just the text of an `Address`, no need for a special property.
2. Some implementations may want to parse the address into multiple strings, so it's not a given that we'd want a single text field for addresses.
3. Emails can use `gist:uniqueText`.

**Comment by uscholdm** [comment]
This is related to a bunch of other issues
See also #471, #483, #594,  #722, #1009

**Comment by uscholdm** [comment]
There are two main elements to this proposal.
1. introduce a physical vs. virtual distinction
2. replace the address class hierarchy with categories (types of addresses)

I'm generally liking this - details to be worked out.
