### ISSUE TITLE
QUESTION: Is there a link to the discussion/issue on gist moving its namespace IRI from hash to slash instead?

### ISSUE THREAD

**Issue by pmcb55** [semanticarts/gist#725]
Hi,

Please forgive me if there is a better place to ask this question (e.g., a gist mailing list or something), and I'll close this **_non-issue_**(!) and re-post there.

But I'm just trying to find out if the gist community actively discussed the transition from using hash '#' in your namespace IRI to using slash '/' instead (i.e., to become `https://ontologies.semanticarts.com/gist/`)...?

All I could find was this reference from issue #130 from Dec 2019: "_I believe the namespace was recently changed from hash to slash_".

I only ask as I'm about to propose to the [W3C Data Privacy Vocabulary (DPV)](https://w3c.github.io/dpv/dpv/) group that they make the same switch before they formalise v1.0, and so I'd like to share with them any discussions, arguments, debates, etc. that you guys already went through (as I totally agree with you guys that slash is 'better' than hash for namespace IRIs in general :) !).

Cheers!

**Comment by Jamie-SA** [comment]
I was not here for that discussion, but one point is that URI/IRI fragments are not sent to an HTTP server, therefore a server can not resolve them. A recommended best practice is that all URI/IRIs should be (or at least, could be) resolvable. Using a `#` in them makes them non-resolvable (at least, to the fragement level). Which is just a bad starting point IMHO.

**Comment by pmcb55** [comment]
Thanks @Jamie-SA - yeah, absolutely (like I say, I too totally agree with the switch to slash over hash). But I'm certainly not trying to re-ignite or re-hash the discussion here (as I'm sure everyone's already very busy, and the (correct!) decision has already been made and implemented in gist).
I was just hoping I might be able to point to any pre-existing discussion/debate. If there isn't anything available publicly, then that's totally fine too of course (and I'll close this issue) - I'm just curious to see if there might be 'prior art/related work' I could share with the DPV folks (and internally where I work!) :)

**Comment by pmcb55** [comment]
Hi @uscholdm or @rjyounes - by any chance would either of you guys have a reference to any public gist discussions of the 'switch from hash to slash'?
(I'm just anxious to provide guidance to the DPV working group before they close for comments soon, and to give them time to digest and discuss the overall issue for themselves before closing their current open-for-comments period - so any guidance at all would be greatly appreciated - thanks!)

**Comment by rjyounes** [comment]
That predates my tenure, so I don't. The best and most complete discussion I know on the subject is in the book [_Linked Data_ by Tom Heath and Christian Bizer, section 2.3](http://linkeddatabook.com/editions/1.0/#htoc11).

**Comment by pmcb55** [comment]
Thanks @rjyounes - and yeah, that reference is useful, but like every reference on this topic that I can find online, it merely suggests the pro's and con's of both approaches, without expressing any opinion on which one might be considered 'better'.

For me, I don't think the answer to the question is '**_Well, it depends..._**' - I think the slash is clearly 'better' (i.e., it's the only option that allows returning **_only_** what I've ask for (i.e., just info on a specifically-asked-for term, and no other noise related to the rest of the terms that may be expressed in a vocab), while also supporting the ability to retrieve info on all vocab terms in one HTTP request if I want too (i.e., by just request the namespace IRI itself (or it's prefix-declaration-defined namespace IRI) to get info on all the terms.

Anyways, it seems there may not have ever been a publicly documented record of the gist discussions around the decision to switch over to using slash. That's fine of course (I was just hoping...), so I'll close this issue now.
