### ISSUE TITLE
Create separate ontology for Internet of Things

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#729]
See: #323 
Move classes
- Actuator
- Controller
- Sensor

Move properties
- respondsTo?
- hasViableRange?

Look in old iot ontology file for the rest

**Comment by rjyounes** [comment]
Implementation specified but needs assignee.

**Comment by rjyounes** [comment]
Consider with #462.

**Comment by Jamie-SA** [comment]
Move to gistComputing?

**Comment by rjyounes** [comment]
Closing - duplicates #462.
