### ISSUE TITLE
gist 9.0.0 web download issues

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#73]
I downloaded Gist 9.0.0 for the first time from our website. 

I noticed a number of problems:

1.	The catalog-v001.xml file in the download has a number of issues. The useful part of the catalog file will be the part that maps to filenames with the version numbers at the end.  In this part of the catalog file:
   a.	it maps http ontology URLs, but the new URLs have https in them.  
   b.	gistDeprecated9.0.0 is in catalog file, but no such file exists in the download.  
   c.	gistNetwork9.0.0 is missing from this part of the catalog file. 
   d.	gistIoT9.0.0 is missing from this part of the catalog file
2.	Also, the ReleaseNotes.txt file is not in the current download. (if bundle was run correctly, there should have been)
3.	the LICENSE.txt file is not in the current download 😲 (if bundle was run correctly, there should have been)

Additional questions:

4.	Should the gist9.0.0.vsdx file be in the download?  (currently it is not, but if bundle was run correctly, there should have been)
5.	Should there still be a gistDeprecated9.0.0.owl file in the download?  (currently there is not, but if bundle was run correctly, there should have been)

I would like to:
   A)	fix the catalog-v001.xml file.
   B)	walk with you through the release process to be sure you know how to run it properly.
   C)	ultimately, after answering all the above questions, put a new web download that correctly has all that we want in it.

**Comment by uscholdm** [comment]
We generally have not made the .vsdx file available for download. Rather, we export a .pdf.

**Comment by marksem** [comment]
@mkumba , please comment on VSDX file in download. Thanks.

**Comment by uscholdm** [comment]
Is there a good reason to release the .vsdx?   I wonder if it has lots of junk like Word files do that are better left private.  If noone is asking, then maybe best to leave it out as we have all along.

**Comment by mkumba** [comment]
This is the VSDX

**Comment by mkumba** [comment]
I guess that didn't do it.

**Comment by marksem** [comment]
The question is… when folks go to semanticarts.com/gist and click the download button, should the ZIP file they get include the VSDX file.

**Comment by mkumba** [comment]
good question.  There isn’t much they can do with it, because they don’t have E6, so really the PDF is just as good as the visio to them.

On Jul 31, 2019, at 1:09 PM, Mark Wallace <notifications@github.com<mailto:notifications@github.com>> wrote:

The question is… when folks go to semanticarts.com/gist<http://semanticarts.com/gist> and click the download button, should the ZIP file they get include the VSDX file.

**Comment by uscholdm** [comment]
Yeah, that’s what I’m thinking.

M.

**Comment by marksem** [comment]
This issue is OBE given that 9.1.0 has now been released.
