### ISSUE TITLE
Additions to Contributing.md

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#734]
If not already included:

* When you start working on an issue, move to "In Progress" in the project board. There is no automation of this change in state.
* When you have submitted the PR for an issue, move the issue to "In Review" in the project board. There is no automation of this change in state.
* When you have submitted your PR, check that there are no conflicts with develop. If there are, you should resolve them.

**Comment by Jamie-SA** [comment]
@Jamie-SA will take a first whack for Rebecca to edit.

**Comment by Jamie-SA** [comment]
I don't see anything about how we expect release notes are expected to be added to the /docs/ directory and then combined for the release.

**Comment by Jamie-SA** [comment]
Having to name the release notes with the PR number means you can't have the right filename until after you create the PR. Is there a better way to get around this?

**Comment by rjyounes** [comment]
> I don't see anything about how we expect release notes are expected to be added to the /docs/ directory and then combined for the release.

I have been lax in documenting this. I will try to get that done soon, if not I can tell Steven how to do it.

> Having to name the release notes with the PR number means you can't have the right filename until after you create the PR. Is there a better way to get around this?

Yes, that's true. You could use the issue number. The filename is inconsequential, so you can really name it whatever you want.
