### ISSUE TITLE
Write script to create file with explicit subclass assertions and include output in release package

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#744]
The task here is to generate explicit subclass assertions from our distinctionary pattern (equivalent class + intersection). @marksem has already raised this concern but I can't find an existing issue for it. If it exists we can close one as a duplicate.

The rationale is that the subclass assertions are needed by many tools - e.g., SHACL with RDFS reasoning turned on (turning on OWL reasoning to interpret the intersections results in an untenably large performance hit), RDFox, etc. 

The best way to handle this is to add a function to onto_tool. Rather than just generating it in a release package, it would be helpful to have in the repo for development purposes, as above. The easiest way to manage that is by adding it to the pre-commit hook.

**Comment by justin2004** [comment]
see also #714

**Comment by rjyounes** [comment]
Closing: duplicates #714.
