### ISSUE TITLE
Update release process instructions wrt bundle.yaml and listing .md files

### ISSUE THREAD

**Issue by Jamie-SA** [semanticarts/gist#748]
I noticed that in the bundle.yaml file you have to explicitly list all markdown files that you want converted to HTML. I reviewed the Confluence page and it mentions that markdown files get converted, but it probably should state explicitly that the bundle.yaml file needs to be reviewed and updated if any new markdown files are added. This is mostly likely to happen within the migration directory as new version migrations are added.

While it would be better to not have to keep that list updated every release, I think that would require leaving them as .md files or making a change to onto-tool (I have submitted an issue in that repo about this but have no idea if/when that change might happen).

**Comment by rjyounes** [comment]
Done.
