### ISSUE TITLE
Fix issue with gist logo

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#750]
Get the path in the README right so that it works both on GitHub and the README in the release package. In previous versions it was `![gist logo](gist.png)` but now that doesn't work, so I've used the GitHub upload path instead. That means that `README.html` in the release package points to the image on GitHub, which isn't ideal. Need to look at previous versions to see how it was done.

**Comment by Jamie-SA** [comment]
I am not seeing the logo image in this repo. It seems to me that you either put the logo in this repo or you link to an externally hosted URL.

My Suggestion:
- add the logo to the top level of repo
- update bundle.yml to move logo to Documentation directory during the release bundling
- change the README.md to reference the local logo file

If agreed to, I will submit a PR for these changes.
