### ISSUE TITLE
Term naming convention - should `gist:_USDollar` be `gist:_UnitedStatesDollar`...?

### ISSUE THREAD

**Issue by pmcb55** [semanticarts/gist#755]
I'm just curious really, but I stumbled across the Named Individual  `gist:_USDollar`, and was wondering if that name conforms to the current gist naming convention?

I've seen a number of issues discussing the naming convention over the years (and I'm sure there were probably more!):
 - https://github.com/semanticarts/gist/issues/20
 - https://github.com/semanticarts/gist/issues/188
 - https://github.com/semanticarts/gist/issues/227

From what I can glean from those discussions and resolutions, shouldn't `gist:_USDollar` really be `gist:_UsDollar`, or maybe better expanded as `gist:_UnitedStatesDollar`...?

I do note in #20 the exception for `gist:ID`: "**_Exception: Keep ID - NB its defined as word in Merriam-Webster in all-caps_**" - I don't think the cost of needing to be aware of this exception is worth it, even in the case of ID, but regardless, I assume this `gist:_USDollar` isn't an example of _another_ exception, is it...!? (i.e., once you let in one pesky exception, then... :) !)

It does raise another question though - the gist homepage states, "**_We have been working on a “best practice” style guide for our ontology projects_**", but I can't seem to find that guide - is it publicly available, or is it still a work-in-progress...?

**Comment by uscholdm** [comment]
This is an old term due for an update to conform to current conventions.

**Comment by rjyounes** [comment]
@pmcb55 The style guide is available in the repository here: https://github.com/semanticarts/gist/blob/develop/docs/gistStyleGuide.md.

All of the gist instances violate the naming convention for instances in that they lack the infix indicating type. For the remainder of the local name, it specifies:

"The name of the instance, with spaces and hyphens replaced by underscores (no camelcasing) and only alphanumeric characters and underscores allowed."

Unlike classes, there is no camelcasing of acronyms, and there is no guidance about whether to spell out abbreviations or not. So `UsDollar` is ruled out, and I prefer the more colloquial `USDollar` to `UnitedStatesDollar` (I've never heard that said).

Note that classes have different conventions, so camelcasing is indeed stipulated across the board, with `ID` being the sole exception. I don't like the exception, and I agree with you about slippery slopes, but history won out.

**Comment by rjyounes** [comment]
One might ask why there are different conventions for ontology resources on the one hand, and instances on the other. I'm not sure I know the answer. Maybe because we're trying to capture something that already has a name, in the latter case.

**Comment by uscholdm** [comment]
In this case it wojdl makes sense to just have _USD after the midfix. It is a standard abbreviation and we often use IDs as parts of IRIs for things like currency, or country etc.
