### ISSUE TITLE
Correct definition of gist:occupiesGeographically

### ISSUE THREAD

**Issue by stevenchalem** [semanticarts/gist#757]
For gist:occupiesGeographically, the skos:definition is "A thing occupies are region". I think this can be improved.

However it's not clear to me whether "occupies" is intended to convey simply that the thing is located at or within the Place, or whether it implies something stronger like having exclusive use. Examples: "this restroom is occupied" or "the guest who occupies this room."

**Comment by uscholdm** [comment]
@stevenchalem Good catch. 
Closing because it is made moot by #941
