### ISSUE TITLE
New model for units and magnitudes

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#759]
This is a spin-off of issue #451. That issue includes lengthy discussion which may serve as background but is largely out-of-date. The latest proposals and discussion will be attached to this issue.

**Comment by philblackwood** [comment]
Slides illustrating a few key ideas:
Enterprise scale 
Measurement vs Specification
Explicit property to say what characteristic(s) a unit measures (e.g. meter measures distance)
[UoM Concepts 2022-10-12.pptx](https://github.com/semanticarts/gist/files/9964284/UoM.Concepts.2022-10-12.pptx)

**Comment by philblackwood** [comment]
We could advertise a value-added ability to provide a client with a standard list of Aspects to use for a given discipline, harvested from QUDT (with attribution). For example, for Acoustics:

Acoustics Absorptance
Acoustics AcousticImpedance
Acoustics AngularFrequency
Acoustics AngularWavenumber
Acoustics AttenuationCoefficient
Acoustics CharacteristicAcousticImpedance
Acoustics Density
Acoustics Dissipance
Acoustics EquivalentAbsorptionArea
Acoustics Frequency
Acoustics GroupSpeedOfSound
Acoustics LogarithmicFrequencyInterval
Acoustics MechanicalSurfaceImpedance
Acoustics Period
Acoustics PhaseCoefficient
Acoustics PhaseSpeedOfSound
Acoustics PropagationCoefficient
Acoustics Reflectance
Acoustics ReverberationTime
Acoustics SoundEnergyDensity
Acoustics SoundExposure
Acoustics SoundExposureLevel
Acoustics SoundIntensity
Acoustics SoundParticleAcceleration
Acoustics SoundParticleDisplacement
Acoustics SoundParticleVelocity
Acoustics SoundPower
Acoustics SoundPowerLevel
Acoustics SoundPressure
Acoustics SoundPressureLevel
Acoustics SoundReductionIndex
Acoustics SoundVolumeVelocity
Acoustics SpeedOfSound
Acoustics StaticPressure
Acoustics TimeAveragedSoundIntensity
Acoustics Transmittance
Acoustics Wavelength
Acoustics Wavenumber

**Comment by philblackwood** [comment]
We should be able to harvest reference data from QUDT (with attribution) to identify which standard units measure which characteristics. Sample of preliminary results:

"Ampere per Joule" | "measures" | ElectricCurrentPerUnitEnergy
"Ampere per Square Metre" | "measures" | ElectricCurrentDensity
"Ampere per Square Meter" | "measures" | ElectricCurrentDensity
"Ampere per Radian" | "measures" | ElectricCurrent
"Ampere Second" | "measures" | ElectricCharge
"Ampere Turn" | "measures" | ElectricCurrent
"Bar Per Bar" | "measures" | Dimensionless
"Becquerel" | "measures" | Frequency
"Coulomb" | "measures" | ElectricCharge
"Coulomb Metre" | "measures" | ElectricDipoleMoment
"Coulomb Meter" | "measures" | ElectricDipoleMoment
"Coulomb Square Meter" | "measures" | ElectricQuadrupoleMoment
"Coulomb Square Metre" | "measures" | ElectricQuadrupoleMoment
"Coulomb Square Metre Per Volt" | "measures" | Polarizability
"Coulomb Square Meter Per Volt" | "measures" | Polarizability
"Coulomb per Kilogram" | "measures" | ElectricChargePerMass
"Coulomb per Metre" | "measures" | ElectricChargeLineDensity
"Coulomb per Meter" | "measures" | ElectricChargeLineDensity
"Coulomb per Square Metre" | "measures" | ElectricChargePerArea
"Coulomb per Square Meter" | "measures" | ElectricChargePerArea
"Coulomb per Cubic Metre" | "measures" | ElectricChargeVolumeDensity
"Coulomb per Cubic Meter" | "measures" | ElectricChargeVolumeDensity
"Coulomb per Mole" | "measures" | ElectricChargePerAmountOfSubstance
"Square Coulomb Metre per Joule" | "measures" | Polarizability
"Square Coulomb Meter per Joule" | "measures" | Polarizability
"Cubic Coulomb Metre per Square Joule" | "measures" | CubicElectricDipoleMomentPerSquareEnergy
"Cubic Coulomb Meter per Square Joule" | "measures" | CubicElectricDipoleMomentPerSquareEnergy
"Quartic Coulomb Metre per Cubic Energy" | "measures" | QuarticElectricDipoleMomentPerCubicEnergy
"Quartic Coulomb Meter per Cubic Energy" | "measures" | QuarticElectricDipoleMomentPerCubicEnergy
"Candela" | "measures" | LuminousIntensity
"candela per square meter" | "measures" | Luminance
"candela per square metre" | "measures" | Luminance
"Candlepower" | "measures" | LuminousIntensity
"Degree Celsius" | "measures" | ThermodynamicTemperature
"Degree Celsius Per Kelvin" | "measures" | Dimensionless
"Diopter" | "measures" | Curvature
"Diopter" | "measures" | InverseLength
"Erlang" | "measures" | Dimensionless
"Farad" | "measures" | Capacitance
"Farad per Meter" | "measures" | Permittivity

**Comment by uscholdm** [comment]
I propose the following:
- Rename CoherentUnit to StandardUnit (have Coherent Unit be an altlabel)
- Remove Aspect from being a subclass of Category.  Aspects such as like length, or inner diameter or cycle time are not categorizing anything that I can think of.  
- UnitOfMeasure is a subclass of Magnitude
- Define StandardUnit to be a UnitOfMeasure that
  - has conversion=1
  - has itself as a standard unit
  - has a scopeNote indicating that this captures the idea of dimension
- Get rid of RatioUnit, RatioMagnitude, ProductUnit and ProductMagnutide
- Make it clear that there is a simple way to create new units.  This is currently supported in gist, no need to change anything
  - create the unit as a new instance of UnitOfMeasure
  - make sure it has a standard unit
  - make sure it has a conversion
- If there is a need to represent the internal structure of a unit, that can be done in two ways:
  - _The current method_: hard to create, easier to understand once created, hard for computer to do recursive computation.
    -	Create new subclass of Magnitude
    -  Create new subclass of UnitOfMeasure
    -  Use numerator, denominator, multiplier and multiplicand to show how to construct the new unit
  - _The current method (simplified)_: 
    - Create new subclass of Magnitude
    - Create new subclass of UnitOfMeasure
    - Specify a direct conversion to the standard unit
    - Do NOT bother with numerator, denominator, multiplier and multiplicand
 - _The vector exponent method_: this is used by QUDT. It is easier to create, harder for humans to understand but easier computationally

**Comment by rjyounes** [comment]
A couple of questions:

* We will have two classes, StandardUnit (now CoherentUnit) and BaseUnit, and we currently have two corresponding predicates as well. Can we simplify this, perhaps by combining the two predicates into one, as we did with conversion factors?
* What is the rationale for removing RatioUnit when they are a distinct type of unit? 
* Which approach to representing the internal structure of a unit do you advocate? We should have a preferred implementation that is both used in gist and included in our design patterns. Using both or all 3 would be even harder for humans, and perhaps also computers, to understand.

**Comment by uscholdm** [comment]
> * What is the rationale for removing RatioUnit when they are a distinct type of unit?

Is the number 10 a product (2*5) ? or is it a ratio (100/5)?  
Exact analogy holds with units. E.g. force can be a product of mass times acceleration, but acceleration is expressed as a ratio, so force could be expressed as a ratio too.   Thus, ratio unit vs. product unit is a meaningless syntactic distinction.

**Comment by uscholdm** [comment]
> * We will have two classes, StandardUnit (now CoherentUnit) and BaseUnit, and we currently have two corresponding predicates as well. Can we simplify this, perhaps by combining the two predicates into one, as we did with conversion factors?

That might be a good idea, I'll give it some thought.

**Comment by uscholdm** [comment]
> * Which approach to representing the internal structure of a unit do you advocate? We should have a preferred implementation that is both used in gist and included in our design patterns. Using both or all 3 would be even harder for humans, and perhaps also computers, to understand

I will recommend a simple approach. The details will become clear when I do the worked examples.

**Comment by rjyounes** [comment]
> Is the number 10 a product (2*5) ? or is it a ratio (50/5)?
Exact analogy holds with units. E.g. force can be a product of mass times acceleration, but acceleration is expressed as a ratio, so force could be expressed as a ratio too. Thus, ratio unit vs. product unit is a meaningless syntactic distinction.

Yes, I understood that, but you propose getting rid of both product and ratio units and magnitudes. Wouldn't we want to keep one of them?

**Comment by uscholdm** [comment]
> you propose getting rid of both product and ratio units and magnitudes. Wouldn't we want to keep one of them?

What exactly do you propose to keep? What are the use cases you have in mind?

**Comment by rjyounes** [comment]
The use cases would include those we already define: gistCore has Area and Volume. In addition, we've defined ratio units for currency/currency (e.g., discounts, exchange rates), duration/duration (e.g., hours worked per day), currency/time (for compensation), staff units/time (where staff units are an arbitrary unit used for time reporting) and so on in some of our sub-gists and client ontologies.

Given your proposal to eliminate both ratio and product units, how do you express values like 8 hours per day or $100K per year as a single number without loss of information?

**Comment by rjyounes** [comment]
I've discussed with Michael and he's clarified that he does not mean to eliminate the subclasses under `RatioUnit` and `ProductUnit`, only those classes themselves. Now it makes sense to me.

**Comment by rjyounes** [comment]
I'm really appreciating @philblackwood's separation of Magnitude from Aspect (or MeasureableCharacteristic) as I'm working with HR-related ontologies that define PayRate and BillingRate subclasses of a MonetaryPerDuration superclass. This conflates the types of magnitude (money over time) with the thing it's being used to measure. A side effect, in addition to confusion, is that you can't re-use money/time entities between the two. That is, the PayRate $200/hour is a distinct individual from the BillingRate $200/hour. (Of course, you could say it's of _both_ types, but then you're not using the classes to make a distinction, so why have them?) Instead, $200/hour is money-per-time resource, no matter what it's used to measure. 

The PayRate/BillingRate classes would be like defining subclasses of Extent: Length, Width, Height, Depth, Circumference, etc., which we do not do, for good reason.

**Comment by philblackwood** [comment]
Slides from 12/8 gist issue review outlining reference data (examples based on QUDT) and client data.

[for discussion 2022-12-08.pptx](https://github.com/semanticarts/gist/files/10188306/for.discussion.2022-12-08.pptx)

**Comment by uscholdm** [comment]
> We will have two classes, StandardUnit (now CoherentUnit) and BaseUnit, and we currently have two corresponding predicates as well. Can we simplify this, perhaps by combining the two predicates into one, as we did with conversion factors?

Yes, I'm glad you reminded me of that, I looked and see that I did that in my original draft several months ago.

**Comment by philblackwood** [comment]
clean version of reference data extracted from QUDT (change .txt suffix to .ttl)

[uomReferenceData.txt](https://github.com/semanticarts/gist/files/10471167/uomReferenceData.txt)

The data was pulled from the QUDT SPARQL endpoint, downloaded, modified slightly with UNIX scripts.

**Comment by philblackwood** [comment]
Slide deck with proposal and examples. See slides 6 and 7 for a simple before-after view.

[for discussion of Units Of Measure 2023-02-02.pptx](https://github.com/semanticarts/gist/files/10574248/for.discussion.of.Units.Of.Measure.2023-02-02.pptx)

**Comment by philblackwood** [comment]
Attached is "the gist of QUDT", a set of reference data extracted from QUDT (change the suffix .txt to .ttl)

[uomReferenceData.txt](https://github.com/semanticarts/gist/files/10900097/uomReferenceData.txt)


It is also loaded in Allegrograph at [
](https://agraph.semanticarts.com/#/catalogs/demo-catalog/repositories/pdb-UnitOfMeasureReferenceData)

**Comment by uscholdm** [comment]
@rjyounes 
I think this should be closed as duplicate of #697. Do you agree?

**Comment by rjyounes** [comment]
Closing - duplicates #697.
