### ISSUE TITLE
Distinctionary pattern for Units using RatioUnit or ProductUnit is redundant

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#76]
AreaUnit is defined to be a Product unit with multiplier and multiplicand both being a DistanceUnit. But having a multiplicand and a multiplier already gets you into the ProductUnit Class. It would be sufficient to say an AreaUnit is a UnitOfMeasure with the multiplier and multiplicand as above. In addition, it should have a hasStandardUnit link to gist:_square_meter.  

![image](https://user-images.githubusercontent.com/10777545/62255940-4c791680-b3b4-11e9-9010-1654becae4df.png)

Here is an example of what will be inferred to be a RatioUnit:
![image](https://user-images.githubusercontent.com/10777545/62256064-c27d7d80-b3b4-11e9-87fc-1ac407d246ba.png)

**Comment by rjyounes** [comment]
@uscholdm To review this issue and report back to the group at next meeting.

**Comment by uscholdm** [comment]
DECISION: leave it as is is.  Strictly this is redundant, but it does make it a bit clearer.
