### ISSUE TITLE
Deprecate isRecordedAt

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#762]
@mkumba observes that this is just a datetime value on a Posting object. 

If implemented, close #693.

**Comment by rjyounes** [comment]
Need more discussion with Dave. Jamie argues that it's a useful predicate in contexts where a Posting object is not being modeled.

**Comment by Jamie-SA** [comment]
Discussed the difference between date recorded at generation of some data versus the time it is posted into the database.

Heather & Phil offered to look into this more and get back to the group.

**Comment by uscholdm** [comment]
@philblackwood Have you had a chance to look into this?

**Comment by philblackwood** [comment]
This property is being used for our internal data. It is useful. I suggest we keep it.

**Comment by rjyounes** [comment]
I agree with @mkumba's proposal above.

**Comment by uscholdm** [comment]
> I agree with @mkumba's proposal above. Reopening for further discussion.

I do not see a proposal from Dave, what I see is an observation "that this is just a datetime value on a Posting object."

**Comment by rjyounes** [comment]
I interpret this as a proposal.

**Comment by uscholdm** [comment]
@rjyounes Can you clarify what is being proposed.

**Comment by rjyounes** [comment]
Not to speak for @mkumba, but what I understand is that he wants to remove the property. Whatever client ontology requires it should define a `Posting` class and add a date to it. I'm not sure whether Dave is proposing defining a `Posting` class in gist or not. I suggest removing the property and opening a separate issue for a `Posting` class if we think it's broadly applicable enough for inclusion in gist. 

> This property is being used for our internal data. It is useful. I suggest we keep it.

@philblackwood The question is whether internal data should be modeled differently; or the predicate could be removed from gist and defined in whatever ontology that is.

**Comment by philblackwood** [comment]
It sounds like the proposal is to use an Event to record the fact that something was "posted".

Triple patterns:

           posting event      records      thing 

           posting event      actualEndDateTime   xsd:dateTime

Yes, it makes sense. Add a property for "records" and possibly a subclass of Event for the action of posting.

It's a more accurate model of the world, because saying a Thing isRecordedAt a dateTime is not saying anything about the Event itself.

@mkumba is this what you are proposing? If so, I like it.

Note that the solution is still somewhat limited; ideally, we want to be able to record when triples were inserted or deleted so that history of the data can be re-created (like rewind).

**Comment by rjyounes** [comment]
Probably `atDateTime` rather than `actualEndDateTime`, but that's a detail.

However, after @Jamie-SA's explanation that it's used internally as metadata, as in a SQL create date/last modified date/etc., it seems most straightforward to keep the property. If that's what it is I agree to closing it.
