### ISSUE TITLE
gist:contributesTo is too similar to gist:produces

### ISSUE THREAD

**Issue by justin2004** [semanticarts/gist#764]
I think `gist:contributesTo` and `gist:produces` are too similar to be siblings (at the root of the obj prop tree).

I propose that we:
- delete `gist:contributesTo`
- create `gist:partiallyProduces`
- make  `gist:partiallyProduces` a sub prop of `gist:produces`
- give `gist:produces` the alt label "contributes to"
    - I read that label as "contributes to the existence of" which is why I think `gist:partiallyProduces` can replace `gist:contributesTo` 

Some of the parts of a system partially produce the goal/function of the whole system.
The system partially produces the goal/function of the whole system.
The system + its environment (fully) produces the goal/function of the whole system.

**Comment by justin2004** [comment]
Maybe we also need `gist:fullyProduces` as a sub prop of `gist:partiallyProduces`.

**Comment by rjyounes** [comment]
In my mind, "The parts of a system contribute to the goal/ function of the whole system" is not the same as "produces." An engine contributes to the goal/function of a car, but it does not produce the car.

**Comment by justin2004** [comment]
> An engine contributes to the goal/function of a car,

Agreed.

> but [an engine] does not produce the car.

Of course, but the goal/function of a car is not the car.

**Comment by rjyounes** [comment]
... so we still have a use for `contributesTo`. I don't think we want to have to materialize the goal/function of a car just to state that an engine contributes to the functioning of a car.

**Comment by justin2004** [comment]
Isn't the engine `gist:isPartOf` the car?

**Comment by rjyounes** [comment]
That too, but it's more than that.

**Comment by uscholdm** [comment]
Some of the ideas posed here make sense, ontologically. To add something to gist requirements a higher bar. There needs to be use cases that are likely to arise often in a variety of enterprises.  

For example, a property like `fullyProduces` or `partiallyProduces` could be useful in a special situation. Less likely to have widespread application.

**Comment by justin2004** [comment]
I think the current thing that needs attention is the fact it isn't clear enough when to use `gist:contributesTo` and not `gist:produces` (and vice versa).

**Comment by Jamie-SA** [comment]
> I propose that we:
>     * create `gist:partiallyProduces`
>     * make  `gist:partiallyProduces` a sub prop of `gist:produces`
> 
> Some of the parts of a system partially produce the goal/function of the whole system. The system partially produces the goal/function of the whole system. The system + its environment (fully) produces the goal/function of the whole system.

This suggestion seems to create less useful information for a knowledge graph. With `gist:partiallyProduces` there is no indication of what contribution the subject provides to the outcome. Maybe it would be better to subdivide what is being produced so that you can say with more clarity and more information, what it actually being produced by the subject.

**Comment by uscholdm** [comment]
On many occasions I have used a property that i called 'facilitates' which is close in meaning to 'contributes to'.  Subgoals facilitate goals, subfunctions facilitate functions. People facilitate events (not in the sense of overseeing/running).   Technologies and techniques facilitate the achievement of goals. E.g. consistent naming conventions facilitate ontology clarity.

**Comment by justin2004** [comment]
@Jamie-SA 
> Maybe it would be better to subdivide what is being produced so that you can say with more clarity and more information, what it actually being produced by the subject.

When that is possible with the information/data that is available, I agree. But often data don't have that much clarity.

e.g. data like this is common
```
{"event name" : "Sally's Wedding" ,
  "event staff: ["Bob","Fred","Alice","Wanda"],
  "sub events": ["Rehearsal Dinner", "Ceremony","Reception"]
}
```
We know the staff members each partially produce the services of the event but we don't know exactly who did what.

**Comment by Jamie-SA** [comment]
> We know the staff members (at least) partially produce the services of the event but we don't know exactly who did what.

Sounds like `gist:contributesTo`, not `gist:produces`. But I'm not sure I'd model it that way if I wanted to know who the `gist:hasParticipant` were to the event of producing the event of the wedding.

**Comment by rjyounes** [comment]
If commit a change to gist, I am contributing to gist, but it's a stretch to say I produced gist; gist existed long before my contributions. Unless you want to split hairs and say I (along with others) produced the exact state of gist as it exists after my commit. I think that's too fine a point.

**Comment by justin2004** [comment]
> If I commit a change to gist, I am contributing to gist, but it's a stretch to say I produced gist

I think it is fair to say that your commit partially produces gist.
The first commit to the gist repo partially (perhaps fully) produced gist and the Nth commit partially produced gist.

Basically I think "contributes to" is really "partially produces."
Making a contribution is partially/fully producing something. It is confusing to keep them both around.

**Comment by Jamie-SA** [comment]
> Basically I think "contributes to" is really "partially produces." Making a contribution is partially/fully producing something. It is confusing to keep them both around.

Sounds like you are saying that "partially produces" is "contributes to". So why bother changing it? Just because you have a particular vocabulary preference isn't that compelling of a reason to me if you aren't going to change any definitions.

I don't find having both "contributes to" and "produces" is confusing.

I still think there are use cases where "contributes to" is more appropriate that "partially produces". If I let a high school group use my garage to build a float, did I partially produce the float? I don't think so. But I did contribute to the project. If I donate money to an local independent film project, did I partially produce the film? I don't think so. But I did contribute to the project. Etc.

**Comment by justin2004** [comment]
> Just because you have a particular vocabulary preference isn't that compelling of a reason to me if you aren't going to change any definitions.

I don't have a personal vocabulary preference but I do have a goal that gist should nudge users to the appropriate obj props. It is hard for gist to do that if it has very similar obj props as siblings the root level.

It's not that I especially like "partial production" but I think gist should build upon its primitives when possible, right? Since `gist:produces` already exists an option is to build upon it by making a sub prop of it which we could call `gist:partiallyProduces` (in the spirit of building upon the primitives). 

> If I let a high school group use my garage to build a float, did I partially produce the float?

The `gist:Task` the group performed in your garage `gist:produces` the float.

> If I donate money to an local independent film project, did I partially produce the film?

The `gist:Event` of you putting money somewhere `gist:partiallyProduces` the film.


Maybe the thing to do here is to delete `gist:contributesTo` and just elaborate on the definition of `gist:produces` so that it includes full production and partial production.


before:
```turtle
gist:produces
	a owl:ObjectProperty ;
	skos:definition "The subject creates the object."^^xsd:string ;
	skos:example "A task produces a deliverable."^^xsd:string ;
	skos:prefLabel "produces"^^xsd:string ;
	.
```

after:
```turtle
gist:produces
	a owl:ObjectProperty ;
	skos:definition "The subject creates the object but the subject need not be fully responsible for the creation."^^xsd:string ;
	skos:example "A task produces a deliverable; An event partially produces an artifact."^^xsd:string ;
	skos:prefLabel "produces"^^xsd:string ;
	skos:altLabel "partially produces"^^xsd:string ;
        skos:altLabel "contributes to"^^xsd:string ;
	.
```

**Comment by justin2004** [comment]
Thinking about this more... I see two independent dimensions for produces/contributesTo...

Did the thing in the object position exist already?
- If a `gist:Function` is in the object position then the answer can be yes.
- If a `gist:Building` is in the object position then the answer can be no.

Is the subject fully responsibility for the production of the object? 
- If a `gist:Task` is in the subject position then the answer can be yes.
- If a `gist:Artifacts` is in the subject position then the answer can be no (sometimes it takes multiple artifacts to produce something).

**Comment by uscholdm** [comment]
> Maybe the thing to do here is to delete `gist:contributesTo` and just elaborate on the definition of `gist:produces` so that it includes full responsibility production and partial responsibility production.

I disagree. I think Jamies examples make a compelling case for different uses.

**Comment by rjyounes** [comment]
I'm with Jamie and Michael on this one.

**Comment by justin2004** [comment]
> I think Jamies examples make a compelling case for different uses.

Jamie's example tried to directly connect (with 1 edge) himself to the production of a float and the production of a film. It turned out that the excessively causal `gist:contributesTo` allowed him to do that. gist isn't doing its job if you can connect an arbitrary pair of things with a single edge.

`gist:contributesTo` offers so little constraint that you could use it to connect pairs of things for significantly different reasons. Why don't we attempt to formalize its `skos:definition`: "The parts of a system contribute to the goal/ function of the whole system"?

If we do then a `gist:Person` likely can't appear in the subject position.

**Comment by uscholdm** [comment]
> `gist:contributesTo` offers so little constraint that you could use it to connect pairs of things for significantly different reasons. Why don't we attempt to formalize its `skos:definition`: "The parts of a system contribute to the goal/ function of the whole system"?
> 
> If we do then a `gist:Person` likely can't appear in the subject position.

Then it becomes awkward to say that Rebecca contributes to the development of gist. People contribute to all kinds of things.

**Comment by justin2004** [comment]
> People contribute to all kinds of things.

Sure, but gist can't let each person be _directly_ connected to the thing they contribute to and at the same time expect ontology users to arrive at consistent representations.

I think this is close to how I would say that Rebecca contributes to gist:

```turtle
:task0 gist:hasParticipant :Rebecca .
:task0 a gist:Task .
:task0 gist:produces :commit0 .
:commit0 gist:goesToPlace :repository0 .
:repository0 skos:prefLabel "Github repository for gist" .
:repository0 gist:hasAddress :addy0 .
:addy0 gist:containedText "git@github.com:semanticarts/gist.git" .
```

If someone wants to _directly_ connect Rebecca to repository then they could define an obj prop:
```turtle
ex:contributesTo  owl:propertyChainAxiom  ( [ owl:inverseOf gist:hasParticipant ]  gist:produces gist:goesToPlace ) .
```

This way the direct connection is just a name for a more principled connection.

**Comment by uscholdm** [comment]
> This way the "direct" connection is just a name for a more principled connection.

There is much truth in what you say. The challenge is to decide when all the details of the more principled connection are ever going to matter in practice.  Our usual approach is Einsteinien: as simple as possble, but no simpler.  Start simple. If all the stuff that makes a more principled connection turns out to be necessary to achieve specific practical goals, then it can be extended. The original simple approach can then be formally defined as you say.

**Comment by justin2004** [comment]
> Our usual approach is Einsteinien: as simple as possble, but no simpler. Start simple.

I agree with that. I just think the gist primitives are what decides how much granularity is needed. Although you can always name things built from gist primitives for more terse looking representations.

Once it is decided that gist is going to be used and a domain of interest is selected then the resultant RDF should just be a consequence of gist and the domain of interest. If too much priority is given to "what are the _known_ uses of the data" then we don't get the atomicity of representation that yields serendipity, the ability to speculate based on analogy, the harmonization of different domains, etc. 

If too much priority is given to "what are the _known_ uses of the data" then we get application-centric data dressed in RDF.

**Comment by rjyounes** [comment]
Designing a usable ontology involves a balance between top-down and bottom-up approaches. BFO takes a top-down approach, and is an ontology that no one actually uses (even if they claim to) because it is too abstract and doesn't help model anything in the real world.

Translating existing data directly to an OWL data model is a fully bottom-up approach. You get an ontology but not one that can provide new insights into existing data or connect it to other data. Library of Congress's BIBFRAME is such an ontology: it is almost a literal translation of MARC into RDF.

gist aims to strike a balance. It is not attempting to find the ontological underpinnings of the universe, or even of all of human behavior. It provides enough abstraction to unify unruly data under a common data model that is, as Michael says, as simple as required but no simpler (roughly Occam's razor, which was postulated about 700  years before Einstein). We do not look at common use cases because we are enslaved by existing data, but because we want to provide an ontology that is both practically useful and conceptually sound.

**Comment by pmcb55** [comment]
Hi Rebecca - I love your positioning of gist in that comment :) !

I've bookmarked your comment for my own personal future reference, but I'd recommend weaving your comment back into the current gist web page (i.e., what's on the gist web page already is good, but your expansion here really gives it weight - in particular your references to past attempts at the extremes of the Top-Down and Bottom-Up approaches, thereby beautifully positioning gist as a '**_practical_** _middle-ground_').

**Comment by rjyounes** [comment]
Thanks, Pat, I'm glad you found this helpful. BTW, we are about to post a rewritten version of the web page, though in terms of the core concepts above it's mostly unchanged.

**Comment by justin2004** [comment]
> Gist has a small number of top level concepts from which everything else derives

Agreed.

And I am proposing that a `contributesTo` predicate can be derived. Something like:

> ex:contributesTo  owl:propertyChainAxiom  ( [ owl:inverseOf gist:hasParticipant ]  gist:produces gist:goesToPlace ) .

That makes it more likely that different users of gist will arrive at consistent representations of the same situation.

**Comment by uscholdm** [comment]
@rjyounes @jamie @justin2004 
SUMMARY: This was a long conversation bringing up a variety of interesting points.  
- there are a number of interesting relationships between contributing to something and producing things.
- we could tease them all out, but that is out of scope for gist
- excellent examples making clear that contributesTo is significantlhy different from produces are provided by Jamie below:

> If I let a high school group use my garage to build a float, did I partially produce the float? I don't think so. But I did contribute to the project. If I donate money to an local independent film project, did I partially produce the film? I don't think so. But I did contribute to the project.

PROPOSAL: close this issue and leave things as they are.
See also #765

**Comment by rjyounes** [comment]
Agreed - closing.
