### ISSUE TITLE
Remove distinction between Intergovernmental Organization and Treaty Organization

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#766]
According to [Harvard Law School](https://hls.harvard.edu/bernard-koteen-office-of-public-interest-advising/about-opia/what-is-public-interest-law/public-service-practice-settings/international-public-interest-law-practice-setting/intergovernmental-organizations-igos/):

The term intergovernmental organization (IGO) refers to an entity _created by treaty_, involving two or more nations, to work in good faith, on issues of common interest. In the absence of a treaty an IGO does not exist in the legal sense. For example, the G8 is a group of eight nations that have annual economic and political summits. IGOs that are formed by treaties are more advantageous than a mere grouping of nations because they are subject to international law and have the ability to enter into enforceable agreements among themselves or with states...Among the oldest IGOs are the [United Nations](http://www.un.org/en/), which replaced the League of Nations, the [Universal Postal Union](http://www.upu.int/), and the [North Atlantic Treaty Organization](http://www.nato.int/cps/en/natolive/index.htm) (NATO).

Other sources agree:

[Duke Law School](https://law.duke.edu/ilrt/int_orgs_1.htm): "International governmental organizations (or IGOs) are _associations of states established by a treaty_ to pursue the common aims of their member states. An intergovernmental organization has a legal personality separate from its member states, and can enter into legally binding agreements with other IGOs or with other states. The [United Nations](http://www.un.org/) and the [Organization of American States](http://www.oas.org/) are examples of international governmental organizations.
The other category of international organization is the non-governmental organization (or NGO). NGOs are made up of private citizens. NGOs do not enter into treaties or other international agreements. The [World Wildlife Fund](http://www.worldwildlife.org/), [Greenpeace](http://www.greenpeace.org/international/) and [Amnesty International](http://www.amnesty.org/) are examples of non-governmental organizations."

(Note the interesting distinction between IGOs and NGOs.)

[Wikipedia](https://en.wikipedia.org/wiki/Intergovernmental_organization): "An intergovernmental organization or intergovernmental organisation, also known as an international institution, is an organization composed primarily of sovereign states, or of other organizations _through formal treaties_ for handling/serving common interests and governed by international laws."

(All emphases mine.)

It appears that "International Governmental Organization" is the most commonly used term, as opposed to "Treaty Organization."

**Comment by rjyounes** [comment]
Fix wtih #756.

**Comment by Jamie-SA** [comment]
If we remove "Treaty Organization" maybe add a altLabel on IntergovermentalOrganization of "Treaty Organization"?

**Comment by Jamie-SA** [comment]
DECISION:
- remove class TreatyOrganization
- Change prefLabel of IntergovernmentalOrganization to "Intergovernmental Organization". See #756

**Comment by rjyounes** [comment]
Other to-dos:
* Add a regional example
* Update `skos:definition` to clarify that we mean to encompass both international organizations such as the UN and regional organizations such as the MTA.

**Comment by rjyounes** [comment]
@DanCarey404 Please include the fix for issue #756 in this PR.

**Comment by hmoore-sa** [comment]
Sorry for the delay- got busy and accidentally left this one off the radar. Will have the PR out at latest by the end of Monday, 10/17 with the following:

1. Deprecate TreatyOrganization in favor of parent class.
2. Update skos:Example of IntergovernmentalOrganization to "The United Nations, the European Union, the MTA (Metropolitan Transit Authority)"
3. Update skos:Definition to "An organization whose members are government organizations. This can comprise regional, municipal, state/province, or national level entities."
4. Changing prefLabel from: "Inter-Governmental Organization to "Intergovernmental Organization" (resolves 756).
