### ISSUE TITLE
Should gist:Language be a subclass of Category?

### ISSUE THREAD

**Issue by Jamie-SA** [semanticarts/gist#769]
I am thinking that the instances of gist:Language is probably a taxonomy. Should it be a subclass of Category?

**Comment by justin2004** [comment]
There are ways to classify languages -- by whether they are natural or constructed, by the phones they have, by their lineage, by the grammatical categories they have (tense, aspect, etc.), etc. 

The taxonomies I see are things like `LanguageByLineage`, `LangaugeByPhonesEmployed`, and `LangaugeByGrammticalGategoriesEmplyed`. But outside of things like that I am not sure how to make a singular `Language` taxonomy.

**Comment by Jamie-SA** [comment]
This issue is not about how to make a Language taxonomy. I am sure different use cases would probably come up with different answers.
I don't think gist should be concerned about how implementers might want to organize/classify languages, just whether instances of Language would/should be part of a taxonomy and therefore maybe a subclass of gist:Category.

**Comment by uscholdm** [comment]
If a language such as English is a category, then what is it categorizing?  I think 
nothing, in particular.  So, out of the gate, there is no reason to model it as a category.  By contrast, the concept of a mammal exists only by virtue of it categorizing animals.  Being non-exempt is a category of employee.   

It might be tempting to say:

`ex:_Book_HundredYearsOfSolitude gist:isCategorizedBy ex:_Language_Spanish .` 
But what does that really mean? This approach seems to be implying the existence of categories such as: 
- things written in the English language
- things written in the Spanish language

But Spanish is just a language, not per se a category of book. We could as easily conceive of this category:
- things authored by Dave McComb 
and create this triple:
`ex:_Book_SoftwareWasteland gist:isCategorizedBy ex:_Author_DaveMcComb .`

But languages and people are not categories.  A more direct way to express these things is:
`ex:_Book_SoftwareWasteland gist:isAuthoredBy ex:_Person_DaveMcComb .`
`ex:_Book_HundredYearsOfSolitude gist:isExpressedIn ex:_Language_Spanish .`

If you have your heart set of making a category for each human language, it would be semantically sound to say:
```
ex:ThingsWrittenInALanguage a owl:Class ; rdfs:subClassOf gist:Category .
ex:_ThingsWrittenInALanguage_Spanish a ex:ThingsWrittenInALanguage
ex:_Book_HundredYearsOfSolitude gist:isCategorizedBy  ex:_ThingsWrittenInALanguage_Spanish .
```
Note that gist:Language includes all natural and artificial, technical and non-technical languages. FOr simplicity, I stuck with human natural langauges.

**Comment by uscholdm** [comment]
> I don't think gist should be concerned about how implementers might want to organize/classify languages, just whether instances of Language would/should be part of a taxonomy and therefore maybe a subclass of gist:Category.

This sort of thing has been a source of confusion and indecision for a while.  If something is treated like a taxonomy, and it is managed like a taxonomy, then there is a temptation to feel compelled to model it as a taxonomy.  That generally means:
- create a subclass of `gist:Category` (e.g. Status, Language)
- mint the instances of the new category class in the `...x` namespace.
- use `gist:isCategorizedBy` to connect things to instances of that subclass

This just came up today with a client ontology. Things have a `Purpose`, and usually they are selected from a small enumerated list. So it has all the trimmings of a category, except that `Purpose` is semantically a subclass of gist:Goal.  You can use a purpose as if it is a category, but it is not a category per se, so making Purpose a subclass of gist:Category may be ontologically incorrect.  Whether something is or is not a category is not always clear. But there is nothing to stop you from using the `...x` namesapce. 

INTERESTINGLY: a large region hierarchy at one of our clients was being managed just like all the other taxonomies, and it became irritating and inconvenient to be minting instance of region in the `...d` namespace, so they are now minting them in the `...x` namespace.  This does not make the regions categories, and the links to regions are made using properties other than  `gist:isCategorizedBy`.

**Comment by rjyounes** [comment]
To echo some of what was said above: We can speak about languages in many different ways, including their relationships to one another, to other things, and their internal structure.

When we think of a language taxonomy I believe we are generally thinking of a language family tree, which is a perfect example of a broader/narrower hierarchical taxonomy. But there are other language-language relationships that cannot be captured by such a taxonomy, such as:

- There was a large influx of French vocabulary into English during the Norman invasion
- By some measures Arabic is a more difficult to learn as a second language than Spanish

Languages relate to other types of things in numerous ways, including people, countries, organizations, media, social services, social structure:
- John speaks English natively and German as a second language
- Standard German is the official language of Germany and Austria
- This book was originally written in German but has been translated into English
- The film is in German with English subtitles
- The product manual is written in 17 different languages
- Translators are available at the DMV for Spanish, Korean, and Mandarin

Linguistic structure:
- English has approximately 44 phonemes and exactly 26 letters
- German nouns and adjectives have three grammatical genders and 4 cases

My sense is that the second type of relationship would come up most commonly in the contexts we deal with, and the others rarely if at all, but you never know.

So as Michael and Justin have pointed out, defining Language as subclass of Category limits what we can say about language and languages. However, I will add that Michael's proposal about how you might define languages as categories and still represent more complex relationships by defining classes such as `ThingsWrittenInALanguage` will not allow you to make connections between languages in one context and another. Michael's example:

```
ex:ThingsWrittenInALanguage a owl:Class ; rdfs:subClassOf gist:Category .
ex:_ThingsWrittenInALanguage_Spanish a ex:ThingsWrittenInALanguage
ex:_Book_HundredYearsOfSolitude gist:isCategorizedBy  ex:_ThingsWrittenInALanguage_Spanish .
```
But what if I want to say that `ex:_Book_HundredYearsOfSolitude` was written in the same language that is the official language of Spain, and that that language is the native language of Gabriel Garcia Marquez. I now have three categories that are entirely unrelated to one another, where I should be able to point to a single thing, Spanish, that has various relationships to other things:

```
ex:_ThingsWrittenInLanguage_Spanish
ex:_OfficialLanguage_Spanish
ex:_ThingsSpokenByPerson_Spanish
```

(Sorry if that was meant as a straw man, Michael.)

Re the fact that `gist:Language` also includes languages that are not natural human languages such as systems for programming or formal logic: I think there are so different that we should not use the same class for both. Interestingly, Wikipedia has a [disambiguation page for "Language"](https://en.wikipedia.org/wiki/Language_(disambiguation)) which contrasts natural human languages with other types of "languages." I don't see enough common ground to usefully combine them in the same class. Even the definition of `gist:Language` as "A recognized, organized set of symbols and grammar" is not applicable to human language with any degree of accuracy.

**Comment by uscholdm** [comment]
@Jamie-SA @rjyounes @justin2004 
PROPOSAL: close this issue.  The subclass relationship has very strong semantics. It means every single language in every conceivable circumstance is a category. We are a long way from agreeing on that.
