### ISSUE TITLE
Implement conventions for repository branching and tagging

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#77]
Every release should have a tag, for those wishing to check out a specific release version rather than the latest on master. I do not see, for example, a tag for the latest release 9.0.0.

In software development there is typically a maintenance branch created from master at the point of release, for patch versions containing bug fixes that get released before new versions. (These need to be merged onto the main develop branch as well so they are not lost in the next major/minor release. It is less clear that that is desirable or useful for ontology development, but may be worth considering. 

There should be a develop branch for development, merged to master at the time of a release. develop should be the default branch used for merges and commits.

**Comment by Jamie-SA** [comment]
There is now a develop branch that is set to be the default branch.

**Comment by Jamie-SA** [comment]
I am supposed to tag the release for 9.0.0. Do we have a tag format defined?

Maybe: v9.0.0

**Comment by rjyounes** [comment]
That works for me. Version 8 was just tagged "8.0.0" but I prefer your suggestion. I wonder if this is something that needs group approval. You could just go ahead and do it and then change it if someone doesn't objects.

**Comment by rjyounes** [comment]
Yes, there's now a develop branch, created after I added this issue. We've established the rest of the procedures I proposed, so once the tag is created you can close this.

**Comment by Jamie-SA** [comment]
v9.0.0 is tagged.
And I noticed version 8.0.0 was tagged as v8.0.0

See my #140 about whether there should be a v9.0.1
