### ISSUE TITLE
should `gist:isCharacterizedAs` be a subprop of `gist:isCategorizedBy`?

### ISSUE THREAD

**Issue by justin2004** [semanticarts/gist#770]
I think `gist:isCharacterizedAs` is a specialization of  `gist:isCategorizedBy` where the domain and range are fixed.
Whereas `gist:isCategorizedBy` doesn't fix the domain and range.

**Comment by uscholdm** [comment]
> I think `gist:isCharacterizedAs` is a specialization of `gist:isCategorizedBy`

If anything, it is the reverse. One way to characterize something is to say what category it is in. There are possibly many other ways. However, we might not need `gist:isCharacterizedAs` - I've never found a use case for it.  

Ironically, `gist:isCharacterizedAs`  is uncharacteristic of most gist properties, by having a very narrow domain and range. That goes against our guidelines.  If we keep  `gist:isCharacterizedAs` I hitnk it shoujld have no domain  or range and should be a supeproperty of `gist:isCategorizedBy`.

**Comment by justin2004** [comment]
> I think it should have no domain or range and should be a supeproperty of gist:isCategorizedBy.

I'd be happy with that as well, @uscholdm .
I think they likely belong in the same prop hierarchy (not top level siblings). 

I was just using the presence of domain and range to be a cue that this is a specialization. Also `isCharacterizedAs` has "categorize" in its `skos:defintion`.

Also the `skos:definition` on `gist:isCharacterizedAs` seems to be backwards:
"A way to categorize a behavior."
While the domain is `gist:Event` and the range is `gist:Behavior`.
So I'f say that the Event is categorized by the Behavior -- the Behavior isn't being categorized.

**Comment by rjyounes** [comment]
I agree, the current definition seems a complete anomaly. I'd be in favor of dropping it, as you initially suggest, @uscholdm. What is the use case when `isCategorizedBy` is not appropriate?

**Comment by uscholdm** [comment]
> Also the `skos:definition` on `gist:isCharacterizedAs` seems to be backwards:
> "A way to categorize a behavior."

That's true. This is an ancient definition, needs to be updated if we keep the property.

**Comment by uscholdm** [comment]
PROPOSAL: delete the property `isCharacterizedAs` because it is historical and was never used, to my knowledge. The narrow domain and range are also historical, we don't do that these days. The main purpose it serves is to enable Event to have some axioms.  That is not a super-compelling reason.

```
gist:Event
	a owl:Class ;
	owl:equivalentClass [
		a owl:Restriction ;
		owl:onProperty gist:isCharacterizedAs ;
		owl:someValuesFrom gist:Behavior ;
	] ;


gist:isCharacterizedAs
	a owl:ObjectProperty ;
	rdfs:domain gist:Event ;
	rdfs:range gist:Behavior ;
	owl:deprecated "true"^^xsd:boolean ;
	skos:definition "A way to categorize a behavior."^^xsd:string ;
	skos:prefLabel "is characterized as"^^xsd:string ;
	.
```

**Comment by rjyounes** [comment]
We have deprecated the property in PR #951, so the issue is irrelevant.
