### ISSUE TITLE
Remove or expand range of gist:conformsTo

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#773]
Range is `gist:Intention`. Definition is "The subject conforms to the Object, e.g. meet an obligation, meet terms of an offer, adhere to a specification." `gist:Intention` is not a superclass of `gist:Obligation`. So one or the other is incorrect.

**Comment by uscholdm** [comment]
`gist:Obligation` is a subclass of `gist:Intention`, by inference.

![image](https://user-images.githubusercontent.com/10777545/201436438-ba346971-d709-477b-85e6-40a94d410c66.png)

**Comment by rjyounes** [comment]
Thanks, I didn't think to check that. Closing the issue.
