### ISSUE TITLE
Integrate new rdf-toolkit option to remove NamedIndividual assertions into gist workflow

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#774]
`rdf-toolkit` provides a new option to suppress named individual assertions. These are added by Protege and we would like to eliminate them from gist. The option is:

```
-sni,--suppress-named-individuals       suppresses all instances of owl:NamedIndividual
```

Integrating this option into our workflow involves:
* Download the new version of `rdf-toolkit` into the `tools` directory
* Update `serialize` action in `bundle.yaml`
* Update `serialize` shell script

I'm also going to move all the serializer files into a subdirectory `tools/serializer`.

**Comment by rjyounes** [comment]
In progress, waiting for EDM Council to release the change and distribute a new jar file.

**Comment by rjyounes** [comment]
EDM Council has released a new version 1.14.1, but I still cannot get it to work and have sent test files to them. [See rdf-toolkit issue #28](https://github.com/edmcouncil/rdf-toolkit/issues/28).

**Comment by Jamie-SA** [comment]
@stevenchalem as the release manager has offered to help look into this with some help from a more experienced person.

**Comment by rjyounes** [comment]
I've already made some progress with this so I'll continue with it. The issue so far is that EDM Council released a version that is supposed to remove the named individuals but so far hasn't worked. I can consult with Steve to see if he can give it a try, as maybe I've missed something.

**Comment by rjyounes** [comment]
EDM Council has released a new version that they believe fixes the problem. I will do some testing and hopefully be able to close this issue out. @stevenchalem I think I'm all set with this one. I'll let you know if I could use some help.
