### ISSUE TITLE
3 terms missing `rdfs:isDefinedBy` triples

### ISSUE THREAD

**Issue by pmcb55** [semanticarts/gist#775]
I'm writing some basic Best Practice-checking code, and in the process I noticed that there are just 3 terms (from the 289 terms in gist) that are missing `rdfs:isDefinedBy` triples, namely:
- `gist:_day`
- `gist:_millisecond`
- `gist:_minute`

I assume this is just a minor oversight (as the other 14 `owl:NamedIndividual` instances do include that triple). And it's easy to fix up by just adding the missing triples.

**Comment by dylan-sa** [comment]
I looked into this and found the issue. When generating the `rdfs:isDefinedBy` assertions, onto-tool has two settings--a default 'strict' setting and an 'all' setting. With the strict mode enabled, it only adds the assertions for entities that belong to certain classes (including `owl:Thing`). These three duration units are missing explicit `owl:Thing` type assertions, which caused them to be filtered out. Adding the missing `owl:Thing` assertions will resolve the issue for future releases.

**Comment by Jamie-SA** [comment]
In the discussion for PR #783 it looks like instead of adding `owl:Thing` assertions, @rjyounes suggested changing the onto_tool config to address this issue.

> Modify our bundle.yaml file to use `all` rather than `strict`. Are there any negative consequences to doing so?

**Comment by stevenchalem** [comment]
@Jamie-SA @dylan-sa Should we keep this in the Feb. release?

**Comment by Jamie-SA** [comment]
This sounded easy... but I can't see a way to get the current version of the onto_tool to use the `all` mode. The way we are currently adding the definedBy property does not support the `all` option, and the only action that does is the `export` which looks like it does other things we don't want.

To get this functionality it looks like a change to the onto_tool would be required.

So I guess maybe we move this to the next release.

**Comment by rjyounes** [comment]
We'll do this as a short-term workaround until onto_tool is fixed.

**Comment by Jamie-SA** [comment]
Fixed in PR #927 but not closed because this isn't the default branch. So I'm closing it now.
