### ISSUE TITLE
Contingent Event should not have restrictions on planned datetimes

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#776]
The equivalence axiom on `ContingentEvent` is:

```
gist:ContingentEvent
	a owl:Class ;
	owl:equivalentClass [
		a owl:Class ;
		owl:intersectionOf (
			gist:Event
			[
				a owl:Restriction ;
				owl:onProperty gist:hasMagnitude ;
				owl:someValuesFrom gist:Percentage ;
			]
			[
				a owl:Restriction ;
				owl:onProperty gist:plannedEndDateTime ;
				owl:someValuesFrom xsd:dateTime ;
			]
			[
				a owl:Restriction ;
				owl:onProperty gist:plannedStartDateTime ;
				owl:someValuesFrom xsd:dateTime ;
			]
		) ;
	] ;
```
If the event which the contingent event is dependent on does not have planned dates, the contingent event cannot have planned dates. One might specify some time interval after the primary event's date, but not actual dates. 

We should consider the additional restriction also used on `ContingentObligation`:

```
rdfs:subClassOf
[
    a owl:Restriction ;
    owl:onProperty gist:isTriggeredBy ;
    owl:someValuesFrom gist:Event ;
] ;
```

**Comment by justin2004** [comment]
> One might specify some time interval after the primary date, but not actual dates.

We don't have a way express time intervals (a `gist:Duration` tethered to datetimes on one or both ends), do we?

We mention time intervals in the `gist:Duration` example and scope note though.
I think we should consider adding something like `Interval` and considering using that in this restriction. 
e.g.

```turtle 
			[
				a owl:Restriction ;
				owl:onProperty gist:plannedEndDateTime ;
				owl:someValuesFrom owl:unionOf ( `Interval` `gist:DateInstant` ) ;
			]
```

Oh, I see gist used to have `gist:TimeInterval`.

Deleting this restriction feels like a consequence of not having the primitive (`TimeInterval`) to ground it.

Also I know `gist:DateInstant` is gone as well. I wonder if we could meet in the middle by adding a new structured literal for Time Intervals. Something like a sibling to xsd:dateTime but in the gist namespace.

**Comment by rjyounes** [comment]
When I said "One might specify some time interval after the primary date, but not actual dates" I _meant_ "might," and not that it should be a restriction. I don't think it's a requirement.

Can you please create a new issue for your proposals about date instant and time interval? They do not, strictly speaking, refer to this issue.

**Comment by uscholdm** [comment]
> If the event which the contingent event is dependent on does not have planned dates.

Agreed

**Comment by rjyounes** [comment]
Decision:

```
gist:ContingentEvent
	a owl:Class ;
	owl:equivalentClass [
		a owl:Class ;
		owl:intersectionOf (
			gist:Event
			[
				a owl:Restriction ;
				owl:onProperty gist:hasMagnitude ;
				owl:someValuesFrom [
					a owl:Restriction ;
					owl:onProperty gist:hasUnitOfMeasure ;
					owl:hasValue gist:_percent ;
				] ;
			]
			[
				a owl:Restriction ;
				owl:onProperty gist:isTriggeredBy ;
				owl:someValuesFrom gist:Event ;
			]
		) ;
	] ;
	skos:definition "An event with a probability of happening in the future, and dependent upon some other event or condition."^^xsd:string ;
	skos:example "Sell 20 shares of stock in company X when the price drops below $200/share";
	skos:prefLabel "Contingent Event"^^xsd:string ;
	.
```

**Comment by mkumba** [comment]
I think the canonical example and what ought to be in the definition is the event that triggers some indemnity.  The death benefit payout on a life insurance policy is the death of a very specific person.  Fire insurance is contengent on a particular building burning down.
