### ISSUE TITLE
Landmark should not be a subclass of PhysicalIdentifiableItem

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#781]
A landmark can be a place which is not a discrete physical object, such as a cemetery or battle site.

**Comment by uscholdm** [comment]
That's a fair point, if we start with the term 'landmark' and ask what it might mean. So if we care most about the term and want it to include cemeteries, then it needs to be not a subclass.  If we care more about the intended meaning, and if the intended meaning was to indeed be a subclass of PhysicalIdentifialeObject, then we leave the definition as it is and decide what to do about the term. Options include:
1. leave it as it is and have a scopeNote clarifying that this is a narrow interpretation of 'landmark'
2. change the term from 'landmark' to something else. I cannot think of anything at the moment.

In any event, landmark is less a kind of a thing that could have inclusion criteria, and more how a thing is used (e.g. to give directions).  A fire hydrant is not fundamentally a Landmark, but it can be used as one. In that sense, its a role class.  Every tree in every forest could be a landmark, but relatively few trees are ever used as landmarks, for example:  ([the lone tree](https://www.hmdb.org/m.asp?m=108122)).

This makes me wonder if we need this class at all.

M.

**Comment by rjyounes** [comment]
Funny, I changed my mind after reading dictionary definitions and thought I didn't submit the issue. Most definitions say something along the lines of "A landmark is a recognizable natural or artificial feature used for navigation, a feature that stands out from its near environment and is often visible from long distances. In modern use, the term can also be applied to smaller structures or features, that have become local or national symbols." (Wikipedia)

Merriam-Webster, Cambridge English Dictionary, Collins, Dictionary.com, Macmillan, ... are all in agreement.

**Comment by rjyounes** [comment]
I've closed this - @uscholdm please add a new issue if you want to pursue removal of the class. I'm in favor. I wonder if anyone's ever used it.
