### ISSUE TITLE
Consider restoring gist:TimeInterval

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#786]
This predates my tenure at SA, but as I understand it `TimeInterval` was removed because it can be represented by start and end dates on an event - e.g., the time interval in which an event took place is represented as a start and an end date.

But what if we want to represent a time interval _per se_ - e.g., the 18th century, or Monday, Jan 9, 2023 - and also object to modeling anything with dates as an event? (Some of us argue strenuously against this model, others for.) 

`gist:Duration` is defined as "One week (or seven days), but not Jan 1, 2008 to Jan 7, 2008 [sic] (which is an interval)."

My guess was that this was written before `gist:TimeInterval` was removed, but nevertheless the distinction is valid: a table has a height of 12 inches and a sink has a width of 12 inches - 12 inches is the magnitude. Similarly, the 18th century had a duration of 100 years but is not itself 100 years. 

If we are not going to restore the `TimeInterval` class, I would like guidance on how to model these concepts.

**Comment by justin2004** [comment]
I also think TimeInterval is useful.

Recently I had to think about expressing when a particular Intention was formed/created.
I knew it had to be after the event when this organization (company) was created. I also knew it had to be before the software artifact was deployed to satisfy that Intention. I needed to refer to a creation TimeInterval that I could put bounds on.

**Comment by DanCarey404** [comment]
I'm not objecting to the re-addition of gist:TimeInterval.  But to answer @rjyounes' question: you could create a TimeInterval class in your client's namespace.
IIRC, one reason the TimeInterval class was removed was because of an inability on our part to define its relationship to the Event class.  This is a dragon to slay if we are to reintroduce TimeInterval into gist, IMO.

**Comment by rjyounes** [comment]
@DanCarey404 I have defined `TimeInterval` in the client's namespace, but I think it would be useful in gist. 

Maybe you're right about the other consideration. Those whose tenure predates mine will need to offer their recollections.

@uscholdm has an excellent example of the difference between `Event` and `TimeInterval`: If I attended a concert from 7-9pm last night, someone may reasonably ask me "How did you enjoy the concert?" but not "How did you enjoy the time interval from 7-9pm last night?"

Admittedly, there may be fuzzier cases. It would be helpful to think of some examples. 

We have slain one dragon: dates are no longer a necessary condition for events, much less a sufficient one (see [PR #777](https://github.com/semanticarts/gist/pull/777) and [issue #760](https://github.com/semanticarts/gist/issues/760). In contrast, dates are certainly necessary to a time interval, though I would argue still not sufficient: contracts, licenses, and passports typically have start and end dates, and I sure don't want to model these as a TimeInterval attached to the object.

**Comment by rjyounes** [comment]
Dan: We removed it because it was causing confusion. Doesn't mean you shouldn't declare it in a client project, but might not support putting it back in gist.

Mark: Was confusing when we had TimeInstant, but maybe not so much now. If you put it in a client ontology, where would you put it in the gist class hierarchy?

Dan: There was also confusion with Event. Was the first quarter of 2023 an event or a time interval? I think it's a time interval.

Jamie: Should Event be a subclass of TimeInterval?

Dylan: Analogous to GeoSpatial concept. TimeInterval is a temporal space that an event can unfold in, just like it can unfold in a geographical space.

Dave: We do tend to need it, especially for accounting. The problem is once you have it to differentiate it from events.

DECISION: Add class TimeInterval.

**Comment by rjyounes** [comment]
The second scope note is unnecessary in the context of an enterprise ontology. Likewise, the examples need to be updated to be relevant in an enterprise context. You have to remember that Treasury of Lives is an outlier.

**Comment by dhurlburtusa** [comment]
For IBB (i.e., IKG), we used the following:

```turtle
ibbeo:TimeInterval
	a owl:Class ;
	skos:definition "An interval of time."@en ;
	skos:prefLabel "Time Interval"@en ;
	skos:scopeNote "There are many methods to define a time interval. It can be defined between two points, from a starting point plus a duration, and others. Subclasses dictate which method is being used."@en ;
.

ibbeo:TimeIntervalFromPointToPoint
	a owl:Class ;
	rdfs:subClassOf
		ibbeo:TimeInterval ,
		[
			a owl:Restriction ;
			owl:onProperty gist:startDateTime ;
			owl:cardinality "1"^^xsd:nonNegativeInteger ;
		] ,
		[
			a owl:Restriction ;
			owl:onProperty gist:endDateTime ;
			owl:cardinality "1"^^xsd:nonNegativeInteger ;
		] ,
	;
	skos:definition "A time interval defined between two points in time."@en ;
	skos:prefLabel "Time Interval (point-to-point)"@en ;
	skos:scopeNote "The `gist:startDateTime` is intended to be inclusive. The `gist:endDateTime` is intended to be exclusive. For example, 2000-01-01T00:00:00 to 2001-01-01T00:00:00 spans the entire year of 2000 and does not include any time within 2001."@en ;
.

 ibbeo:TimeIntervalFromStartPointForDuration
 	a owl:Class ;
 	rdfs:subClassOf
 		ibbeo:TimeInterval ,
 		[
 			a owl:Restriction ;
 			owl:onProperty gist:startDateTime ;
 			owl:cardinality "1"^^xsd:nonNegativeInteger ;
 		] ,
 		[
 			a owl:Restriction ;
 			owl:onProperty gist:hasMagnitude ;
 			owl:cardinality "1"^^xsd:nonNegativeInteger ;
 		] ,
 	;
 	skos:definition "A time interval defined from a starting point plus a duration."@en ;
 	skos:prefLabel "Time Interval (point-plus-duration)"@en ;
 .
```

Other subclasses could be made for other time interval definitions. The above two use absolute date times and are bounded but maybe one needs to model relative and/or unbounded time intervals.

**Comment by kchastain703** [comment]
So for some better examples, 
"Jan 1, 2001 - Dec 31, 2001; fiscal year 2023; a five-year warranty period agreed to on Dec 31, 2022."

and I like the idea of having both of those definitions for subclasses of Time Interval based on how they're defined.

**Comment by uscholdm** [comment]
> So for some better examples,
"Jan 1, 2001 - Dec 31, 2001; fiscal year 2023; a five-year warranty period agreed to on Dec 31, 2022."

> and I like the idea of having both of those definitions for subclasses of Time Interval based on how they're defined.

One can do this by having independent equivalentClass expressions. 
1. Anything with a start time and an end time is a time interval and vice versa 
2. anything with a start time and a duration is a time interval and vice versa
3. anything with an end time and a duration is a time interval and vice versa

The following all describe exactly the same time interval.
1. starts at 2pm 1Jan2023 and ends at 4pm 1Jan2023
2. starts at 2pm 1Jan2023 and is 2 hours long
3. ends at 2pm 1Jan2023 and is 2 hours long

Note that the precision should not be in the definition I suggest to replace
`skos:definition "A span of time bounded by absolute start and end dates."`
with 
`skos:definition "A contiguous span of time on a time line that is uniquely defined by knowing any two of start time, end time, and duration."`
`skos:scopeNote "The week starting at midnight on 1Jan2023 is a time interval lasting exactly 168 hours. A week is just a duration, not a time interval."^^xsd:string ; `

**Comment by uscholdm** [comment]
I suggest adding an example along the lines of:
"The week starting at midnight of January 12, 2023. It lasts exactly 168 hours."
