### ISSUE TITLE
Don't limit gist:containedText to Text subjects

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#790]
There is no formal limitation, but the definition is "Links to the string corresponding to Text."

It's not only `Text` objects that can have `containedText` - e.g., Addresses and other types of `Content` can. (Or should `Address` actually be a subclass of `Text` rather than `Content`? - though the point about `containedText` still applies.) Just because `Content` is not limited to `Text` doesn't mean it wouldn't be valuable to use `containedText` for its text.

**Comment by uscholdm** [comment]
The change has been done #989.  The current version is:

```
gist:containedText
	a owl:DatatypeProperty ;
	rdfs:range xsd:string ;
	skos:definition "A string that is closely associated with an individual."^^xsd:string ;
	skos:example
		"The string associated with a tag."^^xsd:string ,
		"The string associated with text content."^^xsd:string
		;
	skos:prefLabel "contained text"^^xsd:string ;
	gist:domainIncludes
		gist:Tag ,
		gist:Text
		;
	.
```
See also #594
