### ISSUE TITLE
Should isBasedOn be transitive?

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#791]
If a task, for example, is based on a task template, then aren't its subtasks also based on that template, even if there are sub-templates that they are more directly based on?

**Comment by dylan-sa** [comment]
If I've got it right, the principle seems correct: In general, if `:_task gist:isBasedOn :_task_template`, `:_subtask gist:isBasedOn :_subtask_template`,  and `:_subtask_template gist:isPartOf :_task_template`, then `:_subtask gist:isBasedOn :_task_template`. 

I think `isBasedOn` is probably not transitive, though. Examples like this come to mind: Suppose Novel A takes some characters from Novel B, so Novel A is based on Novel B. And suppose Novel B borrows the author's prose style from Novel C, so Novel B is based on Novel C. It's not necessarily the case that Novel A is based on Novel C in any sense.

**Comment by rjyounes** [comment]
Good example. @dylan-sa Do you think it would be useful for gist to add a transitive predicate with the meaning of "is based on"? That might cause confusion, though.

**Comment by dylan-sa** [comment]
It does seem like it could be useful if that kind of inference behavior is commonly expected or desired. 

One of the examples in the annotations is 'A metric computing the average income of a population **is based on** the metric for individual income.' Seems like in this kind of context, where there is a chain of mathematical calculations based on each other, we might expect transitivity. I would be curious to hear if there are other common use cases where transitivity is expected. Figuring out a good name for the transitive version might be tough--the inverse phrasing of `isTransitiveBasisFor` doesn't sound too bad.

**Comment by rjyounes** [comment]
I don't like `isTransitiveBasisFor`, because the SKOS convention of `broader` and `broaderTransitive` means something different: the former is a subproperty of the latter, so that any triple `A broader B` implies `A broaderTransitiveB` - I.e., it automatically triggers the transitive chain. Moreover, by convention `broaderTransitive` is never asserted. I think it would be confusing to use this naming pattern in an entirely different way.

We can probably come up with a reasonable name if we agree on the principle of introducing such a predicate.

**Comment by rjyounes** [comment]
Closing due to examples from @dylan-sa above. Not worth thinking about a transitive version unless we find a use case.
