### ISSUE TITLE
pre-commit hook not running

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#794]
PR #788 may have introduced a bug whereby the pre-commit is no longer running. I thought I had tested the change to rdf-toolkit.jar both manually, by running `serialize.sh`, and as a pre-commit hook, and everything was working at the time I merged to develop.

@stevenchalem Would you mind having a look by trying to commit a file on a branch that has a syntax error? This is how I found just now that it wasn't running.

**Comment by Jamie-SA** [comment]
@rjyounes I am working on a PR to add a feature to the pre-commit hook and it would change things slightly. I can test that if you want and create a fix if needed.

**Comment by rjyounes** [comment]
OK, thanks.
