### ISSUE TITLE
Should `gist:requires` be transitive?

### ISSUE THREAD

**Issue by rasmi** [semanticarts/gist#799]
(Similar to #791)

I am trying to model relationships between different processes which require differing subsets of information. 

So A requires B, C, and D. D requires E, F, and G. 
It is fair to say that A also requires E, F, and G in my situation. I can use `gist:is part of`/`gist:has part`, but they do not quite capture the meaning of being required for a given process. I can also create a subproperty of `gist:is part of`/`gist:has part` that indicates a required part, but this seems like overloading the relationship. There are other approaches I can take, but a tree of requirements would be ideal.

**Comment by uscholdm** [comment]
There are some cases where transitivity seems appropriate, but the word require has many different varaitions in specific meaning.  I would be wary of repeating the mistake from partof.   My thumb is part of me, who is part of an organization. But my thumb is not part of an organization, in any useful sense.

Nothing comes immediately to mind, but I don't think it would be too hard to find similar examples where transitivity of requires breaks down.

**Comment by rasmi** [comment]
That's helpful, thank you! I will consider other representations.
