### ISSUE TITLE
Update imports in gistCore to include all gist ontologies

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#80]
An rdfs:comment on the gistCore ontology states: "gistCore convenience for including all of gist." However, not all the gist ontologies are directly imported. Are we relying on indirect imports, or is it just out of date? It would be better if gistCore explicitly imports all the ontologies in case recursive imports change; it also allows a reader to see all the gist ontologies rather than following a thread of imports.

**Comment by uscholdm** [comment]
There is a tradeoff here. Adding all ontologies is redundant given import is transitive, but it can be handy to have them all there. FIBO went back and forth on this and decided to have all of the imports in each ontology, not relying on import chains.

**Comment by marksem** [comment]
Agree that since gistCore says it imports "all of gist", that it should explicitly import all rather than rely on transitive imports.  Less error-prone if intermediate imports change.

**Comment by uscholdm** [comment]
I was surprised to see this closed. I thought we agreed to NOT depend on transitive closure of imports. While gistCore lists all of the imports, other ontologies do not.   Why are we relying on transitive import in some cases but not others?

**Comment by rjyounes** [comment]
It was fixed in 9.2.0.

**Comment by uscholdm** [comment]
I just downloaded the 9.2.0 ontologies from our web site. Only gistCore imports all ontologies. Many of the others rely on transitive import.  Do you want me to open a separate issue on this, since technically this issue was only about gistCore?

**Comment by rjyounes** [comment]
If you think it should be done then go ahead and create a separate issue. If you look up at the top at the issue description and discussion, it was only meant to apply to gistCore.
