### ISSUE TITLE
Shorten geo predicates

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#812]
Some of us think the shift to more explicit, but longer, predicates in gist 11 was overkill. The proposal is to go back to something like (without inverses, which are eliminated in #506):

* geoContains
* geoOccupies
* geoOccupiesPermanently 

However, the occupies predicates are considered for removal in issue #809.

**Comment by uscholdm** [comment]
'geoContains' has been removed. We now use `isGeographicallyContainedIn`. So presumably, the proposal is to
- rename `isGeographicallyContainedIn` to `isGeoContainedIn`

I think it is a reasonable proposal. One downside is the risk of our flip-flopping too much with  name changes for tidiness reasons resulting in major releases. It could be a nuisance to our users.

**Comment by rjyounes** [comment]
Yes, that's the proposal. I realize the flip-flopping is unappealing, but we provide migration scripts with major versions to ease the burden of renaming.

**Comment by rjyounes** [comment]
Combine with #1070

**Comment by rjyounes** [comment]
The `occupies` predicates will be removed as per issue #809, now captured in https://github.com/semanticarts/gist/issues/947#issuecomment-1679565100.
