### ISSUE TITLE
Deprecate isCharacterizedAs

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#820]
This is narrower version of `isCategorizedBy` (though not defined as a subproperty),  with domain `Event` and range `Behavior`. The latter is a subclass of `Category`. The definition of the predicate is "A way to categorize a behavior." I don't see any reason to define a special predicate.

**Comment by uscholdm** [comment]
I agree that we do not need a property with the current meaning of `characterizedAs`.

**Comment by rjyounes** [comment]
DECISION: Deprecate.
