### ISSUE TITLE
Fix definitions of hasNumerator, hasDenominator, hasMultiplier, hasMultiplicand

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#821]
In [gist 11.0.0](https://github.com/semanticarts/gist/issues/160) we removed the domains and ranges of these properties but neglected to change the text definitions. 

The definitions we currently have could be examples, but not definitions. 

E.g., `hasNumerator` is defined as "Relates a RatioUnit such as meter(s)/second to the numerator Unit (e.g. meter)."
`hasMultipler` is defined as "Relates a ProductUnit such as square mile to the first of two units multiplied together (e.g. mile)."

**Comment by uscholdm** [comment]
DECISION: Fix per above recommendation.

**Comment by rjyounes** [comment]
Postpone to do with new units and measures model.

**Comment by rjyounes** [comment]
@philblackwood How does this fit into the new units and measures model?
