### ISSUE TITLE
The github action for PRs is failing and needs to be fixed

### ISSUE THREAD

**Issue by Jamie-SA** [semanticarts/gist#827]

**Comment by Jamie-SA** [comment]
I've released a new version of onto_tool that looks to have fixed this problem. I'll wait until the next PR is made to verify before closing this issue.

**Comment by rjyounes** [comment]
@Jamie-SA Is this the CI error we've been getting for a while?

**Comment by Jamie-SA** [comment]
It was the error we were getting. I think it has been fixed since I posted that comment.
I think this is done now.

**Comment by rjyounes** [comment]
You're right, it is fixed. Closing.
