### ISSUE TITLE
Identify a standard set of annotation properties 

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#85]
Overlaps but is broader than #17 and #68. I propose identifying a standard set of annotation properties and no others be used in term definitions, and also defining usage conventions (e.g., one example per skos:example). Proposed initial set:
- rdfs:label (or skos:prefLabel)?
- skos:definition
- skos:example
- skos:changeNote
- skos:scopeNote

**Comment by rjyounes** [comment]
Many tools are reliant on rdfs:label, rdfs:comment.

Proposal: use skos:definition etc., have ontology-toolkit generate another file with rdfs:comment, etc.

**Comment by rjyounes** [comment]
I propose they also be language-tagged.

**Comment by rjyounes** [comment]
Message thread in Teams:

```
[7/20 12:29 PM] Michael Uschold
    
To my knowledge, we always use rdfs:isDefinedBy (a sub property of rdfs:seeAlso) to point to the ontology that defines the resource.  Do we have an annotation property that we use by convention to point to the source of the definition e.g. Wordnet, Investopedia etc.  often this will be string-valued, so bein a subproperty of seeALso will not work -- its range is rdf:Resource. 


[7/21 7:24 PM] Boris Pelakh
I have used skos:note (or even skos:editorialNote, depending on the content) for this sort of thing. Or make it part of the skos:definition.

[7/30 5:55 PM] Rebecca Younes
 I'd prefer a specific annotation in order to provide a specific meaning or function, rather than just a bucket to dump things in. This is the problem with rdfs:comment to an even larger degree. I will take this into consideration in issue #85 
```

**Comment by rjyounes** [comment]
Replace rdfs:comment with one or more of:
skos:definition
skos:scopeNote
skos:example
skos:editorialNote - just for future editors, doesn't affect users' understanding

Don't use:
skos:changeNote
skos:historyNote
skos:note

**Comment by rjyounes** [comment]
This is a decision made with no impact on the ontology itself until it is implemented.

**Comment by rjyounes** [comment]
Based on input on issue #351 from @tedhills  and @vberkel, I suggest an expansion of the approved annotations by adding skos:altLabel and rdfs:seeAlso. As mentioned in a comment there, I do not like the use of skos:hiddenLabel because it is application-oriented. The full list would now look like this:

rdfs:label:
- Replace with skos:prefLabel.
- Use skos:altLabel where relevant.

Replace rdfs:comment with one or more of:
- skos:definition
- skos:scopeNote
- skos:example
- skos:editorialNote - just for future editors, doesn't affect users' understanding
- rdfs:seeAlso

Don't use:
- skos:changeNote
- skos:historyNote
- skos:note

These changes need to be discussed in the next review session.

**Comment by uscholdm** [comment]
I don't think `rdfs:seeAlso` adds anything. It's nearly identical in meaning to `skos:note`, very generic. See my comment in issue https://github.com/semanticarts/gist/issues/351
I think there are a few cases where `changeNote`, `historyNote` or `skos:note` could be useful. So I'd recommend limited use rather than no use.  Slight variation to @rjyounes proposal:

Stop using rdfs:comment and rdfs:label. Instead use:

Labels:
- `skos:prefLabel`
- `skos:altLabel`

Comments: 
- `skos:definition`
- `skos:example`
- `skos:scopeNote`
- `skos:editorialNote` - just for future editors, doesn't affect users' understanding

Limited use:
- `skos:historyNote` (occasionally for things that have been around for a long time)
- `skos:changeNote` (rarely, since should be in release notes)
- `skos:note` (rarely if ever, if no more specific note is available and not want to create yet another annotation property)

Another things that has come up in recent projects is the source of a definition.  FIBO made extenseive use of this (I forget what property they  used).  I have introduced a new sub-property of `skos:note` the annotation property `:definitionSourcedFrom` for this purpose. It can point to a URL of a standards web site, or a dictionary, or just text.

**Comment by Jamie-SA** [comment]
I disagree with the statement that rdfs:seeAlso does not add anything, it is the only term (annotation) we are currently looking at that specifically refers to something else to provide additional information.

**Comment by tedhills** [comment]
@Jamie-SA ditto. I use rdfs:seeAlso extensively.

**Comment by rjyounes** [comment]
Some discussion on this topic has leaked over to #351, which is actually about implementation. The discussion of which properties to adopt should continue here.

**Comment by rjyounes** [comment]
On issue #351, @uscholdm states:

"The something else (according to the range of the property) is always an rdf:Resource, which includes rdf:Literal. According to that, here is a legitimate triple:

gist:Intention rdfs:seeAlso "What one intends to do"^^xsd:string
While there is no indication in the documentation, it could be that the intended use is for the object of a seeAlso triple (whether a URL or literal) to be a pointer to something else. That would make sense and would distinguish it from skos:note.

We could decide to use rdfs:seeAlso this way.
It would mean that skos:note should NOT be a subproperty of rdfs:seeAlso."

The example you give is *not* a legitimate use of rdfs:seeAlso if one respects the semantics provided in the definition. "What one intends to do" does not refer to a resource that can provide additional information about the subject resource. 

Since skos:note is not defined as a subproperty of rdfs:seeAlso, this strikes me as a non-issue.

**Comment by uscholdm** [comment]
@Jamie-SA and @tedhills both  use rdfs:seeAlso extensively. 

QUESTION: do you always use it so that the object of the triple always points to something specific, as I described above? That would make it a more restrictive usage than is specifically stated in the W3C documentation.

**Comment by tedhills** [comment]
@uscholdm Good point that even a literal is a resource. I hadn't picked up on that. Lacking that insight, I had restricted my use of :seeAlso to be just IRIs, either of other resources in the same ontology, other resources in other ontologies, or Web pages.

Regardless of the nature of the object of the :seeAlso property, I've always interpreted :seeAlso as having the same significance as a "See Also" reference on a Linux man page. (For an example of this, "see also" (yuk yuk) the See Also section at the bottom of [the Linux man page on grep](https://linux.die.net/man/1/grep).) It's just a pointer to related items. For example, when I am defining a financial instrument in the Morgan Stanley Research Ontology, I will use :seeAlso to reference closely related instruments that might not be easily found in the ontology.

I still well remember my days of learning UNIX at Bell Labs, where chasing the "See Also" references helped me find what I was really looking for, and taught me a lot.

skos:note just doesn't communicate the same thing as skos:seeAlso. Even if a skos:seeAlso property contaned mere text, one would expect it to provide additional illuminating information that is not properly part of a skos:definition or any of the other skos annotations.

**Comment by uscholdm** [comment]
@tedhills said: 

> skos:note just doesn't communicate the same thing as skos:seeAlso.

> Even if a skos:seeAlso property contained mere text, one would expect it to provide additional illuminating information that is not properly part of a skos:definition or any of the other skos annotations.

Yes, I can see that, from a common sense perspective.  Unfortunately, its not in the documentation.

**Comment by rjyounes** [comment]
We can stipulate in the style guide that we use rdfs:seeAlso only with non-literal objects, but I think we ought to leave it open to both web pages and RDF resources. I.e., the style guide can state not only "we will use this property" but also "we will use this property _as follows_:...".

**Comment by tedhills** [comment]
@rjyounes agreed

**Comment by rjyounes** [comment]
Stop using rdfs:comment and rdfs:label. Instead use:

Labels:

skos:prefLabel
skos:altLabel

Comments:

skos:definition
skos:example
skos:scopeNote
skos:editorialNote - just for future editors, doesn't affect users' understanding
rdfs:isDefinedBy (automatically inserted)
rdfs:seeAlso (can be URI or literal)


Limited use - style guide should define appropriate circumstances.

skos:historyNote (occasionally for things that have been around for a long time)
skos:changeNote (rarely, since should be in release notes, but users are not always looking at release notes. Use, e.g., to describe rationale)
skos:note (rarely if ever, if no more specific note is available and not want to create yet another annotation property)

**Comment by rjyounes** [comment]
Closing, since decision has been reached. Implementation is covered in #351.
