### ISSUE TITLE
Update ontology IRIs, version IRIs,  and import IRIs in all gist ontologies

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#859]
Example for gistCore:

```
<https://w3id.org/semanticarts/gistCore>
	a owl:Ontology ;
	owl:versionIRI <https://w3id.org/semanticarts/gistCoreX.x.x> ;
	skos:definition "gist is a minimalist upper ontology created by Semantic Arts."^^xsd:string ;
	skos:prefLabel "gist"^^xsd:string ;
	sh:declare gist:_PrefixDeclaration_gist ;
	gist:license "https://creativecommons.org/licenses/by-sa/3.0/"^^xsd:string ;
	.
```

Sample for other ontology:

```
<https://w3id.org/semanticarts/gistMediaTypes>
	a owl:Ontology ;
	owl:imports <https://w3id.org/semanticarts/gistCoreX.x.x> ;
	owl:versionIRI <https://w3id.org/semanticarts/gistMediaTypesX.x.x> ;
	skos:definition "Definitions of IANA Media Types."^^xsd:string ;
	skos:prefLabel "gist Media Types"^^xsd:string ;
	gist:license "https://creativecommons.org/licenses/by-sa/3.0/"^^xsd:string ;
	.
```

**Comment by Jamie-SA** [comment]
Did you mean to leave off the `https:/` on that owl:import?

Jamie @
Semantic Arts
Semantics ✚ Knowledge Graphs ✚ Expertise
≃ more meaning from your data
     ✚ reduced complexity
     ✚ reduced costs

________________________________
From: Rebecca Younes ***@***.***>
Sent: Tuesday, May 23, 2023 8:43 AM
To: semanticarts/gist ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [semanticarts/gist] Update ontology IRIs and import IRIs in all gist ontologies (Issue #859)


Example for gistCore:

<https://w3id/semanticarts/gistCore>
        a owl:Ontology ;
        owl:versionIRI <https://w3id/semanticarts/gistCoreX.x.x> ;
        skos:definition "gist is a minimalist upper ontology created by Semantic Arts."^^xsd:string ;
        skos:prefLabel "gist"^^xsd:string ;
        sh:declare gist:_PrefixDeclaration_gist ;
        gist:license "https://creativecommons.org/licenses/by-sa/3.0/"^^xsd:string ;
        .


Sample for other ontology:

<https://w3id/semanticarts/gistMediaTypes>
        a owl:Ontology ;
        owl:imports </w3id/semanticarts/gistCoreX.x.x> ;
        owl:versionIRI <https:///w3id/semanticarts/gistMediaTypesX.x.x> ;
        skos:definition "Definitions of IANA Media Types."^^xsd:string ;
        skos:prefLabel "gist Media Types"^^xsd:string ;
        gist:license "https://creativecommons.org/licenses/by-sa/3.0/"^^xsd:string ;
        .


.

**Comment by rjyounes** [comment]
Copy-paste error. Fixed above.

**Comment by rjyounes** [comment]
Also added missing `.org`s.

**Comment by rjyounes** [comment]
I agree, but let's not do it for this release. We've been thinking about this before: https://github.com/semanticarts/gist/issues/682.

A couple of other license-related issues:  #244, #593. These could all be considered together, looks like there's some overlap.
