### ISSUE TITLE
Consider promoting gist:Us and gist:NotUs from accounting sub-gists to gist core

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#860]
Current definitions in gist accounting:

```
gist:NotUs
	a owl:Class ;
	owl:equivalentClass [
		a owl:Class ;
		owl:intersectionOf (
			[
				a owl:Class ;
				owl:unionOf (
					gist:Organization
					gist:Person
				) ;
			]
			[
				a owl:Class ;
				owl:complementOf gist:Us ;
			]
		) ;
	] ;
	skos:definition "All parties that are not us (potential counterparties)."^^xsd:string ;
	skos:prefLabel "Not Us"^^xsd:string ;
	.

gist:Us
	a owl:Class ;
        rdfs:subClassOf gist:Organization ;
	skos:definition '''Us (not USA) is the set of all entities we consider to be our company for the purpose of accounting. 
If A owes B some money, if A is in the set of "us" then this transactions is an accounts payable.  If B is in the set of "us" then its an accounts receivable.  If both are it is an intra-company transaction.  If neither, then it is just a statistic, perhaps some competitive intelligence.'''^^xsd:string ;
	skos:prefLabel "Us"^^xsd:string ;
	.
```
These have uses beyond accounting, so it's worth considering the pros and cons of promoting these into gistCore.

**Comment by uscholdm** [comment]
This makes sense for accounting, but in other applications one might wish to include data from more than one organization, so you need an approach that makes the perspective explicit.   I have done the following for various clients for internal vs. external organizations, not including persons.

Given a company called Pear, you can create classes called PearOrg and NotPearOrg as follows:
- PearOrg is the set of companies that includes Pear and any organization that is part (suborg) of Pear .  
- NotPearOrg  is the intersection of Organization and the complement of PearOrg.
- This requires creating an instance for the top level Pear organization and using it in a `hasValue` restriction.

If a new company is added to the mix called Lime, follow the same pattern.  No confusion with who 'Us' is.

From this I am leaning towards leaving Us and NotUs in gistAccounting.
