### ISSUE TITLE
Change the "master" branch to "main"

### ISSUE THREAD

**Issue by Jamie-SA** [semanticarts/gist#865]
New github repos start with a "main" branch and some (all?) of the sub-gists are now using that convention. It would be nice if all our repos are consistent with naming branch. Since we use gitflow branching and don't work directly on the "master/main" branch it probably won't be noticeable to most people working on gist.

**Comment by rjyounes** [comment]
I agree, it won't be noticeable. I would hold off until after the release of 12.0.0 just to make sure there's no confusion.

After the change is made, the [gist release management doc for ontologists](https://semarts.atlassian.net/wiki/spaces/OF/pages/1126760539/gist+Release+Management+Ontologists) should be updated.

**Comment by rjyounes** [comment]
Steps to update:
- Fetch the remote
- Track branch `main`
- Delete local branch `master`
