### ISSUE TITLE
Update website links per #816 (Follow-on to 12.0 release)

### ISSUE THREAD

**Issue by stevenchalem** [semanticarts/gist#870]
Task moved out of issue #816

**Comment by Jamie-SA** [comment]
@stevenchalem I am not sure which website links this issue is referring to. I have updated the gist webpage and think all of those links are correct now. Is there anything else that you know of?

**Comment by rjyounes** [comment]
@stevenchalem Can we get a response on this and either close the issue or clarify what needs to be done? Thanks.

**Comment by stevenchalem** [comment]
@Jamie-SA It all looks correct to me now except for one tiny thing. On `https://www.semanticarts.com/gist/`, the link to
 `https://w3id.org/semanticarts/ontology/gistCore` displays as `https://w3id.org/semanticarts/ontology/gistcore` (with a lower-case C).

**Comment by stevenchalem** [comment]
Closing this issue because it does not affect the release per se, and because it's tiny.

**Comment by rjyounes** [comment]
The web page will need to be updated for the new release. @Jamie-SA I'll send you the text. We can make this fix as well. The link is actually correct, it's only the link text that's wrong.
