### ISSUE TITLE
Add idText property

### ISSUE THREAD

**Issue by ct-martin** [semanticarts/gist#874]
@rjyounes proposal to add `gist:idString` as a `DatatypeProperty`.

> This needs to be a general property named gist:idString; though the typical use case is internal IDs, we should not constrain it that way.

**Comment by uscholdm** [comment]
Currently there are several datatype properties that connect an object to a text string that has a deep fundamental connection to that object. E.g
- `gist:ID gist:uniqueText xsd:string`
- `gist:Tag gist:tagText xsd:string`
- `gist:Text gist:containedText xsd:string`
- `gist:Text gist:encryptedText xsd:string` 
- NOTE: `gist:encryptedText rdfs:subPropertyOf gist:containedText`

One proposal is to collapse these into a smaller number of properties. For example, if we  agree that each object just has one unique string associated with it, then we can get rid of `tagText` and `containedText` and just use `uniqueText`.

The question is how to handle multiple languages.  
1. We could use language tags which allow the object to have multiple strings
2. We could require separate text objects for each language.

The current definition of gist:ID has this restriction:
```
			[
				a owl:Restriction ;
				owl:onProperty gist:isExpressedIn ;
				owl:someValuesFrom gist:Language ;
			]
```
If we went with the use of language tags, this restriction is moot but we could not use `uniqueText` any more.  However we could still get rid of `tagText` and  `uniqueText` could be a subproperty of `containedText`

**Comment by rjyounes** [comment]
IDs are language-agnostic, so the language tag issue is moot.

**Comment by rjyounes** [comment]
:contract :isIdentifiedBy :ID . :ID :uniqueText "1234" .

:contract :idText "1234" 
Dan: should be allowed to have more than one `idText` (so not functional), though not ideal

(`gist:uniqueText` is also functional)

Rebecca: can be superproperty of datatype properties for particular IDs - e.g., `:ssn`, `:sku`

Dan: useful for string search without the clutter of ID objects

There was an internal discussion of this on 2023-01-31, with consensus that datatype properties were valid under some circumstances.

**Comment by rjyounes** [comment]
DECISION:
* Add datatype property `gist:idText`
* Range is `xsd:string`
* Scope notes:
  * Language agnostic
  * Not functional 
  * Potential for subproperties to be defined in client ontologies, such as `:ssn`, `:vin`. These would be functional properties.
  * Not a subproperty of any existing text datatype properties, which all pertain to `:Content` objects
