### ISSUE TITLE
Promote DataSet to gist core

### ISSUE THREAD

**Issue by ct-martin** [semanticarts/gist#875]
Re: @rjyounes 

A collection of data; typically, but not always, associated with a point in time.

**Comment by uscholdm** [comment]
This has come up in several of my client projects. It also exists in [DCAT](https://www.w3.org/TR/vocab-dcat-3/#Class:Dataset).

**Comment by rjyounes** [comment]
Current definition in `gist:Business`:

```
gist:DataSet
	a owl:Class ;
	rdfs:subClassOf gist:Collection ;
	skos:definition "A collection of data."^^xsd:string ;
	skos:editorialNote "Should be promoted to gistCore."^^xsd:string ;
	skos:prefLabel "Data Set"^^xsd:string ;
	skos:scopeNote "This will typically, but not always, be associated with a point in time or a time interval."^^xsd:string ;
	.
```
Peter: Is it a Collection?
Mark: Not axiomatized enough to warrant putting in gist. Feels domain-specific, may not get agreement at an upper level. Easy to use gist to define it in implementations.
Michael: Highly ambiguous. 
Ryan: Agrees with Mark - no specialization is indicated. What are the relationships to other ontologies that use gist and define this term? 
Katie: `DataSet` also exists in gistComputing - defined as a collection of data records - involves defining a number of other terms to define the specialization, which we don't want to add to gist.
Peter: Not useful unless a specialization is defined. Other clients will have specialized meanings that they will want instead.

DECISION: Closing.
