### ISSUE TITLE
Promote Authorization to gist core

### ISSUE THREAD

**Issue by ct-martin** [semanticarts/gist#876]
Edit: See conversation starting at https://github.com/semanticarts/gist/issues/876#issuecomment-1670202439 for the latest thinking on this concept.

For members of the SA organization, see this commit (squashed commit from subgist PR) for proposed triples: https://github.com/semanticarts/gistBusiness/commit/3e67edd7409423ddc7adc6109b332e182522c371

<details>
<summary>Original proposal</summary>
Re: @rjyounes , @dylan-sa , @Jamie-SA , etc.

Subclass of `Permission`

An access privilege granted to a Person; open discussion on whether it is temporal.

Has predicates `isAssignmentOf` and `isAssignedBy`
</details>

**Comment by uscholdm** [comment]
An authorization has three core things:
1. person or organization that is doing the authorizing
2. pereson or organization that is being authorized
3. that which the person/org is authorized to do.

The suggested property names are about assigning, which seems rather different than authorizing. Something more like the following might be better:
1. authorizedBy
2. authorizes
3. authorizedTo

**Comment by rjyounes** [comment]
I agree with @uscholdm and propose the following skeletal definitions:

```
gist:Authorization a owl:Class ;
    owl:equivalentClass [
        a owl:Class ;
        owl:intersectionOf (
               gist:Permission 
               [
                   a owl:Restriction ;
                   owl:onProperty gist:isAuthorizedBy ;
                   owl:someValuesFrom owl:Thing ;
               ]
               [
                    a owl:Restriction ;
                    owl:onProperty gist:isAuthorizationOf ;
                    owl:someValuesFrom owl:Thing ;
               ]
               [
                    a owl:Restriction ;
                    owl:onProperty gist:isAuthorizationTo ;
                    owl:someValuesFrom owl:Thing ;
               ]             
        );
    ] ;
.
```

See my comments on https://github.com/semanticarts/gistBusiness/pull/17 proposing that an Authorization _is_ rather than _has_ a Permission.

**Comment by rjyounes** [comment]
I'm actually now wondering what the difference between `Permission` and `Authorization` is. Definition of `gist:Permission` is "A description of things one is permitted to do. This could be broad, such as free speech, but more often is very specific, such as the right of egress through a particular property." 

What does `Authorization` add?

**Comment by uscholdm** [comment]
> Definition of `gist:Permission` is "A description of things one is permitted to do. This could be broad, such as free speech, but more often is very specific, such as the right of egress through a particular property."

As this reads, the 'permission' is the 'something' that one is permitted to do.  In a case where a particular organization gives a particular person 'permission' to do something, I think that's pretty much exactly what authorization is, so not much of a distinction.  

That may not be exactly the same as saying that every example of being permitted to do something necessarily ALWAYS, in principle has a grantor of the permission (authorizer) and the one granted the permission (the one being authorized).  Is there always an explicit authorizer? Maybe it's a law, or a computer program that does the 'authorizing'. Maybe the permission is not granted to individuals, but in bulk to populations. Persons over 18 are permitted to vote.

**Comment by rjyounes** [comment]
I've changed my mind about this based on discussions with Christian and (indirectly) Dave and Jamie. I had misunderstood a Permission to include the assignment to someone, when in fact it doesn't, and that's what the Authorization does. So a Permission is something like "write access to HR data" and the Authorization assigns that Permission to a person. Generally an Authorization would encompass several Permissions at once; for example, Top Secret Clearance, where SecurityClearance is a subclass of Authorization, includes access to certain documents, computer drives, conference rooms, etc. I'm in favor of pulling the Authorization class into gistCore as it will be implemented in gistBusiness. And the assignment predicates can be used rather than needing new authorization predicates.

**Comment by rjyounes** [comment]
The implementation should include a scope note on Permission explaining the above, since it seems susceptible to misinterpretation.

**Comment by uscholdm** [comment]
Per above discussion, which seems reasonable, we might revise the definition as follows (only change is 3rd restriction)

```
gist:Authorization a owl:Class ;
    owl:equivalentClass [
        a owl:Class ;
        owl:intersectionOf (
               gist:Permission 
               [
                   a owl:Restriction ;
                   owl:onProperty gist:isAuthorizedBy ;
                   owl:someValuesFrom owl:Thing ;
               ]
               [
                    a owl:Restriction ;
                    owl:onProperty gist:isAuthorizationOf ;
                    owl:someValuesFrom owl:Thing ;
               ]
               [
                    a owl:Restriction ;
                    owl:onProperty gist:grants ;                      
                    owl:someValuesFrom gist:Permission ;     
               ]             
        );
    ] ;
.
```

**Comment by rjyounes** [comment]
I like `grants` for `Permission` - but do we want to say it's both a subclass of and grants `Permission`? Seems dangerously circular. I'm thinking now if it grants a permission it's not itself a type of permission.

**Comment by uscholdm** [comment]
> In gistBusiness, where the term now resides, it's a subclass of Assignment, and we use the Assignment predicates. It is an assignment of a permission to someone or something.

Makes sense. It would  make sense for assignment to be an event, but other reasonable options may exist

**Comment by ct-martin** [comment]
@uscholdm If you want to take a look at how we modeled both `Assignment` and `Authorization`, the diff can be found here (squashed commit from the subgist PR): https://github.com/semanticarts/gistBusiness/commit/3e67edd7409423ddc7adc6109b332e182522c371

`Assignment` isn't a subclass of `Event`, although it is a subclass of `TemporalRelation`, which might get at some of the semantics you're looking for.

**Comment by uscholdm** [comment]
> `Assignment` isn't a subclass of `Event`, although it is a subclass of `TemporalRelation`, which might get at some of the semantics you're looking for.

`TemporalRelation` used to be an `Event`, but not now for some reason. 

What property does an Assignment reify? One that means X is assigned to Y?

**Comment by rjyounes** [comment]
> What property does an Assignment reify? One that means X is assigned to Y?

Yes. We are using that a lot in some of the sub-gists, particularly gistHR. An employee is assigned to a position, a task, an exempt status, has an assigned pay rate and billing rate, etc.

**Comment by uscholdm** [comment]
> We are using that a lot in some of the sub-gists, particularly gistHR. An employee is assigned to a position, a task, an exempt status, has an assigned pay rate and billing rate, etc.

That makes sense. It makes less sense to say a Permission is an Assignment. Was I correct that that was being suggested?

**Comment by rjyounes** [comment]
No, the Permission is the thing being assigned. The Authorization is the (subclass of) Assignment.

**Comment by ct-martin** [comment]
@uscholdm As it's modeled currently, the `Authorization` is the grant, whereas the `Permission allows some Behavior` (the latter definition coming from gist core).

In the case of entering the building, the `Permission` allows you to perform the action of entering the building, whereas the `Authorization` is the grant of that permission to you.

Two of the points that Dave & Jamie brought up were that permissions usually come in groups (you're probably authorized to do more than just enter the building) and that the grant is temporal (even if the end date is not currently known). Additionally, many people are likely to have the same `Permission` for entering the building.

**Comment by rjyounes** [comment]
I've also floated the idea of a `PermissionSet` to group permissions that generally are authorized together. This is frequently or even typically the way access privileges work. E.g., top security clearance may involve access privileges to certain documents, network drives, conference rooms, wings of buildings, etc. These are separate permissions but can be grouped together and thus assigned with a single `Authorization` object. The SVF restriction on `Authorization` would be to `PermissionSet` rather than `Permission`. A set is not precluded from having only one member, and a `Permission` could belong to more than one set.

**Comment by uscholdm** [comment]
> I've also floated the idea of a `PermissionSet` to group permissions that generally are authorized together.

Seems like a good workable idea for a client ontology.  I'm thinking it ought not go into gistCore.

**Comment by rjyounes** [comment]
I'm OK with that. Maybe Authorization doesn't need to go into gistCore either, what do you think? If we define using `Permission` instead of `PermissionSet`, it will not be usable with `PermissionSet` in a client ontology. Shall we close this issue?

**Comment by uscholdm** [comment]
> Shall we close this issue?

We could - however, we may also wish to give the group a chance to opine.

**Comment by rjyounes** [comment]
I think it's premature to bring this up now. Those of us who need it have it in the sub-gists. Doesn't seem like a priority for gistCore.
