### ISSUE TITLE
Drop end date restriction on `TemporalRelation`?

### ISSUE THREAD

**Issue by dylan-sa** [semanticarts/gist#878]
See discussion here: https://github.com/semanticarts/gistHR/issues/34

gist's notion of `ContemporaryEvent` (an event with a start date but no end date) is suggestive of the existence of "contemporary temporal relations"--relations that are currently holding and strictly speaking don't yet have an end date.

I propose dropping the end date restriction on `TemporalRelation`. Current definition for reference:

```
gist:TemporalRelation
	a owl:Class ;
	rdfs:subClassOf
		[
			a owl:Restriction ;
			owl:onProperty gist:endDateTime ;                    # Proposal is to remove this restriction
			owl:cardinality "1"^^xsd:nonNegativeInteger ;
		] ,
		[
			a owl:Restriction ;
			owl:onProperty gist:startDateTime ;
			owl:cardinality "1"^^xsd:nonNegativeInteger ;
		] ,
		[
			a owl:Restriction ;
			owl:onProperty gist:hasParticipant ;
			owl:minCardinality "2"^^xsd:nonNegativeInteger ;
		]
		;

**Comment by ct-martin** [comment]
Just to ask the question - would there be a benefit to having a subclass (e.g. something like "`TemporalPeriod`" ) that still has the end date, for example, to provide validation on events that do have an end date?

**Comment by ct-martin** [comment]
@Jamie-SA Yes, it doesn't itself; I was thinking of under a reasoner e.g. Protege's "explain inconsistent ontology"

**Comment by Jamie-SA** [comment]
Having a triple that is not specified in the OWL for a class is not "inconsistent".

**Comment by ct-martin** [comment]
My concern has been addressed by #880

**Comment by uscholdm** [comment]
> I propose dropping the end date restriction on `TemporalRelation`.

This makes sense. Also, `gist:Event` should not have an end date restriction. I also think it makes ontological sense to say a `TemporalRelation` is a subclasss of Event, it is something that occurs over a period of time. The `charactarizedAs some Behavior` is not needed, IMHO.

**Comment by rjyounes** [comment]
DECISION: Remove restriction because temporal relations haven't necessarily ended.
