### ISSUE TITLE
gistNetwork uses gist:goal rather than the object property actually defined in gistIntention, gist:hasGoal

### ISSUE THREAD

**Issue by stewardont** [semanticarts/gist#88]

**Comment by uscholdm** [comment]
To elaborate, the class Artifact has a restriction "gist:goal some gist:Function" but it should  be  "gist:hasGoal some gist:Function"

**Comment by rjyounes** [comment]
Impact is patch because original is an error.

**Comment by rjyounes** [comment]
@stewardont Removing project assignment because I don't think this has been triaged yet. If I'm wrong, please add back to project and add label triaged as well.

**Comment by rjyounes** [comment]
Already fixed
