### ISSUE TITLE
Balance should not be a subclass of Magnitude

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#882]
A balance is a relationship between an account (or similar) and a monetary object. It's not a class any more than Length is a class. We need a predicate hasBalance linked to a Monetary.

**Comment by rjyounes** [comment]
We can fix this before any major redesign to units and magnitudes. It's along the lines of a modeling error.

**Comment by uscholdm** [comment]
> A balance is a relationship between an account (or similar) and a monetary object. It's not a class any more than Length is a class. We need a predicate hasBalance linked to a Monetary.

Balances are not always monetary, e.g. airline miles.

Also, `Account` is an `Agreement` with a `Balance`, so  `hasMagnitude some Balance` might change to be `hasBalance some Magnitude` (oddly enough).  That creates another question - what if the air miles account balance just is a number in which case the relationship would be represented by a data property. Alternatively, the value would be an instance of `Count`, which is a tad clunky.

**Comment by rjyounes** [comment]
Will be absorbed into new units and magnitudes model in v13.0.0.

**Comment by rjyounes** [comment]
Closing - superseded by new magnitude model
