### ISSUE TITLE
Update v12.0.0 before release to match namespace & IRI decisions

### ISSUE THREAD

**Issue by Jamie-SA** [semanticarts/gist#883]
Copied from @rjyounes email:

  | Current as of 12.0.0 (not yet released) | Proposed
-- | -- | --
gist TBox namespace in w3id domain (for public ontologies only, currently all in the gist GitHub repo) | https://w3id.org/semanticarts/gist/ | https://w3id.org/semanticarts/ns/gist/
gist redirect and sub-gist TBox namespace | https://ontologies.semanticarts.com/gist/ | https://ontologies.semanticarts.com/ns/gist/
gistCore w3id ontology IRI | https://w3id.org/semanticarts/gistCore | https://w3id.org/semanticarts/gistCore (no change)
-- | -- | --
gistCore w3id version IRI | https://w3id.org/semanticarts/gistCore12.0.0 | https://w3id.org/semanticarts/gistCore12.0.0 (no change)
gistCore redirect ontology IRI | https://ontologies/semanticarts.com/o/gistCore | https://ontologies.semanticarts.com/gistCore
gistCore version 12.0.0 redirect IRI | https://ontologies.semanticarts.com/o/gistCore12.0.0 | https://ontologies.semanticarts.com/gistCore12.0.0

**Comment by rjyounes** [comment]
The version above is partially defunct. Below is the version we agreed on at today's meeting:

Other gist ontologies in this repo will follow the pattern of ontology and ontology version IRIs shown for gistCore.

(Scroll to the right to see all columns in full.)

| IRI | 11.x.x | Original 12.0.0 (implemented but not released) | New 12.0.0 |
|--------|-------|------|-------|
| gist ontology namespace |  https://ontologies.semanticarts.com/gist/ | https://w3id.org/semanticarts/gist/ - redirects to https://ontologies.semanticarts.com/o/Namespace.html | https://w3id.org/semanticarts/ns/ontology/gist/ - redirects to https://ontologies.semanticarts.com/Namespace.html |
| gistCore w3id ontology IRI |  N/A | https://w3id.org/semanticarts/gistCore | https://w3id.org/semanticarts/gistCore (no change from original 12.0.0) |
| gistCore w3id version IRI |  N/A | https://w3id.org/semanticarts/gistCore12.0.0 | https://w3id.org/semanticarts/gistCore12.0.0 (no change from original 12.0.0) |
| gistCore ontology IRI in SA domain (used only for redirects in 12.0.0) |  https://ontologies.semanticarts.com/o/gistCore |  https://w3id.org/semanticarts/gistCore | https://w3id.org/semanticarts/gistCore (no change from original 12.0.0) |
| gistCore version IRI in SA domain (used only for redirects in 12.0.0) |  https://ontologies.semanticarts.com/o/gistCore11.0.0 |  https://w3id.org/semanticarts/gistCore12.0.0 | https://w3id.org/semanticarts/gistCore12.0.0 (no change from original 12.0.0) |

**Comment by uscholdm** [comment]
### IMPORTANT: you may have to scroll to the right to see the current proposal for a New 12.0.0. The table has 3 columns.

**Comment by uscholdm** [comment]
The content in the namespace.html file may need to be updated with this new convention.

**Comment by Jamie-SA** [comment]
@rjyounes the last 2 lines of your table show w3id URLs. If those are the redirect URLs, they need to be semanticarts.com URLs.

**Comment by rjyounes** [comment]
> @rjyounes the last 2 lines of your table show w3id URLs in the last column. If those are the redirect URLs, they need to be semanticarts.com URLs.

@Jamie-SA Thanks for catching that. Corrected above.

**Comment by rjyounes** [comment]
@coltonglasgow Please submit the PR to the release branch, _not_ `develop`.

**Comment by rjyounes** [comment]
@coltonglasgow You can edit `ReleaseNotes.md` in place for this one instead of creating a separate file.

**Comment by rjyounes** [comment]
Amended proposal, to make the fact that it's an ontology explicit in the IRI, just as it is in the SA domain and in the namespace.

New ontology IRI in w3id namespace: `https://w3id.org/semanticarts/ontologies/gistCore` OR `https://w3id.org/semanticarts/ontology/gistCore`.

**Comment by daliadahleh** [comment]
I vote for https://w3id.org/semanticarts/ontology/gistCore. I like having ontology be explicit, and agree that consistency in singular tense avoids any confusion.

**Comment by rjyounes** [comment]
I think "confusion" might be better in this case, actually: it underlines the distinction between the namespace and the ontology IRI.

**Comment by Jamie-SA** [comment]
I agree with Dalia. The IRI is for an ontology, it should probably be singular.

> https://w3id.org/semanticarts/ontology/gistCore

**Comment by rjyounes** [comment]
Votes so far. Go ahead and edit this comment to add your name.

ontologies
* Rebecca
* Steven

ontology
* Dalia
* Peter
* Jamie

ontology or ontologies
* Michael
* Dave

**Comment by uscholdm** [comment]
I think we don't want to have plural as well as singular, even it is acceptable logically and grammatically. IMHO just having to remember one thing is better.

**Comment by rjyounes** [comment]
@coltonglasgow @stevenchalem Looks like the winner is singular, so go ahead with the implementation.

**Comment by rjyounes** [comment]
The final version:

The version above is partially defunct. Below is the version we agreed on at today's meeting:

Other gist ontologies in this repo will follow the pattern of ontology and ontology version IRIs shown for gistCore.

**_(Scroll to the right to see all columns in full.)_**

| IRI | 11.x.x | Original 12.0.0 (implemented but not released) | New 12.0.0 |
|--------|-------|------|-------|
| gist ontology namespace |  https://ontologies.semanticarts.com/gist/ | https://w3id.org/semanticarts/gist/ - redirects to https://ontologies.semanticarts.com/o/Namespace.html | https://w3id.org/semanticarts/ns/ontology/gist/ - redirects to https://ontologies.semanticarts.com/Namespace.html |
| gistCore w3id ontology IRI |  N/A | https://w3id.org/semanticarts/gistCore | https://w3id.org/semanticarts/ontology/gistCore  |
| gistCore w3id version IRI |  N/A | https://w3id.org/semanticarts/gistCore12.0.0 | https://w3id.org/semanticarts/ontology/gistCore12.0.0  |
| gistCore ontology IRI in SA domain (used only for redirects in 12.0.0) |  https://ontologies.semanticarts.com/o/gistCore |  https://ontologies.semanticarts.com/gistCore | https://ontologies.semanticarts.com/gistCore (no change from original 12.0.0) |
| gistCore version IRI in SA domain (used only for redirects in 12.0.0) |  https://ontologies.semanticarts.com/o/gistCore11.0.0 |  https://ontologies.semanticarts.com/gistCore12.0.0 | https://ontologies.semanticarts.com/gistCore12.0.0 (no change from original 12.0.0) |

**Comment by Jamie-SA** [comment]
The way the w3id redirects are written, except for the namespace, any path after the `https://w3id.org/semanticarts/` is included in the redirect URL (appended to `https://ontologies.semanticarts.com/`). I recommend keeping it that way for consistency and, if it is good for the public URI, why not for the redirect URI?

**Comment by rjyounes** [comment]
Do you mean you want `https://ontologies.semanticarts.com/ontology/gistCore`? We decided against that yesterday on the grounds of redundancy.

**Comment by Jamie-SA** [comment]
Yes, that is what I mean.
We talked about a lot of things, I don't remember all the details of that part of the conversation, was it about the redirect IRI or the official IRIs?
And we've already changed things since the meeting.
I just think it is simpler to keep the paths the same on both URIs.

**Comment by stevenchalem** [comment]
Does this last issue affect anything inside the package?

**Comment by uscholdm** [comment]
Umm,  I thought we were going to be consistent and not mix and match singular and plural.

![image](https://github.com/semanticarts/gist/assets/10777545/b7dd390a-53f3-4c77-963e-7cce9b6f47b1)

I propose we move ontologies.semanticarts.com to the dustbin of history, and use ontology.semanticarts.com henceforth.

Michael

**Comment by rjyounes** [comment]
@Jamie-SA I agree that it would be simpler. We'd considered `https://semanticarts.com/ontologies/gistCore` for the redirect, to avoid the repetition. We could go with the singular variant `https://semanticarts.com/ontology/gistCore`.  

@stevenchalem Probably not, but you may need to do a text search on the files to be sure.

**Comment by rjyounes** [comment]
@uscholdm What do you think of my proposal immediately above?

I don't think this is going to be decided at 6pm ET on a Friday. Let's briefly reconvene Monday morning and resolve it.

**Comment by uscholdm** [comment]
> `https://semanticarts.com/ontology/gistCore`.
> @uscholdm What do you think of my proposal immediately above?

It's a perfectly reasonable option, if we don't want to use subdomains.  I cannot think of any pros/cons. We should be consistent with whatever policy we have for using subdomains.   Perhaps @Jamie-SA can weigh in.

**Comment by Jamie-SA** [comment]
I don't think the redirect URIs need to hold up the release.

I don't recommend not having a subdomain as that is automatically redirected to www.semanticarts.com.

**Comment by rjyounes** [comment]
I see.  We can go ahead with the release and come back to this on Monday.

**Comment by stevenchalem** [comment]
I'll proceed with the release once @coltonglasgow wraps up https://github.com/semanticarts/gist/issues/883

**Comment by coltonglasgow** [comment]
@stevenchalem @rjyounes, are we waiting for this issue (#883) before the release or not? The last two comments contradict each other.

**Comment by stevenchalem** [comment]
@coltonglasgow Two issues, one before the release and one after. We need to update the public namespaces inside gist before the release. The *internal* namespaces and the server redirect behavior can happen after the release.

**Comment by Jamie-SA** [comment]
@coltonglasgow which 2 comments?
This is issue 883. The last table in the comments should have the latest decision about namespace and ontology IRIs.
You can ignore the last 2 rows as they are only about the redirect URLs.

To recap what I understand is needed:
- change the gist namespace to `https://w3id.org/semanticarts/ns/ontology/gist/`
- change the ontology IRI to be like `https://w3id.org/semanticarts/ontology/gistCore`
- change the ontology version IRI to be like `https://w3id.org/semanticarts/ontology/gistCore12.0.0`

**Comment by rjyounes** [comment]
@uscholdm Singular vs plural: IMO context matters, not just consistency. A subdomain "ontologies" suggests, correctly, that there are or may be multiple ontologies in that subdomain; "ontology" suggests, incorrectly, that there is only one. I therefore prefer the plural for the subdomain. (I applied the same argument in favor of `https://w3id.org/semanticarts/ontologies/gistCore` but was outvoted, and while it does seem more acceptable in that context, I would still prefer the plural.)

**Comment by stevenchalem** [comment]
@rjyounes I hope there is some consolation in knowing that you changed my mind.

**Comment by rjyounes** [comment]
Indeed, I wish everyone were as reasonable as you. :)

**Comment by uscholdm** [comment]
> @uscholdm Singular vs plural: IMO context matters, not just consistency. A subdomain "ontologies" suggests, correctly, that there are or may be multiple ontologies in that subdomain; "ontology" suggests, incorrectly, that there is only one. I therefore prefer the plural for the subdomain. (I applied the same argument in favor of `https://w3id.org/semanticarts/ontologies/gistCore` but was outvoted, and while it does seem more acceptable in that context, I would still prefer the plural.)

I don't disagree with your logic, I would lean towards plural for ontologies.semanciarts.com if that was all there was to it. But there is the practical matter of remembering when to use which, if we are also using the singular in other places. From a practical perspective, more mistakes will be made if we use both singular and plural. So that is the cost. What benefit to we get for that cost?  It's highly personal and very subtle and one of taste, and therefore IHMO should not count for as much.

To be honest, I thought we already HAD decided on consistency in this regard, and I was just catching a bug. Others may feel the same way -- or not. Let's see.

WHAT DO PEOPLE THINK?
1. use `ontlogy.semanticarts.com` and only in the singular form for easy remembering.
2. use `ontologies.semantocarts.com` and also in the singular, despite the likely increased likelihood of error.

**Comment by uscholdm** [comment]
> I'm late to the party

I'm not sure who turingtest37 is.

**Comment by rjyounes** [comment]
> But there is the practical matter of remembering when to use which...increase in error

No one will ever use this, it is the redirect IRI.

And no, this particular one was not included in the discussion.

@turingtest37 is Doug, but this ship has already sailed:

```
change the gist namespace to https://w3id.org/semanticarts/ns/gist/
```
The namespace we decided on allows taxonomies, ontologies, and instance datasets to be distinguished on sight. This is the way we do it in sub-gists and client projects, and if it ever becomes relevant we will extend it to gist.

**Comment by uscholdm** [comment]
> No one will ever use this, it is the redirect IRI.

Aha, yes of course. So a non-issue.

> this ship has already sailed

Happy Sailing!

**Comment by turingtest37** [comment]
@uscholdm  turingtest37 is Beeson. It's my pre-Semantic Arts handle.

**Comment by uscholdm** [comment]
> @uscholdm turingtest37 is Beeson. It's my pre-Semantic Arts handle.

Were you 37 years old or some such thing?
