### ISSUE TITLE
Serializer pre-commit hook not working

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#884]
An older version works.

**Comment by Jamie-SA** [comment]
Are you saying it doesn't work on your local machine? I think mine just worked.

**Comment by rjyounes** [comment]
It's confusing. It's not working for Dylan or me.

**Comment by rjyounes** [comment]
The problem is it runs but doesn't detect syntax errors.

**Comment by Jamie-SA** [comment]
OK. I seem to remember a previous change in the script that might be the cause. I will look for it later.

**Comment by rjyounes** [comment]
It's the removal of the `--cached` option. When I restore that it works. Will create a PR shortly.

**Comment by rjyounes** [comment]
Fixed in #889.
