### ISSUE TITLE
Should all owl:imports refer to versioned IRIs?

### ISSUE THREAD

**Issue by Jamie-SA** [semanticarts/gist#897]
I think we have a couple of places in the repo with imports that look like `owl:imports <https://w3id.org/semanticarts/ontology/gistCore> ;`. I think we'd want them to reference the versioned IRI of an ontology, such as `owl:imports <https://w3id.org/semanticarts/ontology/gistCoreX.x.x> ;`.

**Comment by rjyounes** [comment]
Yes, agreed.

**Comment by rjyounes** [comment]
Mark agrees.
Boris: Temporarily yes. But would like to see a more flexible import paradigm where the import uses an unversioned IRI, but there is a dependency on some exact version, version greater than, versions x-y, etc. Like Maven, Python dependencies. These would be attached to the ontology itself. It's descriptive but validated by a query.

Michael: will add issue to add gist versions and gist operators - possibly in a sub-gist.

Temporarily: Add versioned imports to all the small ontologies in the gist repo. Add import to gistPrefixDeclarations (currently missing).
