### ISSUE TITLE
Remove domain and range from gist:isGovernedBy (was "Expand domain (and range?) of `governs`")

### ISSUE THREAD

**Issue by ct-martin** [semanticarts/gist#899]
Proposal to expand the domain of `governs` to include `Commitment`.

Would make sense to add `Commitment` to the range as well.

**Comment by rjyounes** [comment]
gist 12.0.0 includes only `isGovernedBy`. `governs` has been deleted along with all the other inverses.

It would make more sense to remove the domains and ranges altogether, so we don't have to have them trickle in as we come across more uses for the predicate.

**Comment by rjyounes** [comment]
DECISION: Remove domains and ranges and do _not_ add `domainIncludes` and `rangeIncludes` statements. Removing the axioms make this a major change, so pushing to gist 13.0.0.
