### ISSUE TITLE
Examples for MonetaryPerDuration are not right

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#912]
The examples for MonetaryPerDuration are not right there needs to be a number.  Suggest to replace with:
`skos:example "20 dollars per hour, 5000 euros per month."^^xsd:string ;`

Suggest more natural wording for the definition as follows:
`skos:definition "An amount of money over a period of time."^^xsd:string ;`

```
gist:MonetaryPerDuration
	a owl:Class ;
	owl:equivalentClass [
		owl:intersectionOf (
			gist:RatioMagnitude
			[
				a owl:Restriction ;
				owl:onProperty gist:hasUnitOfMeasure ;
				owl:allValuesFrom gist:CurrencyPerDurationUnit ;
			]
		) ;
	] ;
	skos:definition "A monetary amount over a period of time."^^xsd:string ;
	skos:example "Dollars per hour, euros per month."^^xsd:string ;
	skos:prefLabel "Monetary per Duration"^^xsd:string ;
	.
```

**Comment by rjyounes** [comment]
I agree with both of @uschold's points.

**Comment by uscholdm** [comment]
A month is not a Duration because it has variable length, so I suggest changing the example to say week, or year.

**Comment by rjyounes** [comment]
Already completed.
