### ISSUE TITLE
Exponent notation unsightly

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#915]
The final release uses ugly exponent notation for conversion factors.  We author this way:
- `gist:conversionFactor "1.0"^^xsd:double` 
but it ends up as:
- `gist:conversionFactor "1e+00"^^xsd:double`

Is this something we have to live with?

**Comment by uscholdm** [comment]
I just ran an experiment regarding #916 and discovered that Protege converts exponential notation into regular notation and the serializer leaves it intact. 
**MYSTERY:** Where DID the exponent notation come from? This is what I did:

1. start with gistCore12.0.0.ttl that I downloaded from SA website
2. manually removed the 12 triples making instances of owl:Thing
3. loaded it into Protege
4. Immediately saved it out from Protege
5. Ran it through the serializer

RESULT: to my amazement, the exponent notation was converted to regular numbers. This happened as a result of Protege. The serializer left them intact. See the turtle files below - github prevents me from pasting in .ttl files - I changed the extension to .txt.
[TestOwlThingInstances-gistCore12.0.0.txt](https://github.com/semanticarts/gist/files/11972169/TestOwlThingInstances-gistCore12.0.0.txt)
[TestOwlThingInstances-gistCore12.0.0-AfterProtege.txt](https://github.com/semanticarts/gist/files/11972170/TestOwlThingInstances-gistCore12.0.0-AfterProtege.txt)
[TestOwlThingInstances-gistCore12.0.0-AfterProtege-Serialized.txt](https://github.com/semanticarts/gist/files/11972171/TestOwlThingInstances-gistCore12.0.0-AfterProtege-Serialized.txt)

Here are the key bits:

**Original downloaded from semanticarts.com/gist:** Has instance of `owl:Thing` with exponent notation for conversion
```
gist:_meter
	a
		owl:Thing ,
		gist:BaseUnit
		;
	rdfs:isDefinedBy <https://w3id.org/semanticarts/ontology/gistCore> ;
	skos:definition "The base unit for measuring distance."^^xsd:string ;
	skos:prefLabel "distance"^^xsd:string ;
	gist:conversionFactor "1e+00"^^xsd:double ;
	gist:hasBaseUnit gist:_meter ;
	gist:unitSymbol "m"^^xsd:string ;
	.
```


**After instance of `owl:Thing` was manually removed:** No `owl:Thing` instance, has exponent notation for conversion
```
gist:_meter
	a
		gist:BaseUnit
		;
	rdfs:isDefinedBy <https://w3id.org/semanticarts/ontology/gistCore> ;
	skos:definition "The base unit for measuring distance."^^xsd:string ;
	skos:prefLabel "distance"^^xsd:string ;
	gist:conversionFactor "1e+00"^^xsd:double ;
	gist:hasBaseUnit gist:_meter ;
	gist:unitSymbol "m"^^xsd:string ;
	.
```

**Saved out by Protege:** No exponent notation, no `owl:Thing` instance, has instance of `NamedIndividual`
```
###  https://w3id.org/semanticarts/ns/ontology/gist/_meter
gist:_meter rdf:type owl:NamedIndividual ,
                     gist:BaseUnit ;
            gist:hasBaseUnit gist:_meter ;
            gist:conversionFactor "1.0"^^xsd:double ;
            gist:unitSymbol "m"^^xsd:string ;
            rdfs:isDefinedBy <https://w3id.org/semanticarts/ontology/gistCore> ;
            skos:definition "The base unit for measuring distance."^^xsd:string ;
            skos:prefLabel "distance"^^xsd:string .
```

**After serialized:** No exponent notation, no `owl:Thing` instance, no instance of `NamedIndividual`
```
gist:_meter
	a gist:BaseUnit ;
	rdfs:isDefinedBy <https://w3id.org/semanticarts/ontology/gistCore> ;
	skos:definition "The base unit for measuring distance."^^xsd:string ;
	skos:prefLabel "distance"^^xsd:string ;
	gist:conversionFactor "1.0"^^xsd:double ;
	gist:hasBaseUnit gist:_meter ;
	gist:unitSymbol "m"^^xsd:string ;
	.
```

**Comment by rjyounes** [comment]
This is apparently due Python in onto_tool (I discovered from reading my own documentation):

Replacement of doubles in decimal notation with scientific notation; e.g., ”1.0”^^xsd:double in the Turtle file is ...caused by the bundler reading the files into memory and using Python to convert double literals to Python floats.

**Comment by uscholdm** [comment]
Is it too involved to just fix it?

**Comment by rjyounes** [comment]
Yes, it is. It would involve writing a Python module, I suppose. 

Funny story: when I first started creating units, I saw the scientific notation and thought that was our convention, so that's how I wrote them in the ontology.

**Comment by uscholdm** [comment]
> Yes, it is. It would involve writing a Python module, I suppose. And personally I don't mind it.
> 
> In fact, when I first started creating units, I saw the scientific notation and thought that was our convention, so that's how I wrote them in the ontology.

OK - unless someone feels motivated and finds a way that is not that big a deal, I suppose we can close this. But we should get consensus first - someone might come up with a clever solution.

**Comment by ct-martin** [comment]
From rdflib issue tracker: https://github.com/RDFLib/rdflib/issues/1314

**Comment by rjyounes** [comment]
The serializer creates the exponent notation.
