### ISSUE TITLE
Do we want explicit instances of owl:Thing

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#916]
Release 12 has explicit instances of owl:Thing for base unit instances, e.g.
```
gist:_USDollar
	a
		owl:Thing ,
		gist:BaseUnit
		;
	rdfs:isDefinedBy <https://w3id.org/semanticarts/ontology/gistCore> ;
	skos:definition "The base unit for currency."^^xsd:string ;
	skos:prefLabel "US Dollar"^^xsd:string ;
	gist:conversionFactor "1e+00"^^xsd:double ;
	gist:hasBaseUnit gist:_USDollar ;
	gist:unitSymbol "USD"^^xsd:string ;
	.
```

**Comment by Jamie-SA** [comment]
See also #775 & #783 for previous comments.

**Comment by rjyounes** [comment]
It would be good to ask the EDM Council to add another option to the serializer to remove them.

**Comment by uscholdm** [comment]
I just did the following to see where they are coming from.
1. start with gistCore12.0.0.ttl that downloaded from SA website
2. manually removed the 12 triples making instances of owl:Thing
3. loaded it into protege
4. Immediately saved it out from protege
5. Ran it through the serializer

RESULT: no explicit instances of owl:Thing, so neither Protege nor the serializer seem to be the problem.

Maybe just remove them and it's done?

**Comment by rjyounes** [comment]
I did not think the serializer was inserting them, but we wanted them removed if they are there. If Protege isn't putting them in, then it's not clear where they are coming from. We should ask if anyone is putting them in and make it clear in the style guide that they should not be used.

**Comment by rjyounes** [comment]
Added to agenda for next week.

**Comment by rjyounes** [comment]
Given the current behavior of onto_tool, we will not get rdfs:isDefinedBy assertions without owl:Thing assertions. (See links above.) Until onto_tool is fixed we shouldn't remove these.
