### ISSUE TITLE
BaseUnit individuals should have type assertions indicating what dimension they measure

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#92]
All gist:BaseUnit individuals (gist:_ampere, gist:_second, gist:_kilogram, etc.) are typed gist:BaseUnit, but only gist:_second has an additional type gist:DurationUnit to indicate what it is used to measure. Shouldn't we similarly assert that gist:_USDollar is a gist:CurrencyUnit, gist:_kilogram is a gist:MassUnit, etc.? There is nothing else in the ontology that I can see that further constrains them. I see that gist:MassUnit gist:hasBaseUnit gist:_kilogram, but from that one cannot infer that gist:_kilogram is a gist:MassUnit.  If I'm missing something, please let me know!

**Comment by uscholdm** [comment]
Inference does the trick. For example, gist:_ampere is inferred to be an instance of ElectricalCurrentUnit.  Click on the question mark to see why.

[cid:image001.png@01D54C5E.DB2DB420]

**Comment by rjyounes** [comment]
There is still some inconsistency here:

1. _second is explicitly typed DurationUnit
2. The inferences work for some individuals and not others. I have inferred Unit types for kilogram and meter, but not the others. See attached images, for ampere and kilogram, for example. I've used both Pellet and Hermit with the same results.

![Protege_kilogram](https://user-images.githubusercontent.com/1693668/62709657-c49e9800-b9c3-11e9-9dd1-b9b3bdbcef6a.png)
![Protege_ampere](https://user-images.githubusercontent.com/1693668/62709676-cf592d00-b9c3-11e9-8530-2ed31be617a0.png)

We need to fix the definitions so inferencing works for all of them, and presumably remove the direct typing of _second.

**Comment by rjyounes** [comment]
Actually, I don't know what's going on. All the definitions of the individuals and the Unit types follow the same pattern, so the inferences should be the same. And your screenshot showed the inference for _ampere as well. Looks like it could be a problem with Protege, though I don't know what that might be.

**Comment by uscholdm** [comment]
I’m not seeing the figures, while off-line, but what you say makes sense.  Have you figured out what is different in the cases where the inference works vs. not?

I think it unlikely to be a protégé problem, but nothing can be ruled out.

M.

**Comment by rjyounes** [comment]
Decision: remove the assertion from _second, leave the larger question of whether or not to assert what can be inferred open.
