### ISSUE TITLE
gistValidationAnnotations should not be included in the release package

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#922]
bundle.yaml should list specific files rather than *.ttl in the relevant sections.

**Comment by bpelakh** [comment]
Created https://github.com/semanticarts/ontology-toolkit/issues/111 to make this easier in the future.

**Comment by rjyounes** [comment]
Since I'm modifying bundle.yaml I'm also adding version numbers to the rdfsAnnotations file
