### ISSUE TITLE
Release notes and other documentation files in the release package render poorly in HTML

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#923]
In particular, there is no indentation of bullet points, which is highly problematic.

This could be entirely an onto_tool issue, but I've added the issue here because it is creating a problem in gist.

If this could be fixed before the next release I propose that we serve up the corrected version on the website and possibly slip the file into the download (or does the latter require a patch release?)

**Comment by rjyounes** [comment]
Fix with #924.

**Comment by rjyounes** [comment]
> I've had to mess around with the Markdown to make sure the HTML rendered properly

Can you provide some guidance on how to patch the Markdown so that we don't have to edit the HTML directly? You could add instructions under item 11 here: https://semarts.atlassian.net/wiki/spaces/OF/pages/1126760539/gist+Release+Management+Ontologists.

**Comment by rjyounes** [comment]
Strange that the bulleted list works in the MajorVersionMigration file.

**Comment by Jamie-SA** [comment]
I think this should have been closed when #928 & #923 where merged & closed, except that the "fixes" and "resolves" hints only work on the default branch, not on our release branches. I'm going to close this issue.
