### ISSUE TITLE
Link to migration guide in online release notes is broken

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#924]
On this page: https://ontologies.semanticarts.com/ontology/gistCore.ReleaseNotes.html

this link is broken: https://ontologies.semanticarts.com/ontology/MajorVersionMigration.html

See #923 - if we update the release notes page this should be fixed as well

**Comment by Jamie-SA** [comment]
This is partly a result of how I ended up linking to it. It was a tradeoff between having the version number in the link versus not. If we don't mind a deeper link with the version number in the link, then the links inside the file should work.

This is the deeper link to the [ReleaseNotes.html file.](https://ontologies.semanticarts.com/ontology/gist12.0.0_webDownload/Documentation/ReleaseNotes.html)

**Comment by rjyounes** [comment]
The point being that the deeper link won't work in repository Markdown files?

**Comment by Jamie-SA** [comment]
No, if I understand what you are saying, that is fine.
The problem I was trying to solve is to have an non-versioned link to the latest Release Notes, like we do for the ontology files. But I am thinking we just forget about that because it is a bit of a pain.

**Comment by rjyounes** [comment]
Sounds good then.

**Comment by Jamie-SA** [comment]
I think this issue has been resolved by changing the link (don't use the original link that this issue is about) so I am going to close it.
