### ISSUE TITLE
Add restriction to `gist:TimeInterval`

### ISSUE THREAD

**Issue by dylan-sa** [semanticarts/gist#925]
All time intervals will have a duration--should we add this as a restriction?

**Comment by ct-martin** [comment]
The definition says:

> A span of time with a known start time, end time, and duration. As long as two of the three are known, the third can be inferred.

So maybe the restriction should be:

`(start & end) U (start & duration) U (end & duration)`

?

That said, I agree there should be restrictions.

**Comment by rjyounes** [comment]
@ct-martin Given OWA, we don't need to make it that complicated. They all have a start, end, and duration, although not all three need to be asserted. So I think adding restrictions requiring each of the three is valid.

**Comment by dylan-sa** [comment]
Here's a first pass definition for us to consider:
```
gist:TimeInterval
	a owl:Class ;
	rdfs:subClassOf
		[
			a owl:Restriction ;
			owl:onProperty gist:actualStartDateTime ;
			owl:cardinality "1"^^xsd:nonNegativeInteger ;
		] ,
		[
			a owl:Restriction ;
			owl:onProperty gist:actualStartDateTime ;
			owl:cardinality "1"^^xsd:nonNegativeInteger ;
		] ,
		[
			a owl:Restriction ;
			owl:onProperty gist:hasMagnitude ;
			owl:onClass gist:Duration ;
			owl:qualifiedCardinality "1"^^xsd:nonNegativeInteger ;
		]
		;
	.
```
To Michael's question, I am thinking we could use `hasMagnitude` to link `TimeInterval` and `Duration`. Each time interval would have exactly one start time, one end time, and exactly one magnitude that is a duration. I've suggested qualified cardinality on the magnitude, thinking that time intervals could have other kinds of magnitudes associated with them (e.g., the number of events that unfolded within them).

**Comment by uscholdm** [comment]
@dylan-sa 
Dylan's proposal looks good to me. Normally I don't like using hasMagnitude, but in this case the meaning is obvious.

**Comment by rjyounes** [comment]
I doubt if one would ever assign number of events in a time interval as a magnitude of the time interval. Nevertheless, the definition seems OK.

**Comment by uscholdm** [comment]
Dylan's suggestion used a min 1 cardinality. Specifically:
```
		[
			a owl:Restriction ;
			owl:onProperty gist:hasMagnitude ;
			owl:onClass gist:Duration ;
			owl:qualifiedCardinality "1"^^xsd:nonNegativeInteger ;
		]
```

It should be someValuesFrom

**Comment by rjyounes** [comment]
I like using `hasMagnitude` here. Defining a `hasDuration` predicate contradicts our best practice of not embedding the object type in the predicate.

**Comment by rjyounes** [comment]
This is speculative, but I wonder if we could also put 0 cardinality on `plannedStartDate` and `plannedEndDate`: this is one of the features distinguishing events from time intervals. Events may be planned, time intervals just exist.

**Comment by uscholdm** [comment]
> I like using `hasMagnitude` here. Defining a `hasDuration` predicate contradicts our best practice of not embedding the object type in the predicate.

Agreed.

**Comment by rjyounes** [comment]
Maybe, but one of the arguments against `TimeInterval` is that it was hard to distinguish from `Event`. This would be one option - though of course not all `Event`s have planned dates. It may be conceptually helpful. Let's see what other people think.

**Comment by rjyounes** [comment]
DECISION: Implement according to Dylan's proposal above.
