### ISSUE TITLE
Add skeletal definitions of SKOS and SHACL terms used in gist in order to achieve DL-compliance

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#934]
gist is not DL-compliant because it uses undeclared terms in the SHACL and SKOS namespaces. Add skeletal definitions (à la Protégé) to achieve DL compliance.

**Comment by rjyounes** [comment]
need to remove this from the pre-commit hook:

```
function remove_skos_decls () {
  for fileToBeCommitted in $(git diff --cached --name-only) ; do
    permissions=$(stat -c "%a" "${fileToBeCommitted}")
    sed -e '/^skos/,+3d' "$fileToBeCommitted" > tmp$$
    mv tmp$$ "$fileToBeCommitted"
    chmod $permissions "${fileToBeCommitted}"
    git add --update "${fileToBeCommitted}"
  done

  return 0
}
```

**Comment by dylan-sa** [comment]
I like the idea of adding the skeletal definitions to achieve DL compliance, but it's worth considering what they should look like. As @marksem has pointed out, Protege automatically adds the following definitions for gist:

**Comment by dylan-sa** [comment]
I like the idea of adding skeletal definitions to be DL-compatible, but it's worth thinking more about where the defs should come from and what they should look like. As @marksem has pointed out, Protege automatically generates the following definitions for gist:

```
#################################################################
#    Annotation properties
#################################################################
###  http://www.w3.org/2004/02/skos/core#definition
skos:definition rdf:type owl:AnnotationProperty .

###  http://www.w3.org/2004/02/skos/core#example
skos:example rdf:type owl:AnnotationProperty .

###  http://www.w3.org/2004/02/skos/core#prefLabel
skos:prefLabel rdf:type owl:AnnotationProperty .

###  http://www.w3.org/2004/02/skos/core#scopeNote
skos:scopeNote rdf:type owl:AnnotationProperty .

###  http://www.w3.org/ns/shacl#declare
sh:declare rdf:type owl:AnnotationProperty .

###  http://www.w3.org/ns/shacl#namespace
sh:namespace rdf:type owl:AnnotationProperty .

###  http://www.w3.org/ns/shacl#prefix
sh:prefix rdf:type owl:AnnotationProperty .
```
With these definitions added, gist does become DL-compatible. One worry though is that these automatically generated defs could go against the spirit of the definitions in the concepts' "home" ontologies. `sh:declare`, for instance, has a domain and range in the SHACL ontology, which suggests that it is not really an annotation property. Same for `sh:namespace` and `sh:prefix`.

**Comment by rjyounes** [comment]
DECISION:

* Move SHACL to `gistPrefixDeclarations` ontology, with a note to users that if they load it, they will go outside OWL DL
* Add SKOS stubs - the ones we use

* Changes to make:
  * Pre-commit hook - remove function that removes SKOS stubs
  * gistCore - move SHACL to `gistPrefixDeclarations`
  * Add stub SKOS annotations to gistCore
  * Don't need to add SKOS stubs to gistPrefixDeclarations because it's already non-DL compliant
  * Documentation: 
    * Add a note in the README to users that gist is OWL DL-compliant, and if they load the SHACL PrefixDeclarations, they will go outside OWL DL
    * Add a note on the website gist is DL-compliant, which makes it easier for you to remain DL compliant

**Comment by uscholdm** [comment]
@dylan-sa 
> sh:declare, for instance, has a domain and range in the SHACL ontology, which suggests that it is not really intended to be an annotation property. Same for sh:namespace and sh:prefix.

I wondered about this so I looked it up in the spec: https://www.w3.org/TR/owl2-syntax/#Annotations
It turns out that annotation properties do have domains and ranges. Scroll down to figure 23. This may be moot, as we decided to move the shacl out - but a handy factoid to have in your back pocket.

**Comment by dylan-sa** [comment]
Thanks, @uscholdm -- glad you pointed this out. I had based my original comment on an [older doc](https://www.w3.org/TR/owl-ref/#Annotations), which stated: "Annotation properties must not be used in property axioms. Thus, in OWL DL one cannot define subproperties or domain/range constraints for annotation properties." Looks like this sentiment must have shifted w/ OWL 2, as figure 23 clearly shows that it's possible to define domains and ranges for annotation properties (even if they won't figure into reasoning).

**Comment by uscholdm** [comment]
> Plus, they have no semantic weight since the reasoner doesn't run on annotation properties.

It's true that the OWL  spec says nothing about how the inference engines should behave in the presence of axioms using annotation properties. That is usually taken to mean that inference engines ignore them - but that does not follow. What it really means is that an inference engine MAY ignore annotation property axioms and still be in spec. 

In fact, some of the DL reasoners will draw the inferences you would expect -e.g. if you use an annotation property in a restriction. Pete Rivett pointed this out to me years ago. I was startled.

**Comment by rjyounes** [comment]
> Move SHACL to gistPrefixDeclarations ontology, with a note to users that if they load it, they will go outside OWL DL

I've forgotten why we made this decision, and it seems decidedly odd. Why are we willing to distribute an ontology that's not DL-compliant? Would it be better to eliminate the file?

**Comment by rjyounes** [comment]
Note: the removal of the function from the pre-commit hook has been done as part of issue #1010.
