### ISSUE TITLE
Tweaks to OrderedMember and hasFirstMember

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#944]
gist:hasFirstMember has the following as part of a scopeNote which wrongly suggests that a strict ordering is not allowed.: 
- `Since ordered collections may not be strictly ordered, there can be more than one first member`.
This should be replaced by
- `Since ordered collections need not be strictly ordered, there can be more than one first member`.

I.e. replace 'may with 'need'

===
ALSO: the scopeNote for the class, `OrderedMember` says: `An ordered member points to the real world item via the providesOrderFor property.`. It is correct to model this directly as a restriction, is there a good reason for not doing so? The revised definition would be something like the following; the only difference is the one added restriction.

```
gist:OrderedMember
	a owl:Class ;
	rdfs:isDefinedBy <https://w3id.org/semanticarts/ontology/gistCore> ;
	owl:equivalentClass [
		a owl:Class ;
		owl:intersectionOf (
			[
        		a owl:Restriction ;
        		owl:onProperty gist:providesOrderFor ;
        		owl:someValuesFrom owl:Thing ;
      		         ]
 			[
				a owl:Class ;
				owl:unionOf (
					[
						a owl:Restriction ;
						owl:onProperty [
							owl:inverseOf gist:precedesDirectly ;
						] ;
						owl:someValuesFrom gist:OrderedMember ;
					]
					[
						a owl:Restriction ;
						owl:onProperty gist:precedesDirectly ;
						owl:someValuesFrom gist:OrderedMember ;
					]
					[
						a owl:Restriction ;
						owl:onProperty gist:sequence ;
						owl:someValuesFrom xsd:integer ;
					]
				) ;
			]
			[
				a owl:Restriction ;
				owl:onProperty [
					owl:inverseOf gist:hasMember ;
				] ;
				owl:allValuesFrom gist:OrderedCollection ;
			]
			[
				a owl:Restriction ;
				owl:onProperty [
					owl:inverseOf gist:hasMember ;
				] ;
				owl:cardinality "1"^^xsd:nonNegativeInteger ;
			]
		) ;
	] ;
	skos:definition "A member of an ordered collection serving as a proxy for a real world item, which can appear in different orders in different collections. The ordered member appears in exactly one ordered collection."^^xsd:string ;
	skos:example "A person may rank 12th in the Boston Marathon but 29th in the New York City Marathon."^^xsd:string ;
	skos:prefLabel "Ordered Member"^^xsd:string ;
	skos:scopeNote "An ordered member points to the real world item via the providesOrderFor property. Ordering information is represented either as a number in a sequence, or by preceding or following another ordered member."^^xsd:string ;
	.
```

**Comment by rjyounes** [comment]
I think we have two issues here, one significant and one trivial. @uscholdm Can you please break these up? Incidentally, "need not" is a perfectly good idiom, so no need to change. In that case, just remove that part of the description and change the title of the issue.

**Comment by uscholdm** [comment]
> Incidentally, "need not" is a perfectly good idiom

Agreed, that's why I suggested changing to that wording.

**Comment by uscholdm** [comment]
> I think we have two issues here, one significant and one trivial. @uscholdm Can you please break these up?

Given that both relate to ordered collections, and one is utterly trivial, it makes sense to have the trivial go along for the ride and not have  as separate issue and PR. I renamed the issue to reflect this.

**Comment by rjyounes** [comment]
> Agreed, that's why I suggested changing to that wording.

Sorry, I read your suggestion backwards. We're in agreement.

**Comment by uscholdm** [comment]
@rebeccca - this is an easy thing to do.  I was creating examples and noticed the restriction was still missing.

**Comment by uscholdm** [comment]
I just noticed another issue. The `hasFirstMember` property should point to an `OrderedMember`, not any `owl:Thing`. The final result should have the following 3 changes.
1. tweaked scopeNOte for hasFirstMember
2. added `providesOrderFor` restriction to `OrderedMember`
3. change filter class for` hasFirstMember` restriction on `OrderedCollection` from `owl:Thing` to `OrderedMember`

**Comment by rjyounes** [comment]
DECISION: Do three items as above.

Major change, so moving to release 13.0.0.
