### ISSUE TITLE
Address deprecated concepts for release 13.0.0

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#947]
This issue spells out changes that need to be made regarding deprecated items in preparation for the next major release: 13.0.0

**Comment by uscholdm** [comment]
## PR https://github.com/semanticarts/gist/pull/941, Deprecated properties related to occupying a location

1. Remove the two deprecated properties
  - occupiesGeographically
  - occupiesGeographicallyPermanently
2. Change the restriction on Landmark to use `hasPhysicalLocation` rather than `occupiesGeographicallyPermanently`. Also, use subClassOf instead of equivalentClass.

```
gist:Landmark
	a owl:Class ;
	rdfs:subClassOf
		gist:PhysicalIdentifiableItem ,
		gist:Place ,
		[
			a owl:Restriction ;
			owl:onProperty gist:hasPhysicalLocation ;
			owl:someValuesFrom [
				a owl:Class ;
				owl:unionOf (
					gist:GeoRegion
					gist:GeoVolume
				) ;
			] ;
		]
		;
	skos:definition "Something permanently attached to the Earth."^^xsd:string ;
	skos:prefLabel "Landmark"^^xsd:string ;
	.
```

**Comment by uscholdm** [comment]
##  PR https://github.com/semanticarts/gist/pull/951 Remove isCharacterizedAs

Remove the deprecated property, `isCharacterizedAs`
Remove the restriction on `Event` that uses `isCharacterizedAs`

The new version of `Event` will look like this:

```
gist:Event
	a owl:Class ;
	skos:definition "Something that occurs over a period of time, often characterized as an activity being carried out by some person, organization, or software application or brought about by natural forces."^^xsd:string ;
	skos:example "A transaction, conference, baseball game, earthquake."^^xsd:string ;
	skos:prefLabel "Event"^^xsd:string ;
	skos:scopeNote "An event does not necessarily have either planned or actual start or end datetimes. For example, a conference can be in the planning phase without any dates selected, but is nevertheless an (unscheduled) event. The subclasses of Event state particular restrictions on planned and actual start and end dates."^^xsd:string ;
	.
```

Consider whether anything else is needed/desired for Event.

**Comment by uscholdm** [comment]
##  PR https://github.com/semanticarts/gist/pull/951 Remove tagText

- `Tag`: change restriction
  - to use `containedText` instead of `tagText`
  - to use subClass rather than equivalentClass
- Make  `uniqueText` a subproperty of `containedText`
- Broaden range of `containedText` include anyURI

New version of `Tag`:
```
gist:Tag
	a owl:Class ;
	rdfs:subClassOf
		gist:Category ,
		[
			a owl:Restriction ;
			owl:onProperty gist:containedText ;
			owl:someValuesFrom xsd:string ;
		]
		;
	skos:definition "This is for folksonomy type terms, which can be made up on the fly by users."^^xsd:string ;
	skos:prefLabel "Tag"^^xsd:string ;
	.
```
New version of `containedText`:
```
gist:containedText
	a owl:DatatypeProperty ;
	rdfs:range [
		a owl:Class ;
		owl:unionOf (
			xsd:string
			xsd:anyURI
		) ;
	] ;
	skos:definition "A string that is closely associated with an individual."^^xsd:string ;
	skos:example
		"The string associated with a tag."^^xsd:string ,
		"The string associated with text content."^^xsd:string
		;
	skos:prefLabel "contained text"^^xsd:string ;
	gist:domainIncludes
		gist:Tag ,
		gist:Text
		;
	.
```

**Comment by uscholdm** [comment]
##  PR https://github.com/semanticarts/gist/pull/997 Extend symbol predicates
- Remove predicates: `gist:unitSymbol`, `gist:unitSymbolHtml` and `gist:unitSymbolUnicode`
- Remove all triples using the predicate `gist:unitSymbol`

**Comment by rjyounes** [comment]
Will be assigned to 13.0.0 release manager.

**Comment by rjyounes** [comment]
Assigning to @dylan-sa as 13.0.0 release manager.
