### ISSUE TITLE
Add restriction on Event linking it to a TimeInterval

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#950]
In the next major release (13.0.0) the property `isCharacterizedAs` will be gone as will the restriction on `Event` (`isCharacterizedAs some Behavior`). This will leave the definition of Event with no formal axioms. I propose adding a subclass restriction along the lines of (`occursDuring some TimeInterval`).

This would likely mean introducing a new property.

**Comment by rjyounes** [comment]
Planned events may not have planned dates, so we can't say all events occur during some time interval.

**Comment by rjyounes** [comment]
An `Event` occurs during a `TimeInterval`, but is not itself a `TimeInterval`, nor is a `TimeInterval` an `Event`.

Jamie: An event occurs during any number of time intervals (2-4pm today, 3-5pm today, 2023, the 21st century, etc.).
Steven: But there is a smallest time interval during which it occurs.

DECISION: 
* Add scope note to the effect that "An `Event` occurs during a `TimeInterval`, but is not itself a `TimeInterval`, nor is a `TimeInterval` an `Event`."
* Do not add the proposed restriction.

**Comment by uscholdm** [comment]
@rjyounes 
> * An `Event` occurs during a `TimeInterval`, but is not itself a `TimeInterval`, nor is a `TimeInterval` an `Event`.

This seems to be saying that `Event` and `TimeInterval` are disjoint. Do we want that as an axiom? Either way the scope note could be shortened to:
-  "An event occurs during a time interval, which is distinct from the event."

**Comment by rjyounes** [comment]
I like the idea of a formal disjunction - that will help allay some confusion, perhaps. And yes, your rewording of the note is also good.

**Comment by uscholdm** [comment]
I think you mean disjointness, not disjunction, which means OR / UNION.  In any event, given the past history of `Event` and `TimeInterval`, it may be prudent to leave out the formal axiom.

**Comment by rjyounes** [comment]
Yes - corrected above.

**Comment by uscholdm** [comment]
@rjyounes, do you agree to leave out the disjoint axiom, per above reasoning?

**Comment by rjyounes** [comment]
Yes, fine.
