### ISSUE TITLE
Add gistVersions and gistOperators to our release package

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#952]
We have developed a two-module ontology for specifying and tracking ontology dependencies. For example, if your ontology imports gistCore and was developed with gistCore version 10.0.0, you can say that your ontology requires the version number for gistCore that gets imported to be greater or equal to 10.0.0.  If you use something that disappeared after version 11.2.0 then you may need to in addition, specify that the version number is less than or equal to 11.2.0. When the ontologies are loaded into a triple store, SPARQL queries can detect and report on all dependencies and highlight any constraint violations.

This issue proposes to release suitably updated versions of these two ontologies. A summary of the model is depicted in the diagram below.

![image](https://github.com/semanticarts/gist/assets/10777545/0cf3589f-33c1-4714-bc13-448415e02ace)

The following example states that version 1.3.1 of the ontology `gistVersions` must obey the following:
- the version number of the imported ontology `gistOperators` must be greater or equal to 1.0.0 and less than 2.0.0
- the version number of the imported ontology, `gistCore` must be greater or equal to 9.3.0 and less than 10.0.0.

![image](https://github.com/semanticarts/gist/assets/10777545/73b87034-7ef3-4fd0-855f-203fb269e289)

```
<https://ontologies.semanticarts.com/o/gistVersions>
	a owl:Ontology ;
	owl:imports
		<https://ontologies.semanticarts.com/o/gistCore9.5.0> ,
		<https://ontologies.semanticarts.com/o/gistOperators>
		;
	skos:definition "Generic concepts for doing semantic versioning for a suite of artifacts for semantic systems in production."^^xsd:string ;
	skos:prefLabel "gistVersions"^^xsd:string ;
	gist:dependsOn
		[
			a gist:VersionRangeSpec ;
			gist:greaterOrEqualTo [
				a gist:SemanticVersionNumber ;
				gist:containedText "1.0.0"^^xsd:string ;
			] ;
			gist:isVersionRangeOf <https://ontologies.semanticarts.com/o/gistOperators> ;
			gist:lessThan [
				a gist:SemanticVersionNumber ;
				gist:containedText "2.0.0"^^xsd:string ;
			] ;
		] ,
		[
			a gist:VersionRangeSpec ;
			gist:greaterOrEqualTo [
				a gist:SemanticVersionNumber ;
				gist:containedText "9.3.0"^^xsd:string ;
			] ;
			gist:isVersionRangeOf <https://ontologies.semanticarts.com/o/gistCore> ;
			gist:lessThan [
				a gist:SemanticVersionNumber ;
				gist:containedText "10.0.0"^^xsd:string ;
			] ;
		]
		;
	gist:hasVersionNumber [
		a gist:SemanticVersionNumber ;
		gist:containedText "1.3.1"^^xsd:string ;
	] ;
	.
```

**Comment by rjyounes** [comment]
@uscholdm I would like to see this in a sub-gist rather than gistCore, and then implement it in gistCore.

**Comment by uscholdm** [comment]
That's what I meant by:

> This issue proposes to release suitably updated versions of these two ontologies.

Separate ontologies that import gistCore per the above example.

**Comment by rjyounes** [comment]
Closing - these will not go into gistCore.
