### ISSUE TITLE
Clarify meanings of `unitSymbol`, `unitSymbolHtml`, and `unitSymbolUnicode`

### ISSUE THREAD

**Issue by dylan-sa** [semanticarts/gist#959]
The annotations for `unitSymbol`, `unitSymbolHtml`, and `unitSymbolUnicode` could be improved to better indicate what each should be used for. Each of the definitions contains 'm?' as an example for square meter--this appears to be rendering error. The annotations could be rephrased without reference to it. Examples should also be separated into `skos:example`s.

`unitSymbolUnicode` could be improved with an example: The unicode for square meter is U+33A1.

`gist:_percent` uses the special character "%" as its `unitSymbol`, but unit symbols aren't supposed to have special characters. We could revise the annotation for `unitSymbol` or the symbol for `gist:_percent`.

**Comment by rjyounes** [comment]
#992 should be discussed first, since it makes this moot.

**Comment by rjyounes** [comment]
@dylan-sa Has this been addressed in PR #997? If so, please close this issue.

**Comment by dylan-sa** [comment]
Yes, #997 cleared things up nicely.
