### ISSUE TITLE
Remove domain from numericValue

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/gist#963]
@dylan-sa @rjyounes 
The domain of `gist:numericValue` is `gist:Magnitude`.
If I want to have an inexact duration such as 5 months, I want to model it as if it was a Magnitude:
```
ex:_InexactDuration_5_month 
	a ex:InexactDuration ;
	gist:numericValue "5"^^xsd:decimal ;
	skos:prefLabel "5 month"^^xsd:string ; 
	ex:hasInexactDurationUnit ex:_InexactDurationUnit_Month ;
	.
```
Because of the domain axiom, this instance is inferred to be a Magnitude, but it is not a Magnitude because Month not a proper UnitOfMeasure for a duration -- a month is a pseudo-duration. Math would not work.

This can be solved by removing the domain axiom and using `gist:domainIncludes` instead.

**Comment by uscholdm** [comment]
> A month is based on the lunar calendar, which doesn't mean it's not an exact duration, only a duration that is out of alignment with the solar calendar we use to define days and years.

I'm talking about a calendar month in common parlance. Exactly 3 months can in the number of days it is, depending on which months.  But I can say exactly 3 months after Jan27, 2021 and it always means May 27, 2021.  The enterprise is much less concerned with astronomical months based on the moon.

**Comment by Jamie-SA** [comment]
A calendar month that is not from the first day to the last day, is not a good concept. What is one month from Jan 31, 2023?
In most cases, that gets restated as 30 (or 60, or 90) days.

**Comment by uscholdm** [comment]
> A calendar month that is not from the first day to the last day, is not a good concept. What is one month from Jan 31, 2023?

That's an interesting question, you had me stumped for a while. In that case Ione might say one month would last until the day before the last day in  February - or some agreed sensible convention for such cases.  I don't know how warranty periods work, maybe no-one ever has a N month warranty period, only in days, for the exactness. But there are 1 year warranty periods. 

Similar issue arises for birthdays and anniversaries or purchases that happen on Feb 29. When is the end of the year that started on Feb 29, 2020?  One reasonable convention would be Feb 28, 2021.

**Comment by stevenchalem** [comment]
@uscholdm Here are some examples of how Excel's EDATE() function handles this:
1/31/2020 + 1 month = 2/29/2020
2/29/2000 + 1 month = 3/29/2020
2/29/2000 + 12 mos. = 2/28/2020

**Comment by rjyounes** [comment]
> A calendar month that is not from the first day to the last day, is not a good concept.

We use this all the time. "We are having our anniversary party one month from today." "I last saw you one month ago yesterday." Etc.

If I say the first sentence on Oct 3, the party takes place on Nov 3. If I say it on Oct 31, the party takes place on ...? This is the difficulty. But it's not that we can't use the notion of calendar month for anything but Oct 1 - Oct 31.

**Comment by uscholdm** [comment]
Excel EDATE - cool. Here are the results for end January.

![image](https://github.com/semanticarts/gist/assets/10777545/5f69e68d-1f98-4355-b35f-4a3f1a7fd505)

**Comment by rjyounes** [comment]
Makes sense to me.

**Comment by stevenchalem** [comment]
@rjyounes Yes, EDATE("10/31/2023", 1) = 11/30/2023

**Comment by rjyounes** [comment]
@philblackwood Is there impact from the new units and measures model?

**Comment by uscholdm** [comment]
> @philblackwood Is there impact from the new units and measures model?

I don't think so.

**Comment by rjyounes** [comment]
One potential use case for numeric values on non-magnitudes: we've defined a class `FiscalYear` to which I want to add an integer value. I could use `gist:sequence`, but I would like the option to use `gist:numericValue`.

**Comment by rjyounes** [comment]
Already rolled into Phil's PR.
