### ISSUE TITLE
Rephrase definition of gist:Category to avoid the word "informally"

### ISSUE THREAD

**Issue by irinafilitovich** [semanticarts/gist#968]
Currently we have:
gist:Category skos:definition "A concept or label used to categorize other instances informally. Things that can be thought of as types are usually Categories."^^xsd:string

In the field of Life Sciences there are lots of taxonomies of domain-specific terms that we're are advocating to interpret as subclasses of Categories, these terms are used to categorize other instances quite formally (as in officially, importantly) from the perspective of subject matter expert.

Is there a way to rephrase the definition of gist:Category to avoid the word "informally"?

**Comment by uscholdm** [comment]
From @mkumba 
On category and informality, I’d be in favor of leaving it in, or saying we don’t have DL style inclusion rules for what is and isn’t “in” the category

**Comment by rjyounes** [comment]
How about "without formal semantics"?

I am more surprised by this statement: "Things that can be thought of as types are usually Categories."

Without more detail about when to use categories vs classes, it seems to me misleading or confusing. I would advocate dropping it.

**Comment by uscholdm** [comment]
> I am more surprised by this statement: "Things that can be thought of as types are usually Categories."

This reflects the two ways we can represent a hierarchy of types either as a class hierarchy or as a hierarchy or gist:Category's.  For example, you can have a class hierarchy of diseases, where each class correspond to a type of disease at some level of granularity. Or, because there are 1000s of diseases, you can represent that hierarchy where each disease is an (possibly indirect) instance of a gist:Category.

**Comment by irinafilitovich** [comment]
> How about "without formal semantics"?
Sounds great to me.

**Comment by irinafilitovich** [comment]
Hierarchy of gist:Category's - is this done using skos:broader?

**Comment by rjyounes** [comment]
No, we use `gist:hasSuperCategory`.

**Comment by rjyounes** [comment]
> This reflects the two ways we can represent a hierarchy of types either as a class hierarchy or as a hierarchy or gist:Category

@uscholdm I'm well aware of the two modeling approaches. What I don't think we should say is, without explanation, context, or nuance, "Things that can be thought of as types are _usually_ Categories" (emphasis mine).

**Comment by uscholdm** [comment]
Two alternatives come to mind;
1. "Things that can be thought of as types are _often_modeled as Categories" (emphasis mine). 
2. "Categories are often modeling things that can be thought of types"

I think both are saying the same thing.

**Comment by irinafilitovich** [comment]
The rephrasing of the first sentence to "A concept or label used to categorize other instances without formal semantics." sounds good to me, thank you.

**Comment by rjyounes** [comment]
@irinafilitovich I thought it made sense to assign this to you.
