### ISSUE TITLE
Add gist:EmailAddress as subclass of gist:ElectronicMessageAddress

### ISSUE THREAD

**Issue by Jamie-SA** [semanticarts/gist#99]
Adding this as a suggestion after a short email exchange with Dave. We would add this to dcao and Dave replied "and we probably should have in gist".

**Comment by scotthenninger** [comment]
Created a pull request.

**Comment by rjyounes** [comment]
Definition: An email address is a unique identifier for an email account. It is used to both send and receive email messages over the Internet.

**Comment by rjyounes** [comment]
Completed in PR #316.
