### ISSUE TITLE
Remove symbolUnicode and symbolHtml? (post-531 implementation)

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gist#992]
Note: these predicates do not currently exist, but will exist after the implementation of issue #531. #531 involves renaming to make them applicable to things other than units. This is about whether we need the HTML and Unicode versions of the symbol predicate.

**Comment by uscholdm** [comment]
I thought we agreed to keep Html and Unicode versions based on what @Jamie-SA said about the likelihood of using them in the foreseeable future.  See #531 and #959.

**Comment by rjyounes** [comment]
I didn't think we reached a conclusion on this. There is the possibility of implementing them in the SA ontology. It depends on whether we consider the need for them broad enough to include in gist.

**Comment by sa-bpelakh** [comment]
Recommendation: Move HTML/Unicode to SA ontology, remove from core. Verify with @Jamie-SA

**Comment by rjyounes** [comment]
Assigning to @Jamie-SA for review. If he approves, he can either implement or pass on to someone else.
